---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-client
  namespace: argo-workflows
spec:
  encryptedData:
    client-id-key: AgCptgKZ4WKdaNomlSz7hcET5dvTj9Gi5kI2ZvDzc0qyzJTke6Sn+hyBvwjZ6Cu3sgZL4JUmahyn+Fpg62D0e3y7uJFxCBSr3Yuml6ws0bqps6SD8OwJqlUcPu/p2Z9Sc4cKQQITMvwFPKRyhwfYIUGyNK3hF9POgKmFWoLUG/rw5bS55o05o5CUqrDjkAfNf0/Tt334Yey6ShiTzfagZ539wXB8ASef5P28O58Q/5dLjz52wpjqEcAsYhaJqoYpVSQYBxGS+E30tRWyrD2fOLSpiCjQ53fh75AWX5AXVZRoNihkOhCn+jw2Nm8kA0ZSvpN+j1FFhACKv+4/fjFblLL5VbZqoS/ad8sUW+Dpe9rXioNJV4v2ge574eS16+wsi0ZaOhNNZ0frrLSOqoAkn4O7CniArSdYeBHmI+lVmmIMjIex8js9kSUyqOUDMyRggGHl6AKzhLlPEr/c/fyAluCpxgyKPx7+jpBWxXYhPkYGi23zWEAL1ehRI1yi1INt6jlB7pWUDb+wfweA9z1MnHNUbu9Wf6p/CXmw3jVvPHqcoH1WicXY9ziGPe+W+I0Zx+IdM2kUYy//Ojzg+8XPXKAg81CmKFprn+VNxxiNZQ3tAEb3hG4GFunJYHBS4Rn/R+s1grEf75OXFwZ1+ogCJh7ib47ZOvEhGCr81e/+kd02i6+rC+IQHWoOUmkzQvPhsdnFkNNoE27TrmC0JazNBQ==
    client-secret-key: AgB+5kbGtLoK66o3KLpjF6eWzaZz13mIl4TaJvfMP1svhrake8dgCGQWAVOpYs9vDaCzqPrvV+Jyv4vWYya4gag18JY7lqvp2SaifbHtRUZ1jtXsLvuh8tk/t5MZzlEvpbsmzFCZ/wkPEGFZ5BxcTmKfHhNb1zgD+O84GKrzr4G/AVmYayJMk5HWptm70iMx7cTnFmyaL/aOKdALoE8YbcY4K16xUQ6MKpdbllP37Ha5/ZcvAEEzfp1GRfQSQCubVFTJVYDs/sTTxyLGdGx7eq1FN9trXq8JJYdJNqxBd7LkSYNuM7Qo/ScID2I50KZUeK2nNxZjjYTU6/meG/cPKU9J4u7gPUPV29/CAX0U6DtoDJzBg7J41k8XmEDtRrJwqPmQ0AEhoqbQp4JQNnDP+l079mjPVpZ8iP0ZFd0OX0qDh26kPvPEc94YI0uQbcoQzNNyt9A7qPUiNXtis00lR5xawzSHnYW+fmApFjQfU54FAAGpw37dHCjqWUu3H7IqygopSiInVzJi0aEa/QWhv4MEvp1JkKr/wZSsYur2guCgkzmUkZ/7cv5adzLGTV+55HilryEtDbgy/Dwzsg7vYjmWUSdOqLeyMFNuOigq6qL2Muyg6uieWuxZQSnX6RounfdBkx8uGsV68U1RrafxvJNlTbmHMkS9JTyvs6Amirq+0CxCnTfO72SatsXv8dnys6SjhklF2QW4ojmVQPLWlo38CsMzxnl3YohC0kTOUzY4Sg==
  template:
    metadata:
      name: keycloak-client
      namespace: argo-workflows
    type: stringData
