---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-client
  namespace: argo-workflows
spec:
  encryptedData:
    client-id-key: AgAmgFDKo52jCQQTFsbw+eP1upvzv7stso3DizZBuk859iKG9/I+F+up/aBnPBOsrWoh+rG2ANrxYVVkMNBDGsxwrXMK9wG7SViPLhA+AjiZHJf00lYNgl1rFT2d+oNlOqMC899LfH7ULND+vPTPFLbzRX2Oi5QU/1drmRg7qejH01Guik0Gjh1u14VmQ1bOsx5xScDldxkMzVKM2dCqOPk831w4Xg+L/pvo8lw1UQxvb4a1FE9Vz98mTvA1mHG12+WYTzINnffvQLNL2uePI5/pSQm8U3s2IdUI01UsuwsCE2yFKAHYUYaAPcFgxfq0EadbGp8jLAeOZ9h6gY6D82AEKjpcrtwUFZn4wQp5s1mtWXoetXd9chc7N8ASxXp/NgDifSdTtRPTNE2rfOutElylQ8jxDmOA62n+EBr7v96Jc6jZ8aLhDQR/ld/KCIpT6Oqlg1c4V+dX3n35Hr2YIR6LaXFnwAgACMuWtLT9Xez7EFwo3Kyb1ARbn0ezZruvVUYFu5z6tcXpGWmE4sGMTM4LI+HH1qrUj8hBCSUkMDnV0YtFsGal1nSJPnc+PciQJ0EiZMx59y35espROkvh8igreghB82ZMvU0KcSxv89IVd2W544C0NSe0YbvftgOupEFM57pr4Q3GEAnlXgtI1Xn1GnMyi3nMcwu9vNwqlSMyEwGjaZEIIlztTE5nz1PtU3kL6bfDG4k+Vo9CuzwGKA==
    client-secret-key: AgDAZhka6jJX7uu6NC82ajibVWJB+ihXlgaJyXCIqA/bBWcZ2/H4MQGWHkQN6aHameTEtrFgdjwyB8BdWz2hUtqKO+uHb/NbJ35VOo9aBrvafHFrw/+aw6Gxw6KIoxVf3DSt19n/FhmgcvzyN9Vh/2+vbJCLOTP+KJi0xgq46WGOqHOe08L5HBZXWZlt2qry0Cb1NwZSf55fEEt5KKjdabL3bdGf/CacM4Lg8gwHCYacOFkRk20hIM7D7K4UVetT7z7Kg/TKaUiFnPl75bAx8aWiKMoPnbzimXq82Um2W1JAbdiOvUaowzKGyQaRrSb3TnxS9B3/P+CaIyMCh94rNdTjHh7prDp+JVzfEAqDeOntv1poL8eUd5T76cSsayy4fsIIvwS7XZhZTEU4zDlA7FUUMxCvQ42Re89g8LuFM9WwJZ+TQtgecqnHMNripdOnJQXx6inIcvAX0ESrIqIJCpIGHtht+FiZQkgMCl4xfy09IqegjALR13jmlV84gYD403a0kCSczeXlOFcGW2pwSDzH1Ig4LjWlH/9Jk0z/pXKnL5bmOoEqbw+R4eCehBVCqbK9gm43SSn0Sr/Vn8VcAjKBi7o2k72puZFF6/qBmqS40UH6B7fA4Zn1O8ONlARonif+etUHUh0qyardO9GooygRCFXzmnglLTu+2s1AQPkr9CSXL6ojBEO6yTR0Mbe+jG9Rr7sY9EX1rhn1TypuOP+JfN0BUs2EfztGus9Fm0u7ew==
  template:
    metadata:
      name: keycloak-client
      namespace: argo-workflows
    type: stringData
