---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-client
  namespace: argo-workflows
spec:
  encryptedData:
    client-id-key: AgBUYawhfjPVhOn/3cDko+7o4tk0UWlrddINI3Dw1j/XpWDMGb9flZ6cuLs/tNq+NESQ6GCzWHv2p+8LI1kNN/JzQW/b+GuPQTnoYiVjGl79Sp9zk9rMTZXs32sim3DTd6366H6Gq0hVZBODeGRsZGYf6+KztrOeteXVpdsZNVA5ZPmrbM38IW5vWkgMhRHO2aqcmyrpd/gUSj9boiEnTVQtXRyhTc2kMyVVPVRSVbuk+uYk7OANesh4qiusbM6HEEujLKQZvrJz0XLtdDQeCOrruPfLqQTQVL2shiAm+ilDauIeAWvSllTYPfI73eYCPOTxlDKvKx88OvVdbaAZbx5aPhGc3TNVolR+ovGvbM7UI+0nI10uuSOGX9ugd8mwe0mWEAaynZN8eJ2MaeQIhlEUgVH9kid1ke181+SEGxoGfUapPvx45i308LmN7cKW2KBIpFwwmsnZed2/bc8qcL3X6aVhZsem6QIIOWC6nJyN2ABTzkLOpwSbis37AvzrCeq1eJ8MudUizm2Hkpjb4+z2R4WkGL5RfFg7K+K5pTtvwMo8Oibunb6APXx1qXXdJD2Lc7MrUAul8syRwiWIJX68hX745ui8AZwEdo7MX6XIXKdl2Hc/CoJYJQCEpE4wHmCIJmjKiT1JFM7njbmOXEwF2FZSQzRVdcPUi3rOX8GC+NIzZGBNzdZw6LdWdXIgiXNAjQ93Iwd3OamITBC3Rg==
    client-secret-key: AgCcAFCndbvMmULZV5w1toSrOJQGG8GQqaXS4qJ6MlzdoclD4aU3+UY9BwmcfcsA+0EwA8collX+tv9iE9/MYRS0nn0qUQlzw7kttyHTyXzFED3G6pNUUD0dn0d7vCNmq7VmTv9qy3wjkFiZfylH95ITwaqSAfhkTtl6L1262sixS60emvlweJwEzlPk34LEOCUTiHfeYlqtRl1PdHQkYtgwkhY88t1LVNze76lorutT4WfUgST+X08yAh8eNtztrobYKms6nBchhkFQpvQn2a04IrywBFMUSQMZimIyx2Bo5Qiu/J/k1wYtOPEcaos8j/I3UyePQLy5zoSBu6n/NjVKDB0tiv1CM1AnyJ3rf/B/Jeq4Q9m2BWop5GqEiD9y+o015PYjuo3evYKRpXh5s5D8cYgDZ5sB1Ix0HnGFAwiI7th4LA7TgPCjKz1R0Il+59OHg0UT0krnyckjhUTBAEtMx798hYjl1xp1584KH0AiWIe/MVnCWE4q9xnuhIliaukV75LEgnHbwyQQ5/s3/doybrEkRz677JZFaQ0Nb1DC6eE5OBIijkQK+2s52i/gWvg6hWIepT1OqV/nW59ob03erreVK5igmx/1u4migpBH+DOUZM3QJjR1pDMI8DQh+9BkCXk1gTxVSptNdrDeTHML6HfwK8USzh5Ig3E1zMBwYqnrr6OxGmQ0944Rs8v6/g4MXZ8tRPMgH9cri5motKNmzADs8EhUvThVBS+Lbs67SQ==
  template:
    metadata:
      name: keycloak-client
      namespace: argo-workflows
    type: stringData
