---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner-token
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-registration-token: AgAl2eAXI4v32L0gMr2gRTmEaYT9kKnSH7rvGfAgcZnVqGCIX9nGNYXekgg9Xh8FWVt215S8QLHEbKhJN2OwFUerMVFuCDMC9xeP7mZ9Pvxjq4c9jaT1pAPdvdPrOhoZG+Gp5v+ZGsl91XoL9kiVaEovj8mJybcvOb1Cjd9ecpVcsajKT4cT+Kb0WWD6oMeq24tDsOS0jZlS49Pu1B2SASNXehTbqtEJik4jcqmQ8WnrILMxvPIBmckP7J3YwQltZw6bohqXotAh2yWZTZrccDYBw0hxSlucxpGBcX0bW8uVn988zhNSXFgxYX3l2yIeZKPxh2KDDMCFgP50Nnq7fEs7c0LkGwy0vT/Euqej4BJshMQPBMKGr9hDkWRsfBB9R8rgygXWXfRCSEvN9GxKi/iHxgRaI4YDS1er1mOL59EkDDj87hzlQmpD1ptkzkaZ6f2nRJaX6Fc5X65sw0dXYWwkhIqejLusoiWZKRZ3sjpfR6SdGyhQ/32pIPnrUiRzML6DcpfdZhvx5HJeVSIzMmEUMMEmmIZfkptyRCRwVnVj61kPpJgxBNjn1LS1v1W8JmSVtHt314QMpO+VtjV/TAbty77KBopZ5rmruWJoddR0FT+M76voJVc1tIr9rd+tz8GvkVGdA9cMjwB/kxfMt2+/zL0VCylLqsENHTYeLCCYS3fTZR3GVm32QFY3HptCUmk=
    runner-token: AgCWYI6UZur8ro2RI7LLEG8703MXed5OMd7Dnu49XMtunSkmk9kNy3LOHczN7kb+m0wUrUyvcXUKc8icUfeweJsgGxWjd/KcXFajDxc5m06ABNfadpbsyBSAx36R79d49f6MwahOVXjofS5/liui1NTiTPaA+N8iC3Q2deSZMgR5Odkr6MAlL59pMYD8rF2AZOMtM/iRDP1UJim7ry7mNRELDGDNDSfRClVCcdpLzFUobjAbG++uZqn9Gq8aFS6xoI6ld2PX0mgqE9C0Vk048lFlJQ5+5Y7W5RmW9bClKATzQQjzDInk6wkIgyU2cFgeZlOXA//GMiJ+dft4tq56CI6YSz0ZhUInmlT25XST3M0DiE7WHPE7YAw9iwDecQn08lc5HhLDH4iOYrUoyFaMr8JXGe2htBD1/qwVBFsA9yMz27KnLdayN4kg9nqX4Zq6y4Fw+akwwdKF2Qsp+EtE8i+r/kqMoueNvOyGQTApsAFECQIw/Tksx53KaUkNj6IwdPouTx04opcCyq8Iq59Cu0XB/HhSa2+7xWBb9ygrToqx3WccXJu+nSXdHcL7a+4hHLvQkCkYjN7NTZ0Q78DomY0e3FmBkPuiPw8PGvcePv/Xm4uPJUJlO0CegBxX/vY9qFhOJaME5tvU/I2Wq/AXdkelr8CS5jb5lJx0rUiWYZ51UJQl7rz1aYWq1eH+KOKSfQ+oYqQWi2cNOjHxKKBheKgwpQo3NZYDOW6LXwhqOoRqGhl/FU1YOCzOzMnSZ5tGpmlhGkGEJ/gsHQ==
  template:
    metadata:
      name: gitlab-runner-token
      namespace: gitlab-runner
