---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner-token
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-token: AgCwuy7yHbvTpGxZVf0bIXLq4Km8+F8MZybo1RpfwUsnfQ2hJsseeJ4TayMznD8sKgLDSRelpTg7i0fzntaq0mibSwBwPcfztUB767bKOf1V/KW98AevLUGIjWpNaTbMn90mLySUY+m1zq+/TWsVuiuWMv5WCONwpkA2KNRYxcvoXZnZggtpNXxnYk23skt8I/Z9u7D894WjMWDARCZasre1heBYph3U1IV8CqkIaSvZrCHR4Qf66t0mn/1EpQ5uMoRxOtZ678h9EJxCXiqMRN3G373VZekFs+y+n+JPF0zg1SJghuvjz0+4xaeT8vV+Sfpalam71TEQa8e4DSIeNhhn2QJyMzG2zCrJ+XCFRr+5Qop+4SZfThwZhpKBs5aFS8zLm4g2coDFF6zILts9oyQdlY0E+y0gmMLGW6Jm6oSnkL8LCW8GU62AIPFAKf6q7js/uPMSIrO8ypfVx3lcKZdOok7IjcblFptoI5XnAZr8suOygVkwXZtS0uIGTwiC4Xlo3aCfjKylwJlaqlhhtysnVBhpq3JiS/HMQoDdUAD9vOL+60NdxEoQjvjLdEeTvY0/KNb0ENts2RcSSjFlO8jJ492qSEQIoWi1KXE98QFTH2JBLp+xHKdM4KPAP7M+gAc9REcdbzV+dnGySpkd5USfDS8iYPiF1q4gPXvHCE16VofUf5ry/1lCKYviPT/hGVCEvH3AZ0NCjZHhiqGmb9eiFCGA/GIHiVVTucYorX0GISrBPNW7clw7JEWz6cWDIYH028wC+7bVZw==
  template:
    metadata:
      name: gitlab-runner-token
      namespace: gitlab-runner
