apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: grafana-mcp
spec:
  forProvider:
    name: grafana-mcp
    role: Editor
  providerConfigRef:
    name: provider-grafana-config
---
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: ServiceAccountToken
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: grafana-mcp
spec:
  forProvider:
    name: grafana-mcp
    serviceAccountRef:
      name: grafana-mcp
  providerConfigRef:
    name: provider-grafana-config
  writeConnectionSecretToRef:
    name: grafana-mcp-token
    namespace: grafana-mcp
