---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jupyterhub-keycloak-client
  namespace: jupyterhub
spec:
  encryptedData:
    client-secret: AgBSFe+H30dzJ0ATGTMUG+VZRmjYE9uy3A0VEznVskg5f/EfUMkYO1u71LCHA/2g+pmZUfi91lIH/mshotEPxOcnjmkUT9gMeHRnw+0nzQbsTluiLPM+C9iaMjDX6okdoMXimPcHJ6ad4RcF3dhdQarNsvVgRLh5Bz1dnkcoOuFlNWlY6paWyNjWHTX9PePfezy45lhYEcgcgWris6vYtAmLpLh4UcWAPi+47NuGXaKozsLaoC1ZRBdfgU2Ej1BLvvMtrvKtpyJl7wLDS8O2yx2wFItMS4v3wlg7LZcGCOCwJRUZMFPBoKbOxjgMzm1OhW1jl3qyUUSBslvZGEt3UPvGuhPiVk5VRjUY279VWn8tstSDTF9HDTOVr5CUoupZkJfPJOOYutGaQ6aOqTPMXJZtILP2e+TxagQpySGBmV1OORzZ+m0ZE1sosypv+b9Iacl4n9g/Rllx7Wheff2DAbkJeVnRnAw5wr/nFWuq0nED6SLqamXivbdjaB1ZOs5Kafyzddl08Bnt78ou3qSLBboDN92WUC5QltbFakZDhhjRQLQ+/yJw84tVWzW12AqI5Dj8acs5Y+l7frtuDeSCY+/dJOw+QKLFT9nhsrd/X+5nkplqHlwVznHBC19mbgIeXc7cq2N/paLE8KCdQJEaLkl2hpj/epXttpm8v1RP224+4PRtwsnKvsP4SumzDUb7jqonlYpNW4uCunDsMNmBzX5s9xJi0ojHJdo=
  template:
    metadata:
      name: jupyterhub-keycloak-client
      namespace: jupyterhub
    type: stringData
