---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jupyterhub-keycloak-client
  namespace: jupyterhub
spec:
  encryptedData:
    client-secret: AgCbbwafbjtmKfgR7RA0Q3zeaKTTlo7m9Oosjrh+aK0a74/HvZXbIh/N3mRCUHn8zVSc3V+NiJCp7POqKNTblPIwgfydYpmPWDf0LXY0KLh69AiTMhqEvv/j+LA4O4VGCQs55KIGoLVJarTOzFaE1TUHHbnUQCd6f9lP2GM+BH9gI5z7D+q3KNOablX1SMKtg5EbnTVLDLt5RfDJAzBw5RZRXkMoNE754k+aPNokl1LlEQ8mRxVHO+xGh0Hix2ojHy2Tmxk18zdysOamerjepDof7btSJwywkAuCFFOCH4OXVc/qEHz9/l/ZK2vvxvDKyIq/PAt6IRHFLY7pID/W5luH3ILweT9WGbrizFr8t9wtsmZ1ymfChCY3eMad/G8sxyTDRvyloi+L4AtVcPQj3FjJaGQD8A9R6BIEh2gmn39Us9FfOQ3rfOwQhwJXJDae4rQL+ziwkLgrETc+nnyAsGNgr6cHhdRVuLnFldofAWrckcRgA+MzhuQw/wOu7RETVtkxIjga44O7v54w8DQ7FblIQzwvrQ2fCO1VqfaITqGDX8l5LFq1cc/LiA738TIauPPS14g7ZY6EBNUb74BEANaUylm10/2opZQCyuxHmESA5g1QEToyA8Q7cxmn/9JKv+hMPNPYPDiyPPQoSvdHSqibLU5u0QAgsBtn2wSm4x7NbiEHhSUEvF3cbQHMos7U5qHNJS6JwofFEEuxeTwqcTxQhWHSo7BlxQs=
  template:
    metadata:
      name: jupyterhub-keycloak-client
      namespace: jupyterhub
    type: stringData
