---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jupyterhub-hub-env-vars
  namespace: jupyterhub
spec:
  encryptedData:
    JPY_COOKIE_SECRET: AgA9XDjjfI50gpzsokvm1JHjLVTKI4taQDVjgKhDeJe99+K9i647QDXHNbGjW8SStotyHHJip+rQgtEpXE06DKL6q/ivfzveQnKxH9pDe5fkuB8SqhKVG/Jw4J6SpdiPtau8cyhMDsApmrNUQIAtNW9+IZxLmZau4IyJWrZef+7ZBWoH/wFW+5Q/d88p+5EQQBX5y1Ib5v08bmbX7LGjVKmTcgg1iBfFs2vo+oHigC9W1QaEkxJbzi7WZ+flK5mGGPJWE56miZzSR86fIuhGzSqC9rs6ug1BlNVe9vK+S+TXO2VL2YAiiHb+ZznywYkjTVQbLKZrukZC2BijIMjI+ALFnmxNDnON6YSpuTQxE7VTTFoaSQiTzY54UOxI42U9MzNT+UggZ8MpBpTuW0NzmvvfiNUL4etmVmKYaqoCEgX4FZ0fKpNCp/D2QT6gcswGOxK2GQ0Dj7Lwzyn9dVBFEgshKwuTjhYXTgVnY9eq08gNww8dv4hRVnwyda398nAvB9LKEzPS6gjDYWu1NbfdVr+/WeDhF6OThqbQziWge6Y1F4WJZ2nyLucCYcmBYqUYjqdvva/18wl4rInBOV/dypLoa5iXu6vkj//vHT4lGbexVX1bJtn5w+MRLuN21AE+N8N0KXw2xngRoGOlSrdECJfD+2D5SEaDKxH/shnkpvNoBiBTyO0ufQ+E9W9KGEmt1voGBIyYP+12vfB+lBHIciiKHYJVea6QGVmVi32nBBx5QZtfxtvJYnZrTdtkBrsDVyOky0r87fZR/KgF5n+vjKnY
    JUPYTERHUB_CRYPT_KEY: AgCzJviDreBWjvRtvbF0rs8gRngYBIhvqnvuVtF6eJKvNrMLsqUfz6XhgPkafNMen4OKfuEOSior/yFIBp+OlWic57glA+OJFLRAMoYqTDLo8tPiWwuYe5+wmZCtEdNjbGTvTc4+yiRlL7ybV2O2etFpXDWFUYGbuaUcqzWlArX8eRFK/fSIsYuYjebXjiucZrzz3RjiNw5gUrkJWNRyZ/jN7N25lUDE/Wc86G6sQmCdhj4iSMrvCVCCYj+BETKKlz9ZuLSpsv62C9dmulC8AK88MhsSDpWvtSYRwOIYP/uy1oTs4YHP7UmVYzjdwQ3wVOnY9NBWkSRQhEcwtuHJMpACZnxytzQFEpofuefSs8c+KJweJrb88sNYN8eOYL27Kmk/w51ObmTItC5u+3PqX/WX/9gBSUI3LRkDw1FLPdxK1OgEzvlFj8dab8aLcZmzVGhkxUfnriB9o3CszLaR+PnDPyMlkrPrp+q7uhxHn5SQrhGQiOiXtpuzzHRIypoSybO+AcUW/9baDTHhJTnR4CA8cxlGLOt9ptKQzy7QIsmXOWshSqtM9CkIfh9V0Mjnm3ZmzF+gkWqWSWOYfLgxiEu0F+YMzxCAPQKFLqcLAABxSZs0/G6NgOXUJ0rF64acfqP6iN9LVt86SIwP6s/ORboqSAMUsKRzpmeh9g3ltxFD3vd5A97iaD+0hK7IK3nSuImGwdfwTVNWwE3vRsvmDOK7wyqL33DpOuo4YxbN0gwwDstjEBynoH6szuZQd3kr1lnqi2tc1qQuSYjuX2qvr8Q7
  template:
    metadata:
      name: jupyterhub-hub-env-vars
      namespace: jupyterhub
    type: stringData
