---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jupyterhub-hub-env-vars
  namespace: jupyterhub
spec:
  encryptedData:
    JPY_COOKIE_SECRET: AgCyquHdTltaxw0SNgVNRVhUegcwUP3JZo9VBqNHDI/G7eyjEMpqPw3BplGUuAhPssRRFwmZTnHhpoZH+SiFFJ/vtmQvp5EXGwPMb6uOnuGX4QVzRXvqMfCF//sQPuI34DZp23zO536AE218O/bfLHKBDsR6+qTW4qe/zFus406yezveDppbHzqeUdeJEXUD6YgUj2/29O0myxa28zG9TwpCaSG5WjRHuxBmOrTr4a7UgNuItW612I+InDX4SpXeH2gdbreTw7gQ7vm+34RaSjCPMlf6LH4rwqsa7iI82tXqv43Yg4P6Pe/UuocYfSyu/gNt6I+eOCZhVjcZLVRVdje9xQWwxLzqBwUlpYCvcGeEesyK56ObbBxTA4vxGGtY6Z1Ege7yrarjPyxNoB7EasKelfB1Bp3C7HA9E06RHxH6569n5u1fA3XNsfnVrhVRIkDj1i3kc/AqgOZxSYjoi6FP0KZNMIqJ5au8mMoVzwvSqId31eM2DRWrkz3EhR6/ow/PxEXxt+7E/KT89ggDgdt/0CB2bTkH9GYiy0UAZu3XO5dzZTHBMbzvg9/KyhaiB9vAEeSqMhQz2XiYzuKr5PC4yqYVH2BI4EfnwdRbmkAR77YkPIhQT5O3S3yIjel9Ywc9wrn3dgOSuH3ROW9zQhNmyco4D9TPe2oI/EsJpLZvwdomxvVn74L8G2MIjfxpc2Uo6lKSd3lvhQZkSSDtvn8yF896K9QMJpulngUiGlTUfjIRpKmaJvnOCJOznYinskMPuFe1e4KfWEDj4PNRSTK3
    JUPYTERHUB_CRYPT_KEY: AgCQ28AU3KSU2IsaKzEoUXVvZRzXk8Ecb8/cfGLjv85YbD/oRwkowEnVhBr4hMNm5Vg+T7VCqBMEkhxTLd4vFMsJ8YjqpCCmoawIDQ/ACDBK4UKBZysz91Zi75OCaKke7geASwuKN0Lq1CpbOCivttNNWKhamK+viFjEULP/8NvIrLXJubMGsscFJC+vDQZpNfPXMRrI5Q8Po6jV+Ivyt/5HLY4npJwi38iQJtD47WQjz8tVxPkF5oX79sVt39RpTyZR51Lqz4GKlV7UkFJgEtvTyOokmOUbLKAuYuwBU10X2Aje3n8PXuFi/FRnrLf0jIu2QCOidyf8iJ5pxNdNz+pQrW1oyy5Psef6p90lXYo7gfKnJlG1LyfYyNdFAqklqcqvO05Ev6Cq/Xe8KvjeABnnMsAQIXWO0YVAT+3NhpUqvfQmSQWmAqha/biPmvAxmS346rEeyz3FH450kCcpAEsooT89eDmAvOYtTcPUlwl7f153sq7KBVmccNKVNrmRycDM+2opkl5VDlqfvAGDw5WCggod2dMeEFlpGCmmQR5o/6u3ygG1pkO4NZ2CsLIeQyNP+Co53dLfCJAwygGIMYKOqSYWyYsJltjCeiZ3H86SMu1VkqgJhkTRvrGgUvwNrQtmPJ0Qb2jGikL18TWm6Q3WksjLD3dy1rxIsb2f+C8OqSgVm982f82EeoW/VNZSA+dQ54wopWukII6k0dro2q3AHpcWU51PJ5wYwjmvuLpP3nCNW8cGk+V2W3YxfnxTjZB4b8Ou+dj2Y9M4YtGxzWcs
  template:
    metadata:
      name: jupyterhub-hub-env-vars
      namespace: jupyterhub
    type: stringData
