---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jupyterhub-keycloak-client
  namespace: jupyterhub
spec:
  encryptedData:
    client-secret: AgCdsGJAhvNJEfzwv/+xTz1/pna2GFB+HLT2T6dApTJ9ExchhQ8j27/MjWFbobbi7sRjeBhnxgj45C1vHSMkr/hv6rpcSvhollQtqllmIkZ2EBufXw/hjpQ/Om5tRV60eXjjJkMIffC4wAfVls13pDMi3Wb4Sy3byNHpmI5Zna91+0mhFXIK+8S8WC15AZf1RpglW5srp76tfTOTxmHYgn6jI0eq1wW1yO58nrp55StXuqsSFZlvne6048r9FEWcYHKj/QXnKDRISzrSlN94bPupn83wnHrxXbGSW+x2uPxX3xr8li5R86U0s23j0m0kuvP2VW/w9TBAHaL/knceQIGrNwvzbD/+77d5LSpLkf3k9mEx+xc03kKBtYWW4xM80XKgJCq+ufI7neoPVmZBWXcqu3Nuqp+qCfPCCWhlqioren8/5nS4lMGb1XEn5AvGS3cwK5jusfIgSt3o+D4doFdKCZ7RsSR4l55j0SD82CWc11V1YjgNHr/jRw5m0M1KRPjOhlgGLn8qXNqMLParu4v4ywbotZYhb+aVj5ozPfmqjcBD3nuNxyhyCt9edZhOzLFTZzjqwx0Lhw92Ulmest+RfMFi2wnbeHFZrXSLfUv19sFRXCSnBoiU4yLM1Te9moj3PrzSc9K+51SCXUCy8IFMM9dhe4FjXo5GZDoHECdKJy+HXxq9eigbQqaZ3lgwmnkqrdlPuB6wITSd/H1W+4JtiITLzuD6aWY=
  template:
    metadata:
      name: jupyterhub-keycloak-client
      namespace: jupyterhub
    type: stringData
