---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jupyterhub-hub-env-vars
  namespace: jupyterhub
spec:
  encryptedData:
    JPY_COOKIE_SECRET: AgDD55ufX0siLEo7014zNPrcLku7oqIfMF+oDOcBvaqvJ+93Dw++56QHtMJ9EqqRhBSAzJApyITq8R1HVDKLzu2VWPJz/0c0T7e0eUF3Tw9r6JuHOsSybHy9UoT8Z6kxUNaWhdt7vr/129Zy3nB+EzMHhtGLu6Bg6jwj9NyvtEwBj5bXE0K1t360UX5H+ZvLmOTDiHRoNXwTj8GlRu/4HmO0pTso9gDjI4vb1Puh7Z4h4YFI/wXLVlOuEYkwE2k8TlZ4CRRLJkNeXkDxtdaSAVBjX8o+8jF0eWAVhtS1xQcOVsjAckjy4R1POSqAK4vV+/pvtyNNC3dTNUg3ALPRjlq9u08ajALuR2SctghfKhRahOrcfoB5Tz6a0sQ3Y1Q25+EDR+1C6CLRIura/vrTyhJi1dsp/0361U26d1Ui1MHdX6EGxPQvJh+j9U/B4UxNBGHZAf3UzCqsVG0MeHFZNnnTIIAJgCKp3Z2eLGvFXovZIAvTKd1CUDUTWXWt4A1tBhesUZUPevdbTMYzNV1W9tPtYdJXgMbXLA7IgvxeFsps6bm6wXH1Zm4n1PG1s6H0liyDLcU2ynAHv4zxD6wds+H+6ksvXFTVZP1gbCAD9PznaX3D//DjxeREPMnjsV3zSx3XSVGUiOo3jMKOkCeJy7GTU01tv7URKpYD12F8oidUp/tG8sh60qNBTANs9lSqZFCM+micnU6ifAQIQPJiEpzgOAmmV/5hl5rqF5XmnT415FMoIbBm4P0uFM88ubGeytnMTdMR5Jo73TZF+KOerL6y
    JUPYTERHUB_CRYPT_KEY: AgBlrGDelbk/op5GcXlWm0C9J28oI7L4OqqxNySMuUlesTLMv6HN+lOfppMkvyV4xSKcu9cLDVN2W36cC5SrQr6EL3uStI5tsFOKQt7DARwkNrIvAn0Zey3/uQAImpLOT0iXNZlwjL4a6X351xgzGrQfZFjpP7LUlkf8frXQVGoeLr26i2v+EbEAIIiulILorepd+wO+5yo6Ef2ci8d3a36BB74aWOWw+xUoh7rxDBHnQCQZHC3quhUrTw4gSPDRrpIhWSjZqmVKgMAMET5wBFARuA/CfY4y6Yp50txoj6XVOm7sY+oQH3lhnitLCw0+RZO9XvzCSJL8QLb8yHJ+wahxbsAutZo2IevxPPx+/oBDWcXfAzc24TMeeG+Gx11K9kzTf+lRlLa19WxZh1Ygd5MogXqiqyWBgd2QNhL5RPdYSPj7G7LVaY1sFp4R4AeX4v+8JsGuNNceLsnK5VWSGWUTbTEr7+r1tEZrDV8zvdvKkA+ZGAWFp4xB8d46ktGOEN7fpDPYPBI+JP2Tyi/f3TEAY8kNuB2QPylsyjusFTU10bvvjwJLEAYJfyQI0iAkArDrxF5T0W33WeM4LhsChQqrh7z7F9RBT6jfSU5N+e5yJTDNP9/muDBpsQN3mX5A5xULYkfVBXGwqCsZx3yOAw8KrtdATVHeTzcysdnxNB/LoiswWeKLn/0MxpIjT5vus/8m5rpb+0b1wKVi8pJT/nm0xtjdzTIGd1efkcSDvyoT/2JTrk8lCmWgaRVZgR5ywexXiZWrLd0Xl6zVY+OgrYUN
  template:
    metadata:
      name: jupyterhub-hub-env-vars
      namespace: jupyterhub
    type: stringData
