apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: descheduler

# https://github.com/kubernetes-sigs/descheduler/blob/release-1.35/README.md

# resources:
# - https://github.com/kubernetes-sigs/descheduler/kubernetes/deployment?ref=release-1.35


helmCharts:
- name: descheduler
  namespace: descheduler
  releaseName: descheduler
  repo: https://kubernetes-sigs.github.io/descheduler
  valuesFile: values.yaml
  version: 0.35.1

