---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-arc-cyberchef-container
  namespace: github-arc-runners
spec:
  encryptedData:
    github_token: AgBpZQzDyMAPcbqQNY07vs7Qv5OacTAPgK3+XOTPCFC6SBL/4bEi9fdS76SnOc8HiOhEmuEScyeuMXTePRqZBwK8LD6g7emW7rRlWO3jUb7evZ+NGYaZSFWCjgQF08Y8AX0PMXYGReNlsnUlCw4NuzIeW/bEktSJd6K7n1GZyz9a2MIlJ3o0NASvZzyxm1jnM3l5tt3wsD5Qtnu6c+/QSh4a6TNq+wSnNKNVkJqdCSEbv39KEJBZfOgwoC2edn3rKpBZWiLoii+R7YVumot9FhOjj5fFPucg10IaVcsaYvVwovGPvHDM2Qh+svoyQU4rx/IEmuilC/Uru/G1KAufh9Fg5cJLqDR9XwPAW73ZIo3fBkHtcrnlz4tfi+1WY3GMi5qKcsbCR3k6CL3kx4tA3tPddRwtNyzu4G3m9E5/XZmeIcaKWrqvzA/rvoQRMKV9qaGBxvvL2fov42JMjr4UePRvmlFWf+x972siA9+jb4fsh9x/tzhMaqREGqggo8RW/rY/++jxysx8XvKX+ONQkFmF+TlfJ+E+zHjbFyU0mdBEan8cJFb+SyHJ9hR3JByFwmF7C1/RQRQyGBOIQYgkFAyxUDq3k9ASK7z7AzKHxZX+oe0a2rhXRqJEJ5JYEtFrOfMLxs7t7biy+SG4ZcPKZpyZb4zwBovMUk1Qab49A//cPx2CLQTvyRH+A447oFZTcHIRYdNAXJlHa4t77RctbnyS4+/oym7ekhW8IMZ4+GsMiLo2nHeENrlaBquSs6xgBiVL7n8xBAZlEGDz/HsswIEQAbgxPu8+0ryruwlfrEnqTV63SqlEdDGTzRoDv5Q=
  template:
    metadata:
      name: github-arc-cyberchef-container
      namespace: github-arc-runners
    type: stringData
