---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-arc-cyberchef-container
  namespace: github-arc-runners
spec:
  encryptedData:
    github_token: AgCYxffyjdBDNswjrAPdVkx+Brmm82jhX75lybtWjIJcf4JV/CjlsX9EHd+egb/h6n0wM2su8f+vWuveWaVEm8vQ3MoacH61OboGHiYgPYaPuawkqHUx3sMlXYVyB3MDJ+1CmxXCmOqOE6Ci+C/pV2f68C1mACHe6r3q29tIpZu9N7v2STjB1ENlnHs4yFT3FOOWyQ26ICgR2VmRMh4PY7lnLlZnusPnpUoMdANqbd3jKeJjijokrX1HZBPqRaqRfgN7/nA+b3zoCJFG2P3s+xPYg0vY8IrFWzM4f6jSeMzkdo/HZuf2I4aQyXUbhBK4VLO6winx5EyLIINgzePJlHCDu3ZhMwnz2+YtQcK78FHB/6ud4XADhTgrBEh9xU7zPc0xIxGHcNBJTHRLPe6Mxb6cds546fQ7tyQyPSxturTxg4YhYCszw0A3w+qn5PZ8SslfouMBvDrKkqCsBhMHrgH0FMsewYbRQD4UU/i9Rrgs1kDGwyPZWbXAzuR98rSUTPNw6MaGs+yN2tpfs8znuJpI0oKhH4CMUS75jp9fJt6lY1opLy19+GhBGXZhFLpHpZ1iIRmSRJz7dSeAG7+F6Q14IdbIKCKCsVRLTBm9kjDHVMxuAwkdo77tZuuLO5VjRKbRVz0OLRaHFBhjHEXOHmiXUddqqbHnW6off2Yz5uwxnnrw1nywOrucft3TVrTXiTs7KhAZ9Ts/lsuqx8JJ2uJFFakBXgq/8f2ib9scxTm6+XhhZhn0C2/3FLMHmHJqZ95jCqn9fJnc/6Ua69TIOfeQmw22xx8yj25oM1fLjq62urYwUjAdh0jbcCxaPqI=
  template:
    metadata:
      name: github-arc-cyberchef-container
      namespace: github-arc-runners
    type: stringData
