---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-arc-cyberchef-container
  namespace: github-arc-runners
spec:
  encryptedData:
    github_token: AgArSTo8i5traXpTqyY2Z5dRUdezzldI0NnylMMczV/KEOVdav+tYhQI5XrJO8N3bMMKwm6tKnUBb0G2eCvmanI8wu89VCzLYdZH2b+F0ZrXleJLtxog1ryTS2BYLeX9BCbdeYOLnNUtdTrXumcHk6t23Tpv2K8NpTFXgRJFJ9fC0STXIdxYH4WwuoMptcYMLThwzjKBMIZEl/LdGseczzZ/Qa1LJFT+dtjDAXGsIDSuV5mL8Dy+kIqlKms55SKrH5NjFTwdySxVHvN3ewR4Zv4vp/kgNP0Nt1GiX6ZsCcR37reJvF1pVU8haWDxAd5/dgYtqdUrsTHbzcq+YYh8mRbnPi17AzDhptZftbLCbUjcLrEsoBLvWlaQtcmASHRYsVj5kAidkvv4G69y6OaM7Nw6I7TPwInn92GpVickkc3bPR1Jh4naeHRzm/heagM7/K5NGvdoEGT6MBZdxBsNVuDll2W0roM7VG+FPFFHe6NLCIiEqRRZQwf+83UHZQhHNlnxhDcm1JpRB72mstG90Atjy95Uk/Lk3559kT49e8D0UjmQNsZP/kPhB0/SXcNqqq7iMMBfmlSJKrWxwUvLkLUlLVWKIXohnALYmb5lCHp3OAtu2IiWjxVnmEmzAY/ntwFvj6+nOrKOWXLb+WF5YSgtW3bEC216fzeLgOH9tXI6FfRtqTN7E8YwAH7boGPBifm/aMBFfwmOc1zxR4DgbwfZla64U7L+4uKdrhA1D7gwOjJhdmiysDPnb6FBX2X7UrrOSzr7TuGtRw1q60/Qwu0+bRHdwTU8q1Khtv6xE5xthiHzvvlaSHnWknlE9s0=
  template:
    metadata:
      name: github-arc-cyberchef-container
      namespace: github-arc-runners
    type: stringData
