apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: nifi-cluster
spec:
  clusterManager: kubernetes

  externalServices:
  - name: nifi-cluster
    spec:
      type: ClusterIP
      portConfigs:
      - port: 8443
        internalListenerName: https

  listenersConfig:
    internalListeners:
    - type: https
      name: https
      containerPort: 8443
    - type: cluster
      name: cluster
      containerPort: 6007
    - type: s2s
      name: s2s
      containerPort: 10000
    # - type: prometheus
    #   name: prometheus
    #   containerPort: 9090
    - type: load-balance
      name: load-balance
      containerPort: 6342
    sslSecrets:
      create: true
      tlsSecretName: nifi-cluster-tls

  readOnlyConfig:
    bootstrapProperties:
      nifiJvmMemory: 4g
      overrideSecretConfig:
        data: bootstrap.nifi.properties
        name: nifi-cluster-override
        namespace: nifi

    nifiProperties:
      overrideConfigs: |
        nifi.ui.banner.text=Welcome to NiFi!

        nifi.security.user.oidc.additional.scopes=offline_access
        nifi.security.user.oidc.claim.groups=client_roles
        nifi.security.user.oidc.claim.identifying.user=preferred_username
        nifi.security.user.oidc.client.id=nifi-cluster
        nifi.security.user.oidc.discovery.url=https://keycloak.apps.iaas.wcooke.me/realms/iaas/.well-known/openid-configuration
        nifi.security.identity.mapping.pattern.dn=CN=([^,]*)(?:, (?:O|OU)=.*)?
        nifi.security.identity.mapping.transform.dn=NONE
        nifi.security.identity.mapping.value.dn=$1
      overrideSecretConfig:
        data: nifi.properties
        name: nifi-cluster-override
        namespace: nifi
      tlsAutoReload:
        enabled: true
      webProxyHosts:
      - nifi-cluster.apps.iaas.wcooke.me

  # singleUserConfiguration:
  #   enabled: true
  #   authorizerEnabled: true
  #   secretRef:
  #     name: nifi-cluster-credentials
  #     namespace: nifi
  #   secretKeys:
  #     username: username
  #     password: password

  managedAdminUsers:
  - identity: nifi-cluster.nifi-admin
    name: nifi-cluster.nifi-admin
  - identity: nifi-admin
    name: nifi-admin

  # https://konpyutaika.github.io/nifikop/docs/3_manage_nifi/1_manage_clusters/1_deploy_cluster/2_nodes_configuration
  nodeConfigGroups:
    default_group:
      # provenanceStorage allow to specify the maximum amount of data provenance information to store at a time
      # https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#write-ahead-provenance-repository-properties
      provenanceStorage: "10 GB"
      #RunAsUser define the id of the user to run in the Nifi image
      runAsUser: 1000
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: nifi-cluster
      # resourceRequirements works exactly like Container resources, the user can specify the limit and the requests
      # through this property
      # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
      resourcesRequirements:
        limits:
          cpu: "4"
          memory: 8Gi
        requests:
          cpu: "2"
          memory: 8Gi
      # Set this to true if the instance is a node in a cluster.
      # https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#basic-cluster-setup
      isNode: true
      # Additionnal metadata to merge to the pod associated
      # podMetadata:
      #   annotations:
      #     node-annotation: "node-annotation-value"
      #   labels:
      #     node-label: "node-label-value"
      # Docker image used by the operator to create the node associated
      # https://hub.docker.com/r/apache/nifi/
      image: "apache/nifi:2.12.0"
      # nodeAffinity can be specified, operator populates this value if new pvc added later to node
      # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity
      # nodeAffinity:
      # imagePullPolicy define the pull policy for NiFi cluster docker image
      # imagePullPolicy: IfNotPresent
      # priorityClassName define the name of the priority class to be applied to these nodes
      # priorityClassName: "example-priority-class-name"

      externalVolumeConfigs:
      - mountPath: /opt/nifi/nifi-current/assets
        name: assets
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: cyclops-fs
      - mountPath: /opt/nifi/nifi-current/connector_assets
        name: connector-assets
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: cyclops-fs
      - mountPath: /opt/nifi/nifi-current/nar_repository
        name: nar-repository
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: cyclops-fs
      - mountPath: /opt/nifi/nifi-current/work
        name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
              storageClassName: cyclops-fs
      - mountPath: /opt/nifi/nifi-current/keycloak-truststore
        name: keycloak-truststore
        secret:
          secretName: nifi-cluster-keycloak-cert
      # - name: example-volume
      #   mountPath: "/opt/nifi/example"
      #   secret:
      #     secretName: "raw-controller"

      storageConfigs:
      - mountPath: /opt/nifi/nifi-current/logs
        name: logs
        reclaimPolicy: Delete
        pvcSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              # storage: 100Gi
              storage: 10Gi
          storageClassName: cyclops-fs
      - mountPath: /opt/nifi/data
        name: data
        reclaimPolicy: Delete
        pvcSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              # storage: 50Gi
              storage: 5Gi
          storageClassName: cyclops-fs
      - mountPath: /opt/nifi/extensions
        name: extensions-repository
        reclaimPolicy: Delete
        pvcSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: cyclops-fs
      - mountPath: /opt/nifi/flowfile_repository
        name: flowfile-repository
        reclaimPolicy: Delete
        pvcSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              # storage: 100Gi
              storage: 10Gi
          storageClassName: cyclops-fs
      - mountPath: /opt/nifi/nifi-current/conf
        name: conf
        reclaimPolicy: Delete
        pvcSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: cyclops-fs
      - mountPath: /opt/nifi/content_repository
        name: content-repository
        reclaimPolicy: Delete
        pvcSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              # storage: 500Gi
              storage: 50Gi
          storageClassName: cyclops-fs
      - mountPath: /opt/nifi/provenance_repository
        name: provenance-repository
        reclaimPolicy: Delete
        pvcSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              # storage: 500Gi
              storage: 50Gi
          storageClassName: cyclops-fs

  nodes:
  - id: 1
    nodeConfigGroup: default_group
  - id: 2
    nodeConfigGroup: default_group
  # - id: 3
  #   nodeConfigGroup: default_group

  service:
    headlessEnabled: true

  sidecarConfigs:
  - args:
    - tail
    - -n+1
    - -F
    - /var/log/nifi-app.log
    image: busybox:latest
    name: app-log
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
    volumeMounts:
    - mountPath: /var/log
      name: logs
  - args:
    - tail
    - -n+1
    - -F
    - /var/log/nifi-bootstrap.log
    image: busybox:latest
    name: bootstrap-log
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
    volumeMounts:
    - mountPath: /var/log
      name: logs
  - args:
    - tail
    - -n+1
    - -F
    - /var/log/nifi-user.log
    image: busybox:latest
    name: user-log
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
    volumeMounts:
    - mountPath: /var/log
      name: logs
