apiVersion: nifi.konpyutaika.com/v1
kind: NifiUserGroup
metadata:
  name: nifi-cluster-admin
spec:
  clusterRef:
    name: nifi-cluster
    namespace: nifi
  # usersRef:
  # - name: nifi-cluster.nifi-admin
  #   namespace: nifi
  accessPolicies:
  - type: global
    action: write
    resource: /controller
  - type: global
    action: write
    resource: /counters
  - type: global
    action: write
    resource: /flow
  - type: global
    action: write
    resource: /parameter-contexts
  - type: global
    action: write
    resource: /policies
  - type: global
    action: write
    resource: /provenance
  - type: global
    action: write
    resource: /proxy
  - type: global
    action: write
    resource: /restricted-components
  - type: global
    action: write
    resource: /site-to-site
  - type: global
    action: write
    resource: /system
  - type: global
    action: write
    resource: /tenants
