# https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set-controller/values.yaml

flags:
  excludeLabelPropagationPrefixes:
    - argocd.argoproj.io/tracking-id
  logLevel: info
  logFormat: json
  runnerMaxConcurrentReconciles: 2

metrics:
  controllerManagerAddr: ":8080"
  listenerAddr: ":8080"
  listenerEndpoint: /metrics

replicaCount: 2

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
