---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kiali-grafana
  namespace: istio-system
spec:
  encryptedData:
    password: AgB5hXQ/FiihoJimAH/etRfEhT6MHJp0z7hB6YLoHYdozdYRsYQafuzifJtnMAMVQnon4RDA4gwMPnhZ49HcxTxqxRAyHnVozmAvfj2bO1o6Hyg2a57DzLIXOusCH+zv67mJv5ldn1ajR8GmqVNUYDLESKeyGbME9JAaTvgNfaxBs5IsldTbEfwgc9C8owCKw0lElArfaxPXmzQHEoZugMwMkxZOcHZj6gibIVEypb6fw+gKERMeADT7WiUtY5VanIQFY4Cm1NHvBIh03UttmwaWP0fZ6z1uwO8BFGR/jP7+hPMIdkTaaHfIvmwKMipU0a1a72oX6Y7uhhI/O9f19CsrNgfxlMK72wLJepJtw9feBR6IfaK2ORu+qWL4Flnp+j6IyNr7lO7cBUfhen0mGwrDo9gIqMZirn9utvFdihCYgLSL/htqhjAD25qyGlW/cfyc6nlXjyr3I0lVOPKVjBmUGXJuQV1eT1wPZNGfSFyYxUwiggsTbUIcfdw2qYFqzo9K0DBug79HzhtNlwf3w3Zs5b1sFq9wC7c3Dl74vMb9N4Ik3NkugMg06emYD83wrD2IsOhugkATB4qocP723xMFfWCkGRXWiRCIiE9o4F97Z17Ni86anPKH3RjmqnftO1+CzPKjjVJhBEbU7pCjHxL2zvOaSukmfjNgGYpuJ+685Clrc9lzGHM16uYD4AVWq7gBOZX5AdvJBNSuAefdyhqDEV0U04T9
  template:
    metadata:
      name: kiali-grafana
      namespace: istio-system
    type: stringData
