---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kiali-grafana
  namespace: istio-system
spec:
  encryptedData:
    password: AgCJtouBgHAP0a10kJsbZGMmxDhQrQxSRbSIkvJcMDfNKL2eSI8nFs1OCT/E6X6yhlNoD+o4S56JCSusjQAN2oAhxqmbWkxXzMlW4NPqK8ZFS9vEaE+mP4O4t6PK8jV6PhTh/9sdgHMku10nHTWaFLYYbRXaLv82EeRNzU1TQbAeGYKr0Cgw+H9qEn4MFA6Oh5KyUdTDBcHhKmKXH5OxpaQKcoKjCZvL+cZjyplX+jqFOydxB/emCj4rUGIaCY/IolkK8jgP6MG5tQT6lgBzPXwFdwQqQpZGvu00mucdmMU9MtyuLeA7G7XrDdbSa6bTgROFRzp1XpJnw4cSt0PotLAbYIJigFTiSRaoWajOHKvCokwSD9Cnul6GqhBQ3mxuCLavF5tPrGSMGi1Ci1tG7kZKY4pIjLoM8t/XUh+VBplTqTvKPFOFDpKeZQAeYr2j6idB86D8Rh3vPLUVnIRKPFxGruf/ayadgpMSdxRwY0vFPMlmI2+9FDsL1pr3cf8u3dyb51lXQxiVUK8LPJh7i/xpSti5E42skrYqOL/pKOePl3G1X/E0xdrIvKr7K0eml0OQXyPVuUC3xYYsMYIm/X+gQWRm/U+X3GM1Z8mJBVimKWnhAxATikrKURFfuCpYPSR4lXNimqGmEPQO5zmM/gmNVJBev3UXCaGPeSyqu6tDXQNSzEuE5XwMHtstvssjDCP0yCom5DbHz1Mq5s9HE1DT5wTuN7Bq
  template:
    metadata:
      name: kiali-grafana
      namespace: istio-system
    type: stringData
