---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kiali
  namespace: istio-system
spec:
  encryptedData:
    oidc-secret: AgCMVMuoBt8lOkqG42cP81uqEicae9GqqYR1e39iTOegXpYIg/3qcjxuwsJgX2NVMrw+DEMj48Y2MYQ0v//GPLVKAGzFTsVKE7G+TVfjBEOzP1bouKWe0HHWCJeZ1t+JDR1mG0QUEAKVNVkJsrfIIEUKiA2A/cNtGrw4oOdIiw25COVMuHqb/ffQRIGxN1pIeMLuOfs+jzDNzICCvKmyKw9qeZVTreoEffxPLKh3x8Srveu5IcsqvMKztCtb4vTFTVI6DJDLyEmH3zl5wezwYV7BnzUKPim8w2X4CNhHGIpNyckb4oVPH777GtNhxf8hDyZXxXaP45eiDzthn6nSCeklVwWUJqEamzrLwBPtcIhGUAHqeuItpnIdDzepQHOFYvn0EiT2v8wYunZEBFOjkq+60xAQBJN4Se7/j7yU7CUgHxBYp0LBZPxeW7eRYuXGW2p62zepx4NZ1Hn6IuOJ6lEKyICU+sUlJR/GMrfalVkcqH/0UDkslfAsSrwGYEMhk2k3D7tkwBfoAvoL6yGyJjKeGdIfaTgf76xylOtMEJdvvd7n62iHLSVF9V93flGki0H2msR/7DGSio+ndFPl3JOM6TmoI878JxGtSXgX7tOhUxTR7vNC8gvy/ph7/LO9bE1k31MOiSLYVtMMqUEJTaAqoPMKafWu+coRHWTT5wZO0dX4KvDMHVpXam4nCIejfm6f+LZsxMbj3rgjpnWSzcVNq0RyL6EH1I3Zh4NL6yFdWg==
  template:
    metadata:
      name: kiali
      namespace: istio-system
    type: stringData
