---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kiali
  namespace: istio-system
spec:
  encryptedData:
    oidc-secret: AgBSk3cV7fG6aqbcB38JXrFEWfqcu3RDv5PmHdghcnvk27Jik939eXdueq9EfxDflKyOXgs5pypEE7lh1RGwrNKzsrYBZd+cdNgI8ER7npyEOED3du9Tyo8anrr0R5XCn7gA7JRStH/NeLwvHiRLtHUTTl1ZJVyaSF/waCQ1+VYEkuq0wn9RIafy9PlTbUaqlErSOJgqhfrVS4QDXGDiIHoIfuS7Ez26nwtLwkolkDRKRkyeg+HZLqwYG0fJFRYeDJlHkLXKVjPcfu7sCDBocJmDFFM42eYHUAMopsPJ1rqsiMS7JTpUJI2WhrBIiT6bCNZCF6L2PA21ZHMwsPqX0QumOuW3JnQUE8EEA50vY7IR4+5NJEAeb3FwccuNFZLRTNDs8pOs/c8ILwSn5gcawni4njFjTgEsRpx8Ia5H/3o2S235JwyZCoFDF8Y3GDhZSiuhNleTSgZPNg0VJSb7I9HSjrVSg+mMsTgXyi5gKYRPWwyIdC7yD/oKtemm/EDeayVz/90KxfO+LidSmRKon2CGOMdFVRK5LjZ6HVjwZsVZR7cPaYOaZI2g30BITR2Cfno6j6vV9o+a15FVNXwFyBfX5rD9nOiCYc6l+Lt1CKhLeRB/kqmdGcO0ClMgIiRi50lksIp2lnwVTliX9Mf7PtRkWG29nPEwN4gp80kHPNisDCsSOEt+JUmK+YwfrI93ASAj6rMKViH0uBgiXaCVqGrVby5yq2bysrtrHf3WfMpnpQ==
  template:
    metadata:
      name: kiali
      namespace: istio-system
    type: stringData
