---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kiali-grafana
  namespace: istio-system
spec:
  encryptedData:
    password: AgDwlnq4CVcbGkO/OKRCm96BD8FxFjTy20RmXjLqBahy+vY/5Or6fHHttzUu73f4lAzPJi4cdXpxFF/Envg93K66uy8181E1kNwH1UrPYEsuOYiwYs2cWVyUSEzJIgYZwyjs5J3s6OyI0NuZ2Dz2DslAqlhBHpAqSHvPcZR3qgtJEZFWcdi1md44ddBopawOi3SOZf2dPCcMBqYMZeW86UhyER80qx0C0iVmkMocma/BJwrbIwwpxEeso7gIekjwPSHqElqp1StfkQE7Hiqbo5lLXfCzpfNF4dZ98WKo5g7OisAf7yYI2vhEc5YWchEb1X2LnhFfsPosn53neUnlPC+/KKRFbz5ZFGvEqSbnmWks4w9VMTL3Hv/Je4rog6tSOfKfgRlhECVZPxPw715EmTa01iPj2t7b0uFcLC/4OG1g1zOHalGkaD9IdIlwTZ9oK8BLUiHAgDTAlE8WjZJ2pDE/fq/4/Dvu2tupY6tJXlnfS4GwbMlb7bUoPc24N9hpebLzO2VEIn5REGT4cjWL3pDHHIgKuJbQcL8xP/mjKzhHC65EmC8VvPaKnWsyYnvRc4bqnrnIMLXJTbSbNRpvIYXSzt/4+fkxNVQ6xnGIP7XCBQEDjSkvsKcoRV7UnLCGlxhjLhv3w3RCKjtAFwmXAmno9G8tLg3gwmKEsWJ4+jcdZUVkqYn7wAKnumrVl1+/6WNzMi7vCpVVE7wJzV201nMMQs0BLDof
  template:
    metadata:
      name: kiali-grafana
      namespace: istio-system
    type: stringData
