---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kiali
  namespace: istio-system
spec:
  encryptedData:
    oidc-secret: AgCHXIkZeLJURhH/Sv8OUHz38AzpN2SVVmAjfMg7hnVelzb+gEmsvbe+GWrmfsHSyQk0nhuIFKI+TCtNl6FrhX7V9U/Ft2wW9CmxBXmdwrzfSMVpLXZteFvkEQlg6G7vGOR73aPOqHl5I9RpV/ckcRS9O2NAnhxkvXZgyud1zz4MD14RxaCaf29idktmk0vrgkIL+17+LngX4na/JRtyelfQmkG1ym8jHMn/ba7/8sq0sqRsCKip5HY1WgkxE+3/PgvaoTLTAWx1L/OVCtbssVKJyAHrhL6VgSwkZy7vH3WIPRJd/pEXnRKXE5ln575HzRpTxQQEaOIDUGaHzYd+eIQDt+V+qfFXkdpMli/Pfk4NDmI8vnsHpuVOZyrmK8Shd5FYC8XxY9tSXGmd6vkBoB/jRqzg9iN5KTtOzzM+wB4MV755pLOOIoIS04mQ/drVUyzodJ6/FbLG4fnZF5zxbLw69Ssdin8dd5+yhdBNOJRCKzJKCvd6CGA7NhxiYVxfIB+bE82I1EsIIl1MZ5BUxF+F/VCyRBZYPb/OaRS9ZdmPCqIzXSXOJyJkSU8EbDMR3w3xW7hLwIc9myHp3pVPfIXBs2GGxLv5eV7BGWuGj4jHf6cxfBEppbT6pL2+/2kOTFS/DMRcAUlk/damjOyqzuc3GTRitepTV6TdU7Ie6bEgcUY5V43E93+AVg87W1Fz0puGxSSYZ5N0GXiqML8Sr+23uCI0MXtsbw7gPRcDW5z7sg==
  template:
    metadata:
      name: kiali
      namespace: istio-system
    type: stringData
