apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: strimzi
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: strimzi
  project: core
  revisionHistoryLimit: 0
  sources:
  - chart: strimzi-kafka-operator
    helm:
      skipCrds: false
      valueFiles:
      - $config/apps/strimzi/values.yaml
    repoURL: quay.io/strimzi-helm
    targetRevision: 1.1.0
  - ref: config
    repoURL: git@github.com:cookew/iaas-cyclops.git
    targetRevision: main
  - kustomize: {}
    path: apps/strimzi
    repoURL: git@github.com:cookew/iaas-cyclops.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=false
    - ServerSideApply=true
