---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-keycloak-client
  namespace: pulp
spec:
  encryptedData:
    client-secret: AgBzjaBXnqj6lmFRzaYmGWzyJ3UMraMBbMud+ifLStOjCW4Ja1uTbxr4tordw6teTuHzUE5QJ2jTjFONIowcf+Z2BV/6jTZ3L7zTeHG5KM1Q+ibgAtW3iKIv3RhjFUaGcV2fNTZ1fg/tL2utXAcVdfdzj7GPzFP8DqUfWNRVx5WEx7RNHEOmAoq6qXMhv1rsz7kphmKPsgbAFPABeACE9Ng42niIDl70mGDk7kGi9BEYfnS0SjAT2bC9rJkzzWL+CLu9UiRz5SBAYPmICz1js2kbMPabybTIzxGNKPuTBJylQS9yz5R12B/0p5DejGP7paOamjwrRuFUmodliQEkHSmSFVimJsyyobqNyrSbYTlFf3oklF0ly3lZVkxel3maWhoCxHx6Wj6lelt68XyqaddJcGvCBs7XiI+DAd1kdWatGVVE01pdfvH6XVBvq+6AJ0CaLIvJdyNxq+m/xUWApdKu3TAALUkkAWg4kpdEY/gu/C7hfmdzkjbH25LFuwrt/9Q9TxEqRGI8g4piI2Uc3uzTKlVGpdTmk/WBbgBrut1zTj+eaudQTNqa137Q16dgnw9AS61jrkROvEjNf4gdRb8tg32fqUIEnIhMY2BM/ealvROelTUH0vzGzJnUvbCqivrVbDYxVJEeou7MmtYT62kA9cmlrSyGDLO3eWrCjwPMHIoX/ZIFka3iBPygLFTZGToEQEVlcRIwOum/+pMiX4rXvGI0DI70FzSAN9K9h8vHB2rbg/pXWnA7AGslkg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/patch: "true"
      labels:
        app.kubernetes.io/name: pulp-keycloak-client
        app.kubernetes.io/part-of: pulp
      name: pulp-keycloak-client
      namespace: pulp
    type: stringData
