---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-pg-cluster-password
  namespace: pulp
spec:
  encryptedData:
    password: AgCzMZbf/6E9/aPofQEIZDwCG/uDggZTsqEwd8jgix3KW7tEVyWHWP2VQ4N0pz0xcQaajrBRfUajwENw3jmPvfwsPjN/7HDcws0D61SCjVT8bX5A7s6e6X1p63C5E7dCQtnyBrmFu4ieu5yvVTFP8GAPSO0Yb0lFcoLwYhsu/TAIvxVUjI/KMnt8p/PXhx7OC8pa0dVOuk6P7GcHjxhiz1/HMT0eXvcva1XXPCvXYPppDSCcTjtjHY1cMBM0313STq+3EzookbTLyVeIXFBLDbbqrpXlIA6MnT+Yha6i/a+6AMIMGOeSGLk0fVhFETB3/T5mtOu/XwxO9Y4KW1yVDmfd2jCRCIM4aTpsbrNQqJ3skdRM7z9h6AuYiAKLKJQkKlCaA/D0z1i1RfKLX4fgZSnWNfB5Htbk/oSCTBW5LMMD9O6J+z585EaO+umYEVnPhgTnKZg0eC0/Io9ycqnveNMXK4Chmylyx2g9d0+VMwMyhGlQgmQCoE2jlAdIWu8taPB+KUpEU1F7SJZh7efAO1Lhjz+QbQhrwJbWxM9lpKVCkuhh9M8slz6yZlpK5UH2aGgtBVRp0n9vPyjW4hE1CjSdMUsRDgwxw54JdJqtIF6jMHFBvq6smN3S+x6/DkcOF1t3r9z7jvFy0+YunJsy+FLse9FbIyF6eaBMN587pwhnfVzLrrhzQ1GARP3XOSKY4j6nGwQK3LhMtGDuA+5WmL22iKr/bAkuLZupH/FW1CQDVlZlBGz/m3hjBoUfFg==
    username: AgAWjNxkNPfclagpS+BI4U8/qfRBYiYpUfKtk4hp4hDqKIyeZDiKiKrUol3iFFcbWO2/mELApIR1ayMBG8eP29TCAvr4IBm8zUJFd5TRPkkRy4bGIOmEYq698UluqhXNr+tkRH9zPtsSGGAxwcH6rGmfgYkdu2zehOYmWwQPeLSjJ5uhCpOo9Jue/URFDfGyT2j+8ivWkZDsbPzyqFPEY+p1VD9pdpzW4UuTGoYeo5T8g6eTxO0YZIKWa5RfFuTDBfgOFhLYxTauESp/X+NNtZQAEFZ4CpzyqBagqVoP5WlP6i/Xu+VXt+nzoBHdZW5WaDHnbbp8xURwuW2I3Bbx5pLtLLHcm0bSQj3WyqG+hn7JhscY7LfGCu+S0Go21F5fM8nUhFqiwMsHBQSRhEjN/lJJPKTfybHmhlbDbri3AC3guDZ01DNCUIqncHUEMnmk5k8NUv56j/XfxsMsnuBveMjCEunK5rR9GoL0zPH1zvWD4fyLEz739HomZiUKn74kdG2XtVDSOsGMQFuKJQVF4IYeZk88wxyrd2agVPqdyCxRRe7JwqY8jkOadgoatFBi5mRL/9sC87PcDg9fCnL+7kE/urH0H5Y0lRMbc9RJNZf600Tz0Mb6ebnoYReGW8GH3sWZvMd7g4l4GfXuZ14lksrwKSYTIMMwMSkf2it5ri9F5hZP+9hoUjGvZfMoEdtkS6mZYE/5
  template:
    metadata:
      name: pulp-pg-cluster-password
      namespace: pulp
    type: stringData
