---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-admin-password
  namespace: pulp
spec:
  encryptedData:
    password: AgBF2bPiYfBpCkaWEFUZCCmobzmXYgPAcoawHbYuODl9w7Fv/hMgX2h5wtarzoOiGy+9YoAHexVXM/IdBwN8UObM/R1k2ovIGbt4zBieqN9k5rb2gQncCoH78RjA/+UAnas57QHMwUV0giDVh2eLM5I0b5YW+QNyV0Ztq4ONoE9zthbUoCyDKa1AU4iPOT4Yo02NASBpw9MXe4TGRJl5HC8O0N2XnhqV6FsMqetkeVePPjmf2vSDgnIZT1OTeLwYKIpbXIpG9P+C3ec5lJeB1jCr7Ri/SUvn1fkcCwAkudmVniMHgpnBbanjmu73PDYTVHvBb9TYZlmz0TH9mpiyRqsGjKhA8qv+EPK8irv+58EEjsgVRx/Uu+qxZDTXpj0FOA6mf83RcRXo8lJ3W3NiH8SSPOtMIpVdWV1oA+vVoPZTRW+QjgLCe8+p8K1rmzK9joMIIITx50uSjMcgVMXQEt09oqCeDo+gUxdVEQ9076KZelIWSy2I9CbJLq+fHbsKt0thIsZsxkdBH/TKQ2u4tJ9PGSrts9/ZQ22sI9GHjpNB3rsO+S2m9DmVtQoS5Kkzv9kDlvXVyNNTsry+pYp85ouAg6YsSUn0j7vrVdT9cL+MbdIp7HyC/yZq+6n3VWsYWhLssiefbgQvgUDVz+XiMBoi3Pon1mCYRcU7YEQUvrPwRmGYr54mDiTfQmKVp/9ftBZgaVwBQRbSpL14E06XrUCiggBgxn0W0gGZshuyKlsIvuZlteXkOqTZzbq76A==
  template:
    metadata:
      name: pulp-admin-password
      namespace: pulp
    type: stringData
