---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-db-fields-encryption
  namespace: pulp
spec:
  encryptedData:
    database_fields.symmetric.key: AgCUyizt5YpN9UmEECNTYIha0i+scx0ejGwcADF5dPus1cRDuOvb9W/tE7f/aqlTmdYhFKDMpwc5UsbDmTUZcSK18rJ/GlK95zUmmbl4FVYtjQ+eeaFIkzqWUFadxdamg6pIb2szTRu5rpII4fQUYxHtkFNbv4a5C1fTwELWurhztwKrSMvqh94lRCWnNL7HluYRrennEhWNaFBP0gv7+1fb/hgLvm8h4A9h0LP5nrgM5aiqPLnfviyLLIytgSenntmpjweR6Trio5jQD5VF+hyh8eZSb1MkJEvpBHFdEC4W7S1X8+gG4sL9X/vgBYH/+NxHA5kwwECiHg+CI4oii6z3Y8rWuup0Dfcefwdonoe3TiP6vwJVYIpe9BX4mPYdN9vNBOc1bkjRE3r0gBkO3B3A81k8H/CcRUhQ6UNwQxmyaIGqkJX4vbiGrxAIYzVNtfhqeJv1BVprhACGF2mMxHEFS/+EnAdQWKwyhFOtKyjB2nuNCVgxjLNiRCknE07gA+ENnJYJxh5ng1lU7YP4QOCoht1fgaCEWJ+kaD5jUAmRv2vkMmWye4x/WYqPIVxf7+eWV9RacD7lZeoSPbmypKHnR4ShDDgVok6ewkt/NuqlU5a5DTolyTASv2+zav82+PoZSRR2qXHAd9nUY9i10AGefXU+U0oEXgxKBMNLUEF76/vXWSRvOZjGJYo0lLNguXqLEr81OO3GfjPBuA66nx9Gp03K5uFCR1Tzc+SLC0fv/BZQIeNy1WejL8kXmg==
  template:
    metadata:
      name: pulp-db-fields-encryption
      namespace: pulp
    type: stringData
