---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-admin-password
  namespace: pulp
spec:
  encryptedData:
    password: AgAvcwq8oNqJkdu6xVSdJR2GMaqzUZHcDo59y+3D2jt1olGeepehNTyRHFcuXmCINd7wZb3v9wkUBC6YA6DMveS4IInsPZTZWLXWnbT73bbrY0AYqVAZuDgn6jfN31o45u29/79ACS2kfa2wHLytUTo1+vl1bMuEVDEPm26XfZGGdazMDCMZmdRn6j0DVhYq3caRQqREHgSwzaTYinbUmOCZBRANWkFX/czNhqc5NOm/U09wjpv7LBC4WnrBPQe2OGy5EhqXDrzG3IUkZ8PKeF9awFD+/mqbdBjqbHUWMt0ylFFRUfngsm7hcVpHtIDM/PsftenuosfeTE6wxB3AvKAwd0y049jA8GXHOSaHT6RbTrBEVcKbNYvkENNCTIeshcJKnSrtbhMKwQFyFYNZjXcqAKCbsdmRLp6LbsPSAu9zym88foHrlf3RkCGiEvUnslS5UxT0UBYztJgG1sSCGabIQsR6yYIkcsESjEUYUmUEqs22aRCKT6F6hDQlcOVTaj08BMhHhFcx6qVEavIzUswCU8v05pOxJTa18RpmyRVa+os+LZCJQFu3GNjL4iW6y29W9jaNkc/8KjLoyO/dXsYKVFPTwutFbe2KYMk/cVgk/frrotTdN7RXnaAkV7YCn0tnGd/LuJG8WM3nhYILY14hiqrdAsjt7B+Vy9YG16RR3gdM3dawIktCnERaJMnlBkKczkfQzeUbaLDM9PYplBF6upeEaII98pfiY08VyXoOnPiBWYsT2LbjdOkJ+A==
  template:
    metadata:
      name: pulp-admin-password
      namespace: pulp
    type: stringData
