---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-keycloak-client
  namespace: pulp
spec:
  encryptedData:
    client-secret: AgBuUfnM3esQitTC/o6+WPeF27Jc+BY/yn9LJW2d+bsjx71M5/K2AreBk9tfpV49lTK1Q9FxWLPe/tG7WKM2f9d4edar/ZkxzfLpErkuNDZd7u0/Qy0KY2NIv9kwowDQfrZsCDt4JUrjMnBau2VcTAHkNME4dTQvHyq1qpF2kA99BFBTjgwbHhr1ClkhrA8d4fvdaJVFfVDvhbjg+pP8vzRyM0j2YmBjBUUN2aVauE+EfksJAWCCbRgOwDNW4M/KhLhd/yHpTZDN1St9FX3/p8z4euIT8N/7nJA4zON24e7ARApgwN2GZEuTyBkjvfXfngRSA78Vc87hUgEKg1eFDxiAvFTjP7vtN4deEFhzeFk8qTH0dkugxuhheyBFFY1mfd0n+6kXBPag97RiIUeavWMPrmWMmqZspCos1Yc+FuNHcwT7juYlucbrGAFmyDWla6R7djKNk4oIrSsrASBCrjfmBeyy5IDEnqCN2TNMGjgTT49bKntuPqnNUI2Y3xsYdm65+lgpVuLm1t88KA/IiOJuvcnTuBMXt7V6EHWN8snvrHg1Dk2A4vbC7qpguSfLLma4C2eoK0vx30YkUZVd/Sy5OttbF/F6SUNYm+n9tb5usiLA6ehr5mD5HUN0q6P3YoLBIURmRvH4C9mf0f9amAU9lt+/kxt92uzMtIPMwwcVfk2CiLakPcQ+6/yb5Uocl1maoGpiC5vT7sL+GapsmZ2ksZnXBTpaxNeqqnXXdtvEt/BSu3zpRhzC7XQMUw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/patch: "true"
      labels:
        app.kubernetes.io/name: pulp-keycloak-client
        app.kubernetes.io/part-of: pulp
      name: pulp-keycloak-client
      namespace: pulp
    type: stringData
