---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-pg-cluster-password
  namespace: pulp
spec:
  encryptedData:
    password: AgAvlwa8zBOwgTjoDvoXFXKRJSocJDeUqsPuTgTuBWGJtJ7K4T32od8Sj7r43reio6Xf7+njTOFBQv+/9/lgb/BACdeOqj3WPUbJ8FJiDPu4Lj2PXAPYx2HzpxZD+pbvfUCHwQmMA6Vh4jvFlqie17VHGssqeVYIfok4EkyRSVY4RD/3jWcb2dNqMlGnbzIFUMhru6l7x1Qs+FVaqIGwFR1FzCR5YYat2RAVIrCulVzKsM+BmWl9mLx6D+cosDo0hNBsmDVCdtMS+U4c5i6F6Twoa++7NDbhIJ854miTp58i35QLpgYzYvEaqdN1BSX+p9Mc/ZBcl+UrdhjCvQuvuwI0kJlRJqKaH60gQ4yyI58oO+z2G3Saw1dDr3jhZlHA+fnDyT2UmgcB9NUCn3NW+gKin4I3wUpS/wazQ1op3V+TGUC/p/UYT6l9BS+ZmskVaehTFprTDTJ8DTyO+aV588Wtcv4NcToN/vhNZHEzXReNkeCR5P5zeQNJPvCxAl7qCupkBI4omQ79rn9V3dLa+HKbtsMBlvBezy0BZ1o6y0is9INJ/WAhobN3k+ctLv3+9bDx23vvJWrApfoUy8En1Hm10IQgHUqG1e00AQfu5v9Qej0ny6yuTpmDWjGiliHKKN1kGnNTtd7tHegfgzY0+bSijVIlUk5MK2OCBmoeLjtZDDd0DCQeecWegq5NmLxks85XGtQoGD6HYSTtOiD0NdDE3vMrlfumAm8X1wHLf4WNPzXGXtxc1tnAiI53Ng==
    username: AgCWoms2ztV5UuhgsGJDySW3m69FSXvxgZ2DG06dUdtJrikVXBNCYRnbi9AL0vfb4bfxvlyU6BrpSs2/c6dffsvzOyQRUGeVDA/x+APMlcX5n0stJ2RKWqSw7iFAm1rO1+fKh1+ShOi/RQDYcaMEebPGNJQ7CPRmhvdMcI++UWps02IYkithVBtgcxCtNXLopz7g/PBr51huJlZHhIFfx9HVgMfsIqn2SjYBoBbaSaiG2+De7S6QjCwRCEmmjPHfhPLY5V3icjRMj5x3gAI7m6rZ4e6H7veqWdryQOQTsssoXy86uqvzSA/01NOwmRyXFd7XHFdkRqTaOMPcccIgY5SeBjySe9MpOXqVqrRosrsMQoUPTompDo5iGVDUqU4VDnjMytPoh5P/zbC/TDbV2h+Y2oHB0H62R+oG3SygEX6iOIgSDK/aO6Q5nXGAObc3wATrajxTXzEb2PtZQ5JbSYN4Znrqnoogo442eFJFFlLVZnhCaEruauOlczs/Tx7iB/QbS9OTWQr5fODJYhqNkGszfXCKGk92gFR+XiEFSKFKMnP8yRzG1pupzt5LKMOscWt1S3+27Qs+Y7JdPtohPv56KgrCHd8NxkbspDTTddeRYlNkoWCIQk9nafEZ6SxOKacEFWvfST3O8h98YcYQZJxyvjbrsZEizbnoYIwT9iCM6rqQB9So1iULA0WZ4ED7mzRcBfyX
  template:
    metadata:
      name: pulp-pg-cluster-password
      namespace: pulp
    type: stringData
