---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-pg-cluster-password
  namespace: pulp
spec:
  encryptedData:
    password: AgAIvKYDnbuRBx+Fk7/TgOPhOQoQZZagA6Al2QoNMMdacTNPbL5F2NQAIkzfF8ckbCWl/NM8onczUZ31R27cAys3keByDLaxnvZbwgrCWYbuou6GFfAEDsIvuLiJOlL5nrXDY1bqKBg0NpNrKDSWdi27Uz1KyB5Q6JHeaffMOKAXoU5OL2abTWy2QIi+j8VceW4tgnNx010YQ9V2TbUSxVqP363O5nDGDRCLTPPdV6eAQ5mtg/uWH3oxzbx3Q2SuvBVvAxq1fWNoP8my1cUI7fs8JQEdFf5l+0rZFDhIsqalhis9zNsDy8846Sot0hLk/6PEK1Kv6uYHszPMcRNiT/MCaTi55on+ZrT6sSx4ebtb1BDtoCRszKmqVoJGEhDaUvMY3C3UunKOCuezGd9YkNxIOylbozbyTSai7ZK6u3j9r2JFMH9I/lK44bRdaCJ9s6a3VWnoE4rr3QlqoI82L9LkUC1UGPByiY8I9JhXp2gh8PI087QdYrd503vjThgGn34v01/QNmod/7lTjMKr/8PG5Tr9sBhSn3DUwf/qh0bdYuK+nSqwWIfn40L94dhBOEfkAPBWB/8jBhhohnFkovOCBrlRr/ll1/2qTd4l6oSNvzXGxYGWuf0KkMFMVCyagLNYV6A1pDxbrHuzlNyKCXbPbx7DJ1BrN8xvrSZGn5NY0viAcnKNQiAOkW6b7t/8VEBkh9oFRcUjEWtaOGqY5fn+UnYkSSjFHDEEa4ssFif10hH/P85QXnheGVZQAA==
    username: AgCCuVG1wL1h44kv5l8nQO2CSKt5MJXl4us+wgHjbvMgjkGPXFgZIjye/BU6G/WZkBKZ9NboKnugc5ZVI4IFzIjVJdAbmJzAJ5znj4H7bi5eYQ2zAwDRW7onDFuAJpmYI33Okw6PefYEfJddFmgNZCbL7SrDCEPiNyeePEeVgXI7bn8i+VXK9T+DlS69LVLgx96WtCIFnBXfsVA5v4HUfVpwiHgPSGB/weNlsIp28g+XkZkYGQBtTEJzp9768WvwBaGT/6RwTID6OMB0ZcZQ9XMvUCJkmjePKQe7s8tIsojWhmtoU4knjhPz6oTILAgN1KGAkONW1iyKaFidSUbhC+OvehDa8TLn8b7LLxXVCtumN014IhYeKDEcFttwpSLMSG6zkCfJHXYXhWzKLeIVd2RPPrr7LBgVaec6A2BqHJDOFCzsHRHFDks31c48Cb6PHNgIMN8R/QDsra5OzRATdM3jT381IYp9SWrr9lsNrf03S/lX5OKRj6eJMuGg48NRsNcm3dQXYB4frbo1WnzC/pQzLImzC9JVv0PrLF45oiaVbJJ9qu9siJnM4lLE/qFNLB1Kin9T3TsGNuc9aPhquuLTsj8FwH0fyiuQSnyQT0nSHyML01iT0uMLR+aRzSeIQpnvr5gvdknCfHm2hbbv+teyulmBaiK4qUgBR1kR2VJK52lDsEo/oUVFYyYtD1HZAe4uOiN0
  template:
    metadata:
      name: pulp-pg-cluster-password
      namespace: pulp
    type: stringData
