---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-db-fields-encryption
  namespace: pulp
spec:
  encryptedData:
    database_fields.symmetric.key: AgDAja2yx3LAfEb2ul7huzunHwiNz1MkbXrdM8ggIk9SNsLqdDvHaP9HZV41OoWf8e/IAi+3ZZGihuwXdJOA83aH76qxcjRRhIfSoPQGbKXNR48xUp7X/2kBIMyJxtjts6Ab2Ho8y0n2qUj89lY9usNFg8KUioVPb+nYe87spb+1lhmrJvbbQaYg4/J1VlteVD/MqgKQ/kbutceWen3z1uVpAaaJIcj6Jand2qI6hh2aE6XHikJEjMcbH30/3/8Y2LR4G5kA94VDidAGQh6ulfLRP+H5v4alBpZzR9/UckyjMfDiICdJVnQoI7m6n/Yf+pgCGmCPHEEMTAOCRbouqxg+3VXhLHvtMw0G7KrnwZ6X18q2tDf5oMTObpX5Zv6yvkH70k3CuXJrf9vbziSTBGhAwLp97ON3QQ152To/bc2wWkbAkg5yhRkUsWY2GNGPTbyWoUnczInZoxZEokaokYwilqSkloDKu4/IUGMIWlgJGGlJrITLlVamDsrLYaQW5iG3DzoR7jD7UkjQniTZVMyQBWAlxnIepPebNwUNuH0AwAMiYlkAKSoJ1Y7GHZNydi7TTExXyTFoZgDl4dfiryec1mf7T13mvHEvGPW+axuIG6WQW+ZD+R1lpVvZAYJjHFygHlN24tFc4Pzi0D6Oj5QH4o+GLZp4OrmKMkvCAZE1H9FPxUCxjbVk4AwFLbKKLXet/oK75h0+w28FCRCfDP65NCigYXBYVlH4azPptre6GNRpROYg7pJK5eD2Cg==
  template:
    metadata:
      name: pulp-db-fields-encryption
      namespace: pulp
    type: stringData
