---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-keycloak-client
  namespace: pulp
spec:
  encryptedData:
    client-secret: AgCOl/Q4sJpatv5IfG6mK8qBiCZbQmmsRfvSqkjTo1xwBxPTYX8Qi7HH4DfTEGYWrRV6T6SFdYXiflUU+T765ay2GSmiQRUCCCkpXTzChMGiZf6jOIB3BPP/iKeJ7k8r0navn4bEDI9casji/efdaFJQiPQEEzmOrpBHcAKc4Cv9h0ia3xjBYn7Z8EnJ9qNHXK9M4sDo8BHUOBaPGcAVeCcz9lgx6hHEse9w+KVXjnmj8UXWwJMj0aHlPytYVzAGZsGIGjMF1f9PKLFSJCWcDvFFd7z4Rn/lh7twaA3HoTu7inYN4yyse6CaSiJzWhSJ9eDJSUIcTTcnqgq0oTCXsKzOiviXApRlW79UFxS/TZaJw9JpyRBFlIW8YV24HLZKUz9aUFwoeYGSJ1w/1Z5rCaIiRbA1YwIAxML0o8YvwGFbUhb0EkxpcMQHDDSQ7DnKD1ZRnXXo+ZaoVjLqh6aObDbj8pWrktHcDKxrTBldEbbB4hWOrsV7XzFT90hqEGQNK+3Rbaqp9aRq8OayCQdTanYdkygmMAzWDIibjNgHii3HHxl2FOqD3S01lafgQn3f8K+Odkrogx+9jVLB/xSZtGpwBpdFhLAGDqBIxyE0/xtYo9qPMZtabGBmti0A++nP0mXrtZmUObGA9nYVFca9GHzxeM+bnBVvKrAlVt8hYGFzPXkyfreLVMlY3LDstySpQ8odx2DNaaQdai2XukQYWc70VSO+TBtGHMJ23i+TkuyyGirp0ByphpkEsL061g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/patch: "true"
      labels:
        app.kubernetes.io/name: pulp-keycloak-client
        app.kubernetes.io/part-of: pulp
      name: pulp-keycloak-client
      namespace: pulp
    type: stringData
