---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-db-fields-encryption
  namespace: pulp
spec:
  encryptedData:
    database_fields.symmetric.key: AgCU2AkgHMhRqynO6ZEcib/O1bVwlhW4/yRh+7JGbCRboxdw8+zNKrYKIIKf1+73yKwJxKwtxoXsxl2Yi9KoacK3kYXICa9JZmIzUFvYIGKxr0INd5UMSfwSSzcDoCUlaHWoJGhVsWg9jgi/q+6QPgI2duWihVHCJtNGfD72aqsHK2C3JinfDLShktz1/WJAvvpg2jTln0dumPG7eJMAOGKK62HvR3mrKXB0EQhRLY/kdyRF73kj/9DeY/+32BgNF8AC6YDqKUjaRCt5hFi4Uzo/putbjdAgkPR+1yXwp6sIsb6xkADBjpzJ86B6dcNHw3WJ6n6APlOGH6PkJW1TAwWUEx13E1najpGRWuHUlqTjf7XkxPDMRg93eoY3OCGZX5Y3cTyvx8T88GFUzLhFxGYACmrGzrYpxxERdK7nfpDvW2PT24jpcn6nxdi3Lj40kc6Tx7BYeFfdyxCRocKO28Wo4OblrC4xNHKcZr8+NR7ZinaBewQOgix8ckAcfYn3Ri1sOGjBZwrh86lPtonU9LoG4aVGVNPgHqiNM/37CjSgFWYlKzxNcYEGdkY03LEs9Psye1rACdcjF73TdF5nNsDzbi/KTOdK+bco7gT9ruAY9stYKXgUlGf4ywKTgOuQL71vfUevEsvTD6dAL3kKe39yMaIVt7O0dXMAWMvtwjHlyr0hGj4jIhYtnExWwvHQ8c3hzJrYFgvGDCqP0a5D4OqnMkoGgn6AkHhEW8GJsE2mn+35N4uoVOtxokxDAA==
  template:
    metadata:
      name: pulp-db-fields-encryption
      namespace: pulp
    type: stringData
