---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pulp-admin-password
  namespace: pulp
spec:
  encryptedData:
    password: AgBhoUbuHQ4wGlnd2M+hWnKm/3xgyvs/M4/bQKfetyZwsVOGXlgxbAQsoo2YNFvUqpwr29d0gSS4LpQ0Q/b5Fu4BnhhNjo1Bv/GbSSxNpGtWnysJTLb0srgU4tnw+jAA8XVJG1vCMmmpqg5Z09A46besweDmzAnXWN0HN3/CikxHh6ydRu765w2DwBoxrpPqHJBww5kZE7x8p4IpCMesV+FIUMn8H+XCwDv0CP7UJ3oKaI9szox7mhHOVwKJsV9KEDLl07Yo9Z/gpQwboZbOqVENEdLFumB0puSv7XZk3wUP0oNnmcFBy4ajpXpW3T6JE0Qv+gYYBtpr2fQTGXxS8S8bSO4bgWi796gNvUPJ5VkPgvxXu6WJN/7bp4J0JR2IYfGLCU6J8C23bOMtJiIiVh3WVbS6Fow+YA9uZPz4quNENLJ4P1Yshp2Qk+tMHoKsCi9oSGa8e4fgxRoi4+flULE1F+vd6afu7yL9dIXuvIsNmq+yZ35+pDmWDZWs1DbjIT5C8X8CxVqR0RxPekKBciSg0dvMjF/PmdmSZqd1uOyrlw/faWOUdGDZ7gGqyGpaClZUBlEzYgrifWIxPcY5nSjHKfNz16WHomKSU5GvpyE6IHYdMNZU+sUZpPRaqbhDeyNyhDy6fWjR/zHq/El0IQvSyv4g6OadJR2E/sI18xGt1KLOVB8CoDb0bqOTkDTJo0Slyq06jA3kPa5rmtdIbS2QcHPuxQaywK4JHx8wL2/7VH1NteCcDfKEwWuX7A==
  template:
    metadata:
      name: pulp-admin-password
      namespace: pulp
    type: stringData
