---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: provider-keycloak-credentials
  namespace: crossplane-provider-keycloak
spec:
  encryptedData:
    credentials: AgBEHLf/+ulWRdCoDIAvkYy3WB94k+5JOS+N0lAZbLhggPgyAb2IMXs1AJMNKzxGX9D7PRIH2gi/Zw9TpfY1dT1xekpOgwa4wdIS+iRJbBhdWL9vWVyEq4RWBsT5J7xVWsHhzu/svuixRFYJtdq6X1g7Lo38Qf+i1odapiPIYdMAxntyQoQP1hbaWrwzZsuS2+z+/w7aNiCnH3EsJkWRtQlHS0b7h3+eIHD759wG3gpHlJbXfRSMbHoYaY0iz06cI6wYsXxr+LMQ1u7kBIxOgwxt9/EBshS2fc1zmvREDOYa1fGQEyH6Kt7cftjWrM2EmA6b/dcZ8q5Z3d/iRkOuqSCDRttZxDtv4+kDjvLP/MGW9Wwz3Fh5Gwv+ILGCQYwEM8dXCsazl2HB7v4WFfaNCLLtKXHxsTc+L6iL/AtSe0UvYn0hMNDCHKw2z+KvZkBWEKvzt2+NyOJw746cLgFVasBBLeCAXk9NymGwP0RZQL0URXOekPREpVG/mLHwzV+9N+XRhnmFOkMWSJRqgOydzK76tjcZjVsxoWDA2fGNcFfdU78+a8rpAfAhuf05f7htQvCguD1aHTT62AUKO7+r6IZqadIKZdidWTxNP8ApQ4DkdvPIIoIkwxIJKGL+0T6eceI4nprhTWjHRXSU+NeITF/yW+v8iV31bLJ5ajFZNHHyyge9EXN81FWZM0jHEiMXT0V1lO2frOpfup1TYaD8UfRU++IfbOJ9B9qfwqG5n5NbycV/nRnb2ApECQF0BJEGGh3nU+VlymzBZd38iAME30McpcxkEOh4OIGM6tyjWGhJaG/cYtNTsmBwYZWqs41kte65y1PNL7EGorYQv2/r7ZL5Z2tfFJBi+nzx7L8ePjtTwGskXfup8hAI4u7eAu3KclYYKO4zfkyjefbUxyZ9VqAtkTjXzRk9qCFgLzsASFzc3Y3g2VTZOAuwQaQz
  template:
    metadata:
      labels:
        type: provider-keycloak-credentials
      name: provider-keycloak-credentials
      namespace: crossplane-provider-keycloak
    type: Opaque
