---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: provider-keycloak-credentials
  namespace: crossplane-provider-keycloak
spec:
  encryptedData:
    credentials: AgAO003HPktpQa/BeztAdnwog6k5wepE8knwcvHTwZW98Dq+xzCtdshMTxo32oaFBR36eVTu790ftWIGV2CKebbCgAEGkGtoevlQ/zz1f22COXQoe2UrlKaiwboGG0LtZDMeaR7DhK310T3X858bpQleb8e+Sl4KpaRcU6IoLXcZg01yS941Xz1mCzlhZwMxouYo1sVgJjN7uiJ80ff7AkNdzT6sd/M+14PyChZwKfWl2s4Hukrm0R7KQWia6+am/fZUXNPrD/dYHIeyIwOKOU4m3ZoPDYxelYFphO0f2guuUgbhfTS1LRtqDE9QofuAY2BHDzDlAm1UUhhKxq4fQ0Zhd6WTttCdgyfhAfisDvfxhIaZHCymrThLsll1zjch27/HGZAQwOYXs80bPtsgXiMpdTmbcauththHTJlOC7oBHpUXXBzomVu1HRk3NeEoX+Eyf7i4ZYrGV5c2MT1V9ney+bRbLL8uls1FfDurIEt6gFNFBys/7cgCJHltBlr2EgQoEvF2G5Ctm7I+HrcM2scVMcKXjJvBlj+s9iUekiD39Sp028QYwD5QbvGitNQGeUvIrI3lDcUhg50ucisQOUiUf+mX4ikdEm2c9x2GTnXpX4WH8KzoalgodXOUqD2r7Q9jI0ZZSZtbjxyriz2QKcb1z5okfTHVFzpXYcM7tqQuME9AiY7+56vMTdhkaWSp9vnv/NmqK12hyekXuXqh+SFYBOAzmswNWfMbBhJk+ifSgc4uuOBeh3PUPdt/Mnl/o2I/QxYP3yQX15hVEP/3jOIzEoWc4sA/Rz1kXyDT+MSktPSEulPc5kEwU7NKC6ZacIQ8PimNUBtBByO11W4Feh8ksJtd+j7APfdFZCeu6Z8cftcW4BbpJUUlLAylTqkXcgFWGA7HWnIjuJApT0xVU5AuJg0mmHLh+kuXuyoOsEl7Ak7zWYppcv/YKbrW
  template:
    metadata:
      labels:
        type: provider-keycloak-credentials
      name: provider-keycloak-credentials
      namespace: crossplane-provider-keycloak
    type: Opaque
