---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: provider-keycloak-credentials
  namespace: crossplane-provider-keycloak
spec:
  encryptedData:
    credentials: AgA7SPkRLc4Lz/JEKZh/SFY087mLwNK3HCgXf/1u8CrNA0buBzwZtHFDzEu89PKsmxTa2eA9G8eGPGvE8ZKK4wgfOAGr9f6dZ13J8yQaz0fiJ3bZI8+Gmfu+DzhhcAanRwPt5Vl1y8M1B74YMhYu2IqOTdSFIXlFHL1s5LBQuoNhqx3RdRx+97gUsTYdcDUzKDCcAiOdPr3pD6MFCYRDxxvi5f0+Qf4KOssh1y6KYMmK3nuh5/pBFgKkz/Omtml7L024W9a6ffnyAl2xcneJ6qAc/iZpd3ItNmu7I4XQqEG5WyXJpEx8ItEDeHo0vi8U4SNPas7Gq447P5YF4tXQwzDYvCHXjUDJz4UOrTe9+uDRnTL2QRXsfUmm8lWiCsfCTJfcOyFtRzWQyxQw3CYp+1w0Wh4iwVtt3K2bLis7MUzXyBahDppyob1jqamy0sl0ExtxG7p+J8gAwNDdgBJfvl/TSllMbH17pohUCZbcYZZx+mTKQMNWK79o++z4HShViZEwRueynMhQYNvt32HJ592sEtIXEkxxr8Yd4OA0p5gKWnOp5qK1J2pN30KXRhnmIAxGCcTQXqsVY/hsOO7GG0e5412OBduaJS50q0Np026MsIyjNnHOn8aoJYQ6HJ5SUBRgEo2/RLUTnTt9Li+Uk6mc/GtqjpbnNtygQmXQzN0e8rP44dYROe0gZw8lGhaRB3flhijVms2X83S/vtJN/nJJxZHdeUoLzKjpB7S6yhZzpBmBUR0UaUvtjysWnnAMxRsHNSANUQbBbRcPxjAYuGonLYIwOIM0enkTvGeR/RgPXYly9aMApe11qEzOzGRll+RlcOvO9sFAo/YN3Oukhf1j97PxQjHiuH7B/QxSwKGINGp9cNXbtAue7AJ/n5xLkFcDHiztBYRHawMNowK7XudXt3ayhVCPsyqXDkla8gWQxAY8LlKpOJQZA1T2
  template:
    metadata:
      labels:
        type: provider-keycloak-credentials
      name: provider-keycloak-credentials
      namespace: crossplane-provider-keycloak
    type: Opaque
