---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-terminals-api-key
  namespace: open-webui
spec:
  encryptedData:
    api-key: AgBW/gB8p0W4AZJ2dTdqc4M+mKV0fe7zMogyohO1LNby73T6YyKfnWi6dgjKdgtVTlfP5z24HL/gip3IVYseypbzXQ7vnc6Bga5AFjECQlQtweuHCbDDY6hGwho69uMRJXBqdKnGGnLRhrAMtqW5Scqzeq8tiLYrmsEevNpcdT0Z4Ec1Rqlyh+OJ+XFI//jXyn+JY6VTHBKhqFPk6Bc82cNLtVhnF4K74UyU3E0Ik+MB4kye4L/bRLKXBsO5nVqNEiVjq97ituHm3XU+SOAsWb0q03SPN2gtD/YTQ3kotaVZ+7BgRmemFn7lGe7cV2sNoDG8Wl91zzmAtNgmLKzFfvKFc+aiJe/5jDi03eOHNcJQEl5HxGmC9r1BsmET89MNYDqnygjwyRlBFLit7Lyp73x/GOsF1vLDoTOAJ0IiBFD2wMRyPgtMmGHRKXHPO1RvPQJAomgtgix1/lw5LGvVV5KyM/nHydK6qfDNEDkwN8JcX0YeOpxQ+Tm7KhitNYpxhFPD12awAT1ZHZZbsJWi2PQp292RynnXMdje4OD7PNVBDxe5CsHZwxSzHXBFRzf1GDYtS0tPIi7OxWDf65a9lfLBxWbKNQ1aySYno4/BK964zNTUnS3QsvANtMpWhWXvcjfA4P+cC/F8HJE33SqJKwid2F3VQ666zz6pR3mwzusR9bEt1koNhwfrHoAQ5UDbKrnd8WlGp+sCayNnpkkAnQaNGkvGm0PcFCn3xOtGVi2GSQCjgWTQyPmi
  template:
    metadata:
      name: open-webui-terminals-api-key
      namespace: open-webui
    type: stringData
