---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-terminals-api-key
  namespace: open-webui
spec:
  encryptedData:
    api-key: AgAlvM+fRTFBfFfOAyWRcibCOxfaR/cBYmo//Ip9yJwXr5pfayURQ2czjPTAZa1vTSDGHxxTT/r/M6uMdM8o6xvwCUx0IL4/rgCvFRa4y5jYkLcBOUSbRS8PRWlhpBwGbeBNOdm2v3umtUVi02T25PDXB5yv+9oOleavCvluyce+UXEsVRiow9CfH9G2N86vw/EM+5ziU1h89F6Y6xLAXQJkag6gEGhWSblSKrCdbyXRji3PUJ1WpPrHwUcBtkMZaHAKxVFmjJfmgiDoYrGXudxanGlU1B7fBAn7bJ0YHL4i67JLEZSp8YaOvJ2oqVCrNeGryJjl+O5xQFCLvpgLETlG4FiTzhYQXIIjpcrY6NY7muWPXgPGqvgiqtjoVXt413jCc4KpgJvkqArL0ERmaNUZkzuUZJRBAViL08nAnx+OVMIMYNHjjyNwicM00ZEMOPmFVovSfnIPwvSGtN6czEyzXCY4fTf0VwZl0xpW3g3om/LRNdwDT4B9jMNg3BAmVNu5BEqZhgLnoJQSozCw63JmbrpRrCjMS2n1hs0s4isCbHpUGEk7A7bqDq0cHJAi/ys3KEMtR2ubRumeSMIvU+VSHPaek13kURygYMyOv6BDslc9EXHG1wsCcX5OxEPbCniUwbunolNC2P6rqYoOFWD3hxRKNcg1VmioRrcPO0NC3qDnUyQJRxqt5mKvCZanXAyXp9GpPhrbL0/eSOKNMbuDnfspe3kmFCAP8PmGZI69PEzj+YZkZeaA
  template:
    metadata:
      name: open-webui-terminals-api-key
      namespace: open-webui
    type: stringData
