---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-terminals-api-key
  namespace: open-webui
spec:
  encryptedData:
    api-key: AgAbYOxqYcE0YaAkJukrpl4lxXBFhtL0GdljjBe/4s17a7v2PYc8JGQTqw1TgMajT/h1ca0Uk5wGYsFIZFQIwyKSg37Z0sl4AIHDZ9V28do0CwTmgkpNBl0DztfSdEqLEUO32eddVd7Anv6rGUpfhPD6PNZyIyUAdNu4SKCNkAp0NkLkXCr/AOQSUMlci+rqRnvrYNFqDwyTWkBxuv6i/w54FTQgXfsBZzSmMJBRD3tyfdOoN1446oM0JKkqyhJUsdQku90RugH88PSmDOTw5dsA0JVbj7R3M2OX8hqR/92FkJVsJqzM+YLRCnWvysHxg/BTaFrX2o59ntKh8U2g6NK2C9behWQKLPgn+xpgbyii+6L20c+9X2HYBYaih6gW5toJqcxYX3uam1a64T16eDD0vDjWQTr/Y36i0u4KFt9bsv23rR178tL9PMnxY3BFT1fkpeIc9P0pFvAjTYVKlP67M/1X93jXCXgCdtY+otShusZQpPCJ9gYfzrC1Iz/Z3/VU8OqtJKkkQSuTuRRwPSs28vyGTPePYsfmekqaj0wUNngefScFdJ86CRVnyBJ9/sEfg3W2YegQoTA8SPcphFejFSB9qTIy0tmAOgX/1ToocnDql6yQjyUKPTRlvy8dDeHRYnMlXsERv9VxRuLjpng3OXzuQanZvACdb5yo2xaX2v2A+wEzRJ2EBzv1f7zD95GctSxpVeTQp3scmaoHd5M/H84icjIyCjqwiw7LkggYXzQLVbTgKaGH
  template:
    metadata:
      name: open-webui-terminals-api-key
      namespace: open-webui
    type: stringData
