---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-webui-secret-key
  namespace: open-webui
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgBEdjmnrLXfKNu+IFBLY0D2RTq7nqQ1wlrZbs7r6BXFWcql13La6LGsg/qKwvwW2JnZRjd5Ik31u4biS9bAu+OevSCqWOcGrZQJ9dzS6v3ppX5AIT0zU7SJELjmqSfsb3DLen9R8nfj4bZws0UEHhM9Ulzw0j2kB766tZnd/qwjFw5xnYY6hrdZzojH/YLpc43FcnkjLoEoBOQcxPu09gPxy+3px8M/n8dL/IWewhpFmCoGqh+33qKH4kjNT/GpaKhzd6VgTWmqi+xBrn/6GUiW4JDaO26qVoz6CIogDROl7lr4UkQiofeCSEbnvVgpFqrX0zL5FlSokc3M/vNpVd7eUlSNdFCXy5OLFBSi77IFyRWf0sAvR1IBI4SCFLSM+KYpkKhk0d8zKeCLFRGXCx1g97Bo7b+Ng9wEs1ALlR1henshFFOJV2Jxa0kP1KRIiWaPXqbzqi1CCARghlWQoTSBJk+XefR6v68HnpZyA3XfszX2JHjtsjLFfgOTvXQJTqC+ttCwaO3jhpIImJcZkUh5fI2DcbL6lARpzJNE00UBZIMOOWC6y0g3cyb/ecw+MeBjXRLYOb1vNHF+tifdx3Ns52tx0SUNxAedhbWie9SzM+cfkdeSuCsUr1VEeNQJ7NvENT7kTDG/gQLNwkcHYJFP4fX5GQAxkAmOsdNmP1Ib+px8WmMcmnMsQ+96cK9CaqoA1FvnMUecgvAr/D4hvCRCl8UmWajL7eLsqh3jRcdpeQ==
  template:
    metadata:
      name: open-webui-webui-secret-key
      namespace: open-webui
    type: stringData
