---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-webui-secret-key
  namespace: open-webui
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgCov6Hik0Mn+bJ0d+KCZvaTVfKAoSqEOm6i2biVVzWeFBnWyi+RBUS0SG5NFt78Cm4AHyT5dFhoJHdMolVit/WkVTDgKmKYwt/kGE3sGm7SCTXHukOf0Mp+89y8kJaGfoQuHj9oXiEK/V0IxkLs+y4+xDOjR0gmTjR+YNh5cS/OIOgA6ERoi8bkLC6FHF+KqHqM2zlvH4LWOflEi6yPkaXjWUr18LR+VxlZeXRZJVmWmhbU/D1slIKgUgY5LYNSKd4tV5m9aN8ZjxgnS0tGuPQ5QaijhtTMmLAWp17EtoBHgM1CxVF7g8mT6w0hlSbiwWS8xD7544bhS4Uhb5YrAcm2O03jPLVGv4w2odILHx1c1W9ACdyFVPM8kHsrzLg+BqfIke7PHr8XcYr30dX2+AL5wia7yU4V0Rgirqgu+qDwtVthEuFb8Mclcod+U7jV0Sz9kNU4ADsrUOQdBVjW77ybqdt+89bPf+tqnHYuiM7GvyWxfKSSchHX9NKzXuwa0w/iEDbHgP77qe1K32gDg4FD0dP0G/yl2XtaaPmSNr7hQjwuco7Q5WTI+0/XBe3WLdMscluumKXCxZnC15ogL2UITOC6M0IlXAxJ/PlFRHXHVTWUKp4N6nFemKkqrQIUN8kQNxHE+7c1GP7Fz0K9svbB3SZii4+CwPOPioVz19KvL17uHyr9WUsXqYYorK1gyEilqQjqyOiae+yZWvApnxYW3DROBF7opNibUi1fZ+uYxg==
  template:
    metadata:
      name: open-webui-webui-secret-key
      namespace: open-webui
    type: stringData
