---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-webui-secret-key
  namespace: open-webui
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgASNifbcRCIMke4PJUqrLpFtQMgj1FE9rTgFYiS4INCJCVvuna9pGetHyhS1KcQPNKC6Nn1OlR62cKaAorQyLhATKDhlzCY07Ts0dpY7PKtnI9hldpgjjmpaWqZZq820CEK5Yel8nPQbY2/DlHi3u9QrNx5HepenIfLrAMTp/0Tvs8iuBqtUPaGN3adckOaRT70KEAc1ZrCl9XSgOHmoiqQ1vEKSaP2ZkE5845Z8vAK5e2V6ssvry/No385X/q50vWgtIgudrdGiC2mZKeoCNVM3deduDbd48wl+vLCrLwfei9j5lBY36REswASW5esZF4Y7ztULjmH6CgXpO3rI3XONwlB2n9OTPysRHIi/wKvUB/gdi4bSIuJhs1WNm1od9Qabdz4cbVbPkRrlH6U7lVdaxK7DZHi9sBkQAFmA0590IWVaNeBHzfQ8eVFP0bYcfWUds4aFkhWfWK4XJYXArtc85i640uZrOaIUZj65l4eY+6Ps8JUt6Dabfypt5fd1SBsPMxHrbW6c01LJyf3ufjsOu/L4PrFjS+V+qolqfohRGF18yYdj3M5XL6Myqt0Ko25Sru0e3vARSKbcQka8iIgmIHd1mKdV74IY3ZIZdV1KEStJC3ULe2i3GuAjxWUKjX/w0sYberDYXx5YpvEDpoh+5JKvd9YFVrABrn6U2qx4PVRR7xlo8eJBwF8wCO9STqIufloUpRRqEXMTq6ZCOkHibcfblA0m5mS+wtm6Qmj4w==
  template:
    metadata:
      name: open-webui-webui-secret-key
      namespace: open-webui
    type: stringData
