---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-keycloak-client
  namespace: open-webui
spec:
  encryptedData:
    client-id: AgCQzykG52vT7J58PsAa81QGdwEJ/ENQHZYHmddv7uQ7uhKcXUOybCkXwrops5+zdlyvF/2Kr8t4sgkpl1U5uQ+B3GcEb0MC5tkew2H+9o1af35f+2Vb/XEx9YBBDOVw583kPWUCLikzdctkALD2gmlw5+i37gJFZ4niq+DqFOfGsiQNr7RdiQWonwpHAX0/AUMm5K6EbOaxS+t21kQXTepAEWqeA1xTUula7ywQPahme5YR29IXDY5oyRna4JNDl5RcxBd6LRPl9Q5auzHBaO1MuMcQMBmhzIWoSeWdOj/pOkZEqLc4S4gjXarmhVQPVq0tAw04/n1cUEzJEZgirDn0upRiqJ3tvLGkAiAm8DnPXIYcxxTjlVNm/0H7Q84Alib8CHc+DSIqdp7P/z6UFdV2cIolsoUAUoEnu4GyK5nULRffQS/nlk4ehaRhIqBmlYJf6AcN5Pj8xkqpguxRQ4/5NxCmxrFzkJGiW3Uv2BgPKPra8M/XE1EUlGHH6INRTsr2L0Xi8zH9HjWYfcrqIo1sbXKjCApuLuArcN9lK5lGc3I0ZEeMtXD85lqSbY2/ls6BVT7hT6njWY7PzYVhophpSEmVxgDJZPHwtxU1uWYpOQySGF8Ojfnj2Kgk1v5mNT6moXfB83nP+Ef0heEhHO3LsWi3p/Ionb+7gUvZx9W8yDl9RLWykV4S5OidXe/MBk45AwlP8HKLBAxE
    client-secret: AgCJX9LdJz1EAgg/dpGoDjUa+dA+YrhKgJRveKNwZBr1H7JzEzGIZZGS6zbH1Tldd9Se9vjNvMlEzBtvOen8firl2LfDRTtmDF41dCiV61M8Q1gLKWhu/TCESGcZE3KBR9Qk+A9U0ODN2A4qdYJXkZiqpEF/uGJsqheuzXuD08dNWPf0HCKIRAdsEQ6yJ9RB+mdxjTW8+PxBYnH7lBtJyw0npxzTmvfxF6ryaIc+wi8xgDVqg/4zg/b+w+82toQ0AuNt25duD+wQy1y/baf/gaPffdDq8S6dUaau45p4N1ay9A/qIWk/+WUu+rpi5Bc7JoSQp/549M4EyR3MmUA0yU8QRJDrk7Hq91I8UMxrqT2IHPPx8P09U6wKgFBm9odZTOd234J6N+Fc1GOaT14FjuKTcmAonuH2Ge3Tnsd6alhI+CN4p5Ykmoi5ZcW8DlRxOxma0aD0mtuYwJhvgS0O296b2YGHLEv98kwrqzFb687Ky3O8e2Hyed+24KjEuYnq5HCzBIlaA00UC89Bk9KC/bRzFoBBsQHnW2urmOPv76HFyhW8cwtW5WljqsH99wIEVZnR/HSRvc/85Q1bwWVs5SVcl2f41YEeZFamKwavObiHXKc/bulQ/i49R4BbtXj6afYeFvZSNh4Tlt6ULllalMsp37OCan8jPJOZHAeGy7Eqtz58wFO7MtEEJkEY0iSDvEjNmiT4MSJ/Nb90fY7KqP24z0ucPft9NvBKBF5wXqiNwg==
  template:
    metadata:
      name: open-webui-keycloak-client
      namespace: open-webui
    type: stringData
