---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-keycloak-client
  namespace: open-webui
spec:
  encryptedData:
    client-id: AgCFK7HDWbSI8XjUm1iQwbOpRx7upHABIU6F5Zu0zCoZsDLHLu5zUdnprqpxuPDNW/UhiCKvXaRnfOmtlnKLavZbp/B35Rau0oPH6u3BCufKP8Aw8s2Ycakmzn+E3yRihw2Ln/s/8pnNXaJD8ZUdBoSaxO7qKv4HUCztLqH3Q2gQZoZwExooz4jmdy4s1Wn+4L1ciyRmSUzcpiK1iyb88gbM3+QNjvjX7nGlecAi6Y0enq/jK5p9dmVnDyyjoKjuUfa2K/EEEwHi/yJQ7lNduydd8hnhJPbL7YhYAyngHrQ+14PfvG8pFAp5LSBVupLGzqkbRxFUmRnV+SGF3Zan8OVc/buyTTjf7BnOINGagh3RB7SmeSaxBPrAYXETRvV5ynAlz7+m1U7IHiNUucpmD9OKR0B9SXlRwfnL0SRy6UhDBolhpXd1e+qH42yIcu2tZslt6onUaHfm8O9P9SUK09YuqULkf4N0ikEhiqqlDXQQQxYSnkHcpdH1WEnXBcRJUlwT2cOCsQ9XDpIEEqSnv2YirgzIJskkasqNs9GKteexWNfY6vZy8H0nGMtS7G9TZHu5okDRwlo7F0iCG9o7Btm98TsxngnvHuNScGyQrLV81pQQX4NRp368uXfwLDfTQgScvSjkfNk+nq3Nd71wbFnlwOSufQlhbmPGack+YC4tgDcOcZRNxmzY340IbdLTEOB1rWJsMGO3aaeU
    client-secret: AgB+PJ0Z4H9Q2TtQSV6EhpjB/i+Yn5tGKBrhFpjK7jJiDBnqDRb2Ui7UFioorRHkvIHZ86okxoCIxgqeI8dLlTPBQiDjpXfkzp41Zlokd6vUsCYLn+YoQnnAm9b8OhsaJFfiS4iwSn49OesK2zvPOt4CtB0DlXdZGjx7E9BXHmbm/5/aQ82fH6Yiz37voFCjCNX9DQTVc5tdHR6gjJE7FeE3mPN2nT7t92P5BDo3dVIKaQ3FRFIt8r0yQFcnEKce2jwKPKhiT/rU9EdNnDaxBXME/hdU9cHUUJcxTx2UuAua7uQpo+qRiYIUrj5oLsMAbLP4AbrKfcyqNTVaKjWcH1yhGCIG9TeZ8Ujm9QKljSMgDDSQdj940cjIPrwwGTME6dkiP7KvgB1BI+Qms8g+6zHqymUCMN85p+O9LPpa0lHe+sBjrtcS44bOxxHPGg2Xk3QaMpHPFbyQMN8ZRWA3Xl/ZknUr1BpcPX7D7I/Ei9UhOM3Z9dGSChZbyfq1L7H5lsDh6IdJv3glt4vWEi1MRlrw3umkzSl9VZS8q518zoTF3eLZJubPc0om4eV3X/v5HOqTJ9JFPabzQL9V23Q4apbxVOLJNGF3cM36ArfZ/RANO89+eK4ZUuq9tvVQcn/qZbd4CJwCqjb8Oi7qSFAucRbCORFJwlULq7aS8qfODC1WLw2kiFJ12zca54vMLWhiKBBk4BDMFo8Eq+jrTPB2rEkpp3K/oBYDgZdRLwSa2PT/gA==
  template:
    metadata:
      name: open-webui-keycloak-client
      namespace: open-webui
    type: stringData
