---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-keycloak-client
  namespace: open-webui
spec:
  encryptedData:
    client-id: AgC3/0quP5of6s6lXMcj5RavbKTpzjvp1s2Ud74dapb4XJwdaDFWHF4G298puaUEyH8UttynbOzap7HydBxtPv25uyxZ2aoesUtoIITneUh5m6r2uNu/NJKLUeZ+dHykNOMcHkpZ6ymCYQr4VGnvcZu4BQyREnI+cKqzoEz+Lp8d+8dJ/2/0szUE3QQH8FsWDJkc9ChqQ+yP4Xov5wI945kk4GJwmhyioLHJZgt62UQw3ZRerpLZPIg+i4LVGktcrsPvu5dhKTsX/YDjWna9TeEkdLfcBCJmLJsIq7Pu+by5mrnIsNpWgO9PU1RylFLMPzPYIn0/frW5Icw04f/G1zd79vvRVlwzXmCSA6/8ZRzQ4g5/6js/k/IpSxQ07ATVkY/6XQ+rWOJBWhA0MTorRTwk7RzBcFMXnIB+nX/IXxZny7OolC3RX1cY9xWGa+15c7/nbpShevSu3zSrtw4esEfo8HwasZ+ugPEBtb+8MAY/X2f1TY/erLIQGE/AFQvlSFwMwjo0hqbdBmjMq/kws3lWjpaIWqvcxP6kng1T02u+s05UOzTmhQ13j+BC/e5UKP8BODZb8acCdNbpytwmOm74TcpmqblIFUl7lx6CvGSX/J50mYYBIrNeAvSOjqDwaiQFkn9o32Lg5TcwdApGmPomeHdfXEeZJKTOOzOFe0LBvxfKGts31BjnVzlmhqWwXLhsP/Rg3dCXxCAz
    client-secret: AgCuhRYvtkTNBrxzydoHMAbKiY0ydyO6afzRJzE9oGfQhfulkAQzmmZZ3ZqWgM5Ai//1pMfaeVCLMxMIZU2USOh74mZUkskCxcO2X6QgsBtun+5UXA7z1oWnySBfF1LWsfRbo14ej0qekDwXQflGIcjPYJ6Rd5JugXURErdvGTeoR9H9zrn06BbdGHEfkC/p872b+J+ixu+XegB2WUSYuEDICL4WiWI2hru2HB8sRbUzAhYeyxjV4MrU2kVDRENqGnBuA/1JsyxbZt3yPVLf/hMwcL7dmvotE2PgWX12mu4ENrTzNDWxtpQNmFxeOBlyCKVkInAKjrhdtffJFNb51+vk6EaDpS0GeVXtnbsDc6wPFKe1pOEpNO7wG7PyKtJuQVywZ9qZt911Hjq8sqbX2QDRkKHROFrbEk/rNiL8KG9Ts3o3XR9ITjUXLD9FZHz5KSB9LL+GujsuF3L4EALrAd/7255H0m9Yjb2zXXsjYvqcIg2I46hCGHPhoH2g3xkbmhKVHJFVRrdLXuqoVJCwTTJo8xFxILiWmSnasAXCanDnV2jpSfGQ8rjPBY1h7jhYVkBqtEf/GR88DjLhIh5m5RYren2WimyYLjNIQY+SxlUCVYCS11k23yM/3HROyfzCyUGQZXqJiSStTPwoj3h+OvEXnsRh0pejUCbbeYMkvJ982ESjNJl+c5+9ymoBgQkvkKTbH2iCMd5UoJN1OCtcT/S51vigFRArhBB40/eqdJzTFg==
  template:
    metadata:
      name: open-webui-keycloak-client
      namespace: open-webui
    type: stringData
