---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-web-secret-key
  namespace: open-webui
spec:
  encryptedData:
    WEB_SECRET_KEY: AgCD3YZDETbFrd378WYqpNeWOrhq7xqCo6omEfQspXC7h7tS+scmjmwK3lM2labrMmVy2TJujYENkO4hLnROH0WkjJtdCEABL+AwpY8TB2MuVIwqRXCO0hd+lE8T2mD1Nsmy9b1PNGtBhPE+vB+L/eOUAqJsgY21mQENTbbN+yCsKwtrI3pl+f2QiOhUQV1ajwadxIPGj4H04fYGYjkVdq+b5HrV0N18KKh1nh75JxYQAwZqRQ3iITYu44J6c2KmaADkoqhgq4KBm1fjlE8oJTW1bd28ps9dVwkBid7av1t8MKCRaJKSnEwMKuUWxc5oq//Rg5kpJ3qoOpr+Onx80ObUXmyulo7ep8Fftp1f2NviJPWebdjf8bjJaex/PWFBhuzfSdYQHA5oGcdgi/lGorLxFPAVK9mEVuPfsoQwXjprgLeh1eAr8SvqGjGAhJsjL8hHFnkkz41gMBi3x56z6kxSVwtbp4Rjg5tiWoTmmtMdgXh4VlONnBiUUOFkkurgK+nrOv0rmp7PCq+//wApNRqnWYaLVo2ZM1JwZsd0oulRb8u87RCaZpPfFNdxRoMYfbZVDIRruQKlkelg1wxRj9Vm+8AuRqD/bFDYVkigijBRUzSCembJJ36IlCylXaxfB5SmzMFr+kHtcPgyYNGPubnEPdVTAzEkHDuOcQo/0K+i8k5rke8+Kg0H4X0gc1IJaoD4y35TkHmpYJ1UlrDMu5vMV3OPJckKxwPF7ysl6A8lhA==
  template:
    metadata:
      name: open-webui-web-secret-key
      namespace: open-webui
    type: stringData
