apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki

resources:
- base/networkpolicies.yaml
- base/objectbucketclaim.yaml
# - sealed-secrets/loki-valkey-password.yaml

helmCharts:
- name: loki
  namespace: loki
  releaseName: loki
  repo: https://grafana-community.github.io/helm-charts
  valuesFile: values.yaml
  version: 11.6.3
# - name: valkey
#   namespace: loki
#   releaseName: valkey
#   repo: https://valkey.io/valkey-helm
#   valuesFile: valkey-values.yaml
#   version: 0.9.3
