---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: crossplane-keycloak-provider
spec:
  encryptedData:
    credentials: AgBcI5HDOgY7qt94laSLHXdUZ7SwTZarbmhN8Z9W+QJlB1NEpVJtgEOS5HyTxBPFJjl1S9qiAVdUiC7H5cJgLXk1SRNTJFnyfRdb5Ilqzg/cTHi/6R+iyRPf64QlVmOYunDTQYvRpqm8IEtQrPr3PPjbr27wZiJDUhP0w9Biz3l3WfIvEE9gppfOcHWHzToPu+/3mp2QSetliH7goVEjhkedTSX6E9UAGD/Cp4pN93z3ZVZVpFBV5/DtI8CU7NNCDTd+ClQpdcE5Gt/pWyD6aagvNoRcwUVImNWgXRZlwQTpfMEDdTV73rRDPNtMQU0VGSyWoDwclOE5g4D+Seu2ZCyyt+C3OBpyVMVnYxuObtgJqTntw56NxVtELfDMNjd2FP0GdfMxivRzGRQRb6/pToBwyucuaMCQUHCJFnrtHyyrGLrZ5WzHzIi20m4TKYPbwNdHKqFHasqJi+SakLIj3mOlA3gEhk6WIJsFMKxbf2/DtAzKmuksdlDcFHzIe4otydyAv66LK6P/oUllEoM6APEA+dC98SKyrrM5+SRaDUi+88Uz7vdGp2guZzsZ9CAGcnWz7tFgsfPS6MQQr53FxyokTqgSMYvdqrQIwnhnt/yLu59vpqwi6P93nxIihTykuQqdYZLSXqyOrxNcLWp2zLN8WxYaLu+VwuTflOctFzPOMW/s4mg3UqI5eBw3U/Bj7Axr+f3w1ymAJiLioA3d63RqlQDALUhiGPJvBjCUCxaZsXLrlzruSE0lMKllUwT+Bg4squqMFGQAX/NipPZsSY+/4yzEju0wEGun1Ee611mn/7Nvtpj0DWWCQXsusciShyHoxg5xhUHXPyGYWtyWVuKJWZJT6nzennrVR5ABvv+/sMwl1hH/nRTKza1R1gyvUC8h7r1Odv2KcXSk/+biWB1yVuSnIl2/+LwfHKy9XTLXyY9fhB9g99sZYQrc
  template:
    metadata:
      labels:
        type: provider-credentials
      name: keycloak-credentials
      namespace: crossplane-keycloak-provider
    type: Opaque
