---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: crossplane-keycloak-provider
spec:
  encryptedData:
    credentials: AgCD7VnJyzbaq4uJ4bln8YPq7dMYxLAl8xaNX6E5dcye75ww9kMf1zlGKVe+L/wblpGCX2bGLTyvsltiGMPtY5zjt6ICHSTYXePYSC+gQJd4rZ6YBzMdxJrT/ZUJB3E/8HPoh0Odkos238/CDtKaPKJnbTn9OwnEDehlqjT6IN0ZA99BLNgNLbyoS3PBz/Gi4yrczBEE69nDWFN4/TTjkGXW3d+FugmIYVr1UGP1RRNVqiRlRznuyqx7w0PmWVyj94YzjjUOPYrXOUutoabrw7fUbjUABW+X+SO4EVxZR13/FcQ2ZHzwVHhSi/Rtc/cK0cajdFB4TgGPVVpTh5aj5naXuzvEK34ZFeEmS9+2FBoMVhYNOJlY2R5s2FYJ1BEGaXbYxVV3q+9pn5Lc+0bKWAzqAIpnfEFQQWbJW3LPNkvQfbl+q/BNi5OLpDZG3qOx2F3Uzd9LTsIxk2LMCmsGHje2V9+o9I5Emp3az6XfI+XYBPJJ5H5OKID2uRi3Ze8qNL8Z9SaCAqlxTWgZfDG4i+R5w5BM2EygSkoIIMBP1rUhr+G7yABcyZHy461gbhFcpZ7C50WL4hyVLc0gdgR4Vbkppc3KJ+veIIPQ7bXkAAES0bA4mK/u59pHbwf7t0w/6ZStd5dUduwyrVqAcCU3vBupsIrrvGIDWCOnW84Dm40QMgWLqjZwvUb7FzuavGO8CG1sroMfXXNXUX8CV0t6/h0FFjzHFyOjVIJpmbSs+L7JnvHUKZvbJ178ta0ejlt5K73QYsE/eRBe4uzjmWtAEKME4q2Mhn4OgpzMYFMFZ5zlcnbFMlKwR/8caK94b84h9TuZ+y0yUKRAG3xjplXQ/E2yXTI5HqxzTt5yDuc2AvnPqstE3spZUrDRRi32Xw/uqpJBMpYQwDI/I8XoivWhaeA9MdKBgGhH003axdlNPXYd6X+GupZl4OGhIrtz
  template:
    metadata:
      labels:
        type: provider-credentials
      name: keycloak-credentials
      namespace: crossplane-keycloak-provider
    type: Opaque
