---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: crossplane-keycloak-provider
spec:
  encryptedData:
    credentials: AgB/1eqF+nxaok22MDOmpdiisYdgaTbLIa0plnr+IoqAMjFbUS7JYH6bwGwmbpmVKkqMSUBZCqFSw9fppZmuw3XjOC7OmIpgOfB4PimtpQTMZl8hKl6deVNb3el36ddEuOB3bGCrqyCY1rqE7tH2j7iiiqSMeWqXZzD5GE3NomrzUIfeJDpRkwS5XEps5knOJpURLxL05xWcU2TkhZjRe7TguuFuQDoKS1weVS8wX3gb9JvoOlMV8Wrw/7ee5v5I5SQxDgrBNiH1KRWfGyIn4rrEKmK25oKQPC1T06JqNp4hKr0vbW/TVMcnzf6xmr4Wmplb5ygaqcKz19qj9AGOh5jPCrk5FBf8ZdRx+5fNClVEn0lvnuenE7xlQZMT8JhSIrNeFBk2NnQY6oM2EXij7LySUDVN+ZMdWWxl1OyvNp0XzPAh6fY3HL8Cpkts7bLzEPxc1Idtq1yF2nHmd72CAYzZB3Bu1l1V1A/Nq4lYfkdewzFQBoln7uVErZ07uDM5CiuA7+bGWLINMcZrmbffJy44mSQGrMgPFl8c/nUbQGoCAcsMNAk3n2fg/yW+Mx7mxqzSLXtqFd/NgJ7UvxWNRNR50N2X+dDfGg8du6t5qYSQgTVm+1oWtFpzTNZizQcysaDfuRYHX0cgWmP4MmTHKFEGCLDSLXFPUwUMDek6oB4KnLyz15gntUYxtT6tzHDnMJ85kgeEXhFEhe1RdPn85zZUjmimJ/L+ffszCpOHRxLCOKj6U969geGvKHlR3+qRXDIa21a6tTii4IfOKSR3m5fUOap0y3oP3UTD3EerEKRpH/2KApVePgdnH/23n9y+wVPfRNC0A4/OFnshEA30psLozOHvHI3zPMNDWu4M/isdOpaghCTX0KERvxOkeScdyzeVQWdj9qIL3KsPB8oQV4STYVNcW7ovwW9nXXu6NlTypqLVsf9r69TtmXoW
  template:
    metadata:
      labels:
        type: provider-credentials
      name: keycloak-credentials
      namespace: crossplane-keycloak-provider
    type: Opaque
