# https://github.com/cert-manager/approver-policy/blob/main/deploy/charts/approver-policy/values.yaml

crds:
  keep: false

replicaCount: 2

app:
  logFormat: json

  # List of signer names that approver-policy will be given permission to
  # approve and deny. CertificateRequests referencing these signer names can be
  # processed by approver-policy. Defaults to an empty array, allowing approval
  # for all signers.
  # ref: https://cert-manager.io/docs/concepts/certificaterequest/#approval
  # +docs:property
  approveSignerNames: []

  metrics:
    service:
      servicemonitor:
        enabled: true

priorityClassName: system-cluster-critical

# For example:
#   affinity:
#     nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: foo.bar.com/role
#            operator: In
#            values:
#            - master
affinity: {}

podDisruptionBudget:
  enabled: true
  minAvailable: 1

# For example:
#  resources:
#    limits:
#      cpu: 100m
#      memory: 128Mi
#    requests:
#      cpu: 100m
#      memory: 128Mi
resources: {}
