# https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml

cainjector:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  replicaCount: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

crds:
  enabled: true

enableCertificateOwnerRef: true

podDisruptionBudget:
  enabled: true
  minAvailable: 1

prometheus:
  enabled: true
  servicemonitor:
    enabled: true

replicaCount: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

webhook:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  replicaCount: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
