# https://github.com/grafana/pyroscope/blob/main/operations/pyroscope/helm/pyroscope/values.yaml

alloy:
  enabled: false

architecture:
  microservices:
    enabled: true

ingress:
  annotations:
    cert-manager.io/cluster-issuer: iaas-wcooke-me
    forecastle.stakater.com/appName: Pyroscope
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: Observability
    forecastle.stakater.com/icon: https://pyroscope.apps.iaas.wcooke.me/favicon.ico
    forecastle.stakater.com/network-restricted: "true"
  className: cilium
  enabled: false
  hosts:
  - pyroscope.apps.iaas.wcooke.me
  pathType: Prefix
  tls:
  - secretName: pyroscope-certs

pyroscope:
  config: |
    storage:
      backend: s3
      s3:
        access_key_id: "${AWS_ACCESS_KEY_ID}"
        bucket_name: "${BUCKET_NAME}"
        endpoint: "${BUCKET_HOST}:${BUCKET_PORT}"
        force_path_style: true
        http:
          insecure_skip_verify: true
        secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  extraArgs:
    log.level: info
    config.expand-env: "true"
  extraEnvFrom:
  - configMapRef:
      name: pyroscope-bucket
  - secretRef:
      name: pyroscope-bucket
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 10Gi
    storageClassName: ceph-filesystem
  podAnnotations:
    # Scrapes itself see https://grafana.com/docs/pyroscope/latest/deploy-kubernetes/helm/#optional-scrape-your-own-workloads-profiles
    profiles.grafana.com/memory.scrape: "true"
    profiles.grafana.com/memory.port_name: http2
    profiles.grafana.com/cpu.scrape: "true"
    profiles.grafana.com/cpu.port_name: http2
    profiles.grafana.com/goroutine.scrape: "true"
    profiles.grafana.com/goroutine.port_name: http2
    # profiles.grafana.com/block.scrape: "true"
    # profiles.grafana.com/mutex.scrape: "true"
  replicaCount: 2
  resources:
    {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  securityContext:
    capabilities:
      drop:
      - ALL
    # readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount:
    create: false
  tenantOverrides:
    {}
    # "foo":
    #   ingestion_rate_mb: 1
    #   ingestion_burst_size_mb: 2

serviceMonitor:
  enabled: true
