apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy-metrics

resources:
- base/networkpolicies.yaml
- sealed-secrets/alloy-client-credentials.yaml

helmCharts:
- name: alloy
  namespace: alloy-metrics
  releaseName: alloy
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  version: 1.7.0
