# https://github.com/grafana/alloy/tree/main/operations/helm/charts/alloy

alloy:
  configMap:
    content: |-
      logging {
        format = "json"
        level  = "info"
      }

      livedebugging {
        enabled = false
      }




      // Kubernetes Logs

      // End Kubernetes Logs




      // Backend storage
      loki.write "loki" {
        endpoint {
          url = "http://loki-distributor.loki.svc:3100/loki/api/v1/push"
        }
      }
      // End backend storage




  # clustering:
  #   enabled: true
  #   name: kube-cluster

  enableReporting: false

  envFrom: []

  extraArgs: []

  extraEnv: []

  # extraPorts:
  # - name: alloy-client
  #   port: 4400
  #   targetPort: 4400

  # listenAddr: 127.0.0.1

  listenScheme: HTTP

  mounts:
    extra:
    - mountPath: /storage
      name: storage
    - name: client-ca-cert
      mountPath: "/client-ca-cert"
      readOnly: true
    varlog: true

  resources:
    requests:
      cpu: 333m

  storagePath: /storage

controller:
  enableStatefulSetAutoDeletePVC: true

  podDisruptionBudget:
    enabled: false
    # maxUnavailable: 2

  # replicas: 3

  revisionHistoryLimit: 0

  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists

  # Must be one of 'daemonset', 'deployment', or 'statefulset'.
  type: daemonset

  volumes:
    extra:
    - name: client-ca-cert
      secret:
        secretName: alloy-client-ca-cert
    - name: storage
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 10Gi
            storageClassName: ceph-filesystem

crds:
  create: false

rbac:
  create: false

serviceMonitor:
  enabled: true
