apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guacamole

resources:
- base/guacamole-pg-cluster.yaml

helmCharts:
- name: guacamole
  namespace: guacamole
  releaseName: guacamole
  repo: https://repo.helmforge.dev
  valuesFile: values.yaml
  version: 1.4.7
# - name: valkey
#   namespace: harbor
#   releaseName: valkey
#   repo: https://valkey.io/valkey-helm
#   valuesFile: valkey-values.yaml
#   version: 0.9.4
