apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      # Feature gates are defined here
      # https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-config/featuregate/active.go
      featureGates:
      - CPUManager
      - ExperimentalIgnitionSupport
      - HypervStrictCheck
      - Sidecar
      - HostDevices
      - Snapshot
      - HostDisk
      - UtilityVolumes
      - DownwardMetrics
      - Root
      - WorkloadEncryptionSEV
      - WorkloadEncryptionTDX
      - VSOCK
      - KubevirtSeccompProfile
      - AlignCPUs
      - NodeRestriction
      - ImageVolume
      - LibvirtHooksServerAndClient
      - IncrementalBackup
      - EnableVirtioFsStorageVolumes
      - GPUsWithDRA
      - HostDevicesWithDRA
      - PCINUMAAwareTopology
      - NetworkDevicesWithDRA
      - DecentralizedLiveMigration
      - ObjectGraph
      - DeclarativeHotplugVolumes
      - PasstBinding
      - ConfigurableHypervisor
      - PodSecondaryInterfaceNamingUpgrade
      - ExternalNetResourceInjection
      - RebootPolicy
      - Template
      - VmiMemoryOverheadReport
      - ContainerPathVolumes
      - ReservedOverheadMemlock
      - OptOutRoleAggregation
      - VGPULiveMigration
      - VMStatsCollector
      - OCIExport
      - Plugins
      - GraceIOVirtualization
      - IOMMUFD
      - FirmwareAutoSelection
      - MigrationStallDetection
      - MigrationDowntimeTuning
      - CrossArchitectureVirtualization
      - PortRangesSpec
    # permittedHostDevices:
    #   usb:
    #   - resourceName: "zwave"
    #     selectors:
    #     - vendor: "0658"
    #       product: "0200"
    vmStateStorageClass: ceph-filesystem
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  serviceMonitorNamespace: kubevirt
  workloadUpdateStrategy: {}
