apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-valkey-certificate
spec:
  commonName: grafana-valkey-certificate
  duration: 960h
  isCA: false
  issuerRef:
    kind: ClusterIssuer
    name: iaas-wcooke-me
  secretName: grafana-valkey-certificate
  usages:
  - client auth
  - server auth
