#!/usr/bin/bash -e

REGISTRY=registry.wcooke.me:5000
REPO=cyberchef
VERSION=10.21.0

docker buildx prune --all --force
docker build -t ${REGISTRY}/${REPO}:${VERSION} .
docker image push ${REGISTRY}/${REPO}:${VERSION}

sed -i "s@- image: ${REGISTRY}/${REPO}:.*@- image: ${REGISTRY}/${REPO}:${VERSION}@g" base/deployment.yaml
