#!/bin/bash

set -e

REGISTRY=registry.wcooke.me:5000
REPO=cyberchef
VERSION=11.3.0

podman buildx prune --all --force
podman build -t ${REGISTRY}/${REPO}:${VERSION} .
podman image push ${REGISTRY}/${REPO}:${VERSION}

sed -i "s@- image: ${REGISTRY}/${REPO}:.*@- image: ${REGISTRY}/${REPO}:${VERSION}@g" base/deployment.yaml
