---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-valkey-password
  namespace: harbor
spec:
  encryptedData:
    REDIS_PASSWORD: AgAx7ksCNSk7tZJFTg7ffJ9Q6b0VogkHUCfCE3PZTe90MQIIRPAJZkOhLqUnEJl5szH0VeZ3BIwLB/AS5+lpqdhzVaU4P6Puq8uP8pN/AVa0bEohD/3CKvtoaSe+lyT0svvXzt/po+chDmNPkLq8bnKZK689ZBbSZr8b273nObJ9fdjJcGuMWGT/BhNWupYZp6lg6LP4WiWablXGi/DzGDLRjRbq7KNjYfJS8Dw4eQXA3BUkd+3+RwQupoRSCPejfxPzR0yVlV1xR0RajZVJfGf09Kp5d8Cjl3dXHMHXbaE6JE4NQgnLNyeOJ2WR7dgzVMtfp+LwPyFAnYgU+dTF29E4q8PMkGdcJIf+ClJ7VJ0BEBxBhL6xTmsoiAwVSeTJKQ79jJUSHVFHg4JO3SKuLclpelO6ZhVEnPrJmL3gO4qD6oRDtMr/E/+0acm9UxsQ+5kcDj0la1Rtjv3oyG26P4GyMdSjRJOZfejmuPtlpD6xpC32foaJpOyZpjRU5QvwbBS6xE0hcB/9ptr/ZENeZ9/4dU0Re3WdrhQ+H1XlkvN61AnW2UhQD2pY81IlhllFP2hHaxcP0LuTBA1mk3NNDqVgw3f9PssyNjjRjW48VyzuxUTXovAWYeM9arOmRaJAl8ZAChECCm0n7qYbGm+fiFLSuRATLCJkYX0IXyDnE6b1/KQLZIJzKzMx25lQD3Zi9aU3+wCGrR/Gw4UruGlld0aLNgKUNNwfHS8vr7cnE5GUHWgd79PwLMPuFmB2
  template:
    metadata:
      name: harbor-valkey-password
      namespace: harbor
    type: stringData
