---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-encryption-key
  namespace: harbor
spec:
  encryptedData:
    secretKey: AgCH0bxNlfy8mjTF94R++AIx/gIP/0rCl+ySgGnNv8SMCStpTVrVKJVESA3Ol5Omd/dt7eeQgRehzl5vwGSrymKPFFYZpqqRGx5fs0QEBpCtEE2wQa5uJWtHCAXTF6Ca91JHFF5WKVaTVJ2+1Sujyi1QJrMjxFvHRBvqxKTUhoPzHiI5JjPHmvGFxTC1DM3ih4NRONj6jfxCcuGFnOfHf69Xwq9zOJHZthgOMY4Xt6ctGXb/Ri6so+meFgg9rlJcfBftc6/xb8p6gkEopmC8sIsUAahbVcbpS2dRQl1M/gbySRq8fcrNKehQusn1EwCnW+MfvGRLVk+5Tz1ilqugkDsZFktwCNS3dc2yvLZ+aLlVXhTYfjRQs7mBN9357a78xenCfK6SCNegUmNBFMbeKisr+nAUoaLBUiVmiFgZmLkGFrm4iVZsFcUpmPVkyVf17eUPJqkWlgVNd6m3XerGxNDYaNXWYpNfiDKvGGzGss6tgYovKbXOoJEdt8WSRxuLfGVsKE0dPevT/tU7u2p1If8KleUrZCD69ZyMRRBnPLsAQavwo/tMvKOlUt6x2HEh3DJtdGbD/hCnq8dZyzZrSbZ0a8UVot9HiAvBH3+aeH4qbKyq96iH21JbiQlc5Qs/YJmN2v3wUynGJ8nhO1QpKP48jBTUscREbhtennY6UShw5QSkk8PnGzBZmlJNoMytqaEpQnt0omdmYFSeNXKwXIm1
  template:
    metadata:
      name: harbor-encryption-key
      namespace: harbor
    type: stringData
