---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-valkey-password
  namespace: harbor
spec:
  encryptedData:
    REDIS_PASSWORD: AgCiBRjgu/HYuxwHBExE9JbL9hyrg5s3JC4wb/oNXElIpmAPp/arfBcNTFcGJqW8Bg2JRltt3kSf90zRHpcgwXPrpuDaT2RljFCOq2rfI5n2yJKzu8eZbsN7kz9aML6qos7PjjaOkm8dq6PRCcyxW4qnE0/N+SAm0insijxiD0AccvnHMhPDYtoC9jkE0upO7hxc8RYcSjd1O/usI3qcrgJTKFsrO0aukNxTOhIpt7ETI9MFbCrL61Cj7aPyFXrtCe5FYguiWgkJh9EJt7qtb40mA/nnhHl5l1tucyB1q6kJiGtllBIJ5UJDSFW49zi9b60SW3CWJbSHDBFpRLZ9Pd/QQ35VPlwicFFUHVwb9CMzThfXZFlvtluScRG3BWSQ1pWdyuuJHf3G/915DCx1OobrW8KJ93ZweMq6hq0GN+9DYSVJFicPYATjCQiRuUkPik1Wm1SIG2JiSfxEVVvRn3eqLVx460acK9gqNLEGhcboxQL3LMc4a0viXIY/M9UaE3ArSMOYtPqCuNhAVLctte6ovUBWT/hTZL3dtSEaCOQemZp2tjaHgz3p7QNpSxBURr8eZht1KiinSaAJRfFteK/Yh4rWjgpLU8PiKN0K6FDlkxsTDklUcZXNGUZgZ+OyoIwDcWkDMTTyOAV8CcVyByToygnxm/0q85oz4HdlSvvcwugWq6m4tp1Xxk8L6XYxFNR9dXTKuRPfPJHO0pFaTT7uC8fbNMwVRyX4HyR8wjFKAhIxrUsq0y/quvNi
  template:
    metadata:
      name: harbor-valkey-password
      namespace: harbor
    type: stringData
