---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-keycloak-client
  namespace: harbor
spec:
  encryptedData:
    client-secret: AgAEkN/Rv+QkyXwKi4e8JFlwJZy6SQ8dKeMuUevDFEG1zZclBsgXDqPTi72HuObrRcnZ6EFVaBrzewrKHz0el++yjbIzVz4LLTKqtQgZyDzVhHuHeVNzrcf07u4/QI6fkzX9RzdvRuVs1lMZ5jcVydsDc3NH4iElG6kFevtkzeBA2aN07mrp3HgumKxIzMBasyNl480akxwpVEw9eqyNFfkrsBT+EYiBeasGPK8ECRS/iQIk25vWfxVg2XQr2zCP4RwpXss/igoU38hCacEwcFQpk1fHvKKEUm/NImpst4ikyfPYbbAU7fNeqr7sJOybsnJ0dcwTMc8F3Oh9tQhtRvUjfinRpNdzJ3+YgKfa+T1OJiog1EfRxK//kjtg/jeSrFg382zj/wjjptdnp++QzknoFQBNKgkqMlBZtYbnjDkIhmHajlZBBGC/xen3onbFBN4LV2Oq705uqsdFr2wN+bJs+t4Vt4R/702lUIXV8ufbALl3BVUbxOreNVficDmLo+sfURIBceKw7cD/E0++mBXpFceABZrRzv0rFqCZA4AqEHnmDPmbKB8fxkxtpgxHkeLsr6s44jTRX+8Xv4wopIBBC6sq+M6chT6WZEgocJT0y2I3h+XJSkVgqeqA+O13Vp1KlGvpwfp0Uj8SCViZOrRM9VxF8Oj/UXfaoqczeKT2WtsfMvREGS6BqfrNzelzFxVynb8jFEc7ShuSZCCfW7FmniC15dw9JB3qJG62+op2EQ==
  template:
    metadata:
      name: harbor-keycloak-client
      namespace: harbor
    type: stringData
