---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-keycloak-client
  namespace: harbor
spec:
  encryptedData:
    client-secret: AgCaHcwrsSIcbUHgMNVil2+nwpezR71spN2bKFTC/1OpyoXY2Z0PHnqRahWhmY0iaLB3dd9GM/LOA2mNgcDAdvkGcPIB3BwqUMc93lRmpRJXzA7AANTYrC7X5Vd+OSmvSt6WDGJuBm36ot/1ibZqOu79G5QRn4BrOKM9ZNcnzbgKfnmHIGH/HdIR92NRgK6ziDO5vYLvDrnzkwsOEmsCc0lT/b0vrVGr8aS/Zfv2HjQYfvi/I5LM+F5ema3ZVOVL7lVUeglcrshGV1EFdTk1eixKv20y46hs6FBLPC2Od22olLJ17GdQSezvCXhNgDVzKjipgDi4xaI5ykkIv6RjdbXnpWf3cTZRQk+ofewRXJ0quXmhkLtTJALzdAW4rUFSAB+x9nixAc5Ps8XPddVdPY271GTffeYjyECM9c04nqrRjh5osq4NSSwzmJYWrdrk4euTk13qfX37qz64A1gLayxJbZaHd3HLuAA/AjUtUGLWhm09F4Qheu19e8uDPRz/W6yAPYIoiMHGltX/kWMtovQThnpycYKwI2XH6BUYQf7PyyxH2i+zK5/iKAaxpVJFwSlekVhK3niNFVB3fitJlaoHQSaJkAxPET75Jfg0lJQBHt/M7PmCxkRs922vHK44vCMPHvNTOGkrXttafJUL8mDsl5a2ms8i8vHjztqe2/73NJgUvZd2xtF955Lu4EOIOVAF1EtytQth6wslCrYTJRA8tJo0OK9bV4ds2Ppw7MLggA==
  template:
    metadata:
      name: harbor-keycloak-client
      namespace: harbor
    type: stringData
