---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-encryption-key
  namespace: harbor
spec:
  encryptedData:
    secretKey: AgCtRHXGMY7hkdvUYJ2V0oiOyN2m0nnS1fIK/pRDWBZNdJjD9sf1w8u4pNCQ58NkFY/8BfrWTKRmw7jfQs0/V3fPd//SuMcfen2bhd1Zxc3cNm43S1tCzjeFUara9r1AnssQ8DjhXzrHImULNU/LcA/eaARGYtWeqYJzbzjy4pIT56Vgf3BQSx0j1ykRIaWculbwMo14r//YtYLoW7HM6dqG9szHdqEaK0y4pM+VwsQMI5MHjw4Z50cFL6rvJYiLdJN7W6vPe4Lp8hGsV9Xbrg7JNLfFW3+9B0Fng1sXIp52MCJynldU3gCaSCot6FMRDLBNSfhieLAZHQo8F9sKAcdULYvt1wXihxeRmFY2WC3U6LhTHiEwhQve9GEXeC3m/09EevEUsZY6R1m9OUBIlJIs35wb9lGHZi9lUBfRsNrROgNsDobdGIqrYWGPGapHlKg1dppAONKMm8oncXsYeF056ZTxEQSHz9FywKkv6llEfnOdR2iZJyEUHbWcp/2CWy/VwOwXc70NyCkV1FrrVNBnaC95+rf5dE6aHsiHbci+JnM1XGKC2T8KzhqB63OwRNao9ZzYWZ+RcjtF3Kc8wPfXPpjSoYsoYyQcYoLxLzefKEPB8mZiDMipBITNeSsrPy9OSImHxYY2FX4MgcWpxDxos4YsdXaHpvhTUhI0nIbEs/z9N9/Ie4cqOenF6zxGgSt30lOMBNKo/zHtskkqE68E
  template:
    metadata:
      name: harbor-encryption-key
      namespace: harbor
    type: stringData
