---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgA85PgHk+GKRLvc8Iie9zMAdgI2kmshdvUSO+KhZWvhvy8V5y9KJxA2QdfMvpOcPtXBK9U3kIh9mJpBc5ePOkF6f2fAGJc2l4CYNQ2G8we66hpiiIEyoaBdckppjXaX5dEVua6iIy2F097zJaHjXVnw/EsRB90Mx2nI8ANiwkYSgBEju3zhigtTf/hVExrRT+yDjtg8ofQJ04vWwKtvt27ZQP/Nno3TeAR/bepb+siDc0d4WHImFDgqSEScEiP6M6/QzDstjPz/lnp9eF4weizWvenM7b+vWFZcGwJAcsv9vvQsfpMZjVEBLVV4JstM2Kgjbo1WCgW/cBxOm62LJWSsUPUUV6DWz3sBueXs49aR24vdF4ojT8VPjs0QReWxR8mEolDleRz3LmbKlLw3+lnUcGqixl+JCl1rIs4saoPL2/F05uDcRVFR0jg/ZXxWoQnrXnXc3OhWLhaBIdmg0zR+NgpVtIdFDOF+205sdqdC7LOHHXTAcYn4G8bg9qgRKOV+vDDbZJKH067zpCOcueZJBWy+sGABUWYW4Hv95GsDQKyn7nN4NvR9jAbNiDowBMff65Db3K9NopHvX2THZJYL9RcOarB7Kz9Fvd5x85WJ6VPfzX9UsQ+TBM66c+BjzcPkpkhbBBvD7k7NDHCxp6Mkl3u3xaitO36VCCsCHjk4vIEw7C7i1o076pzqPuxBmVkqtW8kVZQ=
  template:
    metadata:
      name: harbor-admin-password
      namespace: harbor
    type: stringData
