---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-keycloak-client
  namespace: harbor
spec:
  encryptedData:
    client-secret: AgAM7OHM7IK2stxR9l8goBo1uhF+ZoU9mVyUZ87+yzO53ulYLWMoKFEFLn9ZZnKo/NdXeCYNyTMiEgWcY0RdIkXJroUS1fTCrZX7bfhwhCr5/iSJRg3N/eeMTZg4NDB/sQXYqmMVa9+iMJVGGaCymyXpdUtwRhES5vLbfM+GT62KbP3AjHyIPCFtPidRKYuBbcfnLNwGEn9iwvdGJfES4x2WUwW4KQtJO1LsagM1H8bERbB2dz4URRXsUi25fDD+WVKVSjGi2wKC9mcc9j5ZkZAx32NrvEQztyZLRZkveqy2ayYBXi1diTYK5pUKsVh2vSvM6UHDEvS9pLymTgB7yg3cA3gm9a5+Vy6LkCCkQrZ9291U4vC8Gc+Vu1TzX1/EGNwldCU9iW8MahNUEqTANtw8bKqDatSQpHLoXiWMjggX3W6Uhk8YXiUaeWIzYQRV/fwMwtSRDyYGI1WIpRFD2cKibNCstZBcWISZsX/DASaXZZB7b92pipECD3kUQve2xWjguaUrqLc6If6tU3xJ86rKY7n9hYWYvkOTF5PWcDeuZdPvSkuY04ADgIN6BiooD8vs3jUKopfMKsvml7n6VylHwa8W7jItSUhfLfQg/XqhHqHr5sWYZOqeXzHKrPhYOanQOmC8lJuVgkV7WnMIH3Yo1WkGmGju1GBxFpWUZbIGmq+hvlKOo9CGxV7CDaTPcUTfD+TmTFcKzTcTH7euG+N3sivkqC9riAdkJ8Yh3L/1lg==
  template:
    metadata:
      name: harbor-keycloak-client
      namespace: harbor
    type: stringData
