---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-valkey-password
  namespace: harbor
spec:
  encryptedData:
    REDIS_PASSWORD: AgCeeaaY4KdbXb8YXb9qvq/LCy79J5tDuCAzLkElbg8TYCaDw54LMIHg9n6n+W1jotfWb/49WRinji0P3bS0/bFZIvuJ2WWE9eGUAx/3vl46FzyAmaNQJxzCMowpD0/rAdHa7MLlB56JKW5xnKTbDJtArxu21m42P82nSSk2WIP12aynxTjPKKi69+dT8PVJArkxo56k1zYzFSYXEILPI7gZsRl25VnQuUu/7RByQPeUXjGJSXvo8Up1uuhYNE4/ZQm4m9IDc3COXFIHlNV2WO9rLpRDzaTlG3ocKZ9XySZVtKmNDNNWD2MvipLeNK3xocvRWaqc9Mmi3ZOdq1gp6SEzLiOhHoJFFjriYGu6rKdUTU11l8s7VoM/IQSsFIB4A4uwTSF9CBMVoLriZdJZwe+3fWIqNceJjIPB/sl2iX7QY0vmsbAXK4O+gCmvzcBf4c0g6JuZfzJlgIS569tfBk3Bc26z4qCE8P5Qt4e0DBiZZcaC5Qgd//IJQpL9aDAIeNbnaI/i6CIthl3QmFsyTI1kCLofqsSP6rNP8SESRBMid3uKx4rRoQ23dSexdD8154gAbmAdt9LUucg7KWs9mOEbk22So60eUYWBOmFvPuxzVN6/r8l0DULPW6Hhbtl6j8x632WS+q8rNnYZG1CVder9sNCKc6QWY8uwy1p5k/sfKA0XVv2CtwV1lNLViB6OdoynoKmU3XIxQzzyZQGsuMdkkOoXVz7T84xs+4043mASnb/mVPOAsy75295u
  template:
    metadata:
      name: harbor-valkey-password
      namespace: harbor
    type: stringData
