---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-encryption-key
  namespace: harbor
spec:
  encryptedData:
    secretKey: AgBo5fCPPojyvyiIXcoqnhmZKgJb9dcCyZqrU2SWRKVL0tpXpRJDFpwlwDBUkkJs3a0fZ/q7vkf9MGPkRt1Tsb8rQgFQs6429O7MKF0E12TntHY173JKHV3PKQWY5AJ3kW1Y7ObflZxdOh2I1anPnWGfDq7l3SPwgcH3cqh1juxyLV3cR1eJjp/MsIwMJBWdf/Se1ye5cOCJKOnw+H+0vGEGrkyXIXelWFGwig5H5DsbpM0GW6LgjZkTQC3RniRwce11ATjJdLVsOkZnsFRnEPRlVbmF0SwOzcLF1CcZwgghwcJElJQsBYwofLc9R23P7rvIA+fjWVFX0TfdvuWJT0Qx/lGUPLo23ANJUkRp/NkYkrsY8JFP7qqNuXj976sMRDMBoAvI+oGtU8Atg9+2qUDqqIwEAzhtFJT9eGBfhXnozgyxW0aI4mTPF2rW3NHNYPjH4nhZo6SI6GsbVx6bbbez/lSwZ6ck4W5N/MFwGOHK+cv4YnVlP8b/jQ8ddr/6hq+w7PQOvkAZ4RbPZPLGNbvD/AbZSDFp5eAjTXvuwlN8pjnGN52OKrQk4OONHelrGC+M6VxCUmeuS+MUyL1hdx4IWoDR07bFpo2T259ELdb8edGX7YDe48DfL2dTqF3mERAnits+Zl98riRUYWwjFOrK0G2FK9QrGITJ3aoWQQDJMDcEqy1gni8amKH9O/1FEfdSqrq5ZdPn+83RLD3pyWfE
  template:
    metadata:
      name: harbor-encryption-key
      namespace: harbor
    type: stringData
