---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgB/KWLavdAuDckwXqYDtzjHX0L4mLEJUngGNEzIOkISsaERxVb/ugaU7jZuLvuCBZKCI2DZAJSIsfzdwEVI1L+NKcKgjNi9dQ1FAgWNUHLae8rZ1iqHYGrzB3ulyXUF91EAOnVlncsefjsi24hcp633CJTGsX79ZjBYwODiLkMV7hmotCuz180xp2v+cVaIGjzwKudHjoaMYL6aTE6zmHliwaidLuuntgyHKx+FnLe+uEixx6L/zQmQjLUQcrUsRaxD1/h3KOo1dvJUz4wkcgQxf8jDdgxLwSHdLI2c+VEXf8zhPHD4O7uXYeCuTZjYQ9wWWiQb57d0Z7rXSTxaDgB4FTOJSC5cDxGtRfNbSKXKPaA2tAMAHxeWzeFrghVsNGzC4Wk1PEY6Lil4HWwX6CybZ0pNJm+nDGt8kn+5Lv8uciulB58jolXakz5zsMEO8iqd5eVfJcczs72D46wLKf8W+Ty0aUBwIDe1aAz7geEtY7S142uoRDQLtOkljxKU/lMj9aFDzpedVf8fitbOGSUbWUcAaNt2P5n9HLu925/MlJ+SZyCSmSti7HyTyFZul6POASr6f4LCY3pleTTXSmfOLACxy4j3vg9RSaMZ9EGVT4p4tEpc1y5bATmcBvRx2apn9uMjZoyM9ztTm+CR9VIc2+Dn8JNDdeDpV0DBOkx4IiO1Z2C4ylJg0F0/JK97Y+rnGx3j1HU=
  template:
    metadata:
      name: harbor-admin-password
      namespace: harbor
    type: stringData
