---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgBeHPTX06wqM9hlkJGgDiA8TpwdLFxc3XjCvhmENfTOslpw4fXnTw6Hc+6+ozWLO39oz0Yti415l4O/xsN9ZDSH17wS1TNZ0W54p26GOvOgslMt3iM5Tl7ai2qn1YmWhGLdOVH25igUKTKT/PKgUiKeQoOkU+Q/ekhUVOkYik+DCxdEeoNg4JUQd1GVMLM2j/Yt6WA3W/Q/xyO9U7HcbOmX2UdJS/9XzwkqpEsETAEOb5UDjzFNk3v5qTuHzQ31HYJPkCWKe6EaGHw4XWXIhHndiigteo+XqxMTe1vHxC9qtlSssKmXPAg+rV8ReOffy5S76lYbus3xx9hct81IaeKuHFapLvICkLxuDJHe5st1w/108GeQZJ0u2+hx3BfxSi1lGy9ZOUYS0vdJbsIxuBzLUJRsil9/3LksuybnsXtgxbZp5+qZZHrbZ8s6l3vEwsVPKbYGEzYi20X4COuJsuV8vNZrUjdvWEhyqlk9Bs/v7AkiXGMtbm472aAcAholED0Q1oaVXA8AgA3Gv8yTx15H1QH5VC3O9BxcophJNYEfjje0MAIqZnyiYvVXwtzyEuCaWmvmr9MPC+ctw+lGak0q85lwg+cXYv+Jcav6qhxiCo1TWdA6Ma9PTxMboidIBE0MFX9h5jl7LSV54A11GAdGjUPsZnvAu20MiS61QD3YJdmChirip2bS/3p/XLWPFV/9Oa9H4SU=
  template:
    metadata:
      name: harbor-admin-password
      namespace: harbor
    type: stringData
