---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: william-credentials
  namespace: crossplane-keycloak-realms
spec:
  encryptedData:
    password: AgAPt+Bi/EuKfVl2AoBZiXwLkJpr4Xy4JplDN0fRFJB2YJNxRG4B6qvITah369f3ZDfffc27nO2yGaD3orbSYlqOG+oo1SBStn5z1UciAkS4ByBXFlM1d19CgQ320AVvn2/32MklddQkYd4sF4rf6FY7xnJwPkp6CrawqAFhm/x2pHH4SDzG9RDSx26fUjiVmjuHLOog02B60yXOZAohBr+fngdnRwyn4TnOJmeZzb1GUergTHeSYe0cmEjqtIxKFgQ6BaRp/tjVMFhgRnxiCanmD5BY0rp1cT5NekX9H6t3taZNSESKCbCGo33ZeaYB8wqFwvmpKFMavx0dyoJLULI61WHm+algjSngtzwhIw4sxJFZXoVA277gyIyqK3/ksRiz3TsazDHF3UxJDR2B0LJiidlGiN7a+Drvu6sSI7d+pnLQKlXBVZF1jGQBOqqyLq/CbH/S4x6ws/cdZ4qqFKiFnmuygk53ZB3a0VpocWzINruI5HWs3EN2Mhl+nMTukA3yyfOhF+YWyfjwiduCo2MOP+jfJwni+26XEDzshyiAhTIAp/KqTms8BOu/ey91Sf0G64rptkASgqJ4nw13BFzl8NpC9eoYjnTcJdHt2exqXMw4mxhRa1+rwpTeMny6dDhZh8dR5K5BO1cbRc/e41pbdOs/rnXUHzN3Tjm3G8jxwI5RAKSs6FO9ghk9x8hKsTm3Y4Mv/+/BBGAYhRgbfykCndEEvA==
  template:
    metadata:
      name: william-credentials
      namespace: crossplane-keycloak-realms
    type: stringData
