---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubernetes-oidc-client
  namespace: crossplane-keycloak-realms
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgB11xdvrH5NxeI5VPJfShTJLelQLa/uL1b8D8zU/vBnOQsLm4mzt3xYukflqdgbaY1kunq6j8HrGIceco/Bn54T9pn6rnjRNzRJTMObcUJatu2fOtBZaW0tAe40tUA7g3ClkD5JVSrjFVELBNRc11TiwgbxlfLBJSRRboAm1tUDBL35NmmDYHGPMWzpavFAsYieRmq5mA/VoRMbwooan+1R4E6l7fXpBz63eSfnMnYh/9jQxCjAAolq2/aHgBXpofL6XkeYo7HlaICIGORUK6+N+g26gEZCr4i1RulXzg1aIYrv0KQBLA0CNmcWnXmy85y2JrewBupuuARA7molu723Cay8G5p0uJVMB9mbaeCzuVf2Xr03/8ldC02r72Rq5QHVCyMVEZJiCbwP96DCGGS3DnmKS0ffa0w2eKuxhtWikQtzbxqeAiI9+WeHqPr/XZ/ttsanXKENVDylhlDoDGW7ZJDzNlWyjRI24rKwDegrPH3EUIuGrkeKLb/xpDT+zHXL/SKVhsBeJZCAwYj3nPunXMUj59VDXMV9p00m3LPzNa7Gg3Pg12QSDM6YaCNP8DvXb1nrMAxplYuPpNaZn32cm7PKhSVYR/LthM74unAiDy8BQ+NzsK/tJ4QxbJzkpNPov6noII36mW8fORKUZWg7zHuBdq7bqBOUxpv++v6ENgWx0OBE46ojkSu03pOjYy/+PZtRU4B5Yy7DLCgURnxUH6WF3jXTFnjqxDNKhmSXVQ==
  template:
    metadata:
      name: kubernetes-oidc-client
      namespace: crossplane-keycloak-realms
    type: stringData
