---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: edward-credentials
  namespace: crossplane-keycloak-realms
spec:
  encryptedData:
    password: AgA6qEOhuBAQmo4IP3ihOkE6ddbRwIwSMGHhkngdFbw2vVRZfgffkBG6Ensi7gLPR30cx2F9hRFTkfhI7DJ1Q26w8EEdbHTNIVIO5TR5zTMlb1KUTBCuztR9NPM2v6I+RDEaoORh4bZw43Hb5BZsMR+WvC7ulOK0m0eKg6kajBa2XnUvhVxUBMNSN/ApWtKCkZZwovGYrrlyGytrEYwMNzTjJA9WgQRxbuyVpbWLrEZ0uXDSUS+JT3Pe4kTA64mZvniLz/ZamtmG81WKKwVBsXZnBO10rG3LzLsTrV7rtv5wKLFxm6cXMwO1cg0qn/Pd3+xTsEJbuKTB5GiTdNPtfo6HqODA4EU2N9GAh+oB29/OaspdgD1sIw4JkiS/axWtEhiDU50I02WOlifCaCAmjD5LWZ9vvXYSyPhcF5KDtkn0rV0HcZT1SvGZ7V/YSn9EjFckb9Zupj10MfYxIoD5XX+qeaZDYTU9q6+2kCKcDT6faARVg75JZX/f4Fb2tKxn8V4RdqBCBTR5e32GQMEcHWwEnyxKzePQiVNtHWCgcggBeNamfR59yaX0TCW44QvXlG7rTLrY8WQKrLklVDBd978x7ECKHGQVoaQolvNJG9lei/MEl87AypWcp1NezPAwVNmDxkMW4gbM79SIcBzLcB01Yb2uqeKjT8GQa5tYAh9pimjMRItOgAcjKb+XoQdevJw9HwMU16xb0QxIc5sJAcydTbSO5/w=
  template:
    metadata:
      name: edward-credentials
      namespace: crossplane-keycloak-realms
    type: stringData
