---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: william-credentials
  namespace: crossplane-keycloak-realms
spec:
  encryptedData:
    password: AgCzPKaw5vUvI5RmQseN60zcvAoV9rPjJcFW6bC0/H0PMs9ZmZTUT6fKSBWlo+H7ssd5xmXGSCgBvwGgLuh0W6VPIRCQOKKwGC/VK5RMnzmZafAdjUeWvm/Zd6pkdAHV9kU+2vbmned+Od43jPxFvn6zP380wWQYb7aTLsUBgSTlUJGWOH7uQ6eDtDUgYsoISaSwqtbknS5dz14EcnM3T1qixxXGYGJX4Hnhkotp24+E/MxYxSNusr+C5+uFKXMfgwnqhNwFAesBsCLqyIF/u5foCQq3nrZ4rwymRT66QAtfEYRrZuaZ8wu22tyarSCOYxBNDwigtPxnpBePe8hUqKWfQrf/LBsksmXL9rcvaK8IaEAY/juIBqh7UimWydnZz1zEJr6iRNXqK3NcOU/tlnRy0N5AMyqWm7cmM/WhMD4AraB8+9q78o/y37zw/X9ZhA+u5iGrvGOd3Mx3XozQciaSRP9W6u0X22oUAHctbMeOOdB0z4i0tW/6Lsir7aD7J0B3NC+VjFILZrzCdGVEFJmTc0ffmkKDVwXi6SpybWMsVpZfXGkcHUo3M2WqHS+HKpIB2a/SYEQ3LHJ/Mz5n12qf6yE8BefvSucbQwJEdmHrpFXwaIJ0tmPyeoMLdKkuQ+QfIUhgiLp1/hSeF5iDi2LIh96gaV3ptCorY68aGlehm0PcFesuxp+mARUIYrdPflu9uQqqPS9uvsQQDdByCANAamvAJA==
  template:
    metadata:
      name: william-credentials
      namespace: crossplane-keycloak-realms
    type: stringData
