---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: edward-credentials
  namespace: crossplane-keycloak-realms
spec:
  encryptedData:
    password: AgA2TCa/hPataLQfmYP6qB1jyOR+mRezTmNdhqzIKysVclPCtbCMavMVlnnkzOj8RNjVSj8Ha+ANflcaZh55wCQJXLYhinto4Btqa5EnsDE2e3ZK520X3TcGq96PV+dUi3SrbsKAprwiiHnbDcQQMBwrTceEI75Ygo0+ALv7pVG5W4aNs4g7CdgL8DVdsZHSFpN/LCzg15300Y54CIYiFw1dYslGv3Hak29wJCKn1p2OjhvPq32GCB2bvBynUot9tdwIfo6Ig2w16poMZpJXKQSf2XSrD+EfWReHfM8cE+UmuUZ1KORHBZJF5kwCozkw5vp6QcrD3d7aBMHoP2Fn72S7HXo5pVrhea87l8m+ZjDBJM5h0Q5cu3fN8CqOXSqlsACkbWaCcyFianiRP5neBtJt0kTO/Kirgd8W9y/Ib++L3YezA2MOP1+Th58W/DCg34Ts6rnXr9Xu+3p+O1qkAGO83izd2Dyp6U9q5EbEHIRfet/1mlR6FDnH39xz3VnoJaj7YSB7ITuwRyzyT1+c/XRzRaE/1wtGoKHtpXNZinFpUYvtgOL9L4RVoaWB08+2tXR24ZfVImVNCiknYGdXGoi3h658eyc5PFvqQy6TpSKyYGvtlvxid2F9NIayDUuW5ho7Suo//h07tV/FUa+6KqdiK400jc9EkNljjvyLFsdRELA3GV2QTB1G6f934Zsm0Cznb26bnKPFPzDy1V42j22u9JBisQ==
  template:
    metadata:
      name: edward-credentials
      namespace: crossplane-keycloak-realms
    type: stringData
