---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: edward-credentials
  namespace: crossplane-keycloak-realms
spec:
  encryptedData:
    password: AgAYwhlUI7OnsrRcl6oOu9WhHSkTE4C03nOK4kZmyiUY9SCqDtyRPs0PZy2CKWNlZGGs6ugD0mfoZS9PdJ1fnxN5Ed+uQd3w9+WzwVBfDXmrDRN1fTdATj26cq3DsTxC+9hi4/z6tUV9Rqsu1J6MSEaS0Fjlu88E97pkuQDYxG/TPxUYo43+S6dFAaFusn1iGYcvhe24mfZVGe/f1tgo3/vqQDZUXRZ5e4Og83m11yQ/1UOXHxYoUXEsY0Gr0RfuPHpp4AzGcRmoYSX/pV6r+ZsVJ5cQ8vnu4fQore0Q4q+kL4SoEfKRUkN8voKov+inp0qHoWDePWpqXwtQpEmVq6KgDOfl6MJNTzYor3/8SuqVPNfX+2tOGvsO5t7JBTDWsn4Nu8HdYYMnoFabSXz8OXGtGMI5oMK4xthxg617MmjU8ffsaZOjLTHcIfGxlyrzknLd1S4h0suBWCvBdsUCFfx2kNqDeuvk0LjD5V/D7YL5sxeExaq/oZ7HSnmXddix8UW4Q3ufns+ZnzmzWfGfq5NPWelOm5TjZlL3ng6w8cx8jOY8McSUZf8xC1TUw07j53QkLEVjhQxBzm5Kp0cNFs4U4t2TkUwgxWEsoxcVcc/xUVeJje6q0IdCvKQdHbAS2aGyT7LNiYjl4xDBp7z0XsflD6wSv6DzqaHZ3Uy2smlPtfDIE38UccoXVgw14pI8inA6zZdDIXtJMQhdpXoOO6tfSwtr4Vw=
  template:
    metadata:
      name: edward-credentials
      namespace: crossplane-keycloak-realms
    type: stringData
