---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubernetes-oidc-client
  namespace: crossplane-keycloak-realms
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgA7B8H+zw568InyFk9ZBaqy4YtqapS5o/ofkn33b+bdekFE3rdGPp79laeE0YTEZHHRXAU9WOJAQLNajWogiVM4zrQseekggwqb9+V1QhXWTirdAwuOy998wggMrnxlgwBJF3Pf7xPneSaG5AF/W029OLZa9jBfR95Hj8MldJROcnsJU3lE1qustdlfquZwDnjJHnVf2z7+M0Zpjg6vnVVTE/Oj6gvw0iJfC8HgCQGB7h0MmdsIMKyK9or3nF/JxWQgNofCYI978aMzJQ9lt2yclaUABL3qn3yp3YYNTI/PcZhFWxyeFis46F/72y982r3JLo425SM8JWhc2wrBMIpdZOhyA+H4Gq63kZWXUiiVzf6VdZURYVPYhqYeW5610pBkFK3SBNTdvgvZiOWphHorwfc5poWSA4svRthO+IJAi7CFDbuPcFcA9BP4jBIlimbTIKfUAVUSWi2dSdZ6KzX0y2xDjtqIf0oyyuOWZvEgJkjJFrfU3wQAWdhCzSYiqdhQF6ljax+aaz2yG/54ltSH5s7Fw5G9kHRr/ys1wZxh9sTmFF1udBlxZBVYP0OQSSQRCvyjdJ2xRChR4bWNiVlnismDOyBfZXqbKGFV/U9nEUlVHkhcQNc+VaOAb2rT5GzCk0xYIUzIcPqR6Gehr0bxcWgfzh6+MxMFsGIyUn1jNuykrhrw6xJuyc3m1triFhLsJNRvO0YKggiim0WHZrLDjmggeBIwQ0pw0D6y1t8oqw==
  template:
    metadata:
      name: kubernetes-oidc-client
      namespace: crossplane-keycloak-realms
    type: stringData
