---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: william-credentials
  namespace: crossplane-keycloak-realms
spec:
  encryptedData:
    password: AgCITVJtT0Pxh3uhLW9rM6ojPe8xTMzfyj83/TXgWff8a6AUVq9dssodZ0vev9FxjQc99BsY9mtuW3zskLT5gNt9OZ7Eab0Qr/CASMMYheivUndWMZlxnfVNZPuBoxHCywnQDefgqXp/hFBL8oWIsODJ+XKijs7YEMQgqzHhUSzMPqn5paMxXpCo+E9c7X2TjPRW+rCTFspNpOKq3v53hwFx5Whe6v1cIHAjwXEktfEy1XtrH70lo7/QiLTdqmIgTkwtDioJV5MioVZajk098asb3TYUADjhEfMHV8N66kli3BgY6kE6b3TK9dKRbaYsq/zOHBcNHSgfHIA8bUcjxjKbV31VMIGl5YnDtXQCz6p5L0MKjQX1Tg1uPORuMK69MDPPMXJoLnrCWmnRysehh2kp3okdQQJSDgJQL/NibxR2AGnqYW1R8Z0AeaQuSig0hCxRdGFdh+zNGToBhEpRDh/zeUyvc8hc3zt+WjjtyS9bJC+yA/5XB1u+oX/6LiFOflQOEifqtfQwe5ETmQ9Mj/ttohFCXSS/HXCoYjEh/tdZjB4EatYXxtu460mw5PHvrRfkr8nYRbJpU0VBcWlULT4cQt/uDkMux+CuZfJ2hVoJuPluHjoYJtuA7yvUc0aufzcLjLopY3N8KYcP4+hGPcnRlkM9iMlovVTR5vwDOPAQcOaYrGtRTcXv2eOgyT7Sp04j/QFJ01ubkYERm0luj4j5HQ6YsA==
  template:
    metadata:
      name: william-credentials
      namespace: crossplane-keycloak-realms
    type: stringData
