---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubernetes-oidc-client
  namespace: crossplane-keycloak-realms
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgCX2mlIqQC3M7uaHyQkpivlBxJ1LQdp9meBgAebboNORFAY4O69kWKq1cJvwW5VePWbWlo+f54Hu0YRSemcPe7vTjrthdktDasG6yjsLk+CfLKHdgQAdJVdhh2ZrKnauPNYf7mmGiFf6kKwLBRH1A15eyJeqUJ5B6o/v4j47ErRizwOmTEBFHXZ91R6xrcRkp58g+sE7jd2FKMkSzPtYPR6PY8Fdl1XSn0kbMCsqQBbeGzdGSoUmZBq0jFbirVt47fBaeMw2KN+yX2Pwgx2nCFoQJA9dj+zI//3b6mvCMiSeugEWB49K+W+9OcMbvpjUduGExTEMg3udBSLVzfKVRXl9n/+GhDpvuSzjREtPpus4HiOaXgd3Emz9V6om7s7587efVZJ3jRC6z1AvVJ1L1KUWqB5+mHbOa+KPNqAQHJdUjwuLp7Wsofz5X0nTQTTPbwhia1SGOZNuQqdEtmUmJsmS4d0CaLZ9kzhcUvtsVf4D8rmHqQZsO7ci9buBO2zfyq6LNtyEMHrVdx3EUeALVij6LvpOKhXm/0OR7K+9VTl74JaIMIbX7BvYPOwCiF4iDlD/nJxuqjcLU2uC8YHh+2aPdzF+TQFkh6HVGLF0N+OnwUy8+k9hqoot8IBl+6obDjis1nLUzya87AEU0F3NcQ0h87cFpzUukFei2HrLmXcsolW0JCmqS0wJ6YCcYYR13oPRaqqDebo3RJPXHaJfzvvlqu3GC/6iHbTpamirPaE0g==
  template:
    metadata:
      name: kubernetes-oidc-client
      namespace: crossplane-keycloak-realms
    type: stringData
