---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-admin
  namespace: grafana-test
spec:
  encryptedData:
    admin-password: AgA+vOObnwW3HPDQ5oxJjalA0e1CZ6plYXW7/L94Ncdb6u8xfVcoF2+0TPZ9OE67XlIO4I24UIgcyn3IaF0vPncwvgmBG2dHPY0cBPEk3NfWANQpw3Gxtn52aKs4vae9COpNm5OowCWHJHLcRlbqy6oWInxHeZcXkxXPUKSUBH8BnJso/U2SriYbqKqC18xrQe7isSC7mhXWzPW3FRqw1jQhq5uMI6JT0ssqmukLxsFkYIXrIUpfD8PfcIVj+VNyUq8GE2HsE5Yb9mGeqwv/uM+wrOnk/V9VSuqN/GmCDrIXeTW5U/AKEuTbAx6+3niOF0hWSCYJmgbU6mYvsIFqUVpxEdXvutDM057hApzYpZ/GvlB4DWdJRerM+Go98Gk2YXVtrLaE4QnEnrpJB6lqCqSz2RCiSqgam0hsxcS+qz5lHcon7NF19EnovK4ZX9Ww6/WSom1K4rdbZQeoKtp9wgaZ9aVT9g1DzQ2uR0Mp2U4IKx7CYiMUgAj0xL333QjBM4PZEyHFlCskwFz3SYYr8m0vaqknwdUIMa8vVwQwT833WqbE+6vJKz75lJ7ZWKNY8HBbp6lig4Bd1eyoszM4Sy24TtZa/0HZ5lJCuiKjDg5qtg4bV6Q+j6YW3xErHp3/98Z4HTaIhLO0+ybV/ya3VBndpjX3JkvXt9LvUNevENjHbMGkhQeLkWjii6WKy3VSIjhDb6HDSncI
    admin-user: AgCX2ZFuhQvRWzpv8N6gqr33jHtG/NylJhQnn7b4lFqJxJXuqzvSXUzR+CFweJ9adYFhKWIPAjuHTrnCyVmNk/kdG/QQeB5fSxUN/2WYTAemEZp1dC4xnb45OByRgjhpr8shba5i8LwmDq/t5MemVYqlzRJVJB7vURn4pEMj9k7dfEBaLpoaJKA/lMJfTODKCYJT3sVqvDZXzt8ECc0Ic26LkSdSj9iuLUv8Ikns1LHXT2OToySGDtl1Fx16vIrxtsNrWGpVRA5bM2id4fAB1U57G1nij9mFiqw8XCgpQ7HvCsdGVbMXf2FvAyrZWb2a3uPP1qJwzBBnwQmWAzGPhitIEp6DHoXQ6S7F2mmc8WKsxfEAIkMWM4L98Vlhs5d1ovBirdDFDasoYGKaeB0KnEqBugvyk8YLZHtOHIm7hd13MyZn2tEHy9A0r5Sgb6YOlEFhczVo7dftDy58lMbgAYGcRY+M3yglRjl4LioGzW4iliDzcBfOxXFIYTAxdUDrH4xrZxrHiAC9gKF1ikrjyqvfElJmmNWj7KGutfklr3vVB8bsqyneLSl1l+fB4EEy1wROgH63ompFYz7w9lCXshTpcpWGkx3mqAaPlQeoJQvyzbuT1FVt6tWCH0s40v+qOhTGM4CqTM79eNhUUw1Ca5yyMottXFKGLkWS96wyTEMFrt+WueHzGHnnrn3mAoBvee3REFLhkQ==
  template:
    metadata:
      name: grafana-test-admin
      namespace: grafana-test
    type: stringData
