---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-keycloak-client
  namespace: grafana-test
spec:
  encryptedData:
    client-id: AgAoIR4qppdyX7F8ki9i9FPbVF+j/Fp4VWaZDsyRgoUITQHRQecVSTKHC56k0AkxZXU5w5WYX2fhryb7jA+EkchpRmE6pgq4CmMWQ12Vf+c9rzASbLAOHm2XD2XlDCu8U5mA6yZ5WSaHU+myONGkziZzugk7TZS+OLgKRWiTR9zoGsLSbKrgqL0bTNfUaFrfUo0nn8hTiiHmzTnjtg5IzCPSUqlw3Cj2a1+eDa3uin7cVtk7cO6o/zYUMfC0bAVXg0ghyKkaNsAxDRl96CaWUVwUDLrNMvxbqRwe0vjHRdwPjzOfiFJb9uMKgZvzYGOdYVCaKNQexpma57DZwT8slQW3x3VW5HqjWngvRmpv3kbZsCOX46n8/i9UsjzsoHO/4YbFOHvrxXs+IwF4FJpzcyWGtCPvqf/XvBeu7BzuarlWIlr9qkuw8tkrQe5jqTHEbYxD8olA7OxLp91NXIULnSQ6gL17ZDriQTTkxLWl/w64M88N6DBnvIAK+4Hzkl9u/dAHlrMYtwwchFoNDOHU5zRDTw2cIXgzXzf+xUzUKMdxnvdiKQ1zyw/bKQo7UiATsE6PbxJhodQGK5Th2dKFuH9MAs8MtZW50khKSFpOmjy4y2nT8gtKMabBgp5AmjVBALHYg32iZlJW/u3jv1XQFCLEGgeBbtlQs+mHkCbD61YNi3HnOpyrPRMFgJbiSDCHQ0beEzO6TdES
    client-secret: AgBvtQiP3F88cjKvIte54QEyLvkF3ceukRnTr2ddDAES6zI1u5LG2aXbecUXiNS5NvH2ok+J6nZjepBinqJ0Rf1uRRZ6jbZLPtAbhWQrboGls7fzfjA3xPpYRHCGTx8cgd05So7Df8j4Rpv8uzuoG+vEnj+GJJF8GGeH72MECl7yKFcU3s4AVAk5HEnyLJ+RRgi1xC2SeMZVFEvzwY7nmlhvtaw3uYcZrmPczGXbGFLyDEIOXhHDJAAin7aVTUw9yWzUz5I/KI7BA/uVCozFjIj1sVlLOSsb5XAD69eOHZFWe1guz9E1smSsdmgsFvOuzJa0IA1mOz7GSeDL/NgqyNzhAOW70V+Sc90326K6ne96L0YVkLmrFGAiIvrBuxXKBlNf5eGMm+1g8KxfscOz9Z7mFee2pk1IL7+XhMd3n07QRM0/kkaXaNPOBQwC8oew5SIz/9zNl6xjyI6TdRU5gkwbjuflSvdo7NmvhcLPX/YRFtfXJakPWuqWWspT4EaWm4soxApZf27R1zVI9r/Qzt/+3O6DdnyeWeuOccNHeiZUPqenni3KEW33sFh2eoIGCFNV94H3L+zRsSqU8iXK0irJ9zrMl12niSoPxb1fpDt9BmPl2XWOOvFx2wbQVllmPP/QFT2vXpB2aPfcOr8zkvVgqGwwNuBbxSebzRjLWUD7kYvzKrHGhgC/u8imZcfy2PyV1W7Kd1tZ0l6zBvPMtivnTsSb+/7rKryHgxYtIf30o4kkf26d/qlPQfWxvm3O0t0zXMKMHHS44jr+636Ww7z+3D9QW5yMVBsVAPKdqPvLlyot8TbBTA==
  template:
    metadata:
      name: grafana-test-keycloak-client
      namespace: grafana-test
    type: stringData
