---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-admin
  namespace: grafana-test
spec:
  encryptedData:
    admin-password: AgCTS55jRzhlgmMeiA2SdfHG5k7dfrU5AxZZ7FQsyr4AS1jeUk5hcKUWhZlSPLjspWyMkr4bslfh03SZdMDRc/MTAJQTayXWSW8fIrtfUufvs3XYdA4v2RDmgdjTppLH5RABotKmxsLf/MVO9k6gVGhMuCRux8TOy+WoXTreHgO23mJFH2wJrMZ1Dl58w+I5zT2yc0xlXOZYdLI/bWW/hpYM+gqbyxfnoAyKrGMAYdI2CAAW7IXU1aEFRtd+BQpwr4D8QTrVEpsmuxqQHymJdic/2BM1YTFXaKy7pGDygOkcKQgo7V5erBX5C9KHTnc14A2PW7hHgw6FRxoT5N0RNbjRbjeYZar/vG5p74P7JY6vheO/piKfHGWhUwylztOGkZBN3isJ0APqOe+VofIaQzNSAH4DF8erTtRcJj5puouT7HnE7/6+8fTVNk5XeM/OwGpdolQj2UYYDAKuAWqkMAxF8D8T7a7vYpT5xg4QTGV4hwZowopUStSZuvmJFFgb7aaKFIm68C1L17hdVd7XE2cAHg75Gct5PhkyVRXX5MJ0TTDzb0whpgf0YAa32IsEZlhs7xSqfHi4GfSGscnkmz9Vwe58ydETPtnCFAgXhS7BgTSG3AaDTxjIPuvZunr/N6D34/x/B/mE7M5yZJ5yu57wZq19PtlMG4a3F+W/BM5511RE+Y7I7PBzP9NXj/tzMt+w5Xa1DpC8
    admin-user: AgC0xvr5SEBQyNdsX1bKPq+V7pakfdD9aqra7/DxMb4ZKAhFRh1ugX4NLfkAZ4Yfk0kAmDTwwkWjr+AbH0KovrOIKHMu1X8VcMz5YBB9umX+O5TjUvHgd47bdXm7g111oLLrmuLwgm4vLi3GXRPTIxYvJgL8wA6ANnH1/ILZQJY0cM/kNaeuuuiOBy+39GhE8UhgQF9x/5T7DhFDHfHpbnj6bDTMgMPL0RBS4Gcgcuxm+nwvSKhFWR/io+pP8gz3gvJwKxfXT/bSWWnHrm2UL201zX7bg3cZSyue1XUE+Pnp4L3976sUucKNDk/wfaJ1Dl+jRlkNdxG6A3qZ7Pp1Ag/4dd+5HBto7k2C3rnA6oQwe9XRtKtmKqvDebBFsqGed/FZz0HUbznaRdg8r4V1CTYBwQp24OND3OlKURApfaw/Cx/5jCyRh0rIviUiB9nwjCQh6fexGN1rsIbsQ1O4CMARty1b80f+kDdXyo1jvs7gQSaZcgJk6+icLyXADN4iwpOVZctJgKp22INvszaTxg0RGCRLwh2pQ62mcSHciSlcN02zx89L7B4AjpOAL800yawtKiPJ8AkTJzfWuVgq9FzK4iaUj7FGIja126lIc4s6f86XWFp1DW6HfpFShp1cQ9KwDmSH3pJn6c8mfMlWJNlZhXZcHrQrp1pKcF0amA2yF4dM4nqtvKONaJ7AQQRJx+5pZcAD+Q==
  template:
    metadata:
      name: grafana-test-admin
      namespace: grafana-test
    type: stringData
