---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-secret-key
  namespace: grafana-test
spec:
  encryptedData:
    secret_key: AgBLTNoEsBsJEJxZ5AIse8I60t5tIYPt6xUTsOT5TnDWXxv2BqCf0GG+FUswh3FPERyu0WZz3wSfnrv7+i5lx+5cQou5bI2hcagxoJmCeX8Udt8QZx5cfiTdsqCIamOMSHIqcofe66R3tNjezhrDpbj5jwp4fQyytKrUd6/9sPKh3mOzcDPlw+RDpyqZ/pKKJBSJStCd/pL71+baqjNMgjv5/4esNsvh+aBuWY8p4m9aXqO9ln/NWHbCxrJ6f5EipRAMQ9tJuehYSLTus9r69VBOVPOK7blbidd9NHK69No2XO0FpFm8fbF+McW3QY1PNieR9ISgiMATq4FLkyHzOCv5ut88LffRAKv2vOWX4Ij62bsyvlEvZB9ddvgDeiFGhCJ8FTnZ0fmalB0actQkTAAzJX2ElmyG/QLML+BmzmiTYb9GIeGiGKRC5K3o3J05+pFiYGZniFa5HeDRS49NIHuRucPC8hHC9UMSt+XYDSSafvB5Pit3J3623TFlvBBZ6q0m/UiTHYdTqjFjDHMLxIKSTcvtGyO/C58KwV2tV1NkQHV2lUWfKUrmq/tSoscCiN3tPS94JBUQUZDzjsW+sLDJXfWpiY5kYFDJyd8IZfz0juMPj+T7eUWKZPOgSaeg1Zt5RETTGzKJKQLX6b/3GZ0BDsHbHRq0/XFRDF5qEgDaKuiedTSGOWQRBjXaKNqs8+v9l6i7/gvvkS0n4JnJBhPFz2/LyOmkXiJ0ZlKAIHH2mCQhw53tbRmtnnjgww==
  template:
    metadata:
      name: grafana-test-secret-key
      namespace: grafana-test
    type: stringData
