---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-keycloak-client
  namespace: grafana-test
spec:
  encryptedData:
    client-id: AgA9f5oTwaXH4x8r55jBgjCgBF5zTma+AhRjx+dWSO3PB6aAO4UBVarmjn49Ckm2autxH+A4kawNwf1/6Q8mSvYMOw+Q4LpKODXGZmCLmTbFmzaSkVt7HPbhdIklLNj3kL1uM8PeUtZLNg34cORl0NywDufPLf8xrCZx9eBYcBT1ZLziKjHH0FARVxXxilEhULsBkMvMvAEg9IpRSYp8QUChyliYvEjc/CI+nlEZu7X0ooEKfk6Jm7ESwscn0BOBaeFHuMUYNxrxVDuhCIiKI1m7+00wfUJTGpNAaToBUQJSAOdlFYtfU+aF/fEDSsbG3pBQouiLUIU0f1REYeJc+uYboJksNaZnl1gOIB93L4rlIlaW4dRzTSdurtWSNJs6kdr/5y1H/+inYgk7YrL1Yy9GiJ0JmgZWjDGVlBvdVhoci+BIra43E6/6r6/hkp9iNhs3hSJVzezU4FLbvACc+54C8BSigDbBBHBC/u2aM+IHOlGKsunhSnSlWBo5XDXjLkcYYDinKXcyT3zdlRcdiLvh+L5GTQqvyQOMV4SvlxSfLf8/f6jMKcj7eNb5km7ILHd3dw9UHjCwd71j6JgvtEjmun8bLCrTLz9Fzh08EgYj4GTNNYEgajWNmTNdQIB7KwPkAQFQnJt8nZ2JCcKC0RNmSVzC6bl1yIX2hwUerVvFUfVQs+SjmXb086YpMe3MEqSeOodKDXBY
    client-secret: AgAy5pjelu3KVUg7pTb38lk/xPJtkB3rFmKiVzS1xFmL9HCctVxgnpelqi7RFGEc78rdWvDYmSsZtgjVqszb6jNEd4XiD0n7KnVb5Or/zACeQCeDwkK5CIGP+UZ1ACl9fwZXu+Fxfax8hv4enSLuhgVQ9u3nrYwcEKwrkMbnSIwO7C3kWLMUnoAxGUeFJ4ULDe7HDKQGPj7OlHIc4XRxa4TjV3nRCWlbE7yO5fV7Kkdbgesq/gngl8XDV17OZKzxuKUn6sFQoEV5TRnr7yX31SfTeFkKAtyYDeu38nFZ6id9kQdO1A3VN3i3SfByRTPJ5dsXQeTVP97cB/2dKmwXDdrECUpgHbHWNKOg9sBaoBBcCKhXDHU8tzaL5gW0kPNoc/eq28OhhHJLsW8oHa+I15YGnDJVMCkH8wZR4lA1pY7gGrRvhEF4Ujgy7TLxfKb/Z1OUhx8Ucruc31IhWQxOwDmJSCbvBPBBnPgaeoJK+q00o+LMMr6F3VIQ4rWcusUedAGLakOLks8bESasm1XRg/OIeM9Bx5XzL9VUX1Fn3QCcXrBN1A7276MJBmUlpFM5qBG7qx2oAVv6YDD/Yba4JdrefZ88JJgyiFK+U0JZMqZBt0fBpVkf2dLrP381/DI1qZbjZGb6HKYiUh+xeq4JL7Dkk5aP3t8bqKOe7cPJTQ7LUNl1VH61fCxW2jB8urKr4cSqz3Lmum2iSA1tmmUDjArx/ozLuU2XHAysgnWqzh81w7NjsHVh4gNXOUZDiiR7PakTZV9w9FI5MCcwBsFZb/lZTIG3uKrQrZUVdOooXLLnsZ1liyaAZA==
  template:
    metadata:
      name: grafana-test-keycloak-client
      namespace: grafana-test
    type: stringData
