---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-keycloak-client
  namespace: grafana-test
spec:
  encryptedData:
    client-id: AgBmS8y4fqOpbZSnImb9LoJBvj5JZ/7bgn5HXvjIz0hJ8i0pzhY4s1b1Q/pnrnQqeX2y6fOuJWb48NgeE6cpuVWQtabVyVa0mASnWTuKyj/pn2GgXRuluH+BawJjWEPHdiHJ/N04jGCaeOwMJdvmISf87TRw7SiVl4MyA6sRmTIpONIEUrcUHhCGdLxFmsMiaPXBGz00VHescMVkosWqbx27xhZsp7sKQ/RfsgyDuGdOYxCa7FJD9LVZfTyJ/xBwUV+xygbtReBjUzJzFwJJoBsLHKzUxyCyfUafqJ7r6uUZXqWGl2Oxjq9aZIBJmV3LSVwc4MU/BMuoUtxUYd4A9TrLNU4IEl0xqIzn3TaowKlMVRo3gN+oWE2Y3x2PuAHqnucFs3ntQgAlVWVREXZqXPHgZDL7uYQlbjutlw3vzjhYSXb0LjADiPM+mPJLuctr+iCXB5+oCKx0HWh5/+xbg6Xdd7PO67KZ61AVxIzb7jJ1yqfGqVxKl3VeC3A4plNylcLAFSXt6K6Uutn92NDCWFpRWx9bn09L9lWV314jRfxuPPfONL8POMjIKSBhB5d/8quz3JrYyBKXOdjvSZIoEi4WSM/3b6C8bKURjsUj49RkSxaePYQH3tbh7cLiPeSCzeYYnX/k1Kpi8elB4C9rPq347eyfVfexTyxfgy2pvQNsinctv2g1VPmBCjEL35VOHMwBlzd0Pf/T
    client-secret: AgASA3OJuZYQaWs8ezfFrKpzzM5cMdTMK39b0WIOkk0WkNX/I8NJ3s6Ynwxv6yiZ3Ruhz+sIdamaPC52SFWt19Dmh9MNw3kKDwB2tkbZclsS63XcsLouVGUFASzVDKxJ84qHWJy3bUdzJTz94bXqnBa5srWUSiPml0NrF9ZEXR98l8O3BZWmFJQV85OxL5CGBvWoHcvu/UIeTBAuMTcg6wLk9TNBItNEvM3J3lL075p3ScPgyEkDz+x5F8pYE1Ing5MzaDlZAoFkvk1D6y20/0ocLx4inXDyyzB0OreeaZ23vVAk+tpymuGubP4GdMtZ6XKDvLN5P8FsZ/0LJ3w1eUN9jDQhMt/IJN0qeCqCVLONUX2j7JsUHwR3SydlxZfJpxq+Pn7WyqvITiRpLI6yIK3D2wEZaDfYsm//GZn+aBlc78DjLz5HFHyLGn+X3Z5GIJhcwzgRXrT8S2xHLcjtKg9nUubNMuCaMk6ykUqkK3VDz/6mTu27ZUb4s6H55GWsVYlg5bhB+fgdbn0EhyR9sFgKFbzFPcHhAVz5ud3JswVnhwbEe/pEo6MgQO0Xft5TTPi9ufVX7gnrffi2syb7OtrEjf8YNyKFieOyDe9wOeuwqVBzv0tA735TAjHpqBVJb5Zj01ylfK5uFw1YfyBl2SKAGKcOdoH1nWpjcGBuB96IP1FfYH3N4L/kGJO0SPF0/bi7Grv4V7+kSQOzUUOQg1VoZamXg6UtReJfRUUxwQg5mECwVhakrgXd0AWIIliHlZKkwBf7HCXX6Y8Nf+Fq+qLfhRhcrw+sUbDpDJnZzQBxhqhHxwokBQ==
  template:
    metadata:
      name: grafana-test-keycloak-client
      namespace: grafana-test
    type: stringData
