---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-secret-key
  namespace: grafana-test
spec:
  encryptedData:
    secret_key: AgBftpLS+pJ9lFss0gwIP57iJpWs/H1rZ7Q8sqUVmceDVuUVUQUofCZSLFdeUaoD9ihI4hjKZVPO9BrN1IQDs3bK6jL036K1VLygKDXiLk+EAlBGi1BABSnipgHUCrtGNeOYKhfz3ywleh9pz2FfpFG7Cefir8107G95hjeYNyU38vJLcziDAawlEwfRhiERXZ2vBsybfVs1NOk8Zu2YsN//Wmke1O8vO3wNQBav6Uc5j0Ti17Ta4od4q0mnUl0P9Q6fTX2GOUf+hErPZ4q4V/L1iPRtjXnL+T9eyGAOzSLDNrNdnzSOZRiRk44mdeVLMLBXS718m2F0d0DrIUzcblOZ1XeHbqxQZn4iJRaUrC5QFSkE5xd4NC0kuEAUu542vZAkxFDE47ehQBO9Fl/U9RH+oYLHFb99j0ToV/0dXACmKW1yt916hNp5WmC/mTzMnyKl33MdIT1hI9S8Yp8Km1TUfWXwNSlJFoU/j34ryV3E1/SW1V/LB0AO1utJof8ZH2i3bUbY+h6cEOcRzkRY5o3myhZSTVQhWTbUJpX9I0ZqRD6wIHvgeppD6cmdtmZQyvHLqVUdQwxN6aoW2ujjE/Gf0qjtaofBLg/qTr6Q2t4eutRez8U2NmxpSrvh/D8S7lgqj7CB8nWpjZX7+4Ke1+mZgUMTUitzS5esPe7FqQP4w24QxwM04EqD3BiMtG/YA++Ycfk5LP5uQlMlxJ49ZHubjjoB05JOGpne7aOEc5w7GiyykYB+i66o2ooAvw==
  template:
    metadata:
      name: grafana-test-secret-key
      namespace: grafana-test
    type: stringData
