---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-admin
  namespace: grafana-test
spec:
  encryptedData:
    admin-password: AgDJBNDRAYC3lXU76OehZUuk3u+4GvVJVul+6YZU/ZlLIF3o8l0dLET0dor9QuBHw+6QfE+SajT7a771oFAm4lJ5auEFR3yoe5pTA2TuGPNSPpiRHY66ikqqTTICvNK/U2pSolJ2p3ZDgOjXh+ua9Xasu/8gZ7FfcVfcN7Rwxo+IUlIhrgPRJ1nuFwsWZoDpC/ODQvKh3kMiBaXQQxang3Z8K2XJmx9rCMUYjcSnYj3fdK4ARZO7h5f7i+2gb7eA2b3xus62KROhWDZrm9sdXZvbQZ/gz4ocu6IHYZ5hR/+tp2C8tKJ6evwO8vSKg1turL9lSRv8X+hLoGLQXEFHMmh+mPY8rm6PaVdq41bHBaCGrwcdJdzK4fnVIzM5V7NL9UbX93qDcK1xnDhrsHd1Uaw64ckdypvVawyPRwICwAKVsZI7Dk+sGNyQ9NmX5m7Zrzvi17VXf5ctdfUlla48MTaLiIQy0fur/0spNies2hAAOz6Y1fRNTSSeGU7iPwAy5YWu+k7VsKn43v7nn/lUYn/UubD3TByTFnOAz/fH7bxt/f2UIb833NmVfg7RBU3mUwFnDcIqScFRgv3DHlh9Lb+27S/1SEy+pca0RUiabAWmIyS87Qqo14nKfY1+op8+i6/TqgSUsLtDcyTOgvAhRnuHeDyUa2O8hW2/3/PXoTy06e1476N9PKvKk0p4+DlMpeEcrA8USJM5
    admin-user: AgA3nU9pK/CYaYhOaLxOpAP+ZbnJnK0zbrOUW/p2YuP7jqrGZZhTDtZIWhQaFu9LyvQbbL6NODlTy99P95FeBB69r294+XbkoGBvaR2d5vDHfP5HkG4KYxQuFEskVNSnMptFohfSYjLfwwgM0vnEIB47URPeAMmDcOmNCwIZ2JbszBeSPNd2v+Y2LrfT/ryYMl/4dSHcsf8LtIzwzdIouzIBQ141cBoZiS0785wGmFKpJk20btzoEMJFg/EtAts5oHH8nazu8AnuaafC06TMp3X0WZepeLzS84ja4ospNzVznmjrj4FmwR/8itucpXq0R6FYLhvECS0ztv01v1q4M5gaeY76Udh0h5ur7dkLu1DooRRESUF9pa/QwDg13zYrTyDJWkMRUHRYefTwUHP0sT6qRJTwoH9i9ab6L1bkbgabHxIrlgVpPXPEPyxyss3WE8L6amtfzm6PdwZtBkIa1pU9kdDgpJ/E/bbjSeu2nxAw7g6xwxoYnB4YX7YcSAUxYHLnzFQirj5qVqqLmvg+Ou0BgaV2lQTn6AlbJerLLfth1plv84LsJcBXmGyvx1OToPWuqJ9ew3pSmjXnhZIkhUQ5XtWiVy9Q3a8o2I59esJmQNe/fAWJXDmi6SZ0hcMI499/gxQInld0KVX6fAr7E6+V8s7KRkW7PDZES/j1+SvptsS6elwmKqkUHjyhxncEGjgRVSt5TA==
  template:
    metadata:
      name: grafana-test-admin
      namespace: grafana-test
    type: stringData
