---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-valkey-password
  namespace: grafana-test
spec:
  encryptedData:
    REDIS_PASSWORD: AgAMqrLGjSYa/HDViTTlFip1dqm82tW912qZt4yVE5NqsDSd4t3UDH93Ec33etroVmnDY54GfQqt6DcBIh6K0IFx0XDcXLJRYnIL/jswFAP3qlEc3pmDX/m1AMU/eviX1QHehN+VOb2qdodA5n0BuQktJuJo+tbARWJfiBIt4b8u2xNhtZJ2l/Q16fAkDwDW3bIpGNP4/Cd+lnFsJao+jAJLkR5hO9gM7hOUUuthh2LNTey9McRZDjJF1XAHMNsmmYdsMViaepOUhQdIYlgEA4bZwYDmeK8WZ3chyxMVGNtEB2WgAScBUa4JT7aS0HZPFAT3VjXDBDeEExPUyS5EbStegBtQ1EfcJKtC1oZKrSan8P65n3ldO2tOf7mltg++lwwE2ZmXc9qYdB/Z0FmoDdMB1eE3HTjhrGXZ2G97nLmbqK1bardWWRrb4MoWRMNuASOp5y1DOMCIIdeSM+KYwHoD5ElFPuol6rtlCr1+y2CJKyBx4I9kg+IbgM5bI3Yzm4YIzDpAxT6uJelFR8XZOEmNms3oiA1HcJqZqBgEAxUxkj9k4Pdp14f4NIbMuvzMMbgnoRnFTtXr3//Wwa5Xp0GOMrYxqSv3S6Ar+AToGxkl97fdctou3yYJGG89/ojv70vAG5EVEGQF4jV9sTxB1P7GvyEa4KlaBWYCSmv2Y/1bnYMzMNRm9tOfJG/46JKLevd0ovPkg1oq4sE1YvG2mKK6NdreHC8svVygubjmcT137YjAd+pn8lmCnK6B
  template:
    metadata:
      name: grafana-test-valkey-password
      namespace: grafana-test
    type: stringData
