---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-valkey-password
  namespace: grafana-test
spec:
  encryptedData:
    REDIS_PASSWORD: AgBiO9s6vUf3zwFFDLVL1LcdaGkzZmPQKs2sKh4A+3ZghDZqztRxCc331c0t52tbgPrUikVZXBY4eFRUjsA7pOmCbhzmsTcd9Nj1fqkg8DSfraJ37dhCmv2JWrutjtWyLzLiEUDJjliH+x5aESPohJVRz/oD8yZJFv53dgjYkh320Xodj3bYJaZiV+t+Vf5fOCuDl4Xqgd/l/8W4tTTrWR2TpiHkdqOonHlt+SbUaPfPeGA8LHpFGkJX38I4vCZjTe4+qsvVkaCcjNRrBhOUbKY06rNsng6V+GtrRn25g0KVL+Gkkk7diwAcoAmBFOWUZf5D9glUUy8x7BCRve/zLJ5xDnSxqDhpHqD46fm2Jze67tVZKjNKpRTw3GI104kAMCs5Mv62ZZ0fiX2cDX3BTSSJFhsmwFZBaYXpRwFT8ToOU0siVqERLwNC5756hKHes5HR1Go87UXNhKjW2uFewzSo9GuqIXpHzTkBIJFpFDmREG3q79MdPmAsTof5LNC/dhWdvz/IgT0EjxpHIxhPYQMjoWU+aLgWlzWM+i0bCdQ2A7EpHkZdc5eIJXLKS3lBBnpL5pN1WIAcQvao7H5Hg4eVacr9c1K4m4HqAmE9tB39kN8AZxVAQc3JocDRZIyuNPTr4SPd+qzgCvAiXFZh+FssvCzFDP93Kv1aXac+H9oy5Jtv7dp5APtbvL7Bain4+IeX6/tAvlVrt29XyiKftfvQnHzkMUCPI7fXYLiEmQKiqGCrCWMcsh1ZCwBX
  template:
    metadata:
      name: grafana-test-valkey-password
      namespace: grafana-test
    type: stringData
