---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-secret-key
  namespace: grafana-test
spec:
  encryptedData:
    secret_key: AgCseJ+88CXxZX8l3TNfzeqrbEykl61wM7Zh5cmuUFndo0BPd+SjnwFd+XDuQdkIJ2gGY245xPTrRZHASSH78FDk8ZQt/2fJmCT0nj+VghsmdTMMEpCHzrHcyEYhAL6GCiHFBtAxtZz+rXeAtSeFxWjEc88aw0pMJWYSxgg1LQuNjoyRJML7WzXb9QytAXopiRJOpEToAy2TsyFKQPfnq5DQ/ipXYM/sPFhkETXZlhBzHP+Lp2Fo0aj7pmE7dxTMAezj4UyHSugd1t+QIk7cMou5nGOosfHFgsPvID2cV3ISzN0Pw41vsFWa4jDoQexxBsTBAa6rUJhYOJmCNpAxSVhS536Qu4TkUztS2/wfr+bHa9Nju1LV/0vtTdptCIh6ZfuwxwyglN7sqvZuA/egLvmHzrbKNtXOEtqdvhVQdMAu/iEQUV5J4jSFS+GU8AdOakPYQGzkd+dt6g3H+Bdp81MzvlVqOgYFiEtl5nTu7kjZs7Ava0JK4UVuDtD5JJ2k026bMPxxPwdyNvxxULGAlQ0/9Vyz3J9GFIYb/bEfAhqhrQJAei3lbMDj+U1XpMPT4S2qXS9jd7mf52fCek+WDj29lU8oWWW3MwjAZuRngQ5uQb1Q22/eN87Z0NkpQ2YQwXhGkHYaMCvmAU88yKABQYzZhSqUE6Do4Ls3D59OjfF+MubtFSSIdsdIbhSmALPzp5NNCG87BbU+LFLJLQU92jysA5kdsMmfdzv179Hedf81isLc3JLJGXnOAcZdUg==
  template:
    metadata:
      name: grafana-test-secret-key
      namespace: grafana-test
    type: stringData
