---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-test-valkey-password
  namespace: grafana-test
spec:
  encryptedData:
    REDIS_PASSWORD: AgCnqVWqOm8bidn0jB3G47AB1PLKv2DsyoX2KUcZ2dpinsSRW2/rHQokgawItTXk09ryhpldrkqAAEPz0Gjr0+/Zs6ukM38Puke4ZqvCwPOxI7fYrxa7HDX9q/2BVgCWqcUsmQ8Erpq24u625di1yUPRq/ALFXBr3Em7JAoWBuAANFYqcUnY+Pu0Sg/6Gs5Wc6XIS1KxNMqTbjmRDiZ9mFfmm6IxWp/6NsefzZJB+66FEQZBvAdYLIx653GDEemnGbeXpv7Oc/nX0Aom+bDnZg95nAzivcjA1iz/0zC2R9PgV4BuhLLDIYtQIALc2q7SC3LA75kZRrPUywGpORK9wpJF9e2ZWynb5wmTMUS3JufORSanqctyY0h04j+DEOaZGwnr5Pl5JYzxthTxBkecKGahyEx8dt4ZDBgNJLmP7AHav/6J/nLk+3YWVXzQy323s337rTKVaa/F8cbFA1IAWr/zBtlOm68fGk5HGqVnI9NphaLTlk6wDSUyZUwWJNRXou4oVy7HyqL0/6oXRipQ8lP33e//CAGl0FzXi6FSLqgFszoTcmDJvTZAnBqJfxMKXUj3mW2hE5ZDxCusMpiRz77RVKuLLAnn4Ac+FjqYF8ecA4VLJdCtrUJFAT9XPTuNzYKunlZG5i6LHa0V9rN/DTu6G15yUh2dTWUvwxB8+jty1IZCwydQUF0yVQx/9usRa2xrOyrs1cr9x/qc/cQC8c7Y0OFGJappe/LqEcAMC5JViDXeC9lHSHVpvzFh
  template:
    metadata:
      name: grafana-test-valkey-password
      namespace: grafana-test
    type: stringData
