{
 "title": "NVMe Exporter",
 "description": "Simple health dashboard for NVMe drives",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "NVMe Current Critical Warning",
   "type": "stat",
   "description": "Number of current critical warnings",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(nvme_critical_warning)" }
   ]
  },
  {
   "title": "NVMe  Percentage Used > 80",
   "type": "stat",
   "description": "Number of devices with nvme_percent_used > 80",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(nvme_percent_used > 80) or (1 - absent(nvme_percent_used > 80))"
    }
   ]
  },
  {
   "title": "NVMe  Recent Critical Temp ",
   "type": "stat",
   "description": "Number of critical temperature warnings over last 24 hours",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nvme_critical_comp_time[5m]))"
    }
   ]
  },
  {
   "title": "NVMe Recent Media Error",
   "type": "stat",
   "description": "Number of media errors over last 24 hours",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nvme_media_errors[24h]))"
    }
   ]
  },
  {
   "title": "NVMe Percent Used",
   "type": "timeseries",
   "description": "Vendor specific estimate of the percentage of life used",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvme_percent_used{job=\"nvme-exporter\"}",
     "legendFormat": "{{ instance }}-{{ device }}"
    }
   ]
  },
  {
   "title": "NVMe Available Spare and Spare Threshold",
   "type": "timeseries",
   "description": "Normalized percentage of remaining spare capacity available and warning threshold",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvme_avail_spare{job=\"nvme-exporter\"}",
     "legendFormat": "avail_spare-{{ instance }}-{{ device }}"
    },
    {
     "expr": "nvme_spare_thresh{job=\"nvme-exporter\"}",
     "legendFormat": "spare_thresh-{{ instance }}-{{ device }}"
    }
   ]
  },
  {
   "title": "NVMe Critical Warnings",
   "type": "timeseries",
   "description": "Critical warnings for the state of the controller",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nvme_critical_warning{job=\"nvme-exporter\"}",
     "legendFormat": "{{ instance }}-{{ device }}"
    }
   ]
  },
  {
   "title": "NVMe Media Errors",
   "type": "timeseries",
   "description": "Number of unrecovered data integrity errors",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nvme_media_errors{job=\"nvme-exporter\"}",
     "legendFormat": "{{ instance }}-{{ device }}"
    }
   ]
  },
  {
   "title": "NVMe Temperature",
   "type": "timeseries",
   "description": "Temperature in degrees Celsius",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "nvme_temperature{job=\"nvme-exporter\"} * 1.8 - 459.67",
     "legendFormat": "{{ instance }}-{{device}}"
    }
   ]
  },
  {
   "title": "NVMe Warning and Critical Temp  Time",
   "type": "timeseries",
   "description": "Amount of time in minutes temperature > warning and critical threshold",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "nvme_warning_temp_time{job=\"nvme-exporter\"}",
     "legendFormat": "warning_temp_time-{{ instance }}-{{ device }}"
    },
    {
     "expr": "nvme_critical_comp_time{job=\"nvme-exporter\"}",
     "legendFormat": "critical_comp_time-{{ instance }}-{{ device }}"
    }
   ]
  },
  {
   "title": "NVMe Number of Error Log Entries",
   "type": "timeseries",
   "description": "Lifetime number of error log entries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nvme_num_err_log_entries{job=\"nvme-exporter\"}",
     "legendFormat": "{{ instance }}-{{ device }}"
    }
   ]
  },
  {
   "title": "NVMe  Endurance Group Critical Warning Summary",
   "type": "timeseries",
   "description": "Critical warnings for the state of endurance groups",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nvme_endurance_grp_critical_warning_summary{job=\"nvme-exporter\"}",
     "legendFormat": "{{ instance }}-{{ device }}"
    }
   ]
  }
 ]
}