apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        default_type text/plain;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        location = /healthz {
            access_log off;
            add_header Content-Type text/plain;
            return 200 "healthy\n";
        }
    }
