# https://argo-workflows.readthedocs.io/en/latest/high-availability/#argo-server

- op: add
  path: /spec/template/spec/containers/1/volumeMounts
  value:
  - mountPath: /var/lib/guacamole/recordings
    name: guacamole-recordings
  - mountPath: /etc/ssl/certs/ca-certificates.crt
    name: ca
    readOnly: true
    subPath: ca-certificates.crt

- op: add
  path: /spec/template/spec/serviceAccountName
  value: guacamole-guacamole

- op: add
  path: /spec/revisionHistoryLimit
  value: 0
