# https://argo-workflows.readthedocs.io/en/latest/high-availability/#argo-server
- op: add
  path: /spec/replicas
  value: 1

- op: add
  path: /spec/template/spec/containers/1/volumeMounts
  value:
  - mountPath: /var/lib/guacamole/recordings
    name: guacamole-recordings
