# https://github.com/grafana-community/helm-charts/blob/main/charts/grafana-mcp/values.yaml

replicas: 1

grafana:
  url: "http://grafana.grafana.svc"
  apiKeySecret:
    name: grafana-mcp-token
    key: attribute.key

serviceAccount:
  create: false

ingress:
  enabled: true
  className: cilium
  annotations:
    cert-manager.io/cluster-issuer: iaas-wcooke-me
  hosts:
  - host: grafana-mcp.apps.iaas.wcooke.me
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: grafana-mcp-ingress-tls
    hosts:
    - grafana-mcp.apps.iaas.wcooke.me

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 250m
  #   memory: 256Mi

automountServiceAccountToken: false

volumeMounts: []

volumes: []

metrics:
  enabled: true

serviceMonitor:
  enabled: true

extraArgs:
- --allowed-hosts
- "*"
- --allowed-origins
- "*"
- --log-level
- debug
# - -t
# - streamable-http

debug: true

env:
- name: MCP_GRAFANA_SERVER_TOKEN
  valueFrom:
    secretKeyRef:
      name: grafana-mcp-server-token
      key: MCP_GRAFANA_SERVER_TOKEN
