---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: terminals-api-key
  namespace: terminals
spec:
  encryptedData:
    api-key: AgBwFwpHeoeMfTSbdl4Rvoq9G8ZfGgfDQkMGqfI1ovQa47GRtKtFgTyzOhBywGoj1BV37IRywCHaiMoSdHh2c5VlG7+/Pqj96xkEZvooYxR5XMDKNIlPbLiYL8sva2nYd0h43Lnzqv+dXqgk5SdWn3iRH0xRhWrqXkWAR9KeKCShSqHQr/1OVvgPIXEPey6CuvdnGZXMmbTMpKwZN0ZAdAujkG1myQkCQtnCNXn6PG/FMwxSCzN6xZr1kPUcxZUFk1sWhQOOs4i8pVY9WXMD5kfCeHrj39MM3uQUMCQMF59YrHj8XayDRxUrN3zofzEdS++W4gsP/9S48hiaEqVCeMQJCfjTnuVHJRuxCOHxXrdPf14wvGq5bEVwsC+QBkzI1LioX+Pkz9mrYhyVr37YgZd2PzkPqeamEBWjf2QVjSDY8JKWQpwfVuCYUAhj0mawd/71OAL1cmJ0qzn6mEuQ+QPEsRPeLn53Zm85zRmgFtKKfle/WjXu2zqfP2657Y1N242EyjyJg29yGUfca7pGpW0QJw03kst/jk38RYp5JY/3KB/u7/9/6o6g+SvkM3Hc9J7h4GGuQo0NWFZ4D+5NyUHnA91npsteg2BhNwNroDIgMguKtvqmdqpeagnj+6/usib/gL9YYA0sHyVe6ctuXd+gnFw2zhe5sLNd19mruE4NUj/dwkGFVRxVDdNCv+HlNZYl7an/aLlcJgP7fpLF8dFkDobAVstrXlMnurqXH2mhsYOwJxy1kd5T
  template:
    metadata:
      name: terminals-api-key
      namespace: terminals
    type: stringData
