---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: terminals-api-key
  namespace: terminals
spec:
  encryptedData:
    api-key: AgBQTpiN7FElJOVTfF8sZaEhMEZR5Q19GLHc+EDBUAh9Cuofi6cNk6Q1i4jtOwlOK5O1w/Q9us1XC5YfNbEomCPvUXmkLyMGLLWMdzpVLypudXsgmI59k+7u3vWU7/4pr/zD7Q+D+41lFIQM5eMwZX7X6ZjHpQBvDmGh0rPMd/aFLQ0Ep/abbeMCGQ43uvDmcGXq3CO90QB4UG1Wh3yuacv1lPS9ksshY4qjdEwvbGB8v7sIHipGKwfOiDKmdlijYV11/OqvICGdJ/vk/q4PeGwPaeaL7HZKU+wzuzvvKottNguwqJYDJdgS7T4XWQuVUaJ4mar7IIEgnZ9Uxdo5uloE3TgZMt5OQTHfnE+rhQb00aRkXGlKFjvX099cD6Pvbkza53vm8sBaWReDndWs0j9NIF+SFi0HTEAl8WnHIv2B5/BURTyNnNSM/pWyfKg9xlcqzUUUbh5/ZH6vlWdgvLvfcanrCxjkHMKJrhyXMHmTwwBWJ8mAKtEvaXdO2Z9/qPYVwUeUv0Hw7mZZvy4juFramb/vGVsdjDP7+n8C3vcymHXemKGt2wn7zhJVHlMlMKas080eNeNAgP6wWraLaiQg1bSMLAnN8pEkFzoJSo6yzdQcHP/u1cSSTIHJr2KcZBiBkszi5YXV3kH2eB8L7u8My7JLGI0DyznDiRYSu+ToJDWramvQTNVRZQZJR2Uf3/jOxgL9Z1pvw42P9o3Qso5b3L9mihT0J8ByEZKeyCobASWNzLUeylLR
  template:
    metadata:
      name: terminals-api-key
      namespace: terminals
    type: stringData
