apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner-podman
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-cache
  namespace: gitlab-runner-podman
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: cyclops-fs
  volumeMode: Filesystem
