apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# patches:
# - path: patches/mounts.yaml
#   target:
#     kind: Deployment
#     name: rook-ceph-operator

helmCharts:
- name: rook-ceph
  includeCRDs: true
  namespace: rook-ceph
  releaseName: rook-ceph
  repo: https://charts.rook.io/release
  valuesFile: values.yaml
  version: v1.20.0
- name: ceph-csi-drivers
  includeCRDs: true
  namespace: rook-ceph
  releaseName: ceph-csi-drivers
  repo: https://ceph.github.io/ceph-csi-operator
  valuesFile: values.yaml
  version: v0.2.0
