# https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml

csi:
  enableLiveness: true
  enableMetadata: true
  enableOMAPGenerator: true
  logLevel: INFO
  nfs:
    enabled: true
  serviceMonitor:
    enabled: true

# discover:
#   tolerations:
#   - effect: NoSchedule
#     key: node-role.kubernetes.io/control-plane
#     operator: Exists
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: node-role.kubernetes.io/control-plane
#           operator: Exists
#   resources: |
#     '{"resources":{"requests":{"memory":"128Mi","cpu":"100m"},"limits":{"memory":"512Mi"}}}'

hostpathRequiresPrivileged: true

monitoring:
  enabled: true

#nodeSelector:
#  node-role.kubernetes.io/control-plane: ""
#  kubernetes.io/arch: amd64

obcAllowAdditionalConfigFields: "maxObjects,maxSize,bucketMaxObjects,bucketMaxSize,bucketPolicy,bucketLifecycle,bucketOwner"

revisionHistoryLimit: 0

# scaleDownOperator: true

# tolerations:
# - effect: NoSchedule
#   key: node-role.kubernetes.io/control-plane
#   operator: Exists
