apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-recordings
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
