apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: guacamole-pod-exec
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guacamole-pod-exec
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: guacamole-pod-exec
subjects:
- kind: ServiceAccount
  name: guacamole-guacamole
  namespace: guacamole
