apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: guacamole
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: PUBLIC
    baseUrl: /
    clientId: guacamole
    implicitFlowEnabled: true
    name: Guacamole
    realmIdRef:
      name: iaas
    rootUrl: https://guacamole.apps.iaas.wcooke.me
    validRedirectUris:
    - /*
  providerConfigRef:
    name: keycloak-iaas
---
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: guacamole-role-mapper
spec:
  forProvider:
    clientIdRef:
      name: guacamole
    config:
      claim.name: client_roles
      client_id_for_role_mappings: guacamole
      id.token.claim: "true"
      jsonType.label: String
      multivalued: "true"
    name: role-mapper
    protocol: openid-connect
    protocolMapper: oidc-usermodel-client-role-mapper
    realmIdRef:
      name: iaas
  providerConfigRef:
    name: keycloak-iaas
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    keycloak/realm: iaas
    keycloak/group-admins: ""
  name: guacamole-admin
spec:
  deletionPolicy: Delete
  forProvider:
    clientIdRef:
      name: guacamole
    name: guacamole-admin
    realmIdRef:
      name: iaas
  providerConfigRef:
    name: keycloak-iaas
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: guacamole-admins
spec:
  deletionPolicy: Delete
  forProvider:
    name: guacamole-admins
    realmIdRef:
      name: iaas
  providerConfigRef:
    name: keycloak-iaas
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: guacamole-admin
spec:
  deletionPolicy: Delete
  forProvider:
    groupIdRef:
      name: guacamole-admins
    realmIdRef:
      name: iaas
    roleIdsRefs:
    - name: guacamole-admin
  providerConfigRef:
    name: keycloak-iaas
