apiVersion: v1
kind: ConfigMap
metadata:
  name: cookes.io-ca.crt
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFGDCCAwCgAwIBAgIQCO9ofnVDLGyDJIRJYKFEGjANBgkqhkiG9w0BAQsFADAl
    MSMwIQYDVQQDExpjb29rZXMuaW8gcm9vdCBjZXJ0aWZpY2F0ZTAgFw0yNDA2MTAw
    MDI5MjFaGA8yMDU0MDYwMzAwMjkyMVowJTEjMCEGA1UEAxMaY29va2VzLmlvIHJv
    b3QgY2VydGlmaWNhdGUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDB
    9D8G/7RAjuM1nrKJjg+ENkvxiF5bSizuduHS9Qy+SxXuj3U400+y9SiWL98asSxr
    LYpsaPZnVhLcCc+jSJhxDb7rG3KsCXSYUcYpTTERkHYrVxoS0XB8L3JGyd9yup+u
    DZMkyqTLRAjM/RcCgY/MEeRgxzWbwkVnnSmWY3K4Gn1SijmQJ5OsIXFeyV2zcH+d
    jPVbfp9ajApxtc1JLj16t8M/tFm1lGIMA9ZSOB0kwZGrZpHRNvz8KjOnDDdKF9ov
    RrgZ5AsmKTrP13IqAtIkSXMyqzNTWUy0bhXxJSrWnM3KJQaW2OtfAWLF9KpFnICr
    q9g9xcdqUw9JrNzXvvfhdUTIncnSi7oUPD9UktnY4YV8r8z5OTHFFRb0LgJxklb/
    hzq9TxL7jQgVRi8L7oN+QD1TUM1YSx9Wg5+m70hie9hYpyB7TbZLnh/B/CkqIzcy
    ZPR4G5sbT1WAq+xdwgKfAfnVWRc2FvILvIT134DhwkvRT0Pjta3E4FSKcGNT9Ob1
    ecPwO8PoSwK7PfrTKq43G+brQ8HInQHtsDynWf5OCtzpqJBWdBO603zB8aSFTucZ
    KhtwfS+WKZgZPyZskEp8MbJ5hv1spex4AivR/4OElMdeOMZoz/tXTawUc+lrlV+y
    BhZnffIe8CIz4auGeswGUOR17GQNVJnVeWxk4j/KTQIDAQABo0IwQDAOBgNVHQ8B
    Af8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUcjPBbGduN0mpISPi
    zPo6If+o6cowDQYJKoZIhvcNAQELBQADggIBAJGD5BgkYNJZck0Lk51C0K43pRFe
    9mHU//w4xdhVxq930VAQeO2v/Vdvo8SlF5A+LVXqc6k4rgdBmPNpBlP1uC3hS5UD
    8M22/+YA/Ss1+cugyzSMXoemEJg7dRNj0oUw7N3FMU6f23gH3KbWIw/rxjhqs5Cr
    BRT8TdiC25P9lOA/u3EEQG41CSYc1oHIDJyxEnOR67S//brxcXfDYLZKLWQv/Vf8
    bll+k9A7RZsBWPIwTh04uPDvCl2Rl2ZWljPZpbRaRkX8XVavC5CFqxN3VLPOWXVV
    v2JpSGCaZ3tu3fHmgWgQIXQgK29zkg6fqmSfCWxpTjAIVYAY1ypy7iXoNfLFVxPK
    IvlT4nLgstkXcNgR/TBCtOFnIS3YBSUdk+iwZvdkUrGcgHiQSwhcYoyb+GqEFsIQ
    Pk1nvK6GdrhuVDE1UB6KRPkHJmICf/011oYhRtsn+W0MZHCKgSecyj2FfKJvUlym
    /qimuc25+uXdDGATRIClh+8D/ogZkrk2MskZehCg/jPKqJyFVakb2+LGDMP0mjK4
    AY+zGPlE3wcdlck3n6qecFe9qM4jN5gP+8hTfYrPNiXgaXeC3Ws5VmW3RFDDw4JG
    AdPZIs7btmpjfDIE3tLgyv6JL9AQk7DBR8/wxaXTTUmjqcbzM4kxb5mLTAqlf4OC
    5AnWDzusDqj5PuKE
    -----END CERTIFICATE-----
