---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seal-key
  namespace: openbao
spec:
  encryptedData:
    seal-key: AgAWT18cWrVMMQXgf8cToR/iuMy+sS67UGgx4kA8tphwHkuP9BGw9sOIipR/xBekf2Jr39QEtdGT7/0EsTQiJ8XBqwdSa57KuMGNJYjpMfKwUJLAPOAKmGqh6XQO6k58YHQ4LBWlpQzs4BrMPvekEupMglckAIjbhnLeY9ydHC8PeHgHCPDZHtzWgyeqNcXyOnzpHS0GN5pPefL2tn3jtVexvuHD9MBbkB/NVpcNgpndnDqBYxExjXyuH07/ovFw1RGZx2y/hnGj4CflcHYaGew/h47oG1AuRYtE99NkoOAnfsDNPDJC3Ht5Jt4a205+dxtbK29uVljPGqS9XKJKaqAGeoMhBLf+38TLHfbJWjImOfolTsvfeHNSvfuwccvBdEVq9Sp9zAMog29C7iBd4/C1GMQSrz7b0nUPRa4NzOuHczlX4Ik49n7n7hY72ERVgIvvg/rog63UrZ/GI5F0i+U7v8vKEL+Iq60heqwNqJJhAdRV5+8wIzEGUIhI+6Gy5jB1rxFJMgmp33/s7NqU0SNJq2bunsv69pXhvNXAkl5PA5blmozE+1SBNcWVOGm01YLReDhklJHImmFQ0y7xKDioJlbixpfoMlnVnlkwXg9a16n/JCOA365DOPbFvG7bWKY7fZig6J//z7x850cUrVX8YgGY6oJuwcmtFkdy03vnkqqN3v/LAm87f4Ni9xeYLQv6e//3XkkiaIzL2y4GFc12GW8dkgczI/deRdqrg/OpAg==
  template:
    metadata:
      name: seal-key
      namespace: openbao
    type: stringData
