---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seal-key
  namespace: openbao
spec:
  encryptedData:
    seal-key: AgDJv3gOEp55Pfd2//aaLdp2IGvj1e2MLiaXmOYXaUoi3AXI0YXppPqXdwBKPheLYay6FGbgX1GNHPZwIongkwTgxcIc93jY3fpghW1FGLnkgBwi9ETQBvaG+pJzV/a/+6XlzmqBOeX1/ovv79+SItQwFI6DZ2R2CcOocv1cy20KhV96IRfsQX4E0Gpx+l34NiLojMalyDsdRXIjkd+fqaYC2YVcY+qXYE/nrW8/zl4TQeoPzoyUbwM2TpVb9KTechtssYOyWutxsdnHMi/6eJXtTMgTkV8S4uyDqPOlkNCPgrHhJ/pepoArFKii3VIJdHhf+IfXpDw+sPNA/zbmSE1qWpnw1KjWdhZi6ZtGwFqyestJM4Wy7DY2GLc1er0kAHJV42DGeBJgZGfTA5xmxX4Z4Na60Ith3yO+QYgFBvN0abgiLKCBCF91vJlooY8Ey1eHa3uVTvDQIXZOUd0VrsQKnR8+4vhLxHH3lAkpVv1eZ14i/fQ/6YZwUdRNzLvE8+zLP67MAmLRxrf+F+KnCiDrolIKEdDGuHg8+fkwQlgVznNUc6R149Cqt3rSqHh+/JS3ZU6EUySVQq+7+aMFxiqP9KJ8EAYl9BO4dx6GMZopELI7v1L++7yetdyyoIy0STBA/5JvoSU8ShTyE56KaWXuTRqzvQc3QOSBcN7NdqmbrIiuDulZ+xSOglBdwfICGnn7VlW0zL0mMLMDVb2oI6L3+N1kXql2sWT3TUFEc1pUrw==
  template:
    metadata:
      name: seal-key
      namespace: openbao
    type: stringData
