---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seal-key
  namespace: openbao
spec:
  encryptedData:
    seal-key: AgBIuzKV7alYbcxbYeUqjJtUjzQ/fgh6GtyDyTt76Nu88uZenr3FQcVctVn6szpnsRKtadsmZtCA11D19+4pHpem0apEV0nLK6jtRw5cYEpHjj0oNTc58wKbAdpwkwPctMDBUvEDpZvbrRT2MHr06xXlnN+4D4OwJSkVqrekBbowMM4UU/gh3Cn1wf73VXBhdPMJ0qWOmYKHClm+syX0XvgGHimoWSgaTbDB60U5gXjD5/fPrrtiuffjOrhIPZvMKe6vQk/J8deGZurqKatSE4jkcBGfEibo1b0eiH47ywqrMxSFia/lda78uTcB5QEsYXZLVhVzVZdVkZz8vdiqX9w9MsFww4v21Zl0s25AvDusWsUbTz7ailZIRI64nqwfTsjc5b3nVqx5HjG9XXXa6bcZNp1SaUMS6IOGgY/7/ao8IQz9Hspv7lA4mAvlRvRPg46lEw4KS3d8JWRiIY5rxZ7rWGW06d6vex73AOV2vPaQqPcnyLPCwVBZ1lPRSFyHOI5UCdmy6yAZ3nkV18RtMdVVfd2Lg4HKARWzdZNqQvKaINKEW8eEKIE0ZH1344exFgFK4uWFAeUbMOjC2X3+OHt6doX4AcnaJHMpBjW/aL1/gHmGlKOHbBhAopaDXd5T3hxVz1zUwqgCdJU65Dtse8nSkY+gFvIm194edGpI+05KnhYUChPXFQACHbBWaa6BhL8fReGUtGiSx5DWyc+rDY/MUSSCZcwyTTUbHqeFIDRb2g==
  template:
    metadata:
      name: seal-key
      namespace: openbao
    type: stringData
