---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-secrets
  namespace: mattermost
spec:
  encryptedData:
    MM_OPENIDSETTINGS_SECRET: AgCLjCBBwxM6vyaETeSoRPEL6BFHqMFwqG5srhnuVqsiP2vFtr/z5mcEz60owTKP7XJtoVCIiJhzCF/u1RUIuNs8sw8gRlci4zEowSTfH/jkvXdLDEF66BVEEktdugxNGmbnZ4TxiL85FQYSmCfZ6LunjPJmhUyMU/02s6YR1f4GzBO6GYjIftSglqj7FA3Zg8g7DexkFVGafcDCf3Oc88tsBInfEk5uK31DY8UQfjJkwFDAR86jZCB5kg8+6g2uLBV6hFKvpCzI4CY2XjM1vtCD4PhvbQgKyNum3KrLSmq3EemopJJQsGluuxpjeeNRjzhgjBuuwCpXfrFFpetSPExW3H0s9HoF7xs696ClYUNwoxM6C0NdaW8eojBSrUvrhY/OKinmC2AsYILY+P34TrybWVa4+SU4/FQzISk2ilHS9E4/aBPx1JGV5+4Z17gUErpUmXruS0z2U7FKif8mRlQpVsFn2vPzfCYpS7nSreywZ6+QwvbReCz3lduilOWsdUAmtqMmAV5k2Xk8e5C29HpTRyvT1m8eKucWm+jF/3okNuQm/PBwO9sF8b9b10KiBJpB6B4Lpez3eYYWEePDdP0FSh7QLnvWueMFJcWDA5GSFjh4H1K0QaUNq5IGVQlK+JpEddzDNk4eTVuNiK062btYV7ZRj1eeQVOFd5sWw2Of/XltE9Oa1A96geBhK2arkzzCQZmRpTgGoQNT54b1nWVQteIkOV7DddcdXUnM5dSUSA==
  template:
    metadata:
      name: mattermost-secrets
      namespace: mattermost
    type: stringData
