---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-secrets
  namespace: mattermost
spec:
  encryptedData:
    MM_OPENIDSETTINGS_SECRET: AgChlaQ8omxCx8rBYQVS+0qVVJzCMig6jkG4KBsphV4Ecr2QsjW1IWz5qzc3y/xgCeUW0uN+P8kA+Tf6sPZiODGwpUh3/4eC/4AXhvfedOagAiS2vm/IvEOjTpsWK77YUVAUEgIjd6ONpraHk+angFLEzgJMuGYRjYGuW50BIyC3u+calL2hTAwD4OAxA80ErbQehHU26YnkncbnUjV4JZgxhqA6Ciw1nIJLmjn686OofNyftNeN83K7JErtOI4NQX1NY47vqp8QY9dgESgS1qMMJt99doSsbkdBZe87DS8MEHvrC65i7BJW2RKuCnJSmEC2zsUThs3jeGg2R1AzD+FBSadoLB2v8MB6ebGtLj/poAwR1HV01fkU3y1/ujAzq8bMfpaPHvaqfU1UlFQkD4r1zFc4KlD4Ts0L1LpfIWPWCfeuLUqjw0sPgniHWeLYV3m04I3Vhq2PEWbmJ0d+//S6/LuqsaBIohmIzQXYftrMxkS7+ukrNzoXLUEMItDRQ9RVltfctZs8pYBW5tvVgbSRd6jW0YZJ9JDx5ugPGcsmXP8VeMAbiBZKtJPBN3hLMYayLP6T723hwj5bem3HJY+uvkPN4WT7SZgAVXqsCC/s01PVUJB8ZEj9iuzpRp3ILM/WlndPF9WbMvil0nko+puQX/WwG7Og2JR/J4wZATnyjjo2jLa7mC/xuYpXayoc6i1yj6DAQYsX2IHZaUwrvEEskRJSGd/ispfvVSCrzNNo/g==
  template:
    metadata:
      name: mattermost-secrets
      namespace: mattermost
    type: stringData
