---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-bucket-credentials
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgAAOwWrXAcOu6yE2CrP0EmtONM3BNKMt1WQDdMhNCNtaoRuRGSwBY5+jakVtcC3EA5zj3zBElIOFwNjZlSJg2Fa4qJ//zjbONJmt1LtrxWguI9sQkWjJ/B+hzpzGhG4+13Q5oFj+fYaj/pasGULqvMRM+lISlxvT5k4mtUcjLZLdkSPclv1RlbhxwWjFKweCMwBQIDhSTVAS1j+ErKMvF1BmWervpMDFS81nh2LBiPCOIMAAbD3XMNOfadNgY3CDCvK9lxufsMTwKvT2GzWrMweLTmyreQvTus55uYd0UEDkTotSswEWpM7mNHKzekuihqyZkp2SmMsPsgZgTXP4c9ywbedXKbYBVVCDWmbCXeQkSSdV5vnKQH/fkjOohmr20+9SdK9aSbN9plCy/m1gUSDqtuK2/2FQkGoVv0nyOHPSyS0nvdLWT+h6UuPNmWIucJRqG8VgjRVk07jZyPEKN9OlDhtcvjKkZjHvclN1BreXhkE27cCaSfk+D27wmi+pG0QhYzzSO2ViLkvfG7PhV42uNFFEnvGN2viKEq7f7P6SxQuAo9nF79kFCmdVKIAZdTbMMmz+PDdrrn/9BD+UnzqaeAgSZCZtVZJutzg71S/Q0IxLivHEN42g5clxsPz+gJ39yRv1kQHJqeA1H/LRSkxepuPMYhu5M37bka43+begorLIbgnnCU8N589PIvpJvPWB5EC+x9qa+cbZCx5PAEeIQ0PaQ==
    secretkey: AgBIi34CFXKJ8AwF6ZkNvid+frnI/j94dOXgaM9r2z6wUbMsLBLDtA1HdwR4tVfi7LEYl0t57iSQXOElW+zmkvRdNUawa7KAvYENLJ/oWoigvvsIxSGhMa6U0+3h9/6+U2abV/PPXMSoc7dJ7oTvuUaKbgVXm8KWZL8DfvVeR3pUmOhKwQQoPRl1+7J0g9CI+iEe0tcUgnC+Gdyy57QkmIdV8TODttIxNz0q6xcbEFGRGy71tX1MmdmrU7zLtfwW4tKP1XTJT2ppCX3N47meOhEQzl5zKkEJO8o4414WwP28pHtFVLw6PMrrq52TV7QVKsIFGiFpra0BBeq/3T5w+3Hjz1fcw78jTPip6gtjQAQ7r4LMP7GI9Mtdgr0DQ3NOnP+NW1kD5Ns0vCDK91A9SLdsunFmatuRvEZx251LxQo1/ucaLGNAhAtKHGeShNRmo542WnHO/GvCnKnoAQW09kSuhM32TtL/iD4uWyeypZmZRN58hfk+wSyduTMyJoI9I6zRnHYBiiFAeBYbTVd29DRwUxgYWJDA5v0n2Q913d6wjp//u+hXmu/uj2ezn0s8iLWaFga89x05N62P7eyB8RAqmIR3RJwH7e+EsvFjInvTbNpnIGtXUbe6L09TL5CoRS+W7TCbO5x1Ox7KbovzkXgfol2Nddh+Aur0wkySrWUJ33guwGxUkZ9OmBvWmYmbYSzlzU4LSyQsAe7gh1JL9y8T8Le0B/YNsm/f1ghdHTuqu+Mztw5qh6mY
  template:
    metadata:
      name: mattermost-bucket-credentials
      namespace: mattermost
    type: stringData
