---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-bucket-credentials
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgDHR7rMB7zInCv1SJlhS/YayAVY26IFYdg3U8Mu+YmGOERw52NFifJThSWtH0V7iqPBYUyyOCsJTGCZLc2VrFBcGgIBnWHBw0ba+qXtbDe3ko8Uo6XnbVCkxB0jkzDNAPzebKskDUNAtbF5jQFwA3XI0XNrDerlFs+8hcUxFL7bKgv2iRFvsXiAOo+YMcjYA+ApwSCfdH4YT2dtddCjaqpo0LygfoR6xKYdNZq5NLVfWlBgnx8dVIuCp8mtaIW43PR9MXXUGk6AgMtQDxzhoZJx3WB4JPlSQP6jS/eHUlo6suewrbpyzCA6JW4oEgsEdniYCUkeHOhk0a6LsaGsTrDc52KCqj7cXm3Jdk4PvY6X+ScoZniOuoKBhR5UYz7dGCqc76K3mZt0IxxyTZatMJKOgmMOj3Whtdxk3tT/e1iWVHlD/qLbj1VjMP7A7/6ic/9sMNSNRt9Btzab+WOkl10MIOYXni+PQQeGnZlZYhdlsWiQzcQwVXkYlJHscXC8O7NtT4qXh3S6zXWVVxhaI8PFkAHNZG0zVB2E7rcZBQHyDw/g3s9eE/lMSo0u7tfshcTrZaMJdb/jSXPe+CpwCnGYERgc/sl76pt6epzVcFrYjIi4IlRUMiRyHQpOKLYcIes2lNoc0MkC2UtVqHh4/3XGpRCKLWwMlffil3ww0m2Ci90vZFiO2Tjae9h+/nEfVsBn9LKjlX2EP7PZ3Zmz25/26jjDew==
    secretkey: AgC87UpMinvYnUshNmFRzctkqMc8l/LL+Rr0huAnfyeOV48IGA4CEyFRCV51DSUHKOwlD6OZKXWrluf9Bd4UKHuHk6QcG26vG4SswvihoDRFNnX1S/+lk4DDHwKUIc6xc1EOBvHDpvGu4F6Lo45hk41LscIjUJmqThwnIiZH5H4UYOeEmsQob8mYxOA6cZLUMee4RFIj1nRYg5e9iz2PLiM0unc/H1X0m4lNeYe8Ea+Kf0EksLMLZ04P4jkgELq5ak++tfldQQZPEEyHZVrfEHvz5OGp/WGHwD/5sKim8Mm70yVI9ScsiMby4Pk7Lee+5lAybc3gBOshp1XvfqNk5aRX8yfczAYaiVgHjEvqdYmsE5V6EFJoB4NGyEeTgV1nTttf0Aqt+Ie9rdXrBYCeVnUGhJ2h6UR3XJ9JY2rlo6NAdcLR17K1oJIKnHe15Ift+Wkh1g2nCqtGXgIBwhNkngEbKYyFktD7mDrMCPjxakUttb4pf4AcigrRVu6akfjxBGRUvOCk0cDOTcmjIx2OzoA74A6poMVBPWj0grV3KTUcdfBGXC8DB42OjH+Y3cvLTrJzIMC7kvg3Up1aCYnnu6sdQC/92XZA2NisM5YSWkE9LhVxpAWLc5ABG5MgblCmNbCC/rfCOrqrvU9ZJ1zfZOxNMG5HC5swI6F+M7F9cF67BzV4pydF36WOwBv4JCDz/YdFmKnxZqBrbFvEgDV+MGcpu2kJ+dnBGzMfZwVnUyVWAEeSoMm1KcCR
  template:
    metadata:
      name: mattermost-bucket-credentials
      namespace: mattermost
    type: stringData
