---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-secrets
  namespace: mattermost
spec:
  encryptedData:
    MM_OPENIDSETTINGS_SECRET: AgBH+30rC/YF4AOSNVuCNBA3vCeItgsNILD8JFrH1uMVlwO/c/oD1sBcndmTnFH0c06X02p0DGzFG8kUuRc1tzlCGdlftwHjNbF1uDYklQllsNO6C57l8Ak6YzlU6pQZ/hBM/O9yyVwTYzESmP7LgUfI//vRu4+xhKcP+07N7hHpf794g5zpFX0gUSPMTp7jst7PMsJD1n4a1BBDw63j1jdDDML/wksADEBISW3xjhm6ZcLTFYhTs8Q1ExgcJQKWJsG+XxA89QY0joHbeQgwfiXCa9kj9MjL5IW8HBZn15RJblX/bc/wF8O3gu8+rXAjHYe+DBZPP0T63C2oBEQOtDh7lGsVNdvoCkxQyIJxMHt2oE0lDg4u6hCaeU5PTBF57E3WRufl3TeVvpdvf2Txw7GFcH7aGIf2BH/xfyRX3tjpTeVV/22ov07MzE3RQjK5twKs52SxmbTGquQYS94NZEb0WCSdSF554UsIH8K/DEwpBUOKm9oxiuvDFPJHLYMr9+kozTZMLfFTjdFptyns6ldW8fVRXL5FzIjLOjqDFmQxeV+J7OPOY4Gn9nn2/cezZfPVfgl7Q0cBIlKnSmz3fn4My8h/02RGXvXyFYVWHOssMpVo+mIQAMozQAGFePFuTfiYuDmdKa8r+ff3EiLSYY6Km8cAg3tNZGEB8nRn17AJJhhcVDwTcdTR53dJtdbHa8Jgfye77NO2qGzQ5QDzEVMZDzYT+NTWpbjFJlQbqWZsnQ==
  template:
    metadata:
      name: mattermost-secrets
      namespace: mattermost
    type: stringData
