---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-bucket-credentials
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgBJhVhkUALB8qJp2kCy5Q6ZMZd8S0vQR4MhFVkZHNDbW2ULOnzuxQV1sXNeLdSjMEA4RGmLGdJddFuKv5eyMdHmanC4l5cU/qbeC/RB8B/QpZNMhmX5MN93Ux7aDsEd7dWtJTbvA33c5G/mQYzpXLKoMMNtzbYluYlre6Q1NPS7BVENKsL2ibt07um14HojF7b4C+cEIcOBFNymrsB8Efqm/A7JXVRjLGu0CSQXE9WNY2QKXVa150YJZz5byw3aXiBybfs9rDNUpYEDd1dPdZk7i/f3giXX0E3AFARPKxnZqlY7oD5OrZrv5H4+0qzLMEKW8e+UYlrK2hpEeGj7W9j5khJFwGS3T54WGuKq+y1AxRViKM5lnKqqZIRguxIttNNfiSQTKDACoUsszsyeA+Cdz6YvG5b/GzKkQx+wBw9LcN3y7ecchVRd56DWvx0BG7a/JF3L/DbvF6zwBD/2ArjjOpQN+ycz0vc6mNRV7u5T3eyrm1yp7sGww6bkhYj3oK7gQhmGIfgKRV2x2e9LxDFq0gaqTHMTdHFb8kQ7PkVplQ3IPNGil3ry0L0BCW6jkFlImq2rm33IYZ6gyPmCIVZoBpYgKALjSBqrsUH0HhPp5sVTZJ782AFTSCHeNJr+IBfLF8qsahqmFPTHDGdRxXkoDZTNThURs2CeOc5JdPd8dTaGqMC3n0jrylvmA9SxwIm1m8NtChdUQ4pI6YHEWy1VwKqU2A==
    secretkey: AgDKR4o6yvuuhbiyn+OFOT76OKZ9ASsMQ2CB8I4W10+nMCVFq0yaEfqbpZzcYO9tE0J4RPifPwMM7LoCRj/j4W51Jj1uUTCtUDZqLAOo2jh4/WSZY5kgF0wZyRi0s5aSX1QRitn5tCczlSB1/cVh1LuDk6OKfaP0FZ6g0ANlao7+g327RUnpCKoQpamJ3UMTcB+EajGSfnn6RQx2phniwxvqLcXgWVjltnWGtrBAbGtKwbk6UXybLrWbH7CWGWBcjp5RmHKU8IRa+FIEQvs7uwFyRbRbutSY1Kejbz50ZSNQ9Xz3j9gg0E0Ok9P4SOueuzNweLDqbaoJtlwa9r2ztt/DSSyR+ChLfW02yZhilQl+bzR1G3uLMiHv9cW1EniWwDB8JCrE648K5cQfxtZLP09fOSJLdLfg9izq7msVsMM1ni06F1+fLGcYw478Zb/BGEbTZP4C96WBfTXNFjYzLa9VBE28kqs2OIajJJUjAO3Ljd2TYzKH5IVtgKvAcapPWpHzXR1DrWtmF4+9yFRzSWn7aAmN0ZAQ09aCa41PbIVZvYjJgKt4H9xVDoGjWlqr/T6qws7EzJP9qEViV+gGbzmbaYVMFddYB1jR0/PT0/jPpo0ph4nTr/jCcU0PyEWRvDK01Qf/lvW3Pc4SGYhyI/x7C+HLAr8Dc83AMB+GVJLyDR1DxanD5sOEbFKDSgn/9S54OwQRXELvcOY17iJchM/8SZIHmTEI2SfKecQP7HhLku0ITvbsyHTJ
  template:
    metadata:
      name: mattermost-bucket-credentials
      namespace: mattermost
    type: stringData
