apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/eck-stack-kibana-certificate.yaml

helmCharts:
- name: eck-stack
  includeCRDs: true
  namespace: eck-stack
  releaseName: eck-stack
  repo: https://helm.elastic.co
  valuesFile: values.yaml
  version: 0.19.1
