# https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-stack/values.yaml

eck-agent:
  enabled: false

eck-apm-server:
  enabled: false
  elasticsearchRefs:
  - name: eck-stack
  monitoring:
    logs:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring
    metrics:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring
  revisionHistoryLimit: 0

eck-autoops-agent-policy:
  enabled: false

eck-beats:
  enabled: false

eck-elasticsearch:
  # auth:
  #   disableElasticUser: true
  enabled: true
  fullnameOverride: eck-stack
  monitoring:
    logs:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring
    metrics:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring
  nodeSets:
  - config:
      node.roles:
      - master
      - remote_cluster_client
      # xpack.security.fips_mode.enabled: true
    count: 3
    name: master
    # podTemplate:
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: cyclops-fs
  - config:
      node.roles:
      - data_hot
      - data_content
      # xpack.security.fips_mode.enabled: true
    count: 2
    name: data-hot
    # podTemplate:
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: cyclops-fs
  - config:
      node.roles:
      - data_warm
      # xpack.security.fips_mode.enabled: true
    count: 2
    name: data-warm
    # podTemplate:
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: cyclops-fs
  - config:
      node.roles:
      - data_cold
      # xpack.security.fips_mode.enabled: true
    count: 2
    name: data-cold
    # podTemplate:
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: cyclops-fs
  - config:
      node.roles:
      - data_frozen
      # xpack.security.fips_mode.enabled: true
    count: 2
    name: data-frozen
    # podTemplate:
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: cyclops-fs
  - config:
      node.roles:
      - ingest
      # xpack.security.fips_mode.enabled: true
    count: 2
    name: ingest
    # podTemplate:
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: cyclops-fs
  - config:
      node.roles:
      - ml
      # xpack.security.fips_mode.enabled: true
    count: 2
    name: ml
    # podTemplate:
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: cyclops-fs
  - config:
      node.roles:
      - transform
      - remote_cluster_client
      # xpack.security.fips_mode.enabled: true
    count: 2
    name: transform
    # podTemplate:
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: cyclops-fs
  - config:
      node.roles: []
      # xpack.security.fips_mode.enabled: true
    count: 2
    name: coordinating
    # podTemplate:
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: cyclops-fs

eck-fleet-server:
  enabled: true
  deployment:
    replicas: 2
    podTemplate:
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
  kibanaRef:
    name: eck-kibana
  elasticsearchRefs:
  - name: eck-stack
  monitoring:
    logs:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring
    metrics:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring
  revisionHistoryLimit: 0

eck-kibana:
  config:
    csp.strict: true
    server.securityResponseHeaders.disableEmbedding: true
    server.securityResponseHeaders.strictTransportSecurity: "max-age=31536000"
    server.ssl.certificate: /kibana-http-certs/tls.crt
    server.ssl.key: /kibana-http-certs/tls.key
    # xpack.security.authc.providers:
    #   oidc.keycloak:
    #     order: 0
    #     realm: keycloak
    #     accessAgreement:
    #       message: |
    #         * Ah ah ah, you didn't say the magic word!
    # basic.basic1:
    #   order: 1
    # xpack.security.authc.realms.oidc.keycloak:
    #   claims.groups: "<example-url>/claims/groups"
    #   claims.principal: sub
    #   op.authorization_endpoint: https://keycloak.apps.iaas.wcooke.me/realms/iaas/protocol/openid-connect/auth
    #   op.endsession_endpoint: https://keycloak.apps.iaas.wcooke.me/realms/iaas/protocol/openid-connect/logout
    #   op.issuer: https://keycloak.apps.iaas.wcooke.me/realms/iaas
    #   op.jwkset_path: oidc/jwkset.json
    #   op.token_endpoint: https://keycloak.apps.iaas.wcooke.me/realms/iaas/protocol/openid-connect/token
    #   op.userinfo_endpoint: https://keycloak.apps.iaas.wcooke.me/realms/iaas/protocol/openid-connect/userinfo
    #   order: 2
    #   rp.client_id: eck-stack
    #   rp.post_logout_redirect_uri: https://kibana.apps.iaas.wcooke.me//security/logged_out
    #   rp.redirect_uri: https://kibana.apps.iaas.wcooke.me/api/security/oidc/callback
    #   rp.response_type: code
      # ssl.certificate_authorities: ["/oidc/company-ca.pem"]
    # xpack.security.fips_mode.enabled: true
    xpack.security.session.idleTimeout: "15m"
    xpack.security.session.lifespan: "1d"
    xpack.security.session.concurrentSessions:
      maxSessions: 5
  count: 2
  elasticsearchRef:
    name: eck-stack
  enabled: true
  # ref: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-monitoring.html
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: iaas-wcooke-me
      forecastle.stakater.com/appName: Kibana
      forecastle.stakater.com/expose: "true"
      forecastle.stakater.com/group: Apps
      forecastle.stakater.com/icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgZGF0YS10eXBlPSJsb2dvRWxhc3RpYyIgdmlld0JveD0iMCAwIDMyIDMyIiBjbGFzcz0iZXVpSWNvbiBjc3MtYXpyeDdjLWV1aUljb24tbCIgcm9sZT0iaW1nIiBkYXRhLXRlc3Qtc3Viaj0iZ2xvYmFsTG9hZGluZ0luZGljYXRvci1oaWRkZW4iIGFyaWEtbGFiZWw9IkVsYXN0aWMgTG9nbyI+PHBhdGggZmlsbD0iIzBCNjRERCIgc3Ryb2tlPSIjZmZmIiBzdHJva2Utd2lkdGg9IjEuMiIgZD0iTTI3LjU2NSAxMS4yNDJjNS4xIDEuOTQgNC44NzIgOS4zOTYtLjI0NSAxMS4xMjdsLS4xNjIuMDU1LS4xNjctLjAzOS01LjI4LTEuMjM4LS4yNjgtLjA2My0uMTI3LS4yNDQtMS40LTIuNjktLjIxNy0uNDE3LjM1Mi0uMzEgNi45MDQtNi4wNy4yNzItLjI0LjMzOC4xM1oiPjwvcGF0aD48cGF0aCBmaWxsPSIjOUFEQzMwIiBzdHJva2U9IiNmZmYiIHN0cm9rZS13aWR0aD0iMS4yIiBkPSJtMjIuMDQ3IDIxLjIzOSA0LjggMS4xMjUuMzE2LjA3NC4xMS4zMDQuMDY2LjE5Yy42MjMgMS45NjQtLjI2IDMuNzgtMS42NTIgNC43OTctMS40MzQgMS4wNDgtMy41MSAxLjMyLTUuMTgyLjAyMmwtLjI5LS4yMjUuMDY5LS4zNjEgMS4wMzctNS40NTQuMTE3LS42MTUuNjEuMTQzWiI+PC9wYXRoPjxwYXRoIGZpbGw9IiMxQkE5RjUiIHN0cm9rZT0iI2ZmZiIgc3Ryb2tlLXdpZHRoPSIxLjIiIGQ9Im01LjAxIDkuNjMgNS4yNjcgMS4yNTUuMjgzLjA2Ny4xMjIuMjY0IDEuMjM1IDIuNjUuMTg3LjQtLjMyOC4yOTgtNi43MzMgNi4xLS4yNzIuMjQ4LS4zNDUtLjEzMkMxLjkzOSAxOS44My43MiAxNy40NTYuNzUyIDE1LjE1M2MuMDMyLTIuMzA4IDEuMzIxLTQuNjQ0IDMuOTMyLTUuNTA4bC4xNjItLjA1NC4xNjUuMDM5WiI+PC9wYXRoPjxwYXRoIGZpbGw9IiNGMDRFOTgiIHN0cm9rZT0iI2ZmZiIgc3Ryb2tlLXdpZHRoPSIxLjIiIGQ9Ik02LjI4MSA0LjMyYzEuNDE2LTEuMDggMy40OC0xLjM4NyA1LjIyMi0uMDY5bC4yOTcuMjI2LS4wNy4zNjYtMS4wNTMgNS40NzQtLjExOC42MTUtLjYwOS0uMTQ0LTQuOC0xLjEzNy0uMzE2LS4wNzUtLjExLS4zMDZjLS43MDktMS45NjcuMTQ5LTMuODc2IDEuNTU3LTQuOTVaIj48L3BhdGg+PHBhdGggZmlsbD0iIzAyQkNCNyIgc3Ryb2tlPSIjZmZmIiBzdHJva2Utd2lkdGg9IjEuMiIgZD0ibTEyLjQ2NiAxNC40MzMgNy4wMyAzLjIxMS4xODguMDg2LjA5NS4xODMgMS41NTUgMi45ODUuMDk2LjE4NC0uMDQuMjA2LTEuMTY1IDYuMTAxLS4wMjQuMTIyLS4wNjguMTAzYy0yLjY4IDMuOTU4LTYuOTAyIDQuNzEtMTAuMjY4IDMuMjYtMy4zNTYtMS40NDctNS44MzQtNS4wNy01LjEyNi05LjczNmwuMDMzLS4yMS4xNTgtLjE0NCA2Ljg4NC02LjI1LjI5My0uMjY1LjM2LjE2NFoiPjwvcGF0aD48cGF0aCBmaWxsPSIjRkVDNTE0IiBzdHJva2U9IiNmZmYiIHN0cm9rZS13aWR0aD0iMS4yIiBkPSJNMTEuODkyIDQuNDFDMTQuNDM4LjY3NiAxOC43NDEuMTA1IDIyLjEzNCAxLjU0YzMuMzkyIDEuNDMzIDUuOTkgNC45MiA1LjEwMiA5LjM2MmwtLjAzOS4yLS4xNTMuMTMzLTcuMDY2IDYuMjEzLS4yOTMuMjU4LS4zNTMtLjE2My03LjAwMi0zLjIxLS4yMDEtLjA5My0uMDk0LS4yLTEuMzgtMi45ODgtLjA4MS0uMTc3LjAzNy0uMTlMMTEuOCA0LjYzM2wuMDIzLS4xMjEuMDctLjEwMloiPjwvcGF0aD48L3N2Zz4=
      forecastle.stakater.com/network-restricted: "true"
      ingress.cilium.io/tls-passthrough: enabled
    className: cilium
    hosts:
      - host: kibana.apps.iaas.wcooke.me
        path: /
    labels: {}
    pathType: ImplementationSpecific
    tls:
      enabled: true
      secretName: kibana-ingress-tls
  monitoring:
    logs:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring
    metrics:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring
  podTemplate:
    spec:
      volumes:
      - name: kibana-http-certs
        secret:
          secretName: kibana-http-certificate
      containers:
      - name: kibana
        environment:
        - name: TELEMETRY_ENABLED
          value: "false"
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 0.5
            memory: 1Gi
        volumeMounts:
        - name: kibana-http-certs
          mountPath: /kibana-http-certs
          readOnly: true
  revisionHistoryLimit: 0
  secureSettings: []

eck-logstash:
  enabled: true
  elasticsearchRef:
    name: eck-stack
  monitoring:
    logs:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring
    metrics:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring

eck-package-registry:
  enabled: true
  monitoring:
    logs:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring
    metrics:
      elasticsearchRefs:
      - name: eck-monitoring
        namespace: eck-monitoring
