# https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-stack/values.yaml

eck-elasticsearch:
  enabled: true
  fullnameOverride: elasticsearch

eck-kibana:
  enabled: true
  elasticsearchRef:
    name: elasticsearch

eck-agent:
  enabled: false

eck-fleet-server:
  enabled: true
  deployment:
    replicas: 2
    podTemplate:
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
  revisionHistoryLimit: 1

eck-beats:
  enabled: false

eck-logstash:
  enabled: true

eck-apm-server:
  enabled: true

eck-autoops-agent-policy:
  enabled: true

eck-package-registry:
  enabled: true
