apiVersion: v1
kind: Service
metadata:
  name: inotify-exporter
  labels:
    app: inotify-exporter
spec:
  selector:
    app: inotify-exporter
  ports:
  - name: metrics
    port: 80
    targetPort: 80
