apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy-logs

resources:
- base/alloy-logs-ingress.yaml
# - base/alloy-logs-networkpolicies.yaml

helmCharts:
- name: alloy
  namespace: alloy-logs
  releaseName: alloy
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  version: 1.9.0
