# https://github.com/grafana/alloy/tree/main/operations/helm/charts/alloy

alloy:
  configMap:
    content: |-
      logging {
        format = "json"
        level  = "info"
      }

      livedebugging {
        enabled = false
      }


      // Kubernetes Logs
      discovery.kubernetes "pods" {
          role = "pod"
      }
      discovery.relabel "pod_logs" {
        targets = discovery.kubernetes.pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label = "namespace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label = "pod"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label = "container"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          target_label = "app"
        }

        rule {
          source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
          separator = "/"
          replacement = "$1"
          target_label = "job"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
          separator = "/"
          replacement = "/var/log/pods/*$1/*.log"
          target_label = "__path__"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_id"]
          target_label = "container_runtime"
          regex = "^(\\S+):\\/\\/.+$"
          replacement = "$1"
        }
      }
      loki.source.kubernetes "pod_logs" {
        targets    = discovery.relabel.pod_logs.output
        forward_to = [loki.process.pod_logs.receiver]
      }
      loki.process "pod_logs" {
        stage.static_labels {
          values = {
            cluster = sys.env("CLUSTER_NAME"),
          }
        }

        forward_to = [loki.write.loki.receiver]
      }
      // End Kubernetes Logs


      // Backend storage
      loki.write "loki" {
        endpoint {
          url = "http://loki-distributor.loki.svc:3100/loki/api/v1/push"
        }
      }
      // End backend storage


  # clustering:
  #   enabled: true
  #   name: kube-cluster

  enableReporting: false

  envFrom: []

  extraArgs: []

  extraEnv: []

  # extraPorts:
  # - name: alloy-client
  #   port: 4400
  #   targetPort: 4400

  # listenAddr: 127.0.0.1

  listenScheme: HTTP

  # mounts:
  #   extra:
  #   - mountPath: /storage
  #     name: storage
  #   varlog: true

  resources:
    requests:
      cpu: 333m

  # storagePath: /storage

controller:
  enableStatefulSetAutoDeletePVC: true

  podDisruptionBudget:
    enabled: false
    # maxUnavailable: 2

  # replicas: 3

  revisionHistoryLimit: 0

  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists

  # Must be one of 'daemonset', 'deployment', or 'statefulset'.
  type: daemonset

  # volumes:
  #   extra:
  #   - name: storage
  #     ephemeral:
  #       volumeClaimTemplate:
  #         spec:
  #           accessModes: [ "ReadWriteOnce" ]
  #           resources:
  #             requests:
  #               storage: 10Gi
  #           storageClassName: ceph-filesystem

crds:
  create: false

rbac:
  create: false

serviceMonitor:
  enabled: true
