apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: terminals

resources:
# - base/terminals-pg-cluster.yaml
- sealed-secrets/terminals-api-key.yaml

helmCharts:
- name: terminals
  includeCRDs: true
  namespace: terminals
  releaseName: terminals
  repo: https://helm.openwebui.com
  version: 0.5.0
  valuesFile: values.yaml
