---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-credentials
  namespace: alloy-logs-collector
spec:
  encryptedData:
    password: AgCFOxpiaDfGAn472V9oI/uGYTxYCDpnrGlm9C3VTUVtYd8+kJavBEDhDXYmnsAmL7ofGoLaEbHtn1RiHyCkNMVWYO9tfMoxlLfVdChUNOEP8oeJ11i0M/ZCVTLGp6mISXxfIf7RkHgIVdVm4Vuit3X697WgMmp8KQN/6scTFAtni3vw4jODhcHOyXWbeXIWiz6uOdH063NjZL3wHVcrL/AF9XDMxYnOSeKBXNd67s0h8QdfH6Bzy1yZsogLc03Xx/w5IsP2JzhxedQhmq0RBc6iiWXMnCz9Yrb27d34Fcz+LWYB8AOsEhML085zdqSwxzbcIjbXCUVBY+rrEzhMNY6tnKaaB+9YRWjyst639o08cX2aPjDxp6BNhl/AWN8G5zdGshCCanVmMz6cFWyHGFtqbBXudRwXV1v8J0Q3q62HrH8sZCeSlfWI4KYkac3/Y47c6NqiZfKrFU+euldMYm8NyEE1DvwkhRlz1bDwBv573YE6NEV14LZulA6yCM7GFHXQhcqeZVhdPGmB/5MEcqyEumiTe50zysokI5YAJlarneGu3rthpNRvbMDv/EjjXBpbiY+vCqmZo40xuXJ+X/D8wu1EWEQvu9oZR3z9IQUw0zmYH2yBCA+nT7i4OBVQZXaJmIVlTP992gaQMVlq7yU5xrJusM030qimOyJSkFfGE0a+kHMu4XffPOKvu2A2MQu1eMQ2UU2rOsOjv5Bka4ofc+3B
    username: AgADO80XKkm7paQXqjdOMEo+q4kLFnTgvVwT0RyLBPBVQBZYTsYbyPOmKVHhbcP43ubgApbcWr03lja3SZCjoNn80U/nGr3tdXGpPkcDp0/YX/1oG55P4A4AfTEAD4J/hRDG/OfTlloGHv3a2CpHTH90Lte9d7/0/qcSnp9D6TPXBk9IAjv8Ivl+qpRNquXS4XlcAhxZjPUIVI7cIKw5cb6kHhi6aOxU9pDPjzY2sK/Y8I83bFWPRDTf1k79nO7ZAcuGa8yZxMz3aKq6fxvz5BJpcKsXdaH/6ejlzESp+sGNpQ4dkh3KYCGTUjfmzQSzXu1C0m+bGfgP4eZDgaGGk3Z0dhqKMCTR0qAnvOYB0+lZkYf6zg7gHsLD6G6WD0rKjkRaG1GDTIagqreW6lcYhWxie0ww8iNzWUUhq6mvXCKZN+MFlop/THzib4V4yeKi7djQwfh1o4i4sW1T66E6KH6GM9R6pmQCm8Q2+PXO73SUTrNLPR37tIKHU4i0Hc7hlwLPSukZX8d9nRzEQsAjz9HqUit5zTg5ma3EqYEZcfMhcEbwabwHMa2Z0VqqOLVrInEBw7bZCggyTnLTcL8+5+h9aQqq1q9sFXIi3D9CVQisJ01EZqsYKG/iPH/yfqihdNvz5vRtQ0A17SC8mgVK8Eca2v8BtTTsgzMhR23dt0ZTIwjNOwW81kJWrZrXW13m0TerYTcm3Rw9JTo=
  template:
    metadata:
      name: client-credentials
      namespace: alloy-logs-collector
    type: stringData
