---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-credentials
  namespace: alloy-logs-collector
spec:
  encryptedData:
    password: AgDRDPrCLmVBRbqSrztqFqbnePx2C1owVCtrPwKf7tneND1mXGdJMtw9ziCgDXcVDI7mSw20hI2ngHI/Ot/4y7fz8ixCuThPO7g2wGe4cMp8ExBiMNArRBKCZdnDWFECA80fGrBjG0n2pmtoZ/W7++i5OqPY6Sg2fA/n+i0/L9MrNn8WGQBN1d5nze8cSD7rVE/nl/LPClbVoNv2QbIpLI8jRZQhyc/6CWvEuqY0x3b2W/N4IXu0mPuMVYjzxYvugGFm9u7g2DGmNldX6Y3ty1bo89XwWghKXNENMTJS7YcdvnTCKIAkBx9ZmUXSdzfC6j3C1GcKO2D5vo/2fa5/q5ZCBhv8TaZhfe7Rcihq7w82iR7tjaRfZhFcoJJe9WybuWXOF0x+CT6/sALOwJ2dgdYrCT5MuhXlNAhxrEa0MqgUe1L0msNMfGW+U8zxG41sbbOX/1CGwpPT+qDcm2LijEEkPCmYGHEjc0EACSQjzQCWUhUHAmBhFROgjB8b+5aNmtsscIW4+eBSCtVuL9uH9v/PTw2uF/xkWwkBNGUFpY9JOyMrtWI2p2fRE9UYvBt/l6MVD05JFBDrhk+ZjDNu89UgpFJdiJwDvIRZL9pX1pziC0aciakkp1oJo7agf6sHp+bjtl8GBvxQSR3XQRk7Ifurh5tzWYcTLK+LW6afU6YeZjHkt3sOFnOx4NB/gmN3Tbp6Ox1ySH6mSgNnj0iZw6REsWjE
    username: AgCscbg3sLCi+fASQtxNCkrEhFPLo+5YlHB/d8Wb9dy1+/TIljFrHWr8cHvAGAGTVN3bG7SnGNVjWiQh792ipinsyS9NCeXVcKwHsID4jVJU8p61U0tVNipd55JjCPQl071SsHLn2dOjsdr3eE0femF7zPHeEOJPslg460/hTqrzwH+ROPpZ3vuFx5x41uKJFsTjeSI4MyGYPYiOksaZNbOBLuFj+bk7oC+uVrT55v3ax51rk5gj9/jFz9hzh4w0IQp9F/QWANtJsFsOLK/Pqchiv3yGyivnhwrjLPbdoIlXTq2XKyGTQYu9wnEbLfmRaS6lxM8NuVvZGGWxJq2TUunr1kvlbscfI2N8eBvevKD/ue2MucLkTUAvcpqwn58YxnpTavQQEQbF61al19zuGJjTpXLA1RGNiFWvUlazNJHpu5fI8KXVQi2n8r8ClbbNtObQn+K+WN/uCKRL0AaI711uOS2iMyOyU1lcsjF1bAFuz9DBhKA9pOmuhuxtTZ7yZETpxYdzWhRgqJHrv1NKJEwXMAwNxE+44A/wAhZ6v8qpqbb3To+EcN3fqKGYdBBH7+wxZ0SEZDOhSzb8ZDIo/6/tCQkNC/9uY7RAeRb+SWo8Zot7+RJYO7anco0FqBp+M2HMWT9qc+oVzF3JW+ZthBtoS3aKlSRb6pg+0g/c7vwCEIP3eSZ9q+QgV9NeVvwYJ0HXGpCyE493SkQ=
  template:
    metadata:
      name: client-credentials
      namespace: alloy-logs-collector
    type: stringData
