---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-credentials
  namespace: alloy
spec:
  encryptedData:
    password: AgB7u4mFzWKpyuLjdUtKZjNWLMpufMVInLtAGk+iEbZsGW1DKTUHjlG/foVvPrdsJi3Xa1kbPkpJEiBu+4ozxfbuRZk2yAvPKfrJqxGFm84lK4KTXScAHfS36ym8qgKN/Egec6UlEa9r0U/VLfLYhFRNNm/M4CoSIVFFFGpAOkBpsQGjVz2Hg6Sxr2L54v2R1+x8XQU4gvpvLtagWdps8QDflpwcq8EvTVbfsLK/+Kwo3z7KGMM8WCvDEDWUwSbZxWljSKvXzxSh/RAopgBzArkZYmz1XOg/oeGdvE+YCXolaIKNST6/4A7YKlamQsrYTONn9pkkSXnhenDed+03gw6f+f68FYuql6XzDNjKy99ssyjoTWDS1ValzNKrAy2lahQrH0I3OpSchcqKn4TExxtkPAzBsjSWr43ZcSLgBHijIHcSAwBw6wdTIH2xrlzdRNkak+oB6DgaiYnftlDdz4MyNyfMbPTOwdMs3kax6a1XvwI6FXLKAJ1JWB9lTEhDpWCfjVXdzZxKm5E4u/jIdlPG05ZL4yTEAs1N4rRA0BOy4CaVW9e6n9Meft2hB47E4wWWs1jaHDAMSVVu9SRNNNLP5IS3YqCk34MSVOWISrbN0gn2wk/8Epsswd3t7FpbY9tQUYJhavGqQBG1Jenp+869OVgkJue0N+CQGFDd4/AQ48W85hkeYJe8J/xqrjqCo/OGy2kLxdLH+hFhaQpsjZ8zRytH
    username: AgCaqauxX6saIB1SSaARy3szWZhqQHZrcH6A5Db9HOAolIQYfqwJqTwN0bRTmtcZtquwX0GEUcVIyyUoSj3x3wEEMMYCz5U+xVZJPcO0EdkTNAJPJEihc4Gc9V6hQIfM1QQYBJRg3LCqbu6M08XY2hUPBH3HkpJC4SMUCdzVo8n4eDKuXrK4/HHsnLTeLYUfhqeWDWhonCcWoJ/GPM2d2YenH77HU+BTuS9MLtbbsUwHJGHVTh8wfP4SseBEfEHGTgo4L9OxCeFACgiPZ77cKINES8E/JVJbl8PqfABDxoAxGKhRXdgD9Y0WBaOqIfkzPKvRk36Ny3XIqIF0ELpZRh1Vz/H4NM3tjL7H5LgrTAoLewFCmiEGiSWIpjnlTppbchV+EgOBcsYvvGMsMXwH5FRYeAUz2WAXYX1y4EaykCE2VzjhfADWkozBWT81UmarxWlnwjaiSlz6tcrhwWV0eAKPkZszRP5V6zWu8zRFiX192HvccFWBdpzje4tFIzXIR230thb22VzdJpP862mwO4wpcDRiZuKFvSwUQ4JSxt94mx1yO84IYlGaeVOU3mjYFIwC2wCkWpcgROnywePTMavlwPfsJwcPZvLj/fxGdGKVo43zTuccr+Vs6NzuPnh5I61A744jcGiJO9dTerV6yMnAOdTpvOxLBc3u3Ne51hDBvo1tmxVQm+NVK6wL1T4azMEnQaQbVxzW9Zk=
  template:
    metadata:
      name: client-credentials
      namespace: alloy
    type: stringData
