---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-credentials
  namespace: alloy-logs-collector
spec:
  encryptedData:
    password: AgB34OVHBiRqvAHWIugyVLyiqpPknr00gBpXV6NqIa3sbrWf5wjOQcxjfqc7qcIhXf8y3uoEGrlf0VmI1+AJtJSBdz+0iXuHNLVGb/oMWiSazD+UtpP3d3KJZEElMn9zeexJe/35tVNu7unlgxotqMXds9sxBzig7NNJOgk8cl9Y3Oa2mmB+lnFDDp9iop08PKBfb5TtgaPOvu01fHbEleXkEpIXIiyx2awGWijlbtcOnV7doY407pf+GrS/VMJKwI/O0JasQiOgZ88bZCY1tlKKh3Ub/xEjUZ0TgILQmO/EruFNUccUnTv3o+JMZc1uO67KD9qs+LJtSq5KCV/OkvYjwF5tkC1nlyRrz6ntQ1nEuWluWN41PCH3y8W+2wIOweQTrdKKtF7uQbb0ZQM1IklZ6X65nq/3q5w6U1EVYwrTApBq/u69YZPtOLPnNV2E/7WYhr+3QdAnN7wzyknzrK8usL+6Jl0BvyYeWROhR1U4tLx6jqfsh4tkgqwkVFhccsRkCJWzCLunc0MP/KcRQX6JCHQLrrl4zUptu43WxPqf3N0lE5U4xQa4/nfAmfhl1voWIpFXE+5//JlbIHELlOUOHZY+OF9FuzkY7HIptXRChv3qgEbUJzWYl+e+H6OlbSSVPvThgDgxJU305JKcvVmICHgTzBAem9u+ZlLvEfT3CoDCvbp4WHRPGdsqD3XdPcvGjuStRrvUjHnZeKjmMCkq6HyI
    username: AgDE8N5eWahHH0/F7nXyBPeBuN2YEmCUlXKnpytcDbDU+FtI2QZ98dwWq6CZ9TRQdPRGmdeHePZJ4JLYCnxDcaIv3SOQSZ76+vz4rrOko8n1zj2/dWzfqk5uW/rP1sTAi/O799sneCDGNdijwgMX3SWgBMZCE+9EYrrZ72PLu3jsaPOmVji5smCRmfY6a+Ol8pR1Fn29qGIUfNliLcCGssYadcVFz3rlZi8X5pUDFwJcGAoJhN0p1rBRLyo1Jy1O65fVl/xgPLBRXqxLj+l2e7X03t2ac4co0GN8/bzE1DelqRk51paIEq4Qxj0tSpuAk/PJBZlS6ecy0iSZynGifWGgGRWi8LgAH3FqQliv9hHKjlQgL4511FSCV2SR3amOe+JvG55EtPjn1o802qQ3wA80TD6KjD2emEiwaoOYquk2s8iSSXnHKjVna5IH/q9ssHemT40dR/4/Cva6T8zLcXc13mk0lt4DVDHBABkBsw+qTYqrEYw3QpBfukPo9fmxaIBXBMRNawZza7Fk7mcqkOTlW5fBGc7EzlWihHk+sMbh3XeJF1f8lyMw0CxIOJR+gPHo6ylsk6+ZInKSca+ehiBCaxeRLYPW+JA+w3q+0bIg4BrMnDGX1EVLdgsUCiAO+AU3cpX4igrsnkfqmrRvp6P9aFZCAf5M469fBLN8osKH6/eWrrDRpst8emAUEL6Aeq5e1XxTO9X0Cjw=
  template:
    metadata:
      name: client-credentials
      namespace: alloy-logs-collector
    type: stringData
