apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-cache
  namespace: gitlab-runner-helm-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: cyclops-fs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-cache
  namespace: gitlab-runner-helm-2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: cyclops-fs
  volumeMode: Filesystem
