apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kasm

# resources:

helmGlobals:
  chartHome: mycharts

helmCharts:
- name: kasm
  # includeCRDs: true
  namespace: kasm
  releaseName: base
  repo: https://github.com/kasmtech/kasm-helm.git
  valuesFile: values.yaml
  version: 1.1181.0
