apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

resources:
- base/wazuh-dashboard-networkpolicy.yaml
- base/wazuh-keycloak-client.yaml
- sealed-secrets/wazuh-api-credentials.yaml
- sealed-secrets/wazuh-authd-credentials.yaml
- sealed-secrets/wazuh-dashboard-credentials.yaml
- sealed-secrets/wazuh-indexer-credentials.yaml
- sealed-secrets/wazuh-keycloak-client.yaml

helmCharts:
- name: wazuh
  namespace: wazuh
  releaseName: wazuh
  repo: https://morgoved.github.io/wazuh-helm/
  valuesFile: values.yaml
  version: 2.0.3

patches:
- path: patches/wazuh-dashboard-deployment.yaml
  target:
    kind: Deployment
    name: wazuh-dashboard
    version: v1
