apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: alloy
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: alloy
      podSelector:
        matchLabels:
          app.kubernetes.io/name: alloy
    ports:
    - port: http-metrics
      protocol: TCP
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - distributor
    matchLabels:
      app.kubernetes.io/name: loki
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fluent-bit
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: fluent-bit
      podSelector:
        matchLabels:
          app.kubernetes.io/name: fluent-bit
    ports:
    - port: http-metrics
      protocol: TCP
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - distributor
    matchLabels:
      app.kubernetes.io/name: loki
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: grafana
      podSelector:
        matchLabels:
          app.kubernetes.io/name: grafana
    ports:
    - port: http-metrics
      protocol: TCP
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - query-frontend
    matchLabels:
      app.kubernetes.io/name: loki
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-storage
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: rook-ceph-rgw
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: rook-ceph-cluster
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - compactor
      - index-gateway
      - ingester
      - ruler
  policyTypes:
  - Egress
