apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: alloy
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: alloy
      podSelector:
        matchLabels:
          app.kubernetes.io/name: alloy
    ports:
    - port: http-metrics
      protocol: TCP
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
        - gateway
        - read
        - write
        - single-binary
    matchLabels:
      app.kubernetes.io/name: loki
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fluent-bit
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: fluent-bit
      podSelector:
        matchLabels:
          app.kubernetes.io/name: fluent-bit
    ports:
    - port: http-metrics
      protocol: TCP
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
        - gateway
        - read
        - write
        - single-binary
    matchLabels:
      app.kubernetes.io/name: loki
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: grafana
      podSelector:
        matchLabels:
          app.kubernetes.io/name: grafana
    ports:
    - port: http-metrics
      protocol: TCP
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
        - gateway
        - read
        - write
        - single-binary
    matchLabels:
      app.kubernetes.io/name: loki
  policyTypes:
  - Ingress
