apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-bucket
spec:
  bucketName: loki1
  storageClassName: ceph-bucket
  additionalConfig:
    maxObjects: "2000000"
    maxSize: "150G"
