---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-valkey-password
  namespace: grafana
spec:
  encryptedData:
    REDIS_PASSWORD: AgCTWGvaDBFPip4pDWoMmc7RY+kayg6qxFfyBr+lcDul7lLldW34zkbVYWfQfpu6Zvqgd1Az6XMp0o9t+plcu+10Nr0frs6jhdcc/kQQojHH+m52is/guji5R5EgZdGYDkdaPxV4312kd4O3xVnnC5U325ey3ZrhP6rxE3FNJtIRP6NcBr06yNWOXzrq5zyzE43smd29h9vybsVpHHwNUiP/v+nOZlyJBm5FlvAJedJXfSlPEmYFS9TS6h2lzSdaeZp5I7uCn5QexJ3d33MqTsGGPwrZjjY/lh/cE/NecutMNm4t4clDE0s9IbospkQ0uEQEThl5I8v7KaTzkYnsQWKrutPVoIG2BS3lRgDMoiRLZ7xQSII61qrl/ssr5dPxk/MVqrFFNb6iQ/YWIjuu2yp0EeNzT4Q7ZpyHpAVEhAqGqfi3/yhLmvi1zDcFK6y2lS8jzwESrFOmiFO99qaKouwIA4l2uwqR4BufUpAq6cqhVBZYgpR4/Vd4UIS5mQYCncToeGPPw+77J3w7l7LTAYib4M1T4sJPHqNiOQ5Ccf3YIyxNqxl4komMlNO8kjIPHFm8R1F5zEH5EJxXXgj+0BW31/SzrYpoXNJZ+UIiiJipRY0zaQtb1rsw1022ciUDtZneeo5+K7A6z77GqJNUvacUpTP5IrIhqeKlmFIPs7Dpnwh4wG4OfdY17VAJieGMKa0WBZzzSIjiKJJmzVbj17gPsA9UlAijwogZvraeE97ho+BA08c0UZ68ml4I
  template:
    metadata:
      name: grafana-valkey-password
      namespace: grafana
    type: stringData
