---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-valkey-password
  namespace: grafana
spec:
  encryptedData:
    REDIS_PASSWORD: AgCVMnrYgtfOAlGnAPqYfXMzlPRj+aRox1/ZrKKA/KnjFsUnwo2Nm6/DQgjEhIaGBtN+EggLr6wNbWZ+ggCmhe3mD/mqRYNyzrClBcjzBVfeeZJPkSolm9iVTwzkcgzX75pgzCotF7ztx3nD5Oi+17gCoZdpHTMA+1CBhpmOKIk9dD267wgb1NDj5PVIwRh4Tb7F51ZC01d7mqOOeHN7S60tqIbwuR/q7qba/u6nAftJN0XGVmoSnfPBNj9OzG0Ourh7p+7D9awuBvwGAK2frSG+BSQ3ByFyqV8HQQyPdMAIhfBJ6/QjNx/5otS9YXNbNSHICIHOm/G7nHLDXgVpoda0KOnxu2LN8j3TShNDFl5orUKE1ca5pHLNYB8B5NjhkL9fmp82wMEihPCSXVFIM+Fcc+5sQVMYxXeI+wgttrSe5BxzByxL+VNxvMEwaEvvBNg0V7K4jIPGMNrpp319WAdGUq8KvJMhAu0rU2WTqyLkL53UnThzFAqBMRFH59JcTIeipI+yU9ylbor3OfK6rMddsaPiRqHStA55uxe3Lhpxj+N29S4gIN5Mp7K0vudmxb5q8IytAyGYuIapCzGALMaJKILYm6oWvI543VhFHLcQ7J+vd+HJyLA0guSJWbtDdNU+JkL4ZfqELKuZlWTU762O0uaQu+XeWEBHQs/rvfvhAPjenPL/PO9koujXrXc5e2DffVmHLYsdDHRbfl4UvCsvjG3vdl0s+ZUlXRcrKSIdU7URP05RNREAPPiJ
  template:
    metadata:
      name: grafana-valkey-password
      namespace: grafana
    type: stringData
