---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCL0Zi356fRoYsuN0yzU3JLBD2JMt7asw7nHd2WEi9kw/N3vJM/CPxtrzngaVB+NTGtvF2qxKFSlF6qwuwwRgkffq9qjSmwg+gLBz96FwlNl2EhUXSSRGzeOiX7Hg8gP1qXT79HOUk7cEWqqO0T8DrPIg40veOe79UzkpIP19N3DZS8YA4Ygo8RYvrgzZTx1eTK6uDz5+tBGItkQS5U45sfLqD/3L+sum8oc22coVMKQSG7xcg4CRvBwM7TR1GeTYwDnSla6pVL5ILqmKoOu5OrSUGl7f3zI101L1nmAUwjM2k6+rB/JqZOECbBk9J8UR2ZejFlhRYv547ApwMlre4YFZqkNlx/SDpPm1s/8tG1wv5BZrj+DfsIu61g6ZkjUVw7p22tWmHQrVN6qQ5pEk/1FfbwJcKpFGoTf8yp2rQIrKqRv10PJ33gjkn/mVdW1zu7qiYtqlAFpBhjz5/QOQeuwkk9zzFTL/JYJONwgLaXqdYL/3Xn/YzizyDOjRIEbhX3hvJhYycRD05vgqpGhvUYP/XjxR7/J2C5WZok8cYi4zeFRaSWcMJx9LYPapbcS2ZS1uhvR6fAAsIdqddHv62mvqB2VRSNhZovND4cjT5z+wlorLaXt4UM5qPZ6zZEspKJjmwkCq50mu/lkZNrtrq3ocHuQWdKOwNVSjp5+VAgyNI5fapXiH7wMG63c+mj/HiIW54/icbH
    admin-user: AgCMHI1jPbbtRxa/49d8pb82WK6bKz7gNk2iwgUDb6z0UoJQgqItQhX7lPLKMNqkFXFFIXjSLLLK/6mhTUHIlvtysbQHK/0BhrheawMICGzgVPurj07JXWzm1EK7uCB3zIj0lw1AwuCQ333q9z24c43/30ZhNhY5gU+C0sllIiJu8+kTpjGj2DTvHr/vHrF94BfgKHIR9W+6OEeyxHKLqJF021wAI2etgY5EtKxHAYhfLFS4SlX78gAI545IAR2a9oSL16GIeeY9rdQUrxTrvp4tpePtmNwWRJB59+lq8bNuAj+UZlQ+b0JHWYk42rNoSI4lA53vdlJPxWXi3SFy/eFtYcMg7DDISS32sMauxR0O0IjJxgbcuzKxDEPWA8cG6OcSeVcbVCuS+qhGb9JAr9NDY0DewzOthw8JcXg9Q6xteno1/5lEFWjfof57ua5masXVuTTHOa18alccjlb8UK5QZFveWe8GwPKR+Vsej043wXikzX8eFTXhY91ULayR3Daj3cLvKE0uqbdVl8MnOndf7OhXFAKiQ6x/pCPsOhwTDG13+K9RxETqJI0zuealJxvraea8lV3lsrMujZZRnxIx7C+7MhDGQGbKcl10PPW/m/QStbSCNnECtrsU40mNqpzLiScr/Iv+rALhoRcD6tqPUCNh20Wgnia0P/e44FHNo4qUcf67OfMDPNzSYeg4ezS6DLwGkA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
