---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-image-renderer-token
  namespace: grafana
spec:
  encryptedData:
    token: AgAOKGfDFJliids7Udlg5BKsDoeNC/bHy+Ce+shaAqu9KWsP7Wbtuzrl2jbXjI1M0aleo/6z5X5q0AatyH1ZZArvsg9i0qtoownPAvdyqEsjB2T11B2A+Oms4hv4fNY+1oRq0Ha+BDyRphIs+y8I6M3RjkQaf2kblV1gSRWztFCrHfd1vuEkzO29lA/ZbbsAQIvVIHk2hm2oX5mTH04daW0OFdHiCzClGwqFVCsQLdhjsyGGt2t4lUOUgx8Y8VrLUbizNt5Y+rKbYezZlFV/AAhjHfbw0EVKyf/S5EbCPlkc1U8SUjDPpvDnz5b9/oDTfVDZTE4WKbktrnCi/w9Ntmn07GMtI7RvSPl6I5cdobA0lq5NyFyWbTB0hsto0pCqTOdaS6NUg8yJgvOfMIaN8I4fw9080oSqnQmtzfyKa8eXoRozwvp256jY2DeW8988kwZVc7CkbsTvAGibO4aP5/hXBtz2qVs9srnaq4+jSKqwVCI3pRi32zgjqp4e8bryPPBQS/dQow8HGM/Ot2ax6mHec+5F/+KAUuOxh81zKsNnCEAuwt/n3wZT13+M7La9Wa9Opr1eM0u5ArRYjfv75xXaHgYylSttV4z/NvG662yQ8QbqP0Sn/oKM+aiAI+soIjTK2KIBfOKbdUT3JkGAvLycCLYp9Jy5wGZXTdTPPqEgH2BRbfndQgBEGubRZjucIvq9QjloBa1Y+S2sYJG3R0gUqXWQTzMW9hFFVXZoGc66i5oEqFDiWNRe601aBg==
  template:
    metadata:
      name: grafana-image-renderer-token
      namespace: grafana
    type: stringData
