---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCOSb3NNnTHm+BwU3Gkji718kZ1LjXIQTt8bs656TA5j+5AiJ/sSQlj6Zc8Jvb0QjDegzxwRsgV+/OkdpTc87FB+XNtsZx7VeOccK9R6ztGh9aGmsxUxdxNWslnqHLv1Hd8jP+qUobCrHjncfzPK8jAl+UkvSVM57KkmLCFmZxoL8mlpj4Gpn3D3MpH70O9HpExjqdOzjQgADPb3kUMQloH45moVBDZ71WQaK3IDILcO7Z14D6bt56IpU1UGLd1aS1lmQMbA+IxwiWWE+idixr5qbSvswObmFvVGJyN3k4Wf1OMXBcbt4+K425y3Hqgrs91EgDrrEcZRTgpqmZrpwNU+j00SfSFUAHVMwbKqadIfCoiOG9EagWwIs8oDkioIagtPZCMBxBq8pX+RVs/5bypni9ZF/XthCLwtCRhJP2E6Ip5gPEnDaaax86eNz66t8yhyBLgftkcp2Az0pvyizbECEqXpnWre4z5+l/+ncFauoXIL0gSvgLLP5uRsZ5Cu1yxk2zVYymqRazHb/xAjsrA1n/Qy/jrGNmr38ktchJ++wIp5Yj/87Aw4XY5c1MIB2/zx6/3Qx5H7tKHrZxZVYhItPiGHQcxQQ9xQAUj5mq2o6A5vT0LyYUiIQlV+RflMs/hDjpY0dbO6igHOOOcnL3W20LGYkn0IIrdTuBMphFATK2SezJfvqSdJ0aFnLnYoxnbFRqRAhVf
    client-secret: AgAGgc3+q7FBeGgoaBOyLgntZqNuJJ4VjzPCHiggcXyo9VfeC8H1zspZB46v1VG2ZSHSTT27eek6OhTSnNSYnmXDC2XuaeJghWEl9bkSQbqqX0sxo3WrF6R+Mu1NRbgpR5xyFGpPRZiPzYGntRDrc/wE22eeCWPrO511YM4UXz3UbQFMjBSAG5MwVRrReRbefq8VUOfanqkCBrOsUCHXDLiXg6VDiD454xCkgOvS2ZAjCDIFvkbFQzpy07ElURPAIza90D7JdRIyGnXnZv761pt05Feo8SGmaSOC5PqLRuTzTdxDZnEhLJIbHqqqzRAoVOuvBG2P/lW7OAdwDf2cMCEseu6BZFN2xYQGEKH0wHVGi+XYjC/DkxqhdEUI7YfBAaPDwHpB8EPG15RHgpHjQPCfA+VqVBtI6OrrIF3X092F6O2F41XZJuGEzHDggSxViOg40de13HkqV6C8Sq530wc9v5zn4hQRVz+Dzp/tR/L+vgKc/OIRu3D4+JHvFNx94OvzOlxLtqtEKN8cXSudlB/Sy4I5ADbEZA5g8Vlr7+O4wPSTFLpiBy469I6m09sEsziatmIZLb4Pjr+KbXPdmDv1lLBm2/WB/5Lyj/5TFdNe7rCfPkARnu1Ugu0nxF7TLRNH3vE7LcJPyvC8PmwuL99iT0Y38nRmusFiCF3Qsuyhnalwf/UL/pAcE5XirpoiwMCtwMQJBqF/6tdYkY0n1mi2t8gqAGwmJdBlEBB5R1TcTA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
