---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-valkey-password
  namespace: grafana
spec:
  encryptedData:
    REDIS_PASSWORD: AgDBFTCKsbUhnb/fABw3p9za3aiu9P0z0m6PLjC2WfMtUUQxIvm8o5qE3PsOM4IbBWN91uLXDXXooVcRL9AEggL9Vnci/3s6X9xduXg50WJMeO4tlvm9fN98FevZwiiSo6TmqzvHKu1uOvtUmXl0CzHUukEpg4C7f5Fdl/O9wo6n2JFByEwWtf5Hs0l55MTVm9z8VwmMcWOFEz3ZYpUW4KgKACirwpn5m+TVRqatm0C7nRe1+YUqGBcwc8RXvyjGFRcuf+4p/nda7QpEoBprkeedR6eg73iczTwutJW0EPldfHbkA8k+DGTzT0jiuP301AhFhzHboby9oN8UgED2gL3bI3IZydu4PQMdilsO7WFrjIpIZFE8EoKR/OlZcxYFUQDMXO7K8AGlNg1sT6IbRIG5Kb0QTtPfgSlUmAlYzRvo6MCrmftvM1tHPyVT7QHTEKjGQQrCxUmJgoP8l+qj4P5mVimzL9ydb5vIVRGBTtqLQGfHIA8qOKgkqrY6BXdbo2HFuq9Q4TGuyyogJEUkyniHR464Dwxz9ynqtUm4ydmBpa585lmt5ggdpEMWQLyEEd4Mgye7hMJ8g0Ckmio03uIt0Hs6GupcYoGZT5LAXsW8f9uHIqorZci/WbQS81iNTor3Bq7kup8BKm1xYhRKKaG7AmFU/Hcolru8COVL9nVY98uSwzlOh2Q6lfwTOCuZCKHXFRK8cFOXRRAXSA5IQy3MhuX5Mz4c79XrEuQiNHd6CaZ5rkuF/0AvSL/B
  template:
    metadata:
      name: grafana-valkey-password
      namespace: grafana
    type: stringData
