---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCmuxe6UIBkJ5mnStJM7qTA8fUaqXdiufc1/pytkTzpD/poMsK1zPLfY/MEk1nf/VPCBclBUMSssY4XTF2cxNjoFbhN9GPrqylabOuSe6LB0cOCFejnUSciAYk5a0BTZg3Qbv2swKL9HnYUT/yEVHZJocxs+YcAZPCurISP3Yje0OhK6QfJV9i/eAnvh3jpgMEYLFv5FB9YwbFEyHNCHXlxtiOYQDSsVgjaihuWgH84EUwdTdUsqoPnvDjM+JNGEGdzVs4QHjIwpBAV2mG1wKzr4tBVwmB87ursl0SIFd4pYj5Tu6r5Ua5oErfzAiQQCzz89/sgEZCZDWfrXE2w8WSCDIzf6b2tQcdaY3364YLl1oQhTBgqLwWknQeQeKxxjc2B/GH4fAUEQnGmBmJXAnU/5Tbccx1sdFjknqj66Jz/dPWpbpN4dDI2uSLqtGmSlyycFeFXra9zQ3hM34K9z58K9b8Kk8AjWgbbrLTjc4SEQZY/U0t8g5apsABbH4KjJb9CgmXw8wjhmD/KCuGTt4roH3goKH1yEQZYWz4N7m0C+3gBZWwcsulA9yiwUXt0HdiXV+E/iPJflTF+3jPeVAr3BRyzP66jj+T7KaGJNbezdtV5BdGQflJ1I7IpXt28GFlAAUVt36WW0csGgpDtXJfLh4CRT8sp66XPBVmtuVizLhE3wxU/p2K4pvgZxZECgYxRZT4K6EjX
    admin-user: AgBo8XH82f3j0+O6GMmXOvWFB2rf/6fVPUGlOysfQh6W3NAIhVhlMa/XU3nCCViMTgXESUh6cjdYfpojpZh0fMQWLgWmHneoHJMz7e3qNKDo3J8D3rr2CMxW1iGNR7aaB7NFIL6cQcQzIxlZVuctrKMlCfdsCU32jEobmh/ldvEm8UOYqSBl1V5MjN5Rdbnj+If+5PiybaWLLJ+T/Ad+ahoBItQpoEhxMvS6yPNDMJDxurbV9ti7SMVVYTr27HWdoDkU7n2N0hdf2vk7EmC1RaPjLWutWTwcExaTimy1Q3sUwFIF5sfRTIbT34iAb4giZBvLcabdPkMaGi9sSkQ1aJ32iH96enutQEA5X5XycmljHsLnsODP+6CWvZ06F36idnbAYQY55ik9bUFmphBnr6PMSjeBw7+ASH7vmFwATZFl+Sa+qKwcZLhvEM4t7m+Uzye0/bY/90VnD3wgaPX3WtERCVuPeq5PFp1PbNEUl78bEPejY4ZmPlh5iIqMonOwcgrtfCj+B5qc/VO89b3VRMPD4FCrl6EMcww0uczWdFHT4L3nXK8F6OBpYPF33Zb2/HKU+2PLybJVXFxSiQdvZb0EDRK6rOBlEybYz9LpMDHl5HMrEx4aKYmQ4fuX7P92+4xs7bVzomnoGfEFwqBM4TuIKLPzs3SN668SbGksCqr8llZe8U8bU9wH6yo9IO8esYjoUFyEyw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
