---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBESy7mVkp8NXpgAllnOrdS3J1lcPrmKhzwNT6J3Biq13t/lXCB1RbMxbb3fK2GScTeLriANIN2TRJNi9a0MYRrI5uOeSbwYPdL1r3Fd+iKGwAgWFucs0+qTufT+gnL2bDxwVKo+LD+x+wSujJ3mYLJEZp4QxF9u6/b5z3i3HWVSWXn5tUkU4BVMDcbn+7xLhSNOzyjPWDfq1xho/SS9Y3Y/Rsy7z5AJIWpy5ZRN0MF5mYEtxZpM7WaUbTPcZe1czQxD5UKwnS/1ghICY27r3iBnDmqjuFeAxbTDlf5fxprFsuZ4btHiBkp082myyTxHo893DzOYa0Mjks5DQLay74o8XwxLJShM4KAFhIjtmxxbREtZ3jihO9PVZ4QwvJTXtLBxcEGEDJVZQzskgIk+Q17fhcUaEhPxWvMkV/4Gdry/k+otqOvZKlicpSG+g1BwCZXymvtNqLJdV68qlQlRacYC5bnqAdkJOz2raWUvOMdi2xlNrWSB2lutfbmK8GHjzqbjKbgsFc62uNVoHjAR0DqhqNlbRMkXrKFCS3iEpla17p/ZLCi+6FVhVm/tSfhgmbUYsTYPJpNNL+e6D2eWWD7Q51GifRisPbm0MGedT8cUxq1DoO+nLBFkh5zENR8HLvJXeaz8HeN33ccshlMv9ZAc/ZiglxWhqzsPZwa7qFqI6GA+Cp8oSZLXtbmzBZQcNfNM/aA2Qf3
    admin-user: AgBkL7klzUDqsDxetkgVonfpVck3FPmyxglgDW7rSCuDuFLHEzVG4GsWdANNKjVRITofUt3tKFob4tsauScD0fY+0C94DgwJOMDxsnhviYjXzeo4QzIreq+qAJpCI3Lx1f3lpjsa6w08wuHnNdFG96JCTtzBnk1RURzNb646gd3SJi6JtK11M+YxBjXZGtZic0D+cRhjiCDf92wZ7aOFNXG4pYnAVMgmBHlUQLD2i2Xsp8nxFa1yRBdXX8IoiXRltP+PlBinuMO0CoiSUNDRXq+k1P6IEFW3yKDy4iR5ZkX+hIIk1Hp1iJ1od0R8O5csET2770C9Mkd/qIsRDs2Ze78oM+FxrNWSO4aCVXbmGoDsFKWjfuMqeE9HpoXWzzETaletZViYPm6jTRbdJg+Nqkw7lA4IxGMsctaDpzcWTzD/XSMy3NTge3T1KOmUp7OfGeqUoKKdGwQEyZGadk91B9IS0/uxkgVEh8ZqHFRJ0hrh8LColi7X6WHooflP2Zj+j1N4PryiJAB8Og4R3y3KLRK8aPTGV7LhCS9IHL3lmMjKikUuoUNbQ0OxIbaBcNvUqnh8xpl9EEnj8LMl86VvJXTvZI5dcG0FQD3XSFPoCZURRpOe2iDipDlu+eiMMCozNFDjH/WfnhFVlz3aTUkIGzVWj8auyegNrBEtgBJJczBw4+Nw8hQ9KqysMZaT+rtubrNAdTDNeA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
