---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-image-renderer-token
  namespace: grafana
spec:
  encryptedData:
    token: AgBX8EPHyE/PygjQuacUu9uLXOKL1bepveYfTGzPFZrhgO/fKNtfgKHP5KZkLRHVneV31tldvYL0V1tTwSZkmYxk1swgR0Ha8xKJahDNrpyYCGMHsQoG7y7swggkMXhfTmLRmDsMQLLqgO6f5tNcgERPTfnSWk78FlqdewoZNaL2Py8Pv76L9+l0ia5tE5obSNuKZUNreGJCGIaPwmH62yvS2NMpDYN7Y0yxFyX44ZT38GxBCx8Suu36ebECNOCjsXiH0M+pxcjRUuSw5zVMG5Ya503dGcZnhOKDAqIDl3aut2Hn9izjKKQIgNfo12hgjCTX8RpRVfp0IFT+NNwXzwpz7SvzX3Jo0TC8/hncsFXD6EIhJZyFaAYHG3AcsMHFFc9kXgqJOra8MHGn7DzITllrhAAL0mj5DgQqhHAzmi/z983wOWhk3SzcfDejkxXyZnc2wGqD58lpUPTG968VWT2FLrLIZePar3Jw7/wkrKP/ZJrFT/yQBkhrK8z8WCrOTCxcfhZJvEFlmrtxAENyIPOYIF0buH549LH3TrL9ZCP3fZZXx/xs9AsBYmhKbMApeBzytJNYUyfQC3FY2f8hxN6H7irplq63dsfwuohQMqF0czBuFm80ECE4RXFT2WexGtTs3006pVy7pJqGB8k9qpoN2dPG6mpoOY5ofikywHXutUC8reFfhL8Yu28JiGxtI97CfcDfgMlmt9quNy776U6seHzGwvWB8ruF0mgGjUvYYZNjPEFJRtGPv9Q+ng==
  template:
    metadata:
      name: grafana-image-renderer-token
      namespace: grafana
    type: stringData
