---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret-key
  namespace: grafana
spec:
  encryptedData:
    secret_key: AgB45R+3KHnFAW93MGhnxt8E8TB5578oJoRyboVpimeQwMiooF8l0ltqFZFfdPyYp/u2Tg3zIIBMJMSLFmQMZAEUq95Hl5n/SKRrfXs8EYSpQIeEDjB1KZi+uLgGgmtfYSPPhidhFu05ZTRzzLdGqwHy4I4mqwNKqpqUdYaZLrDP6Ke1SVGZ1OJIZ04p/fTkcgGmhsyBM2KdeNU6FnHOQHLrwvWhMLNEKgXn04foXrN1Kr+UmMrjCj8YIMa+HD/2CWD9KJMd7pVT38haCD3aTsOww/fTZkQG6HUEdz+Uo5DVYkCMHKjrIz1/+53hOWV7EUrSZO9grXr4VOlUof/CvT2sx5XU5kCl4RhrywXvatbZ3MGlqLC3bJjUqjAiznDlVMVQn1y5fIysuKRSIsu7DhTH+K5wbQMKZo26H4p4qbnSUvhCjccI/DX/OnREsALLcx481a6DNxFcbKhIfhmY7EnqCGQRSpEmHV51oxpFlrbi0G3msakV8Z5x9WQcOFA2BG5KRlMHvZouQ3HuyO5EJKtIa5BbxZhLvQIdmSkmIU1SKRlmjGa4RsuDpQ2EyqMIWUpWHhoY/Xdd2/cJ1qRRI1KFdl6Kh8xHG1x33BOs+lwfxOz7ibDt2IHUXovTO6xWsLGc9Ij+eEBV924AUxKh8rynj0yOpVTlC8a4GDp91CP6nBKAdnfpHw4dDj4sv1EdWf04oPNRMEzPkM3TrrxtdCpMGj52puaDl+T7k/2xzUUMKB7uKDv/fdtCrrExyw==
  template:
    metadata:
      name: grafana-secret-key
      namespace: grafana
    type: stringData
