---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBD5nAV7BCbDjX2okJPlZHC7xHVMog8AeSaYSYCmvMlF9Yh/rTALxOiEy8y8m2D4h0b6kpIG2hhO9lU4uBDhJ4CpIJIwL2lnoZhzqaUXBsv3tw/bmU0GniEESvgBOhO4lDNzaWzfbMPjHbzaUNSR2cVDpna3VsI8tW3Uf/Q8xqT3YQYrKaGU5SmSJCgvwQ1bY8u6zFh3PwJHMg0meAmKoFplYCYAb3KyiiAdT17jFmfuTsyE1dzBOC6zXZkROJUKliKWWHk+D7KOHpF2XWrwFAyC/W0qPrL1kFdb0wq0KUVihv84g5UaupEVDlog7rySOq14X7Fh9gg40OHG1rB+xLhiiItoTAdkI1uDE9HZyvIbJPzEt6RREjcdXDA86u7YSzxFedPrcB7wzXDfrnjMP+qJquS2PawTaTLW8rSohA7DOJuE3uuxrUIILTB89Uf3aZEkNaCd3AgMzaSEYn+0/FKqvXyiYgmbLQ38cV0hnYkNoVYjZSoeGEfkdIrUeWon2j6SqWwLtpygByBtrGqA3wdW5Yhf7mwp7WQwn39rh9dKYBMHudban93lgc4wBAcygOblUXgwuyhdtLLXDiR+VeBMylZGMdZamnqSTLPrAhda4vN2y5aqwDq6UGsqA6r/IJBjZ1k1yGTdeGxDrHiMKa6IR1Nu1c4oVFATvdYEgAmMCBJI2Nw3/vGWk45LInVHN0EYN5a8i/y
    client-secret: AgCYZny84BnbUokMM4oD20CE2jK8sFMJuSzVRFDtSF7p6akCsFl8+D1EwXmngyOslVzmI4CVF2dIIVQqdWgiCzdZ6QcCW68LDWX5Y7HsqiuLBl6Bo8kN+GYdXUI5pM0IH2SuzeMBJVdKSFg4cnTtOd48mnYC8KCMCMKwebOYZgtcbdiZ2VZoDxUEJLc1IZpreaGGl/xK1Xq5lY/0xzmI8CYkN8obzHMLwYs5pVU5XEcQR7Wngb/ZhOCZTPen9xYhovgYeyvV0vjf0o8XtG2/0d71pQONrH0qbUXp6iuxEdaYK5XpoLiXChbBqrj9L1gLkmPGOYdVbRMa8efc6JlKZ+1crYWiw/7RCkjMoPC1pSf3CexqvxhdPcB2XvH+A+YFu5MHRu6i8BimfzshQPLTnxRO8XtEQxFTPiZIezPLeDvO14MXhVly7P6V/1cm+a37zROUPV1I/ZIkfz4a5EXKgbBIrxhfnC//6ZFf7/1JjDN6XiWY6vTQIIwu7Mrbe+VJHCb68nSn/MOQv8Qek1+B+7BDLbhUcGEjv5ZQTmdhJnTx1ughs6JCjBaRRTuD0PLgSNTKoLPdSoVTpPFhiLTTgszgTUpuJZLusZtOs9ItaiZ0EOBtSkx7XdJXEnb3CZ1gJ0Lbb+EHUBatJV+IBFdv9lS0ENcKfs5OCTaHrNBHwTeRMAbmob+/ck6sxpNMZYOon8qUVrefBgXAgYcWxAUPQ1IfKXYdUdZkBsCrieKB5WxYvA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
