---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret-key
  namespace: grafana
spec:
  encryptedData:
    secret_key: AgDFF6hx5+MAk8eMwQZez1LoB1StmLohQHnjXvU6RUY0dKX8iQ4nLVKKWKukSMP+Gta5bEQTAYFbIpqi03pJ1WLLlpdUguvnOwxebzPG0WZ3BzzRB4TIVmc9i0xrsjUjcb41H+Vt7BfFTlPIB7PIYJ4mSUlU8bGtiXoVVEgylmKOyGKmlt6HWtKvjCjWbT5nvMtWq7AyRQhbpAq73lpy1rqo/30+3rU9eiBpWb1pKpviKEUL0QA7wHmW2SgIDe4J01LIii7VNYb85NcWdLl/B8XASU6fLPNo2sWMDFNCRrcu2tWnB+toTt+xcFm0qPlVH2aAPhYFhE8T7UYEN01ta8H+crrXc9RUw53s8CsNuMV5IeKpeR5RoftemJvoqqiy7LhLiXkq/8LXeoKCtWGetfa8LTxv/nXqh/7/X0zkZj3ULiA2lGBcp4GXg1hxDGfXM9K+95NnoUph1yEQfU7TT5DQWGXOqmsnwl304WcobWfl5Ppo1ADqE/6kkScmwKF3fdOiGmotEM75hMtVIIVpFu8eSysYu/9hULweieUdFDfba95kxCnHA3eXjjf+pMf0iK/kEKosBuKqg/wN0C9hh54q+6GZlbKHb2xZfU7qxOftPv7lq+okMzPYLQMeEXtLX9sgzlQnp71SCCyQdqiQHHFhDoUPQGwdTv6nQNo9jjsdVcU3UJn8MWN+CjOHYkYmLi+tA1JPF2Gh2nlq2wgslZVLzGeOkDoHjNlw8QUTt9TX5qVj42HjZzgy8P9N4g==
  template:
    metadata:
      name: grafana-secret-key
      namespace: grafana
    type: stringData
