---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBdvvTjCl0TlttyGVaM/IW3xAWW0aWpS6hxlTSkZ/2ah7qwb01nd8W6Xp7kzrwD8VCrw11OwBYrOA/8S9fmDedyV9gdx9mJ72aZM4LLOQnnnixBC8CSHbUkZ9/WGHNfMwsHsJQTya2aZtZLT+zBbkFGow6BjC42jzMXi5Mv4uWL4BX5cy9NI0TEhVx7qvTr8FQfDGeiz64eGZZzCz3csG2XvcweSW6MIlxzQgUCQRd5Wr152XYSM/iUM9HKjFk6dP34N6pVLmk2HQ/hbem/YF7orYS/DAzknK6puhzfqc8ngnkQcfapqY0IqYkRb5dIoTWK6fFKEG9zKXGMkUFMkhgHVEQIfUUKUX/qKU7MepijSBpvXLlY1G8mBqaHGH3UVOiB7/+kmJNJXAWjSW0/j8MhHrnjURVvVIYWlhokNs1OR/S4rxpd0n9dEE2WRZTuvNaloYJX6awlBlXCbqOD6PRxN6KMOreVCcjsAcjJhFF1lkAGHBTrxh54ggW44537+5kmUHE+77omjvu71mNe1FQMTiwKbzMph5KJTFvPLCihQbOUCBGn3z6CrCz3sBLuN9Z5prjkn3qaFOB1LWEconAgy46k3MyyuQ34P7SWFYsFSqNyx1n9slVxV/NVhQbwX4+uJ/tzMmxsEI+gfnf6l5mbl8ui6bVZiY45GVPl0iOpWHJAOaJPTQMPkE0q/onXqXfu9tFvehg5
    client-secret: AgB/CbquvQPN9ANgBZZaTD8J5hsL747IOCnK7F+QbPPdYUEWfY+iS1P5Zxqh9wudkYhhKrKayR1Ac9u6rMF4vJBZDqnjmPMbpoHPRqkL2hbjbzYo6rKe92bmfBKpMVjD42zg0Gv+dBGfSZHdr04w/5tZ2+m0izlSOEGHDRSnB62l3CBS90QzEuxj9svmtvR/LJGNiNS0dvr3Q0PRMJrrKuHM7Tdyu9vaXuZ2rEP/cPs6vm8IYt8pS0G0oTy8l3a25pnUAeeD2L462Dji9pQ8JxzmLBxpxkR41+lnEw+8ZNXmqq3J6DRD85qfrX4+6b0FKCeG/dj7q7jfk9RmoM2PRER/Y5boJ2vxwjdqKdjXoOnFWEq8+mpCe9ZOnAnnwIxPQwr75io42dA0pAVVSOEnFXt9VE4wuedcw6dyCOGOOq5zApnev+SsRlBGecXlte6QSC51aO6TtmAHRz855HxqzY3mTpB0v9VEG6iRuJ++cKXerOsdxoRCxVp7FK9WYd58cmgyRXkrd0RL4s9ovi7X/bunFHPUplKf4Iz9AJIMk9KwlBYQhpLmMwKCsT9gBnOZTahBsSJUaYfETg+pnwDOJoj6RIqB+Qh6cGmlU9T5cMfY90PshZISqEgWF4cY+MK6FQ0ASSgCvP4CIGig8ROU16BUEsDjGitzl1mRyZ4RPVbjf3bUJ7K2TZDf6aL1j/x/PJU6B5Gw+EZox63JK4GYC8q0kY5sT/0o357wajHt0LylwQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
