---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-image-renderer-token
  namespace: grafana
spec:
  encryptedData:
    token: AgCn558tbEMrSlXOCKt9cHMTWBfCrG1kPHMfPUAcA4FPio8FU5Pbs21p3xqbGpx/0lpnRn0NZoM22VrBIVoyaAkcjYqahd8RkcrLFbEGYqULI/l9/SdemaF5PgMrZoW0++3wCOZLh3yq+KiCmnmJW/SQYYPsUtwexrkryKRxM/02dUmjtMWdBMDVpzZ3C60rWQF1mR6mD4c5to32LQb2cJoOi5clOMbWqWaF1qNmhY8kaC+aHXItygtpqF6LlMS1wNRwASJuYrAdDuQJAJwx59LMQBqsUENkNyzWtM/bGzBEJip/Z43YUYfWX29vHtyC1JhPI/wIBzEtoRc4J5+SsZlQ8d5aHrkX0U4exqMN4JWqFEhCoapkmB67fAwbXNHgITzOpQ+yMfBKb1vpK5zFwngsdlOg1zcDB7j8SoUbYgjACGo3ZBwVUMPAra85tXuAJ6gl8zxY9iQPlMbDKI3A4e6iVIVZJmFkINGTpgnJGg5HBfAZdInIZKTv/e6/TaAcWbfe5+hLQtuwbN7oNItZmM5AdyTzk+KCPEfcJbooqrcnbpK5ZmXJsGvOiw+2lVHFqqU6BBLTDau+m9GWZ8Q74Ih1dXEKP84/N+vrnRauTHeq8ySHkQHm1PbJSZgw4Zi4aAvty694pFGYkJBvA7hSkkj1/WWoXOMTDTgCgVWVLvvJ4UbJQiuvwrzaaBsCPwx/r1froVn/dVORZEI/3B3l8Sx/UiYSY6j9VAGRam7P657pNDbQPEms4N8DrkXbgQ==
  template:
    metadata:
      name: grafana-image-renderer-token
      namespace: grafana
    type: stringData
