---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret-key
  namespace: grafana
spec:
  encryptedData:
    secret_key: AgAhOypwVObfNToi1KqS0haUOPf8v2d8Nkzk4O7hW0dYOmHovLH7Ir+p+DxbdTPcBuxbLN3po6gA5ZyiV7gbwm8Ybku+XzQx2acTl3Fi7m1el9fGpZqMCKXnFyy8XDmcRq3z9NJZSaWUI2w5D4y3Fe2wxKU5VV7f1PKZxDUMGWIaNSQZWOVR2NQh2g8hcjeNm3dIAjaUeL+itD3f/DJNrviFL+QVO5v1Pg9X41HKsFEBoTicU7gB6UuV1JXcYYlZ5lhKZ+8ejAfaHMLzF16O1dJiCGajN6UymAdnAkHBLcbY3aNLXrS3vnI8IlY2ArScbWRd+KpEkPvKO+LcJrC6g57SXqAodmILAI1zU9rC1fFiB1G7tVPLmfw/qvSaABYE3b1aCKHDMwJl/MaGTTm53B6xzRmwoxUY1Iu7btJG6mXMe2++SaNl+hs+buYRU9bkqn7sewVRVH9z70HJyFg10bMA647XZ1QdNVd4s7TdBB7nb/NeuUz0B40XLJjnQInS50bfbiqJZ6la+3NPdWsFS4NBlm3vTzyzWJ1mJrABw+kXpotPQ9uaV6gyGnDHX4R5McTU38EKo9JhQfQYkawuzOMjNmgHyYzWW2IR9fA3JXvgMaf3L0KJGeCySflpO5x6UqdCkl2N/ZhvEf6bSs+ab/Qvi5DajFqEtaq6Qkh3gzG8q23K9Lmv1GMLqVFsfwxP3Vhki/e7/Aq5o3wiFxWTrT7+5wQquydGqSo0FtrC/wzD2EZaHtJVSn3mNVOKeg==
  template:
    metadata:
      name: grafana-secret-key
      namespace: grafana
    type: stringData
