apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvidia-gpu-operator

# resources:
# - base/ingress.yaml

helmCharts:
- name: gpu-operator
  namespace: nvidia-gpu-operator
  releaseName: nvidia-gpu-operator
  repo: https://helm.ngc.nvidia.com/nvidia
  version: v1.0.0-devel
  valuesFile: values.yaml
