# https://github.com/NVIDIA/gpu-operator/blob/main/deployments/gpu-operator/values.yaml

cdi:
  nriPluginEnabled: true

driver:
  enabled: false
  nvidiaDriverCRD:
    nodeSelector:
      cpu-model.node.kubevirt.io/SandyBridge: "true"
  repository: registry.wcooke.me:5000/nvidia

dcgmExporter:
  enabled: true
  serviceMonitor:
    enabled: true
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_pod_node_name
      regex: (.*)
      targetLabel: instance
      replacement: $1
      action: replace

node-feature-discovery:
  worker:
    nodeSelector:
      kubernetes.io/hostname: amd64-1

operator:
  cleanupCRD: true
