---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: crossplane-provider-grafana
spec:
  encryptedData:
    credentials: AgAsnKAMY73uR20b40Kj6lHS7HFOyY1eQ3NJqN3PKMwmVdws3Yc9SjR6562mv28R4ZTbLqFCC90Gr1xHeM/khdZi7FRY4920ZU6qqIfcOjrQ4zE0C1VLwJmeb3XIOoHogB8U/4vuj0cEvtdJ+IKdj3Nk9kOmHnCsqguvnEL+a3NKchtHdliY7N6LitZ8I6IG2R7bNlxAXN9jIby02tKAejTzSBI061t0Gt3lJFME6me7uMX/X3Yq8iDI6ppz0kBlh7zykBg7MJT+SJF1Ts7ezCl/u0pA4vF8fRoI0VAXqAmNnUJvyrVKzibY6jde09zMtDOe8sI2vRDoN1K+urctBcoWi4UcyZHCkIJSd9huX7eRz2ilUm1uoryom8ENPvx30xwFrNVKyX7lgIXKZKQ9lIy7pMTVD7xXQwR5+41gO22TH5YcUmyzvwBWI0MhChWdjifk+PWpxxu06tMBs8dNEhM4FzWUuBgjCJz/MH7JY2j1tcQH4yJ4OABfolZnO4Kq4JxZb9B2yGiVOGD7ty2qSDYN+os8MOz+8rKCAnSnfTQb5UqMcsSSo+6qfV2RAqmA+zR/zRxMddQ0/Z7RS7+shftsqJ5MBw1MAVXEhkY5JcxtuHTSyZuni9ij14oCqJ9X+yajaHWzUCKURf3A2vE3CyoUoCVAEWrKgr3sQ1q3XaDQGvxcVUZgwJAVhcYvGOQWpQ1P1FK2wtPeH8ZOnp60ESjmY296GfdfnCnLhfHXf32FToQnxpu5GvOhd5PLQPRBx0nkeg5xR45MoqQTL7iUJkxa2MzHItY=
  template:
    metadata:
      labels:
        type: provider-credentials
      name: grafana-credentials
      namespace: crossplane-provider-grafana
    type: Opaque
