---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: crossplane-provider-grafana
spec:
  encryptedData:
    credentials: AgA7aXRAy0CIjx/XDNb2OChd7cE9gzf6yvBxrf28qCoTuFc32CsjOq/arAbLaBZfy9K3Dt9LCKnrtxGkOC4VBj4FuXE9wBed9Dbjp+JGDH6xM/pbv6Eqe/LWUOeC5v/PrqkOY2+M29G2ZUNgbKlsyOOrebb8BsFi6Xej8+4GYHux8ykMQKI4oSAn9ZzCLaNppKkkeIY/vwfu5w6PE3cjC0mIy109xItIWD3kKLP1TKGx4pEjTDTimLDGNhOMelQ9KN71ACcj4TR5TRThL2YQp7MaUFB6QtuM6du8as82eSF0q5Z/8dXxJ9PvjSy/pC1VuC/OUlAmlCH5K3iKjgB4TLmew/pXC2d/eVjiykbqjIScSMtbe6teznmt/iSR6WRW+61qKvz/1uKUFalCOenGmhZgoP8Uqy68W7v/8az9imAzlf4LMEijaQXQoXYYg4jqtfu3mh2dPJAlMbyvX9T+BGBlDM2bbagoZ3SKwsKpjAMlGtHdVigh7y2Hn+0BB8P7x6fY0d75aWGMT+WFfqhzIUUz2g6SNqM2rfbtbDvH5YIyNgAEYz3zE+6jlgzY6PbsddjwRP0ZLTGS0eZnNsK+kxGKY0iSmObfXkOPijn3QhsGC+tz30qoLhtPltRlkenBLRDxXdcKy5NfZxolNifSmq78oOa1IZrv4c7M4JXXM0VkMdmOx+4mslBXoCXMdGR6GdzUpTiea4FYRz1tsrbx4Nuh7qaGAeV9gVyWBBHimMiQqa4PydCVatJPDJPq9j/Xw1sA44ugjK6CSEaszWeynEVtJBwKztU=
  template:
    metadata:
      labels:
        type: provider-credentials
      name: grafana-credentials
      namespace: crossplane-provider-grafana
    type: Opaque
