---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: crossplane-provider-grafana
spec:
  encryptedData:
    credentials: AgA3KTToc0KJqP0kmfU6iFWmi46esGEOb+7/AIDZPmmF5n0uPCtQ05AOgxp/fTon1BJYPJonJ1qA+kg/SdZwHsr1P3zVtoxOaEsyL8GxWTGaZfyd08ojZF9I+7WVoEXiR0wgCIgBVUIzG4U+D7WH4kuqWstLwpQssR8hCSe9DRzej3X+XJWVc4qwsrSP5jTsE+eA/haPil8vw7bcRcSKOiEYOVF84R6kXeNHqdCVHpd3OLLmNueqQzO5itAa+tz8/3uJys8ddlSh2Nhu8cWZyIo09X13bdADnqpTTaxK4c9qDy8Q40RE8veKjuAbVFkiDtm7YWIf9LAt0K8NO5ZTQm8I+jth+wYEvwB2nUID0sATsjKBPy2cqRry7sq2E4x/WcgrE4IK7maRMMaoLFxTEHVk5k5hkrl84gigPrOisbELjwh61rA99YRytlVjLfdYofV+1KXN/vyAD1Na7o98ynsswZJx8JkMbb78i2fXrgrK88bphFWyL57wsCkZxu2qKwuEViMadECOgQWqJBlpbRfKG3wgz/qa/rCjfR6n/eS+3Kt/+M0BFp7DIippsiRgpP0YxvkMfSF5RpvtYY2q8GoubYxQcm1/xvvp/SHtjU45xQ9/dsvU01ekwT9x1VbJ0xGbami1iunHxIDLQtUY3v8DdesEG+nQNe5GjVhtWjKXnjR0x5ufzn/WbpX99najcHC0Yl6Ps665T0XfegqSutQQNv6h/jC10oMaXUH8DuRubFTWaFrIk3d+tXHlg9OllebtVLJXQPogS/wEznbK9gpJDMVCzGs=
  template:
    metadata:
      labels:
        type: provider-credentials
      name: grafana-credentials
      namespace: crossplane-provider-grafana
    type: Opaque
