apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openbao

resources:
- base/openbao-agent-objectbucketclaim.yaml
- base/openbao-keycloak-client.yaml
- sealed-secrets/openbao-seal-key.yaml

helmCharts:
- includeCRDs: true
  name: openbao
  namespace: openbao
  releaseName: openbao
  repo: https://openbao.github.io/openbao-helm
  valuesFile: values.yaml
  version: 0.27.2
