# https://github.com/openbao/openbao-helm/blob/main/charts/openbao/values.yaml

global:
  # -- TLS for end-to-end encrypted transport
  tlsDisable: true

  # -- Create PodSecurityPolicy for pods
  psp:
    enable: false

  serverTelemetry:
    # -- Enable integration with the Prometheus Operator
    # See the top level serverTelemetry section below before enabling this feature.
    prometheusOperator: false

injector:
  replicas: 1

  # -- If true, will enable a node exporter metrics endpoint at /metrics.
  metrics:
    enabled: true

  # -- Configures the log format of the injector. Supported log formats: "standard", "json".
  logFormat: "json"

  certs:
    # secretName is the name of the secret that has the TLS certificate and
    # private key to serve the injector webhook. If this is null, then the
    # injector will default to its automatic management mode that will assign
    # a service account to the injector to generate its own certificates.
    secretName: null

    # caBundle is a base64-encoded PEM-encoded certificate bundle for the CA
    # that signed the TLS certificate that the webhook serves. This must be set
    # if secretName is non-null unless an external service like cert-manager is
    # keeping the caBundle updated.
    caBundle: ""

    # certName and keyName are the names of the files within the secret for
    # the TLS cert and private key, respectively. These have reasonable
    # defaults but can be customized if necessary.
    certName: tls.crt
    keyName: tls.key

  podDisruptionBudget:
    maxUnavailable: 1

  strategy: |
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

server:
  logLevel: info
  logFormat: json

  # Used to define commands to run after the pod is ready.
  # This can be used to automate processes such as initialization
  # or bootstrapping auth methods.
  postStart: []
  # - /bin/sh
  # - -c
  # - /openbao/userconfig/myscript/run.sh

  # Ingress allows ingress services to be created to allow external access
  # from Kubernetes to access OpenBao pods.
  # If deployment is on OpenShift, the following block is ignored.
  # In order to expose the service, use the route section below
  ingress:
    activeService: true
    annotations:
      cert-manager.io/cluster-issuer: iaas-wcooke-me
      forecastle.stakater.com/appName: OpenBAO
      forecastle.stakater.com/expose: "true"
      forecastle.stakater.com/group: Apps
      forecastle.stakater.com/icon: https://openbao.apps.iaas.wcooke.me/ui/favicon.svg
      forecastle.stakater.com/network-restricted: "true"
    enabled: true
    ingressClassName: cilium-ingress
    pathType: Prefix
    hosts:
    - host: openbao.apps.iaas.wcooke.me
      # paths: []
    ## Extra paths to prepend to the host configuration. This is useful when working with annotation based services.
    # extraPaths: []
    # - path: /*
    #   backend:
    #     service:
    #       name: ssl-redirect
    #       port:
    #         number: use-annotation
    tls:
    - secretName: openbao-ingress-tls
      hosts:
      - openbao.apps.iaas.wcooke.me

  # This configures the OpenBao Statefulset to create a PVC for data
  # storage when using the file or raft backend storage engines.
  # See https://openbao.org/docs/configuration/storage to know more
  dataStorage:
    storageClass: ceph-filesystem

  auditStorage:
    enabled: true
    storageClass: ceph-filesystem

  # Run OpenBao in "HA" mode. There are no storage requirements unless the audit log
  # persistence is required.  In HA mode OpenBao will configure itself to use Consul
  # for its storage backend.  The default configuration provided will work the Consul
  # Helm project by default.  It is possible to manually configure OpenBao to use a
  # different HA backend.
  ha:
    enabled: true

    raft:
      enabled: true
      # Set the Node Raft ID to the name of the pod
      setNodeId: true

ui:
  enabled: true
  publishNotReadyAddresses: true
  activeOpenbaoPodOnly: true

  # Extra annotations to attach to the ui service
  # This can either be YAML or a YAML-formatted multi-line templated string map
  # of the annotations to apply to the ui service
  annotations: {}

# openbao-csi-provider
csi:
  # -- True if you want to install an openbao-csi-provider daemonset.
  #
  # Requires installing the secrets-store-csi-driver separately, see:
  # https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation
  #
  # With the driver and provider installed, you can mount OpenBao secrets into volumes
  # similar to the OpenBao Agent injector, and you can also sync those secrets into
  # Kubernetes secrets.
  enabled: false

  # -- volumes is a list of volumes made available to all containers. These are rendered
  # via toYaml rather than pre-processed like the extraVolumes value.
  # The purpose is to make it easy to share volumes between containers.
  volumes: []
  # - name: tls
  #   secret:
  #     secretName: openbao-tls

  # -- volumeMounts is a list of volumeMounts for the main server container. These are rendered
  # via toYaml rather than pre-processed like the extraVolumes value.
  # The purpose is to make it easy to share volumes between containers.
  volumeMounts: []
  # - name: tls
  #   mountPath: "/openbao/tls"
  #   readOnly: true

  serviceMonitor:
    enabled: true

  prometheusRules:
    enabled: true

  grafanaDashboard:
    enabled: true

snapshotAgent:
  enabled: false
  s3CredentialsSecret: "openbao-agent-bucket"

  config:
    s3Host: "s3.eu-east-1.amazonaws.com"
    s3Bucket: "openbao-snapshots"
    s3Uri: "s3://openbao-snapshots"
    s3ExpireDays: "14"
    s3cmdExtraFlag: "-v"
    baoAuthPath: "kubernetes"
    baoRole: "snapshot"

  # -- Map of extra environment variables to set in the snapshot-agent cronjob
  extraEnvironmentVars: {}
    # BAO_CACERT: /openbao/tls/ca.crt

  # --  List of extra environment variables to set in the snapshot-agent cronjob
  # These variables take value from existing Secret objects.
  extraSecretEnvironmentVars: []
    # - envName: AWS_SECRET_ACCESS_KEY
    #   secretName: openbao
    #   secretKey: AWS_SECRET_ACCESS_KEY
