# https://github.com/openbao/openbao-helm/blob/main/charts/openbao/values.yaml

global:
  enabled: true
  serverTelemetry:
    prometheusOperator: true

injector:
  certs:
    caBundle: ca-all
    secretName: openbao-injector-certs
  metrics:
    enabled: true
  logFormat: json
  podDisruptionBudget:
    maxUnavailable: 1
  replicas: 1
  strategy: |
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

server:
  configAnnotation: true
  dataStorage:
    storageClass: ceph-filesystem
  ha:
    enabled: true
    raft:
      config: |
        api_addr = "https://openbao.apps.iaas.wcooke.me"
        cluster_name = "openbao"
        ui = true

        audit "file" "to-stdout" {
          description = "This audit device should never fail."
          options {
            file_path = "/dev/stdout"
            log_raw = "false"
          }
        }

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          telemetry {
            unauthenticated_metrics_access = true
          }
        }

        seal "static" {
          current_key_id = "20260510-1"
          current_key = "file:///openbao/secrets/seal-key"
        }

        service_registration "kubernetes" {}

        storage "raft" {
          path = "/openbao/data"
        }

        telemetry {
          prometheus_retention_time = "30s"
          disable_hostname = true
        }
      enabled: true
      replicas: 3
      setNodeId: true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: iaas-wcooke-me
      forecastle.stakater.com/appName: OpenBAO
      forecastle.stakater.com/expose: "true"
      forecastle.stakater.com/group: Apps
      forecastle.stakater.com/icon: https://openbao.apps.iaas.wcooke.me/ui/favicon.svg
      forecastle.stakater.com/network-restricted: "true"
    enabled: true
    hosts:
    - host: openbao.apps.iaas.wcooke.me
    ingressClassName: cilium
    pathType: Prefix
    tls:
    - secretName: openbao-ingress-tls
      hosts:
      - openbao.apps.iaas.wcooke.me
  livenessProbe:
    enabled: true
  logFormat: json
  logLevel: info
  standalone:
    enabled: false
  updateStrategyType: RollingUpdate
  volumes:
  - name: seal-key
    secret:
      secretName: seal-key
  - configMap:
      defaultMode: 420
      name: ca-all
    name: ca
  volumeMounts:
  - name: seal-key
    mountPath: /openbao/secrets/seal-key
    subPath: seal-key
  - mountPath: /etc/ssl/certs/ca-certificates.crt
    name: ca
    readOnly: true
    subPath: ca-certificates.crt

serverTelemetry:
  grafanaDashboard:
    enabled: true
  prometheusRules:
    enabled: true
  serviceMonitor:
    enabled: true

ui:
  activeOpenbaoPodOnly: true
  enabled: true

csi:
  enabled: true
  agent:
    enabled: true
    logFormat: json

snapshotAgent:
  enabled: false
  config:
    s3Host: s3.eu-east-1.amazonaws.com
    s3Uri: s3://openbao-snapshots
  extraEnvironmentVars: {}
    # BAO_CACERT: /openbao/tls/ca.crt
  extraSecretEnvironmentVars: []
    # - envName: AWS_SECRET_ACCESS_KEY
    #   secretName: openbao
    #   secretKey: AWS_SECRET_ACCESS_KEY
  extraVolumeMounts: []
  #   - mountPath: /openbao/tls/ca.crt
  #     name: openbao-tls
  #     readOnly: true
  #     subPath: ca.crt
  extraVolumes: []
  #   - name: openbao-tls
  #     secret:
  #       defaultMode: 420
  #       secretName: openbao-tls
  s3CredentialsSecret: openbao-agent-bucket
