---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-api-credentials
  namespace: wazuh
spec:
  encryptedData:
    API_PASSWORD: AgAFnZiKWQU1mBQ2FUtQQwPjvkZI8r4ha+zQf5vJ2qNko4Rp7f46PH661slTp4nzXGJ2f5fZDNMmqazmZ3kjPTFe1/VmTKmXuAgugZSi6Oc8Pn3cRPopALxfIqhk5UvCvcmRZasIDhVZjExjfuJRG+umS9xj9Ck7RFA0MhCX7BAUQ7UGgPhZUSQFAewjPuTjNlEbgomERhaF2RTW+fzIXtiulTx3Xqeo+ngW8fWY4RbphLp1Xl0Bmd+PfkPb3Vy+KWXgs5Yf+NVBG7LFC/6FcFyZSmzqm/DXmJ4Usr91DLzMj7T6yZ3q5e+TNh4e/czzMZwiMVfPnPbRL4zQxxfnpfrcH99qjfRGm2nAlgM9IqYv9EGCwXgxMT/JXCcs86DmBXbq7ADPUa8wyk/QZRsjUuZYmzTQRsuSL5/ILZH8WbO71ES9Rw3Sjh8lUtK+fsWPuUQTUijrZC4gQohilBzbOuTM0xt7J8wK8TUrn69N7G/VqFyufSFHac7+Ev1pIBCxeSEzso3DIGCI0x5xWQeTe8++tcqnMnde98g9muYnBsJCvSxJECSC5pIS9kNPE2yvpgL2uuppmcDTDcZ/7GAKK/x7rDbINJ4dgqAaABBrQ/HdrMvD+sW8VHG7sE72IbtxWKwXeWSs2DCY93mH2POO1CyGFpzjMLhQgeZm94iUOsRgyrNfXA294/cz2HtfhUicSTvZywBOFbZeuxAGYwfjnx4svegNVfK4j0lOfGUrxVGPwNn4FtYi3Rv5f1Pgvg==
    API_USERNAME: AgBe71EKawdwf4gR0jKVIl0K9YJ+XqFPcKU9UgCyoQQfEVEvdofxiXfkCKbF5ojddtb1A/mHXRP/To0xCr/zLZuIlF7gw4uDRzLpM4ybR2xge1WrM96+1S8S8aZwLaWkqlEnwxTOxn9MpfK6nupJ/kkyoY/EdivU1bmwewBVZkN5WA1OI1a1FFSsy81ChnutqfKjWDZnqCrX7ZLIRzGKZ1rJ8q2St0u3lEvrSr4Uv2hbNa8+TDVldQXeioM9HMH2TxXnmuyTedNJOGUHAX1bLS9I1nKoZw8lGqZBwls6IxDPybJcsPKtTqPwD/4DB4z6QA28m/voAn5/AElLcb/tecXXqEjXBKI0lYt4/4dqU+qgJ+UHpbj3xOSVI/xPO860rcGZ0ogihetwzR28iqmNks6zQBGQxlIAvLwbP7CqTdvSK0/EjRmtDqeM8HjRwe8Hbts3hRoUC1bVnxqct1jG8p2OzKK8m+fs74YgS7w+q2/yJWMmgaQiCKBh+1LtNuqUat2pDZ4c0XgkLKCmJfCiZWWmi3qeQloSBLZH1zhKf4v0Qi3ltAJNgZQhk8RFS3N85evY4bmhA91pHJqaLXzkQHytahRB4NEmRQ7iD4kVJTOveRG9EHfF76QkZchcGXkKqYirdKPZesx1Zbxfw51QrP6vO1JV6SOT7QQmyOwOuaI6aFSKw+WRrRJnSiyvDHUaeJtkdeJoMhuvrzcWjg0u
  template:
    metadata:
      name: wazuh-agent-api-credentials
      namespace: wazuh
    type: stringData
