---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-authd-credentials
  namespace: wazuh
spec:
  encryptedData:
    authd.pass: AgBrIKWPGWaJQPimlVdUywPBtMufTVMUF+rGHKGxvSdl8tgWaygeRDWT8T6Q/AwB9iyqXwawuc4pNiNieYoBDNz9K1KWU5l3P3Xg5BB+tULD8JRxNPqR8vBJOcrsAlv4qMUmBkz1Wak59HM+/6w4I7ciQKvtali0cTLXOhYO/0FaDZZQkZWqArzvFfnUkEw379HLL8iexVNCuOQDCVNadDKnCDOdVIX2imM+T1WD6EizUO8Baccpk8Ru7c4OfnsjHUVpnBOQ7zoJRYgd6TX9sBJtq5bBJT/yIwWb+cDcODJvG4N2PA9M1cuggCY3qyibfbJqcoXXC/MchDuMiRS2HmoFjYgG/LFXqYcAtiJmEEhW3okDRmBZtozVjDpNm2CvnIj0JzRMLA5KE6t8OKtSc+fDOv34P2i2Lw1G2C9PuL/ImBzMb7pASWP7sc+LMTI8xZGEwST4BTs7JXK7+7pncISfoolVEV6zRLMVi15VIGyLG/M2OtElHv07miesjtEEseJYxE48tdTvpdZuP6ZBlfDaq8PaSauPn8Hrt9vl1TMHzIt33rAMmHhYubtXpRYLv089orXBrw4wgZViN9OTbu/molf0WQ8hl5MOlSTJsBGvavGs6UioNT/CmJQ8DHnxfTDwOvNoqnjSPAF7PVx5fhNVzWh19/SAIseYdd95UtBMcf+iDZmlorLz7z15uRNrjzBkLP6I1DHVRn8w0zUm4P21DQTn0sieMPiLphFy5g/YntStpKMS6U+//ExB6w==
  template:
    metadata:
      name: wazuh-authd-credentials
      namespace: wazuh
    type: stringData
