---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-api-credentials
  namespace: wazuh
spec:
  encryptedData:
    API_PASSWORD: AgC6iavWi7AbzZ8xeyAeXVYtdUsDtWiBitYWWfvjngJHhnGvYLn1t5kc/sSw64un8TKVko1mzdCFoXzNJsYklP0DkZYK3QorymRk5JFv0Fy8Y1YkCm6trTU+3z1t+rKcfYvmRb0Dfbl62kYBbaEKWa0l1kIHmfZNOELk3woaOhEFFw4mP/9J4LWRi0N/7qQzmIVfF8sDmSqjyBtGB6YX83EeOnW00v3USo6DaJPh+wGrH9egbx4qaF6OUEh9y9S36WScwiO+AJKE/QsNTItGx4hEoSWBifQZI9dT34yKsxmZIjtb1Xst/iahHUUbPG8YuxPLfEy12Z7/uF5sRPEBmYM9ZhsZIFxTLBS4vHzCm7mHan1Cr6uTdCJIWEbPEV4VObDUN1mO6OXFuzPun1NpczvJMGCcrfWXnqS9RsnFaqFcnCaM08EpmVPy5dxJHUmlnQ3Zu95gV79KxesTGE9Yd4lfCH+8a7c+X0n4twNNUGxfezLPGbPuZyn5bidcbL310bPTOYl4iIH1wxy7c4BZziB28nWoBI6n9uru02ftbCreO9mUtN3RlkZy58qsUcWwy3z96r1tyAVIcPCL04zLCuSHvKpcTDJLsjneLzImXUXsC9mDqFc4HlaW5KezfoiQ1q8W2/4Y20ozbNaHAkWAAgtBdLwYQljPpV+AMvm88bGzda1dEkC+e4ozz9ZhUtWXfZSti7yn3lTVTNyj1zVf6YQEqdqFdD5WlQg2AElmqEc4PjWY43pDpd9hDusctQ==
    API_USERNAME: AgABTQC5xsiF6kQv6JhpYYaqdOqhg60wC99FR7qoqkYliXAKt2qY1yVIav8jy57TuiN2Mhur5Xh3Pym96VDGpZIKF3QUjhKNupuZtB1wCCmrFraxtCU9G/Ul9TYUWOncXxq+7SzBvdJLwZYWAXcSIQLVFvyDXJ4pg32MQDZO7tIv9u4AAHlyyfmNoGZ1+gPbGLpggWAit0zkgaPT6LfreIboYx4BGGGdWEj/u2OKqvW9sxOANOHDUd6m6Y/eW/fodrrrJC+mONay85OaFBomWVD2qiZd9nB8ABUBYflFpJ8klevEz2pqQlh15acop8YjXU5DyDHPLdrDAUl8jqKVE2aT7uGZJkeasbOHTP3tMAe3QWBXE0B9vaKE14UfoGp864cFpaKS6L4KaF8yUTViUBqjB6T2Bx1bTpTRlU4EcIYOFyAlCEtZTepTE9AkKH1Oyv4NfC+BiuQfODOBlUq8cKADSibcb7VuEXqoZwirXOL00eh/we29ILMeehBu8Ovgr8XqIZI0BunrfMSsybOqDvFpRquJIgEKXP7WTmiVyyCfn42voUVxi0te1l3mwc2zUnGQ0yxHmTn9lSRTOgDHVXuQ0BBpLHrg9nEMJKJLc1XGZHYVbvfEPMmi/oa0lQnuEJxyzfGapjF/qvRrrYNTe3gOzHa9kEReJvhGEQnno/AFBWRjC3wYrG9dd8hA2pUyYyHcpJe6WzRy25DHgWDR
  template:
    metadata:
      name: wazuh-agent-api-credentials
      namespace: wazuh
    type: stringData
