---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-credentials
  namespace: wazuh
spec:
  encryptedData:
    API_PASSWORD: AgCUWNAXqUL6XnCAN2Reh4Q3qm4v/6KHd7u0y8wHoYKEXaZ0lb9jKqJqsX/PQLMBivAcyDfDWOJWKXjHP8kguk6wbVCW21UgnKCB1BtWi7flwteb6CN4QJnkc7SbBVLkAJHZ9wBbDGY5YYz63SG2fD7ZGu57wi4EU4mMu7Y2qkl5xnqhrJOy4TU8u6v+GxbU6PFwOanI7ESTwaJ/L7lxFiZfc8bk1KbbNuPMLDPCJseRSTA2VClqcGtBnSokjkJtEIYpl/3Or+T+3tSiXKG5P4UKKDVgKkWVjtfmNeijZ0wjI+ACRzysHRyCvubzm3JbAOP4sO+LZ0arGBniuIo8AIG04GKuCFjGB3IqyyO/8tiD2X8zT68WP2JaHPe/5luU3niWq1zDBT7VDAvZL/NySGNn7v08DxotA5WO4HRQYuFlBwPQ9D/0Z+11W25bEOxpYcBjbt9sdq6bIS1mU8AbQgi5VsLKjCo3O6r578DHgp60SeNhfycK0kJ0wyqBi9xIcik4tSb5dztLu5uYrsG8ZGCClw97JVSpAURD9RmUl5xuP07BMLmmkH9t10Ls9HRfWmUMc+MNU/5SquDkhDhiIyxV+hXSTIKzUVUNYiPYR84hNVApXcwSmxl+Bp+VIbgIzH0c5quLjUZt96EQQwUHzTaodekAPcBmoKGR32tuzX64dxi+3Ct28Ic/rTE6kl3L1MKuQkNzuDgdjhlHKU/70gfcTAtcZBENU/7gDf84x5TYlCzVNOuIT+mZUU80kQ==
    API_USERNAME: AgCeh8wWTlRXeTNvNCVLqmlbGNL/H4KnYGgatG/cPTe5GXfeepUu9vPus70UUU4tZqMYCN3aAAEw7HRrvFX5eccAH23351j40BQFOxAVcpUQk9xx5Rl9aJs6AhaqplbxHdNr5nAW1NNqGgHGwUpMKddTESay92b9s7LdBwvJmAN01NjCQMcnK1q1itrWXQ8rbyn0ouSgJ3aavOuo/fMrPJM0/eQOQnNIyLQ2x7+bRhGtjO3H8VyBummAbcO3MbgfFfZsNKmSlcDjVfvupBFT89dVJTuwRFBfYzxphn91GFw1uWCvII0l6j6C2ice1mBLUDWPXMzQe02Dk1v3T2sR7jgzlbC10XK1lFRlIBYyHUnpLC/ktuw35Z74IS9L/LC6blto1PZuUiK/9o3jqP1XNyV/rgwG1A8bt2mtOHDMh+jcmdl7m94+1HElZQeb3s2NirPvrSikjyN+/sfGAiXR4/K2UQhD9yfAL9NrxdcRYOJqkVJPLgCEppYhk6hnpvPS1SUNGLarSph3q/T1yNiu4MVwC74fRuJP9JZEhE6/IdgJ6ol768E5COj7/wHBSsXasBBzqFfeVxX+JCCJa0nGGMuZKy8M1e0Q0ZNy06tVA6CkzuYblJ/sZnoIBlXZlVwh/emzTlPAHsmED7whuxIp4WY5M0h+5ZaoN2sSVW60V77PZELz0YWsKfepiz+zVMNBfyz6C/pHA0w0rg==
  template:
    metadata:
      name: wazuh-api-credentials
      namespace: wazuh
    type: stringData
