---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-keycloak-client
  namespace: wazuh
spec:
  encryptedData:
    client-id: AgANhQiLzjNNezVadT6G2z1pSccpvhT4MxvyF76YA7+73038tuqOjNwwQh36VymoUH2c/m4omyr4CACUZnZp1io2dYJxOhdcEFlQcAR4At7lqM+/90I+hIJugnDgEprnVg3zwQGBvLQg2n9Jnvlw3TQze4Fd38UqkR954cwaGKyBHnZXWL9jquRkiYGbrfX6dszKxTLrOA20PYSnvl8kzPIMxppinUXLNzna5wfkVpvwUWl0w0Ac+P52vbnPDEkHLtZVWvy4ozeQwrwFBtdou/HCMUK62pVLpyDH4fmg6rBoOVMtCsq2dGSuvmAI4QeDQzftI7G1mU+mCZ3gRZpCzxz8klG38SKmDmhKEnVxdNVFVxwoJu6IRkSYrMh9SmLmq67tcU9hfkAD1Khn+sD3oiNTOn84GkAs8pTceWfIueDyQhrrnbVJZUU1J24wjEZhwmSb/Ih0oheWSWqjooLECrZ3YFRyfLllTvhoo3JQykMi8Jpk2+dw68Ubku64N65XVjHreJ5qy9b2j126L4OcJu8Gty2uVA0FO39yRJwmKLl383aDJm+5Q0Jxn0T/ILNuQ/+uERKvI8XmpDVKi6wouFcrLDpE8YwLW8CfqenXk1BqPFZ3m+3B5RhwMf9Cnd8vRGcvSwfzaDvAPVCOygJofSh9D7ujCRGoxNnMJ4Cm4qbYpviiLyszT4XqiTlfaFUv8Cap45EnQQ==
    client-secret: AgCzgUpMQCu2Id7QXvzenW/g6keXDR7Z/kCIMoAzodH4Yrd0+qgaRUf5QEjP/cTe5Z8H2bu/fJkLcpSgxS9asE2NRKDQ+CFBXUPZCyt8Pf3aSBjSHO/om9191jbACGnfKQq0kVDNMBJq2DuGtQV3YYMxKIHinSsUG83WHCA6iVcSiIWyQnyPKfJkm7O4t3fGhHcRLknLzIcLmlTVq9PC9wLSIfHeUwcWVWyiTjagPJLFnlOHeF5MIIt04uQZEQY2lAJvR9i8S9M/xfwDJKx6dFUmKwYHaodCT99QZT2d3KsRyOtUS7JqVZ3U2+1oBwrLeZz/VFFbZro2QxlLuHZse/djWl6664qy6cIj9Xfvtmqz145nOsA1szAQlXwpBCV+vWC8mYbeGCsvt74aaVY+3sQCiDFiqZdUnsXi92m2FGAbbvT5hmcH+AeuTvlzS+Q0HBu2bJrK/hQMJGwf4fRObFhU9KJJnqmOrYYPB5wTdRs/T4DhM2rcdGR2UlLAeO+pG+xV1G+FNq5T0H1ccL+bN8pQiSmq0hGH4D934v/mxGFS4gjCxts/tXjr7lKK4+bjfBQ0icxx60bpoMNbYxHXB7T/ya//zTpdOUZPrnj+N9cu2XNnCoPEOJrQxkKB+ZQmGOyd8HgLBzHepT3sWXEScUYJfL7NG254dRI2TFydUT4FMOxJiPLmjxnTf0d1BEGD8kIgsym2uY28le+7znQRfPr8EOEfzFsalrBwZqIyb30nPyiKCl3wiImYN8U4kQ==
  template:
    metadata:
      name: wazuh-keycloak-client
      namespace: wazuh
    type: stringData
