---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-credentials
  namespace: wazuh
spec:
  encryptedData:
    API_PASSWORD: AgBYg15yBZTE47i69bM1t1vW3xavx+0LRXNGEJdfSOPbLLBGf+1Ri0DQoBh7YF7mq4vysgiAVZTH3USLI2GcxIn5HImRPaDpUfP+4H48WmjIJX43FuMKS7pLZBQYsJuu0KU63vyssJGGFejiEn9XpKXpxl65iAb4pI0MTaj+agP87e5ujodXl2Yns1D9W+9TjNRkzYoEkL9Tkzn6RW6jLwPYM2OgkLg4opR+XHRkicaF1lkj86S8ZrdFV2IptUDXfXTTRZr4uKE3IRChm6S3m21uRuVgJwEPqodkJmR73HO84h+kb1g304ohomJPtGPyrLzcTd7pc8HZ19ASnr7JgBew0M84Va3qQhvAqYYU7g4VUoWFaUDEIMx8h2JPVleeA13IzfRffF0+phPDVWHxzQTLufaKFpPZrcL2RtZh4L/9HWD+A3pffZZuzBmnBNr/Qx3PrxY1tZo7c3DmoRSVxcvj16DbKGong1CX53TgtjwFQUqHnKMH3WA3Pv9KpsFal6sQslyT7PkGiQK0Qm7dUO0ElgphaUFrPFudgtaw7oK3FumYYaW2QvRVkhmjLd3PlYT4ihTq0qCK1FWpd1uj9D800zpw18jLLGFnimB209PkEFtOq35stYhipqD7aWIz3ZQ/3YqF0F2CVI/d1QSFRVGEmT3nNiZaEhlWxfY9NZFtfqqca0wbA+k8qg8pKvcejsJmvWCTuqGLcmMkTYIIzW4nalr4WLl7TnOyrQMPs/A24dtd6yqcvsYhmv/vGA==
    API_USERNAME: AgCnQtA8zAuThn+uvbVJBPO4xBkLS9Ex1JxI5hzrFVuoCZJMX1pWx85hAiEGJg4dE4b3776efG48q0AxkaAv9QDYywEWI/MbdisVoMaqAA4XB78phCUT/CR0tmJ/Y45BIZN+O3aepNPFPkYNxp/3S/luM2/Mcfc26kou4xH74tg3Sofkm8Hj9x1Jh4RiyNvX33O8FyyUaQX31PdH8HbAOACx/C4SoI8fWV6zZlZLMZ8AQInkoF1USn0VhS8tckLQzo3/BgTmyk8ZhJ8qFXXjZbrx6c3MKq0+fVPb2+T4cdFcZsZB9mFrTgUtDHcQjsVCYvK1vqc3fCEL0dJhIzSZAU9SV8/JqILPVVmZaSV+wSz1Yhdzo/8C8jTaTwqERESftRQuKRECfQIIrF7Se7i24O5r480WjAoJmlMyD2RJIyJR01P0xDt2BOoUlFM5w0e9Q6gj8pKuCbKLS6J12MDvsSJ7cPBPwk36MHsVNDyqqZRT8tPDxaTfNXLnhmygUJ//S13yhZ6sXxsUFGM8KGeEJeG7d09jpkb089/rHtLGY6L6kuqUrefMlGN4UhZqMPSftw/8cUqXE12Aso5y/ZX5fXRlLK0toNtF0Ms6fMtlxWXDruFxq/gTe4gp09luy3WHPVTJeitPQDFu2YTnLUwr+KdX9dryW4xQW57cwaYTHGEPFgKxqyIRA6VtSv7X1HjSAWsRbTM5zEQqTA==
  template:
    metadata:
      name: wazuh-api-credentials
      namespace: wazuh
    type: stringData
