---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-indexer-credentials
  namespace: wazuh
spec:
  encryptedData:
    INDEXER_PASSWORD: AgA1qKQy0JwdcGg2w8qQzDJkJnf4Ay+XHYs4cA6mWGvdGTes2W0MZVgVUTrIjH5yPsXpmStrKgvnqiDKDuHGkaizCYvMWGiEolGaqYPpEFVnzRTlj9ZEpeTiEiP26xGjNRe/MHQvyXRg1WUXv76OB1k3+4+sjVSUzvyJtUyj7RcaNVFnzpgFZn3NWTKT7G7Kvfs+3d1D9irDrTLzETQ7hD/oa1cxYP/nLWhV/wiG5UyAQf0SXG7sv59qosFX0XKI90gRC2KDpJsaLuDRBSGU0pODNbZrpPHkgMDJIGSLNHnkTBnyUv8q/SIUOdIVCULnQpigDd3zKcuJ8ZtMzFk1ZnymaQcPDEhMwt8dpeHnfGWghdjnmUzx+V/nCRrJdnmBe4YcQtVzFBN1ZXUNvAZkrkMAJ+kUokrCz5+/WY8I57F8h6RGbDO1PGDZqu0vznlmbVHXZpyW5ytJl3RGC5TTK58J4Bkj58n66ZYXW796Zkxec4w04kLqltchBRkq4hKFLkxhBZa1O6H5QR3u7yN4hSdrTnhJuUPESxYDy7PHm4htKe+YsUxc7cJ7EMgJHIHOsCoooT/f3u9/HARYaDp0LBT7RzTBeG6pCzhjWAtWDCGj71pl9XMuXO+lq9V/16F30LNW/vu8QGWPlIh2T2PmHkm+9gjbs/VqnWcif5fjj7Jz/+fa3rlrFulmvE8gWTedwQsCXNCLtSOT4+WVjrKqxISgQa4d+0qQ9FK9lBz73cCcYmNF+GSuoX2JZDSyLA==
  template:
    metadata:
      name: wazuh-indexer-credentials
      namespace: wazuh
    type: stringData
