---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-indexer-credentials
  namespace: wazuh
spec:
  encryptedData:
    INDEXER_PASSWORD: AgBzwcYegtXXDhaDkCGyr1wSJ9xk9Kt8fV2iw4p/YjRXI9VQ4IUypNm3GgUbXucAsjHT2CjfOSLXyk9q0b2TrPcpzHU+CVxf94bmJ+9dZUE+uqUVtzJDdT8livtcxX3xT/tTicms7JpCxafsDiPh8MtNy6ZAVP+17ClOyg08PMuqo0yHABThIyTRxwBN4uG3RxmkaYNLSggtkLhQaLb2CCo7WeSRkmNvB7l5gzDQyw/cJp5KIynC7z87PmPoRO0r+zng+2mFvshougm4MBi4zL4kWF1zE1cxjMEc71VoM4ecBvHAJvfpEl4TigPUu8AAyMsawgRoxFRGd6pabL5Az6g2aEmVJUvA0H/8Kg2W+zLIDPDMgOa/vsdq12CNLTrYMA5sSiYS/GA/JrK3nh2wnA2e7LKh084z90nWD4dhQT9Nh0JnSKNBPPFHre/J80rJfrUwEUZbgNljh46eoYcbKjfFEdh1XguzsM8ILxHo9CKZ4yci2DMwPuv9flIeRDLZ84xu2IeyjTF56WZJkdoEQImMSx84qO3VMfudcyOeOpnphFapc1lSwh7NDy+rIJFAdkN0C6z2gohJeGf0lWCArST4ZLVVsPBKCKDn5s63KTPa6VRDJRbeLGW90E7s8aNBwHXk6IQKNyanc7wwurpIleNOhIs2TcUB6LEr8Jq9xZgTVQmfaYfhV95WmQ8IH9GgRUPyVGkchDsSfjn9bg3/DBJXIitZdikCUhlh3A2QIIwftq+Od7U+oQlgviGK6A==
  template:
    metadata:
      name: wazuh-indexer-credentials
      namespace: wazuh
    type: stringData
