---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-authd-credentials
  namespace: wazuh
spec:
  encryptedData:
    authd.pass: AgCeQqxsyoBo0w0+w5HplpiPPbOGfk1mDZuqgCK3rkzS1g3fWLL1waCl3lys2+6/PHZraDIfnLwx8OCxA37ORbEWYQZSCf4BzfwoVhfHOdECc1mv7GaO4NtL41xmovrvUOXcuAo36z97AEQkQS/fcLK+TEgUnJE1hQptZaHO0ha9HWKhivnMNYq/hXvcV0+RpINQqn6+Fs+HCR7KaKK6NyTc17BXrWC7peRzYh6lCpoF9LKfj6G5GrX/PNKO0En0xXG8cAK1AYK7ZLaSOc5JdIQHk81O94cPqQXnIyB0qvm8Ur5K4eMHZJHPVOPZum6HjOqwzVl37YbCEJUMk4LNsqDjRRD4bSZNFvnz9yohRMLDDP7eZ/Mqx044C/o2jFUdmwJUjiMepZrgA9iEEI9/AQ/4o+1gFGIv7PPwAngO53FCsbxsGUcwIWAFteJqM+J9CI3EjQCJ4tPT8IRtM1yXN8QkQ02dgh4iTWheMZifWOIis4otvdxIUjDjO2quXD707LBantMN9PyVvOObdkW47D5s18UwzHhwCrk4LVsxj9fKHt6FLuJx4rK3pHBHXr+7Mc8YPSgyLMvfpq46QIRiwKdkfmeaOmvvpF1BXGdZv7mmo6FYsRzyBKBj3xNiGfYFwpbkKjGcV+djh88YDBix31FbG6ilKqWq5N3wP3/NxSXkWz8OlKIeLNXSTLZa1KVKfT6yHouPHuIv7fakxPm41NVI+ctteJ512xgWy6RfojERVJ9kEtxizOcmDJXghQ==
  template:
    metadata:
      name: wazuh-authd-credentials
      namespace: wazuh
    type: stringData
