---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-agent-api-credentials
  namespace: wazuh
spec:
  encryptedData:
    password: AgCy1kzcslGzvsWLanKwAVbOX99XZJ+kreK9OhoyYJpMsHioZZZrQlCZ+K/1OvM41W97PacPwoJyEicpJw2JJNB673ZXRudxd/yU6JyQoncBZzK9TYeQBxB8qAYVt6MMO6Hd1KqQiBObFoBQQYzFVEh2I1cJkKL8AJ4Lpm2xIkvQrPEZ1MSMIxDMjk3yhV0PHiLHKFCnxweEQ6gc+QeJ0rkksCC0S2FcPOH2CeLuRpYWexa0N/DWbObW1D4bFa8rbq6qQ/qzfH/+Erswhkor9C2weX4FGYVWyrnp0NPbXvA9FH1FTXxlYVTpOpRZxx2G0m7dgT4BVeTobEUe4c6WWlddaw1vAWjgYEqnKjFjB8jOZMA8E/dgKTK7qit9n3oQYv/n+qLw1rvGF9Q4VdalHT08lRHQDJZAJ4vEjyV57oVdBRlczid17hjid1+gcIb35f4zvJLYn3d+hqb6LlwyjMNFvAe5wjVRCrkY7dwuQ+rOGG9EN1dSLcLytbjjKN30uUAhh5pH7mp1T6itD1m/GWoIhGCtBrGZTz0+fWistdyYkJkcboswyUasCrCEHLfHeixBMCWMEnzhkj5TNjSfoN06VUGhu9KhnCTSBKAIf7bawa7hsM9zrl8yssCIaPYm1RnFnW3Y/dDM5O48Qzy1b/VR5iWT/zlRmlq41CR8rWA5WH8XVGA9NjccIzrpCASZznSI1tyJQOgAREApAvJ4KcUCnjC4f7M=
    username: AgCWZQgS6l7YXZo9nxmLqF4ORIIhJk+jYDYyGpk1QaTTuTPjxSJgMDhIXDBEKTvdZjzJBe+rMYQ35gev6o928jtxiAnXoCKUjwHwdR92CMJE8XsmraPY0U/TLD7Av0ABLOounN6QePugQMaq0zTh7/VFpn9WWP67ooHl9SMH7qSKl79Br5n4uTD8PBQiCX72QpBCjfqHhZ+A4v40jY2EPkogf3K9JR8GiXnGn2o0VdSdSO7lWm8dbNG+GeyWjlYwyLj1BGqFnGGy+aujtaCbldF4ENlj1olyFgTX5QPsANrvJuA3tz2DugP0J2dfgFLDII2gtayk6bZbEObGxdK2vI8/kmim0tC1pvAkMsdPRWvpPgWm2LEw46TfXsGZt95pBnrh1R5YtSzNxjrF+/uArhaz8+cN2mEFWS/AZPlA0HBQZAO9LEcfZ/OCZR7CFrjlNuE5OvsiWX5IaphHoIxXmPFAwjmx9J3PVQXjg2lxWhemRYWC3hLG2RwUsI81esVqunS+UOuxDLV/qIK157+3o6YAXeHCUZFJ+LfIXneSHyGiENXsmxPHthlGK5qyK0SDV67k/4vCuNgcNtmnD0GkRSI0HrLXh5eGlpvlVj/0bB1m24HmX1LYfmE0Ep2eYYKr3Ltgp/Qs//H/jViNgslRZDEUw7zytod7NZpLezLEEhcKww0Vr17enANwDWffZvDtHFrWo+LrjDODptffL018
  template:
    metadata:
      name: wazuh-agent-api-credentials
      namespace: wazuh
    type: stringData
