---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-keycloak-client
  namespace: wazuh
spec:
  encryptedData:
    client-id: AgCKk5UmzZthHhPHzOfu3NLbPjEA4tEnY9cIOHE5X5VPNy8OGuOhOQ6CO7HAE1+j53GgJjlLAaQwomXj/gJ3rPXKrfOPH6QvQdx2j5/yRa5q+/MnOZhE8qPLBDgVf19B4TNPZBX6FkAhmQVubEXtqpMVF2da+PQJ2N6BRU+mjYU4o4Dpr9B9vKKF9gSq/XxVJdb/OUAd9i7xPJe/W0HZhpBwteTHWcPa57iHfxti4QMwf4RLL7RJrcLlkI0eDrBF9CDAJsn/p7fdvimfCi9w5Cj8mhNIWKDlBp6xotQ0kL7zNu2Ne7svckTg+hNYOKPALctvqwKxhbzcJjR8FDPu5fYpb1SIS9n0sz578OuUStf+HN31cSjzFdeod6j89Xjb0Ki2glw2k4NClXXkhgwhMnzAFRVFDMjUT2r08yDTbiv+nn5fC3xfjBTeMRkBhINzjbaKuvdq/c4Ur4dQBJn8DICwQsXSFDkcvi9zcIZ28p+A/VflzCDYgHAQOcF33iDSDIIqxKHebQohFpsWDM+mq90yFU2NWwDT3E4pCGOl0dRKe44ChjBhh6zPoOq3O8LzE0QR82S4O8AwWikM7NRjD09xBQFXUwGxwhd0aPQmgD1V+AGoWEwKR9QUZiDYP+lSbPqVdLzMbZz0lykJIxC3oaT150wzhOVv3YUr66k4ujDS3tq5k2Yku2Mii0l7QTnFvBuzwlkRsQ==
    client-secret: AgAocmYd/2cQhJUMV4Q6UatHOVMQfsDTJCSUdjKC+Lhj45y3h86fu1XIxtDBCg83O0/fmFOlFB16Gd0bWszB6Gvygx6RNIkUHek6c/afq6p4Z9CKjmkD4iC9aKQPdMpzzxKntSF7xLVvY0Js9js4hS6lFUq84zK5RznoWWBH5U+6dlYf/QVxILO3//6cKF8rTXjIqWHxTaupu1jZY+bseKNd0KUh1CtLkKHKCpbJ8HmCQCVP9I6qaOMMV5ZhhYB+Vj7YZn1VdETWozRg0vSr9j0GHFTXYHcu2O2BxzCuHk5gzHpxidj0gnWZELdb+kQ+5BzUCCdNnD9/Uk4Rt2NXvi0ThBxOwT1Bq85T5+95/pENCQ7sJRLzhSwYc05gzH1wHot2tR1/Ss+CrQHxCbhA98U/USs4UlvdyV4J6MKOS/cFU/kTLja4dEN+W/NVodIWT5sukFyrLFpKAxaXsr6vZBRv4wN9UC7CLTW5y9MNhB0Qwk7HHKS02gYt45To8KuqBdoVaIgtIYmqtyx5GJLzYV5ntMx6asJb5B+GPz3maShBkLr+addvkK4FsaD6ZvZNMkCTW0+OLkaFBbnwxLqczkGOI0rYGeY+DU3sqqXUT7ZJO0J5g79GlXIzvWzf9mE/zCv7HcFILEARW7FXtExm5ygvqmdnJSXJWSihVQbbO3dwzyJHYLusinXq/v2yVet22Y/umPkNMPP/2t1WnPlEu6oZaVYJkKZlebQMOJ65tx3bj0kXcaxahk8FTiliQQ==
  template:
    metadata:
      name: wazuh-keycloak-client
      namespace: wazuh
    type: stringData
