---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-keycloak-client
  namespace: wazuh
spec:
  encryptedData:
    client-id: AgBSUL3euJagG7StEblMNLY2fZt7DVbBosP1yioqqJaBDZCtA1doYdkTsizMe6q+tzKuw25KLr2Z9RthmIVLo72SEge5DBbyvncDUB7GRuUkdPyUZkxdQCK6+8Yom0BV4zEOAVEYK3pjgcPIQ8xjoo6CWGUYDHMWH4gboabxlPMyVAdTuj9xgqFMXH9hxb0kGFQzpFKEZHK7Ktgz/j5Nkpb2eWiXqf6pj99CPtR1l1OeKD/u/lZ3Jn8macNp8JZf9CqkhH2eDOjOXoWZUNIKdR1c8WefxjDwYq9933N088sE+iU49jWI7oMEzICtq2H5E2iU7QUCM09tLYkjaIwphcChU4+wwXlGF9mGBht0GwNq4KquXaAdM9OxbpxQHxeGzeqm3rv3C5+ICYHE1EIyp1EDKgy5+FDEtpMBzL5Y6sQR7//EhcwNZ4oWVl1LCPMBbzpA4wD6tIHfah9l7G5skcokYW5mKgSlateclZO0fKawLt+lHfPbjXnwiQ8AL+W9/MWKNMnVFXkTSmO4cY4vTwkzqdE0r8VYgyyjcF0kFm2QtBb8hSw3pjAqpFPWj/Wa+8oH5B+zevT085nbf179gHM0bBAKNdY2HJtxWiTiSSo23Cr1Q05AARG4kniMt8PZPW7TO15vsD0aCB/hv2ipjahlYejTn5G5F+ORyU7Wf715jQF3Tu+YaBHxjo16Rzm0I3MacIhmvw==
    client-secret: AgCIdAv9RnjVLkZUVkp2nUIoZjse1y61GT0INXXCv5akmH4RGMuTA5hSPwp2+f8yiq5MxV8f3yt0IW6rrTRVcogGc1WvDyfskcVkZnDKiwcW0u6h0pYDvMjs3yIQ0j42nzPvT7HzhkqvfhHwitDAz5u9xaPDwTMJrbHhxnWoDjVG14Xn71RpK5aFnO8q3t2PTBgyYLmFhqfKeHiRGed6G+X50FxO264sSLZIKUms0SOXTYkvbxpXKBwUxxEN26wEcqhvs5wVtYeLnp84VSRnzC4n2Ax3RVEZmTWE3z5yEl+rZMYfEYpZY+FwCUJHZK0ukMA1JAcXcOBfDFeZK6hrgeXCXrK7ljyHp5WRzbMZcdglQcsbRhEOaB/WVqpT3QCOcki4WCVN8YD8yZ6ejHHCB2MCYA1zmmdNy87DhKO4i8us/p4uiOAxDzRbgdh3WFkMAGtolZnMHpqRNpGa9PSRohMwIZvgZZehIuJ40OUolb6Xn5VOvY9BwjSxeheZ8m/9wd/ZqbEiFpp3pR6bzhe6eE3scBg5Kltz1PQVXU4fVbnkSzoDmVCOe3d0RGeJYLCrDncC3qeJJvoJb8VYkLRC5W5xzLoZYurEL8+dWCmA9NdVQazkFa+WzoSVJfwcLIwnxSNdQBWK+HhqUqKJn1NDLcI08XbMSPGhGeooe+99L+CJt2lPHvFA2lQ0ad+H0sSsWbSxbtuvpIZxjB7SIgiYFwZOX8at4pTd8nOBg3vrAxNuHxtl9KrujnzDRyOe7A==
  template:
    metadata:
      name: wazuh-keycloak-client
      namespace: wazuh
    type: stringData
