---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-authd-credentials
  namespace: wazuh
spec:
  encryptedData:
    authd.pass: AgAAdVS//pEKn61pdVexao7m25G0+DDAqAp/wklPJ4OM/WxiUwITF7Esi41lrrHYuBViCdMTYJVV38lURlTd+rPor6cpGhGTuPff2PwTXlJ7Ob71Y3OC5ZPiHUoltuUn0CyJhtOcmUJqWdgsD5oQB4OUSmbttFPFaF4+b1f62xnn/PH3ciex/RTylieFMlyAs/qCHBQwDqJW7G/t0VXI6NdtdPvOf5od5/WTjJRqnf6l8w2wDyt2aI9wIss1DN5xReSheUGCKsx+xfs8O6G/0actDEkAJb6iGH3rb0gBaoTzSsmzFsg0iWvH3U0QrNyXp35YdP9DyJKxECAtJoa/VQs1Si7PmPJTY5uu5+BAQ4qZVHPWRh3Bc7Pyh/Qu7UPUS0aHNtA3bWOTLNCVsSrPjcFeIU3c1LDdDZW/sso2iDfg6kW/DNkQoFF+n7FlI9nd72KzT+/eLpqtmoyEFXbgh0f6zxQAQ8a20LRtm+7Dck8XEB5EV8Ju211YiHrdGbACKpU6qx/XDBo9oC0pqwIsXLs0MjcDXY/bK2eTMWjCsCckqA1MFQRGR0FLTZx/4pNyZuoc7F1swcaRmL9xhNWP2Df21Kl21PXxurHIRgwIlifewmGWmGR4X5Tsd2gxl70lcbKaMbQ0YF7qklqmConGrn8w0uclGFD4ZyXTSLaWMZZVbdoCPeHYuLE1xYteHLb53tERUDXomPz3uFDXdPRyORET5q424BkEWymAjoO0KTWdgQ4CmMxgsg4F25TV6Q==
  template:
    metadata:
      name: wazuh-authd-credentials
      namespace: wazuh
    type: stringData
