---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-credentials
  namespace: wazuh
spec:
  encryptedData:
    API_PASSWORD: AgAV2Excqq98/sBp8hwfkpij50s0cQSUSF+BsBXFLP1aClAbHHXyC0XEihrhM8cMKG29ZNKaXrXQw2ulVWkWGem+Zb3tIEoXX4JjU8o6WsYxwR9pEK7MF178INllKSB3vF0JQvygc0Ixb5biQmKZxK4Rezs7Vmb6osO0X9Y3LR/RMF3owHzJv1uWsa5/k4NYTuRBSh6HTU/3s8aTZ/KF4jdcx6NWDyq9pavTQS+GMw0KSKQhEDrunBAjYpxp58He+jS6SD9bOIS7P8zRPhQp3nOJ68o7QIyzpfl33w2wIqwdbV2MI0D3QzmhyW01gRK0S4tywaC8F2GT3xh5i0hBZkjhYqn13N6Raj1k4stQ2sUJ0OsVxcWHQjvSkB/IPM9OA+K99SYTg3UPbE0hCC4X2eMkrrmhKMlA7j3oDdngWVuvqvqw+QTTQO6cOia6abJmATLzCybqYL4nMDZPB0/kTZkNFkOVC27ipFwVj2IGyLf/M/5UoIpr9dra2vNyH/4eLko9gbQ2RkBmB33mfUfLTnvXSEY5I+qAas/g5dNdO3bAaGQPqPm/yOn9ySxrowtcAuolJB85l8LDb3qgIAp5sWEFrv0FSSgdP9PKFzk5VE0A6f8vr1e2dFEgT98F1okbxYW1PKHijlaGa/PNJ5HlkshukNnU8Sdv8iMr7IsI4hBGYtnWV0lX5DL8D/RFczNiBhQuiTAgoJLioToDg8NJ+Si8+Akx3PVIH4DwHkZxxF8/w/DtNnNiiI0aMXGchg==
    API_USERNAME: AgB+suirVzBrsGYTXeS+xZaHLDlqEx6bgvazhmTbqtbslUNwEh5P6oAU2uMwtUudEFwaiSWw09rrPDGbMIPDXhBGj7Sf1TdER6mcHUH5o/2OE7Td8UixLoeyf5ly4ouU8qwvwxU+yasMG+ueWPako4+ybGsBhIQObeT5BeqTGzniyPJ+NPsX7IlLPzPhPAthmfZSZ2f290AvA6Avg1U/n8o0jCH9XI0HADSqjZLJACBiP1LRDXdVpi9/ha89Y65OU5JE8ysbYlhZsZWcDl6+hiULgWCN4GaqBbE1wciiaA6afqOo3M9ZDkavh6CUihjjQcKjenEaQIIp2NmojtOQxEzTMGWKy8J8Ey7lkgWQraFeWBo+Ajfg4vnljR1LZm6kEs0xhTjE6Zbyq7rOcP+jlCrsct77442FGGO3t9v8zDrD8XZvFMFSSBNHkQTCrGko2J3TgG66SrV/7UCfOsZzcGy8cJgx161IQgbTQtxVD/HTwg2d7nsoUkZr6TzbgRhfDY/sYc86iZHfr3DudMQQFRm+Ni7FWZx8ke364LVXaIIrwm68jo64zKPoI6NwvLwY2MLx1uKL67GS06+nXYty85bVDuZJt2zqZcYxPbCyxfAd4SxEU0H21q4yqxHKx4wXveZExPVE8Z5LzFyUqXogevItrnBX54ChkI+z+edbkWaNavqCgJCY9hTB1t8GoDuwhNk1ChJfsJDjnw==
  template:
    metadata:
      name: wazuh-api-credentials
      namespace: wazuh
    type: stringData
