---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-indexer-credentials
  namespace: wazuh
spec:
  encryptedData:
    INDEXER_PASSWORD: AgBfdBfKMAlkdpuxOw3ShW9CtFmn3SguZzCPwjttxiDpgMgtFrRppMtZwRxaveuOR4bF1JT7w5YtEx5FA/4XlV4Qixt/CX521+kagMAVWG0MCO+cuMzbwhu7ZARzBLLMSuL+VflmfHVWbxt0YRcsdkylWjFbL4ihPy2qJQ6/OA/0GmpwpiubYR3IBhXuBliS4yk3RT4+cJABjD0ng+LCyVcBX7sFpSJoYIVXFL0O9n+3ZWuPodG13Q4+U2zl0AE0rq7umTGlC4jJOPsbNx3DOcbWvygusnsYQE/GIepUqScPfxVYIhr4aNAgGWOzICoD/pUiSzbst5mhzjJ2rGIZwkbFt7rvzoWmT136Q2eV0l1f0JYTCZWtgVfUK7Nb6BnhXCaaQOjmedqHe+EEvNtjwqZrgCSJOK8zH+lTa0X/b00Qumgf11HMf367oUgiZerQ+Plh+7ravl81xBy/V7E4wF9jkTCOdY3j6FofThmtazYguaeJdL6NnRytA4FLCescrFa4QGGfKzvJVUcaLnuZnaZ6IHFw3ms2x9JlU96FrpFeM2Ebo4svyMOkIrCO8JvNpt9VUv4pflZnCAwXdlRrQHFHwwfHVoOMcRysO6s5HC9iSoVGTGyT9iJn7hWLNHXZ2EZkUxKGm6JEFN0olg8bPbtnyVubuRFNgAAeQ7RbN85cgG0bKNV54DU4H+7PTjQhI/wE7Aub9roQGUT98zPKQja3SOMFrCWxLTPk4NvP09NSaRfQxop2C3a8UzF8Ow==
  template:
    metadata:
      name: wazuh-indexer-credentials
      namespace: wazuh
    type: stringData
