---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headlamp-oidc-client
  namespace: headlamp
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgCSukqOBgKmJsCaYNazKFdQaO6nud/wDP28v1dX3FcKlg/TKYs9mhbF+jKGX/YGmLxAFIBVaIsLdayc+abQkkswovSJ+9yg/t8zMBQMSa8uqj8jSrAzU9+F1nXM+7m3q1Kerd1/wtM9/5a/z2i+t70SVq0A5gglwD6bTp6R8oce+fgs/qpOMxiuMAjAkCwJBMyW+G7Q2whZKukWpIbrJ4xEuDTEwpsMCNHo4mFpK76NJYx1s05TJ6QtPUCHWFbF3dQwO/pvmtewfW3ArlZ4ghbtWBO1wBsTSkWchJA3xaU72kzy+Nodv7g38j4LTZ3ZEMFK7SEUE33zL/NgzdqUsdurm61hVIh4NXa8ZeoxCjmza69XSMQPRdeiQctgR/sccG1iJvGBdlWMFMYfnbBgPPBtUtQNmdufH0FD66sObA6CtamOBuXSFcVR1RqkqlFvvFRrtkB/S19GGsphwmHOmV9oCQbg8PiHcaxnwMVMz0q7D5/n0hEnmeIPrP3Kya9gfL7EqhfUI8Z0PvjbnhMV8Q8kLaDFpmCWTu7zPBf/4cVquOuF9XjUgFANjWQn8phQa8NvH8lefagrxppwyovhfSQobLof2GkOvDyU/YL9vUjvewx4DCgKPa7RZmWjgu6PNGm+N8re2zfoW3Zkp3I9ff2wlyZdxmV4hPsMfcEYrKHPNQtxl3fTA5I1kJt5xmUeQPAkcTDw3UBANRd2H/0Q+FuFBGmo/rgy2Ry+Wnv3ELRx+A==
  template:
    metadata:
      name: headlamp-oidc-client
      namespace: headlamp
    type: stringData
