---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headlamp-oidc-client
  namespace: headlamp
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgAUWgTvX2eIBYlZ1olm+GaI+SGCnIddmUwSFpTYn9vjGp/Ow6BJyn2uqSxH7GrK6eoQpue73CnDUr5pqvGNuKNu6R+Fs25MiCfmpoR65ksPrRT0bba/kaLceRJ2Auq/Py9hkjWpFLT3NeuAsf9XO/vJXi9fx/+JWYBo0gOd0HShyu6EJwDSaHo3K8uUTxeuUvR8+ZPy7YtRmfOcgT8jsbBtIZRL2fErKfsRz5/OhX7VF8d0I1+T70ELev0UFSX53Xq4OIKDhFhfqxImFAHKLD0wFZic2Z5zaRdlLe1NLGDIa7a0LW5AMYIyzhHw+V77Dipu7/kTWXWw9MKuSn7Frvhlm05MxM6feTUKkFrWfxTY40S9i32VgYvBBtux8gmPPj1oTndRcHbX8QyHGQIcZGvQO9K5DpDG4IEwuvv0a9tpKTomqQJK2P19q9h5H0IMPRFme31oXmgYaoklFF6f13xX2huSmTrhfMTbn/R23jP0lybw9lmymwD3BiBDpmBdWnjYNY5XphLDU1hU910dhVHhKT0H/li5Xe/rT+pMC7cN0Z4P/7GPV+TP/e9mvGNDyxh3/JW2T2oRS8rpRhK7fwgrWBKq6E0KW2lhChifvsC+iu0pehX6J4J8iAaHR08ruMR0k/idoBuXAUNOFySFXXmFUuaHCH7Ol627Mo5Crn6X/wvklkUZ+PJJQ+4hujc9TA+B/JCGHFb4ApbmbrMedwde2Fsc4OivIYnT1zXPjbQq3A==
  template:
    metadata:
      name: headlamp-oidc-client
      namespace: headlamp
    type: stringData
