---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headlamp-oidc-client
  namespace: headlamp
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgAMuctY1EIo3+nXjAPtmr1rlu/2gSquxAaKCOzHBZQ+Zk50OptBtL7/q+7pfLfWIyhrelHiA0IRmYlwlUdw2QivFdn3ywGNz1X/F479tUqelOW2ObYLkj4oD0w8i5QP+W8MuMp1MdZ+7MTt39e/WPjG2Rbqvaz7HOy5dhtPvC1VX041wgcCETjeNUNSn4XMks0o3CkkL/YHMEqlhZ3816yojl1MStyVvabo31/L8YTkLVybmP9GhZFT5nTuNwGAHtGhSZOvzeAPVjpYGJFD2+Dtpxsg9I3umtvhFzRQ9mAFvqLGHKG5+T8jBSgp5MIT1xS2mUP9z9jvCI8YVQ7fjl1d4sz6W19oR9r4lQ89wa1UV3okfnS31uFk4gPyEuKWAyJwe3UAEREVgXXWAcIADCC4ofrQcDQjHxVxGe+WoMoX6q/vcz2d5D/Rg+IAr/QwJ5StLNBLEg70Ga00mW1DVbPdE+O+Bc6UW5uivogu8bOLipubiOM9chbz2mDKUGzu0bQ0yYhNbN/89hiPmjxhCAxrXzP4CQtzrc9o2BVoF77Ap5DQL5sMF3+rM34d/fd+TTjWQXmYE+pY4x2mAaUFqhaFE2rVKVeUPhy50iIP62rdML9S+zL47xp/PQxGumpIC5LAduuSUulv5wbpyhx0OBs55PY8j8Ivj2E+cb3Kys+rfkqN6TulAiSakqMSkKerf18bHURNZmeMFE+yRA/6rqoSDmXs7n6/B/+YZX0KigA6xg==
  template:
    metadata:
      name: headlamp-oidc-client
      namespace: headlamp
    type: stringData
