---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-user
  namespace: keycloak
spec:
  encryptedData:
    password: AgDda69mFrKNjnm7olyNfq8RLnu3jNeRBJFQGGKkzbGqQbd8jdaTTvz1AicHPmS3+VnJLUlT/ub3Y9SENglVbpt32CCzZFvtKZx8cyXVW5uh90FIOnQo9a5XVI0RorqwuJswJhtoZGV75SRyrTz2YKwo8CCUQ9Iv2o59eWmB9zXE5UeI/QYv6DEaJQkBZ7QDjUpHXS037ATPdcUxZogSFfjJWq5fgZ6qs+i1nUo623cxb41CBnyAVqNTB9hAroDVDJyEDhdKDy5Ap8AFe+ju1MT1DwGSl2Zy3vgM+M9bGMbx2ii+f/b/kIzwFkOg66auJ+EUm/reqVJQNNb/cEzaSko8eOQFfUYZFcxwqnbU43khs+j8hU8ayb16xvS+AyjmC49RpDltvqDQba7mhUk+9i56hr9v93rxLYb5+MhuUL7bDVFtfZleWNxad+KVyAuvj5VD8gWkZ6MBnr5wXrX6diDvkzw169ri+kED6TFCS661b214MbmSSSE7P+EggPH6w5jDNpbljaTdzY+8fhLTJnadLLuFDhQti4z0xuZf4QsLnzr/MdDJWRMoKL670QRe32jks55ttmCg9hExyohmuNbt7FCZIAQaHsMurpd8E5XgLRbuPFR4Qi/MN07TcXOt+vNH02Nx/vRaqmPyyagJj67wQhRoLl25EpN/FlJ5nvqPklqLJ3h9lj0bQh5QNZdNtO9KvRkcZGB39wWk336N3WEz
    username: AgCSgpIi9i1skLW5DC5AedD5hsmkfakeHtQdzShaEZ47mkB01Fev4hgdqpmMa8R21k5kz7MsbKqeVZIhlxwlonhS+FI4T0//9s5jFKCVr16HUDZzmv5ZQpUgV2aAVKY7ofcSqopUV+6IDePmqztJ89rTm3+9JCho/ZTmzxox2WRq5fMCbDVW7cc+5E0iZCEEPnUIN1z994p/vbVPA6ki9flVRweKOjP7wVK+xGOw8zf2LfAjn7Xc2bwmtzB229J5RNaDy0gxUyiM90MalsgxeBPV8mcnf2b++CODADIbKwXagaCI+euCSsBaGwT4eDYaZDI5BZoIt49KtXlOPkg8YlMf2Fzdhcw4qwcBLAlyQw3hvlX9UDUbdkomoATAS8etVTwo1+ulAwinpGRsT/2NxBb5rvUSz/q4fwVshth+9WKzcgzRFS3uCmNzF6DcVeNL4nazH3BQGnzjaaSkZTknp7VG5pmtSXarxBgKywxvPAG64ImOoDLGIi7j8zKMUgiGAetow/FpRxuuvolaqk1gmsSosA27vr5u8vVbMvFAH74coDyzMbI9raHroF1aziTvIPAbHuBdn8Jhzi8KppJvllW5kzXsWtrnI8QetidK8igQFsRqxfUKBukTEHb1qmQg6VrLtdxCot3grugZHokcELfwRY2Giii7xgpEWVhCsFAS9E7zje8cicL/n3ssdN1fqy5NDGqUvOqlTKpSJxTs
  template:
    metadata:
      name: keycloak-user
      namespace: keycloak
    type: stringData
