---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-user
  namespace: keycloak
spec:
  encryptedData:
    password: AgBjwwRvWrgDGHr4M9GMNmwyrae4JWnLxUePguT8JRhXu9rVcg7q90sGEkK7iV/7Kd+HP2maBrxNtsK/y0tjaFiuW5qF9TtItWcQfhlZZgHWtA5vj5Xi3vEfgG+CfNZwd9kU/crrX9E19VckP5FTTH4JkZHCQPz+ZaLwiDLm4jw3K4zuZwKROic/8t5ER2k+xzI4mz5Xu9PnzJu3zPpnlNmy8v4ao06Y8nYEjbb2yXyxj3zNzUPKW6j3KXO130UtfDvs63zC8biiVWCjkjS6PPc1aXaVmwV349sjdTWAkhB+CqAln3hp1YLXHSTiXcgi9JJbmD12Tp+8lFyVaXGmnFIiMDsZD1LLxHh2AFztIZfBpTjnZdf8VL7tBKxJd8R0IKmbLzhyQCPTqFW/enZzIcHLhBgCMi03ErPQTM66ov0q+y0LQwLPYihYDIhb8L8u1GTUZdFzOjg2k+C1/Y3OsKY+llEWPMnUIOb1VjXlkl56EZlr0M+hbLNBrTmcXYh/K+K7McAy2wekoXOrdxfvlRSAzvQuyywtKN5TTfxqVl3p3Fd37zIuXdAo7EpaxcDF4CVEdNHm5LhG6U7SDidXv+cnHpvf8LZruo7Bps+PqDgDqKRY8cw/4z/st23bEt7lcpm1LFOlnyMNOrN3gKDLUEjfDccoVpc98xnZHJ+muNTNQz3nS12JU+Zl8J+Myq/BMVQDYOi49LlC2QZbK43y1t4y
    username: AgB2czgmfNQbaToTWTZc2QT92oXWcSlOpfKJ4MNxtXigz6I7Mr1lY0Gt6EMmVvEOFibue8S6NicyXcJeT+Ghf8l8PQV9/lfJcHPC44EWXseag5yOuYmxM9tmpCFRbKBBbTiaz9MNeL+i4T38322WyAtEEyIQZQXN0baniW7jp9BXjoULO0ZPahwF1He52V2h4eUIoIB2CVjRQ/0YcnFkr3cemE2UnK8r4J2m7rztgHz8HCwEsj72dLidXhvgNp7w9eplaHlybXgP5punGL4wbz8zuShzQf7tga8aZ+hEflqNcXVY/ccx3QxM6Me86oICkPJxbqUPnYQbbtRvu/lCeSCqtTL0/vXfbjuUZI99Ep3tD1g9OcQeSBczgwGM/o9Pjkbu3QBRfaiD9eK+OZJnpcix15WOs99VZRK29ipgrt/V59igmJcibcBnYSlwrGy146Ns5QGv/Y/JayINnhc8f60a3xLJMzt2spJKpcPCDn4475xl7CXqOFqFUyvMZYH7LXjYKHtWpexUHXhf8PoxUW1REJlUTy4GdKcczmlICxnJAKo0/H60oybCzxyYgkz2UlEWw9DFtp76fLxros+yrrGPIEC9jaDSFmLq6h95pkpQt3cRof7pM2G35BGYGytaSmkWsj6fWbh3Rgst6hxkpc1Go4uAY5anMbSJwzXys1nTYC1MHoAFRQriS2PX96NJDsclrKtuvhCXrt4CCq3Y
  template:
    metadata:
      name: keycloak-user
      namespace: keycloak
    type: stringData
