---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-user
  namespace: keycloak
spec:
  encryptedData:
    password: AgCKm+RL4lZqqdJut0fjfUsG1MYUxyrG3aoWdWt0L4FszYARTXcPUcxS8xNKsC3VQAdIUKdPqKfrr7pu80j7hGRyWSpuSSmkKqrnJFiDKDByogJDiQLZMyZ8P/pJmuYNRld5d87MF49A7JAQJHCab8fcVOdJuE4esrAuslelKERX9BqSIYDCI8h6AT4b92jxKE/xiXiipgzIEl1XG+/f9IrfxCVGy3fkbpnvlT9iP5JKjepa5KIsHAMmtxXJpNkXf0vHNrydU//8HCLY0qb/joqck/aj1AAkKnBoGRAC+3JiMkB4OotqKWfffxHF88T1P56KMOtSQNG7SAXKNDiUyiazpScmK4he1/THp6dEi+JboFtjEDKTpGW479gSXGuutZnJMB9HYa/JUpyytS8jk6cyG0NpZCpQacdOYiG7GnbtcGPEzOAyn3bYL5/QNSbZZ3bxe5ibFXyHfWzL9Rd1oQn7nGaJ+r85Tgr3BTmxh7IiapoSQ99+ZDw0RizCkTD5kSd5v0u0fOwqwkWpeHuhTO/UiNn+5oopSgJRAdsfaFTfTIl1FeYEBeEE5M7aFUb8fSl3GXnPGmoWi8spi4vn43BB66Q1Cuj3kjzdIgFUjNmjdw2d7owWixDL1PyYJv6128nnG6Ej3EYAvXIwPOJQAwX6hLuS4C8tLmjBreP/pvAV1PkTYdEvK7ZJTMkM+y1+XMiIHuS09zg17usKdm1Dkrbc
    username: AgBPgddVIt+NioRpcb7S9TSfsHAMwGvjkETIngpmP9fWsY8TqgWL5JIZ4p+Mnmw4xWTX9+rbvy3NHPKnyWhwDCN+odAjgbuqV4iYWX6zT8V7tcZ+jtiwW9omWWo7YKdIObSFXfaZav0pDJUEqouWF9KSAL4vsEjxIEU5ld7PabzdglTF/IFHNh3CUkk1HMvSBdIzL+WvEwBh0579DsYing2v5coqPou313diSAmiS6wTnXUXBZD+Ne7CsIOk6rEZqWIpTbZAx+et6lBSVUnO4rEBNA0rgoVT9ebvajd2xTF5cYzSHNTz/LTcO7UoJYqVwbUGCqe/PxHXvn5t4t9yGOkJQx7SSQZEVeTmxyWhhFqFY5VyTjyKrEqSMz6+YAihXvq5tQmUPsdyMetKS256slCQSuiQL96udwpixdjqg1lHoURxkUZGfk/P0GE9ZdYDQxZFMxUIc8mQmnRfGxrwhYj8nrQ25au7nnezuj2jZquXLLdExYaUM9EniQNVt2Mi53Ca4+EQ078k4OksoG7eJWVwPb0rkj8ibsT8/7sQOfu0XMtdi1rKXOP/ENgFjGqRL7+7nooux+4JNtxZb6WLzWAiOB2VmsQJpCL/uqtESUW+CPz3/orLhBSvyADCxUu6dHcMKgUmFCsVUx9OVParDS8L8IQy1eVsSYTTpOvKhWSvPnylGRjpXCeBrBjbRhZ8oPacX6EgMai/hW2HNOum
  template:
    metadata:
      name: keycloak-user
      namespace: keycloak
    type: stringData
