apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/kibana-certificate.yaml

helmCharts:
- name: eck-monitoring
  includeCRDs: true
  namespace: eck-monitoring
  releaseName: eck-stack
  repo: https://helm.elastic.co
  valuesFile: values.yaml
  version: 0.19.1
