# go, java, and python
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: go-java-python-instrumentation
spec:
  exporter:
    endpoint: http://alloy.alloy.svc:4318
  propagators:
  - tracecontext
  - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  # https://opentelemetry.io/docs/platforms/kubernetes/operator/automatic/#auto-instrumenting-python-logs
  # python:
  #   env:
  #   - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
  #     value: 'true'
  #   - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
  #     value:
  #       <comma-separated list of package names to exclude from instrumentation>

---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: node-instrumentation
spec:
  exporter:
    endpoint: http://alloy.alloy.svc:4317
  propagators:
  - tracecontext
  - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  # nodejs:
  #   env:
  #   # https://opentelemetry.io/docs/platforms/kubernetes/operator/automatic/#js-excluding-instrumentation-libraries
  #   - name: OTEL_NODE_ENABLED_INSTRUMENTATIONS
  #     value: http,nestjs-core # comma-separated list of the instrumentation package names without the `@opentelemetry/instrumentation-` prefix.
  #   - name: OTEL_NODE_DISABLED_INSTRUMENTATIONS
  #     value: fs,grpc # comma-separated list of the instrumentation package names without the `@opentelemetry/instrumentation-` prefix.

---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: nginx-instrumentation
spec:
  exporter:
    endpoint: http://alloy.alloy.svc:4317
  propagators:
  - tracecontext
  - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  # nodejs:
  #   env:
  #   # https://opentelemetry.io/docs/platforms/kubernetes/operator/automatic/#js-excluding-instrumentation-libraries
  #   - name: OTEL_NODE_ENABLED_INSTRUMENTATIONS
  #     value: http,nestjs-core # comma-separated list of the instrumentation package names without the `@opentelemetry/instrumentation-` prefix.
  #   - name: OTEL_NODE_DISABLED_INSTRUMENTATIONS
  #     value: fs,grpc # comma-separated list of the instrumentation package names without the `@opentelemetry/instrumentation-` prefix.
