# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml

prometheus:
  monitor:
    enabled: true
    http:
      honorLabels: true
    metrics:
      honorLabels: true

prometheusScrape: false

releaseLabel: true

revisionHistoryLimit: 0
