---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crossview-keycloak-client
  namespace: crossview
spec:
  encryptedData:
    client-id: AgBHxmXzcbMVn7A23HmyoC+5E1yO4GES7MgI1S/bsU5DD/vukSk8ZhrSrGjGX3I+u93LvdU8mPj/dHVAFYdhCrNN4ZTN5J/uC7xYAvkIL/zx9cRh5jlFjZeMTDKyfxVo7QsDtOntr0S0m9Dsc4InX9EQB1zZMu8VrnkGlFo6fcoJqmOKPaOFrhJX0Y+RUzfPwiK+6VJlGte+ubwQ5BgEeo2WUJEDxRWPV0f6UVcj6WDqetq1SwSsaduEMpWkgT/27kelXC3koxQXBfq/8gIqkWT4XkBZibCeEJNdJd4EuovD6lnX4xubv2/6uTsjzFQz5yXHTyuNYNtF6qKh8h2tGUNL8X873nHVhuzGB1VsBcFiAWSFMjunY4bPxADAXlLJX6B2SEtAjX1C2wEyTcuObCSlDulaP9NLZbbeE5DYnYaFeex2VElAGKiJ0K5ytB14Ja11ESE/qFDW1Bj0CIq/LTgzv7qnYHb1sr26qCnLoQHWbLynncF8qVscQ3vscGbuM/z/qvKq7SzXiMuWRVujhQJY3DrZigDK9cGQkEdEdfCcN64vydFaLB0mlznmSmgc1e+MsYfN0xL1Rwgro7lLfUlZ4ItuPQAqFq41DLcaKxgiWS22wxIvhHh/C2BvET8OdHSyVF6Zjd3TkvQUiUg3jvzFJEM45uW7Eii8zQ7BDNjXEguzkDs2uBzbozPcUiNu1fXdEIHJu5GwM10=
    client-secret: AgCcGSTL8JPsGfsmuckrm2W9gZXQtPtBH7SX9dy+TqkmoUI6IGVfz+eA9CUGMeRV3F4rJzLZqaeDPFdCVMi+r2Io9VA3pL2987vnjbdDS7r/WRNGGJOlNkQQDnI/tyXoSZh78/Blf88ICOsm1qdyz3Uag0AHMlhLvmVBbm1jC7gFT1ZB5XnHAmzNik2vHnIvYCEtMVGFFeeBjmC5PDCKFcTwlxVVbg+EvGFgiyzWZgb+0hAQp9dcwI8JTtqOIVql5V/pHYb1Jg/aPEPYmiwOF75Mnk5C/UaFYKU8HNUDF2YbmgPYHXjgvyBNzdcMZHvF+LQvyy8Hjnq7A1bTKRGbKuBE9QvEr+1J+Zp1F1FLit7ctO/+CTysEY/MB9xrE2n+DfV2D1IrTuO4rJYrSmCVZxlyU+nQ85HCP+ojgWviLARcb0VP0VvlwI2fwU4SSn2UohxZLpLzg/a6PpOFSnlqhU4smiy7bQn4CS/Y2ICncwFcOG6FiPkxCliiRq77j+2vnKXMZfKxxyidYoY+2MYI1EOzwPkj0dkB5wcahNkErZTHnxAF213joGyDiQIqJje0O6fk4QKN9J8996GYJyB1UdMdSWa89GNKJXnVuU77uPs5mtz/znvfiQqDN8a5UjwK+3JiAHkpC84mdn8Vet1pYvmUlEd90L6A3s6brAuW5LIDvic0dZAGRymkYaoGrbtWiEtBzunQVER6iz1ASVt1n1U8UkNOlvfp9sSBkP/oEXsOOw==
  template:
    metadata:
      name: crossview-keycloak-client
      namespace: crossview
    type: stringData
