---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crossview-keycloak-client
  namespace: crossview
spec:
  encryptedData:
    client-id: AgBhHoCunaqOX+ugsEqUF57i+I8DYNzLdpeWTLxxZd8/R5W1YnbCMh4DVvYcxVHLlcLBTtoOqDgMMcpwfKArZRMebVCRkUiImHletYYHIdraBTaVapHqk4DgcUAEJCsQ/RR0kFnFKctikGeMzpqjvlyLPDmy0dAZOZiJ0N/8W9Mzb224mHjE4AH6+1w5g45PBdyDmTOXrt597e4huXEwqUIj2YrO7awQ0F+8c964xFZ6qnQu4Co1rzKxuSp+605AkHFWOW/jppywOOEfDnMV+Uj/6xZH1EtD54+D6t37uuG5nXnIqRcIwVFl2o5ymuBdjTjRh7ImqrcPdftIqE6s5W5P9yRPUWSc+OkraJLciE3BfdcEO/oGhnJN6UpyOu8eamxnl/448WbPPOJWdE0+0Rb+w21BWbyniWDSvnWtQVTxeDIvbUt1ag6TGWzrGULh5Ryy8hFqRB/yAfZHqNtBJivnJP3V6W4IjqcbDufbxxdyaYI13DT+SVu1QSbIeC1wRpIc95tlUIBNzXo+Uk6S91R80qfBs/Iu7GqHxY55hudfB9DbHCbFkpp/49cup7LGU8VKfI5ldULf2GYYySQld/kdH7a//JOSZmAy/j4ddmVVD5FF7fNFODopIEQvkM/xozmU9f05pvhPzCjpyT4elROYCRv8LGBS26yD5Ma+xoEDzD6PEIR1AkE6lW4c1XESCBm6SFBlBrIodto=
    client-secret: AgBTXzGESJQj1c0jfyBqPSBHh+w2mosWkhBOpbYPA1W8MTeXV0nHxAlIdXISc4Thn0AhfGSUbFhmS4tLideigXVy96G/rv1mbAoau5QS1ptdJiQPbIyRWQfTJVPkorY/LRMY/sNQG8DGmwhtIagY83Yt5ZrSZlv6rGbbP4xEbafOSKccVkzcbAaM8hZNIphCJAB5pKwiF4qIuGMBVBzdsfd8RzsdwWYk9BYBk5FNb+cuqsF4dOzYz07zfIviJdQcAWlOUVBmpqHO2jkWbHlMSNMK7GFCMPybsLsO7+f9QjwiuqLCPrQSsbSBgWLBYw5LYk4k10PcEfAFVWGxhyLY/H5kSOGEZeqJ0tfJDSxXLITrRZAVp98aUxn/PjvaUkzM5gS8NHIxCzeAglDvHxHiKyD6aaHANC7N90WPjHvtIedDXauJRHl+hhGT0YiiIWVY/g3oA9HwqQYOtwfeCG771BUQXGDTEWvK8iCOB75sID40s5uVF1HiP918N3KVevRncJ9tWc9x7benha/DHV4+dF+W4TzErfJ4R1s6n8jqFhQQSubtxWgwhNfHKVSN4GfQh3mdTff5rtJU4Zc7PSjKwHlAl25N4oxxzUEM8E8dtKcBqsybdtUULAFlF4mSl2uPIvAG/fvm+aQnu4DL4lc9KoRwB5d2FfzcKIeix10R3fGQ7qUjLpmnTXl6ejQhcV6FmrksK+HGqylzYZB0fULVpo+uREglToPPPzXZG5/nFslS/w==
  template:
    metadata:
      name: crossview-keycloak-client
      namespace: crossview
    type: stringData
