---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crossview-keycloak-client
  namespace: crossview
spec:
  encryptedData:
    client-id: AgCH7gGUUIr+I9wC6yJSjh4Bm3fQmOH0dZI5PNdBiNDj3JOJpPsYQXMQNx8gh1MSlRrMLobiaXfX2fgGA3NZw1OEHaeUahXzr623E2xE109OX8rztFgzik1qFg//lwbVcw55hAwSlJEiSk/Ah2gVhII6YEX3yId9G2gAEb+oZ/GZnu3t4PjMBoJ6rehFk2wUMDAkcGp9gcQjlq+8bUMN7tiiL07RaPATcnAFBLqQyf0Q8svBXiWBK+Ilop3NO3xOHwMCUHC1wi285l4qybmEDhhjvd3ZuaK1N18XNf7Sj5aE3ZVqwlwNhhuA0JAY3AhCKjpevk0x1JHjLHu2mnEOXliwewQlK963RN7ZLkHoUWLodgfTEnwuu7idvv9xrt4NEKDGfW85MzDkI7lwgejGqf0akeZUFb/tNGfgPAlXxEoCz8kRDXDT3ar9fusLnXEYtZnfJeyXJ4ap9v2EpTLw+XZLR2/f/SYw8f2YzEjWmR9dgXGJbfghGMFpyeo37Iy9Fj5OJO4EOmCjHGqWC5x5R0Llv0vHFvtbJ1/eWdrLnT7PdTIVy+w8abaD9TzC9SNRf8pWadayigfGuW8whZtNVRq8LeGiRf/b/iYZNZNSSnbm0X2ObJAa+eUAGRsILPJY/kj4YjCUrF3g7+Z5fFgQ4HZE/XoIHkg+W5+UYFFR3vo0o8gRnsHz0z4kGNf+4+7QbKzfdZQoDrzg/v8=
    client-secret: AgBzVrfI8pW3MzMRhMUilYTsFgYu/KShj9jFIuJ4aTP+CDeqtfSUeAULc+Nr0DwagYpCeRl0xzpaLfo1bdZFkVDTu/7HZxnHC8fakbIKz8clbqgraapgXjUunPrJXJHzmkAlQ1qJuSJ3VM1Pc4bestLmqW6bKUC+DeNrurGnD5EXBVa2ZWXPV8hvT6XEupPRJdCOwMhvYZgprFEMsj96FIwLU7rF8WTWzPl9BlAJsmyjThRBQ761mw3mrGVat4vz+MnyTEeSUrkzt5JbuSoviF4dY7IYsTR5qTpBSXUgnYNfL/6Dp8k90sIL4Nq4GVq4DC8EmPfEn/v5dQk3XLqpEnyYgh2Xet7I92J3lcUXeXk2e9FFZsd3uVZ01cnvpw+EEDHIMf6WiIgahtk3uVM3LLNDzOM42E6hlqFyAmycoaL3KTmLx5PvijyY8XQ9uygKG2RB+++9/GfxDpmTM13rcTID0GbCN1GJrLbRSdMxTtQ+xpbcDzuOGoY3jqv6SSFUHfzgYLRkJWGDKCZ8C+PRxfUm4aMWEwtkFPKwq0xBIjqRmDyWj3DKhVXgj7yR2U505kXLSjO77GcqEZ7cBxrzOUzoSA2zxz7W8Fc1cXtIuXpM+bC2IvjO5FBjxUHfQI16VinYPHJPOLKB2mA0sxNWLa9ygRzm+JweFWQVCeQ3/aHFzePCwBYSWIMDIzsDvZwz1DLnH4B8dahXMYJD4LQ2WNFsKACEkRn8Wzo//7ag6Xxw8w==
  template:
    metadata:
      name: crossview-keycloak-client
      namespace: crossview
    type: stringData
