---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-keycloak-client
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBPAp8tsOpvk0VQAV1k0la70+DX9kRYWnnujKH8BSDyhwZ++7RjuGUjpuy52flKt0nBsHzEs4A9Pc6vUM1nOau1e0uwsZL9ImnmOdTUtwPiORdc/COvW24CJgyGDkxwJXVGsUw1p67AVpJES2hIWdMrYMdzE7C6dVpIEkHnagTZSDWdqF3Oy3cr8Qc55CRJ2MtRx1mG8Z/UaCU111AZUOQIpHjb05tvE7tCy2CC0xkvYqRQhga4MyMicoPuhSDXOXfgxvSeIgX+wXN2aLDWvei+2Ru3XlOI/qbOdoqsHCZcQJD3dTQUVc91ivIfxuKmo+yEVvz+A3EnVofrJzw5HkFe0o3pcbDEsJo07zefi68R+xQXmww37m/59zQv9vHdwqwcUEFdGZvGyS2JkFXK7G3dCSj5qZOFZKUVhAaC4vk4Jn0kwrgwFVmAEGvVY9LJ+zm2g4R9xdb2gsJ+CASyIyAwzSxfiUGtkEyAHhjZcjj2KC7ObhmX/S/TeQtPyEiuq6BetZlKG2C2gS6HUp8SHySuzQPAJyv2Eurf7Hcli2FBOkc+1edTdXqIE3VSyzlJLEWo4JHVopZ0xKWCjaqfSoP3WCBPxmlYUwPj3FbkKXnMLDespFsYWJ+O7RQKEwx0YtCvSBHzpso9qp9TiKqmwEU6Hh5FRx7PJWfl8LbD13jSj/TCPYgX7WUwx+0JjJvcvFIfavSLE8oxq+YLiWQSw4UhREaXdf9uFp486Wh72gIVMQrdCmBL8JfJytkL6A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/patch: "true"
      labels:
        app.kubernetes.io/name: argocd-keycloak-client
        app.kubernetes.io/part-of: argocd
      name: argocd-keycloak-client
      namespace: argocd
    type: stringData
