---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-keycloak-client
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBI+dSOJ89byt6tKZ1MRYEeD/tLqU8G2qjSK5AY9gkiE31mDTd+3l5awOxE8XDGbUCHpSfdNHrUQM2ZJOGRb8JbjU+USIwQ656TjN5opHAYqOR2OM7p5NVxgqw5PejRV+1eb9AxjEfZyESgsnwqLgjkVlnk9RSw9cekMR+U5kQKcTC6bvfM/YNVhC+Rwr9vn+AAvxF9jeVm196OgwflMeL4aB4l1yjpLw4jLvkLR4SB4RUmXOpYSaOS4hcAABKvCZzsU9m0hEtpaBrKgLaBai8vhEnx6E5LgE2bNsnhk2SjIcdMPrxHnIYlWvysqxG6g+ezlO4l8yoWr5pcL5UpUmih7KHVDJZjvLUy2YkbOnY0du86Vnb384Pm5iYG+rR3RseYpOgqh0IKo2hbr1++4NeSZ5vD85ynq5q3c43vyt67CgCOjEccJCXp1zNDoB+/0+7N3klSoPOavD5JfEpcP0Q7KJtOxPm6+di/wCd06T5rjiI9ZMvFWUXC9j3HL+R3J5P6cDsrboRh2BbO1TtW3GtMnfIKKXTjal77Wcq96LmdUz5/O7xDSyjvXjvWChoy1EJgB41iyPadDkJf7GWAU8LgKH+NwSgt4KJti/q9/RMgyFecwx0wM/vh89Ch0M2Ok6r2WHyWCTKoiWdu0YHabN2Ml/epv7GxgLrYhXMhi/ej5baHOtN8dzNYQhEf+HpG1WPT8/h+9kFiRZSWuf7GWSbc0aYcIMyFm8LT6Uvn2zgpLG3/bh7xbPmyVk4FFw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/patch: "true"
      labels:
        app.kubernetes.io/name: argocd-keycloak-client
        app.kubernetes.io/part-of: argocd
      name: argocd-keycloak-client
      namespace: argocd
    type: stringData
