---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-keycloak-client
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgCY/MDrvza5duGzoDIHII9OQIBXpOOaPgjLM5xdysr6cQlEwLsPwY/wwBDBRi9k5HWDwOcjxJDA0SjjM0P8udklhcnQk/yREqQYPcgvwgkXFDJ9cTfuxNSUqlnSrG/2qnddnQtiDZRcScV3nTqAMiMOqtDkMgCT3vpVp96UdL9nzxzaO2j/CiswLjp5WLt9MKRhkPWaBANXijWMRs6vYi2p3W35+SInfoUYdYw9npLoDEcu2FemP2tn3jpVUPII7g6JXp2agpL4XH3T1gAOO40k/Ob/YeaejJdhy06ZHNPeHDpX1Ud59PkyqS/PCYDfYyCwYGHEoGeyrxjqbxaUFAzM+A5LHAMEXRe/H3YK+F84X5KXlDa/3f6YUNIZFKIMBZpCuY33rNItX5xzNZEX7IsywUKCy4YjjQGo/yQnMyfVBWaKQuJHA0Nfofpb5XrxGzmWRsG5zN0cycb44HFhuu79C8krSBfSJbAgnUxzsrhJDFPE9TfH1LeII28ICr/9oencqZai5rxK0a327hFVl4RqiRcKJMWm/FpBAnE4WfAYcVImK+7hLhLXaP3Uulg0PTLw58uiNm9lBya2varDcAiqmDjIB4jRFg1id/iWCoYalMc8pjMS3Caw4aPDvm3dQIkljuiV4ijAsJghEijR4hRXT89VyvoHxvn0HMPnJixiNoy31nefJm+kG+AFrVaZxuePIwp823ban0j2kULrmOfXNnLZWlR9odP/T3BPvFCcH2ccD1hqjhMlL0NM+g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/patch: "true"
      labels:
        app.kubernetes.io/name: argocd-keycloak-client
        app.kubernetes.io/part-of: argocd
      name: argocd-keycloak-client
      namespace: argocd
    type: stringData
