---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neuvector-keycloak-client
  namespace: neuvector
spec:
  encryptedData:
    client-secret: AgBjFCO29n9h3Nw8hTEl/41XlXqSKOG5tDZRvpVNiPiJI7KAUAzhgV07knvvNIeuPxZjeFnKzj7GpaagS5muj0NoQhPxZJyETY6fCD0/GDDxd2fpo8edDWFTMtPbVPIm+cU0XCPHBKkDtsi2xF3QRD9rPADCG74mx598ItU2/Pa3YKsvg8Fx6enfm8WA1WXERjc8MRkdodd/cY6wEnb5Opslup6ounLm+UekVk0bHYrP/pH1ITN9WNSeiAym3QkGSEpRhLqeqyB53EKscZ/az95GwMhGYuOlr3qT2/ZFIrU96fNhJKK5U9QgcRcW5PwCLoLQ2xb7w5GEhyZlzSn2yH1LRSzZtHCTQD2Hl4r4vl2ktO6Ybp/u0334J2/I9cKh/8kEiGS/y7nHcUKKw4bjArplWVxXx2McmzvYl7Fy0N2qf9+uFJaNmJjUue68fvZR7290kOJead8Dxb8bgm8FnI4HqCgum1wAe8qg2mGGZXm88TnZXaHgILtfyYOMYpuPVXWpyeca096H3UhWt+0PiQcC3dIKmOKcmlqXvSr51VeyvTeDeyiB7/y22P+vInG3JZdjV+uCn6GETN3YsXDCyQS7mIElrkH2DEldb9SO4KXvamNw2BHvfQRCAjHi5u1HIhPgU8uIOXmYO+c+65rXtH2z8i5geWG/hJ0NHHSI6Ajw36eXOcKnZ9g948EMpdEuJuWFwk7ajpwhjUAxyNrQwv6han0dEGmWhW5fvJAlAJqx0Q==
  template:
    metadata:
      name: neuvector-keycloak-client
      namespace: neuvector
    type: stringData
