---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neuvector-keycloak-client
  namespace: neuvector
spec:
  encryptedData:
    client-secret: AgAWxZPwNxp9XIkA5gptDi+/Y6xyyEvHGWaYR/xO4K2u3kEr2RkskM/f7J8yCW/Drb2AzdTqt3Qat/JTO9WmbLrWlrfH4tODQ+o7MY/hO+c05ehFRmCyqryuQ7nanRlEvtbTW4uVKDDccIfzQrj3dw3QWFaA+z8H3BCvZ/jT62c2aGqdPDz62zYRTUEBJ/odib/f5l85nuOqzOj4BNWNnsr95dwVgtulP80TyoZyaKOAXJp8ko89Wlj5z3FHgzSXJL1u684NQd3Ys7XPaYVrOx/xn9/zeQub1szdwKyfK1mUU5reY3gFY0AsBq8AJDn4U6Qn4MPlygPWHREVPpYFoc++yjgm+ZV0cNdtjFhFq81p1I6wgVfiH4wkMBvQiFcIJ11J/UXh/y5NNRednnnZMNVhMejXondyvm9sbag31wqXR5vw7j/cuTfjtYUkUl1+47n3OYYC5jgbk6RRswhDwoOFrwXLfkOyFvcWrGYbInYMqwxeVdPd78LJaqUMiWPm7nvkuWCH77W9WG5yVIgR6lbXEQ5Plgx/jXcgalTN3jwrb/T6RaUwhBMxtd/k/X4arTYQibKxo6F5ONfHMcB945BTklDwtbNwwjwKA/vML/Yuu+oNGTv/aCUdrehcSjD7DT9U12yv0yrSR1EXNKoP+Fg7HLzI5PrODm9PJU9epcXaHVXNcwDcYRRQzFe85IgzdZx5FhvYv9l0uYysJhkco/zinMGDbiAEtLADSgzj5NjIGw==
  template:
    metadata:
      name: neuvector-keycloak-client
      namespace: neuvector
    type: stringData
