---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neuvector-keycloak-client
  namespace: neuvector
spec:
  encryptedData:
    client-secret: AgAGO5Zio+6X1iBZNz9Zjt/aXIH9xkbyJPg8X4nHkaGplMbWdkytelkdhpXSXcv/tWtwt5jUzV/qrBgqAbEpOyoCrlE0A5w0bBH8+kS244GHCakW9c2GW0mVfwM1lgGDawnqeFsMx1bse7/DxfcV74d0lg+8aqqX53t73FLQTr6BVaCvlVMxaewkVD2ZrBhw+nb9JTW11n+b93aSpJ7DqGDkXUMhCiM9r/YBCFdRd6m7E6JRceMZcwXl0MYlTHo/AihsDy+VlK3Ox6Hf04JuTjeKyCyKxDY3O3QjzYASaATSzE9vElkeBBv84GaVpnGXPW1U9ffkjnBcc++obkRIF8CddnlX7Jr/kW36wlh0j3qleIYS1tCzAPMcxq/YHraHoZzC6wy6HqJhnleob1f0yPjDbMhF2UmjmbvfSTyZE1KPCztW0LeH/3qM/t96OfrX/WqvgZINIxjIzQZbf7rVL0ybbxz7p8URB0OoSGq3/YHUgKFTO4Jy59Vkiz1R99NdMOnQGc04Ra4SjJGYLEz7nKYCHOQRvNLHp/2qxOvWZf3OwB1kUg/QPJ0xnnDDBSoLlNv6hkmV5HKN9I3T1b7npW1cE7wodRsSZX2pLkiBX5cV32ubJiH0UG46w+8OerJ083Sx37G8lJZ0g8dofhT/UTnioqFjqF/BOIf+rtsMN4ShPZGXCnLO7TsMn1BAylVb9vuFjTG0RC7DhixxWMBueiUcqXwKgq8kzkgja/ZkSwRBBg==
  template:
    metadata:
      name: neuvector-keycloak-client
      namespace: neuvector
    type: stringData
