{
 "title": "cert-manager",
 "description": "Monitors cert-manager certificates in the cluster using Prometheus metrics exposed by cert-manager.",
 "tags": [ "cert manager" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(certmanager_certificate_expiration_timestamp_seconds,exported_namespace)"
    }
   },
   {
    "name": "certificate",
    "label": "Certificate",
    "query": {
     "query": "label_values(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"},name)"
    }
   },
   {
    "name": "request_count_action",
    "query": {
     "query": "label_values(certmanager_http_acme_client_request_count,action)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Left",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\", name=~\"$certificate\"} - time()) BY (name,exported_namespace)",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "Certificate Ready Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(condition) (certmanager_certificate_ready_status{namespace=~\"$namespace\", name=~\"$certificate\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} - time()) BY (name,exported_namespace)",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    }
   ]
  },
  { "title": "ACME Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Overall requests per 2m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count[2m])) BY (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_http_acme_client_request_count)"
    }
   ]
  },
  {
   "title": "Request Count: $request_count_action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "repeat": "request_count_action",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(action) (rate(certmanager_http_acme_client_request_count{action=~\"$request_count_action\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}