---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guacamole-keycloak-client
  namespace: guacamole
spec:
  encryptedData:
    client-secret: AgCGFpboD7Ao4SS3fTKftvsh53KubBk9BJWkJUY64WNZufTNkVtING2ni02TfNLXG+dJX8qUJejSgQzOnUT2tESaLoRkfu8Z9E+9xo7cfHCHa0M4mIjDbjDyJR5a1R3SWtprtpCtHs5kLfkq+1wCZVreBNyt0n5ASX73iJ/7I7B0fqiTHMBzhS0Hm+HuddisodBPzmhWEurZJ6IIpw06VRwJXzK6OLFPu06gOqsrrqXCGwSRwKO+w+dllt217dOteTNMEZyVJXAmQU9jHtM+KHNWihdWUvqtl4mK6yuuERKQH6JtRvCxueWO69niqfP7zdXH5VvfZR9YBO7IUbhEDFdEge9qe4RVJYsWDJSdF62HslmYBc8Qdk6XZ+drAlwsjOYaDYQEiBc2mJCDc1jK6VM3iPHaYbmXaxAecUG9gyw/cVElUUVhn3Kny8V0osBOH9HknrpC6Di7Krjg3izO7iZ70mTH9suK+Q17F77lcbozGa6jRT8wT7l434MGuNP7YZYkim0ebFLr6B+cXINIozT3Vy1Aewg/tjzo27i+14vXDe6VX79sHv8CRwd/fEXj3UTDpLjkTbjAGkhQYUxA6X0k4Shul7n24finffOdm0EtXaqRrTkbzoTnI1C5QRg/m+lpHWX0TwpbRGjXdcbtyfKihlYohSEtYU7VJ1UvV+idv7i1Gc9baR2THOQcXdUTwy7tQ7ZQXU2CGLhi1JTpYJnqF4V6+AzD/NXaLKBeBzXQ8A==
  template:
    metadata:
      name: guacamole-keycloak-client
      namespace: guacamole
    type: stringData
