---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bucket-user-creds
  namespace: gitlab
spec:
  encryptedData:
    accesskey: AgAZIjQQYzTUhSw1KBu0Ak96zx+2eD6KVk6kSZBgeoUCepv2NeEFqJnkjVeOAFTHH66K+5O+CfbzigUPZGCQMi/1zxlaJw3YLsMJKfVSmslRrLUBxEIdz7SPkvernV4XLP91znYYzFsLaj6bTtaNE2+BcFzYOxdN0NYoD4b/q+6ObpyAQmiOyKAehnuB7A2m7qwnxGex+ex0go1LywjIsfrBKLt66UnuR5M8SgkfGHYIjBhlqaRwIhEcALL9MPhQxo/BdazEMQJu5lkPAvf6eaA9t3MhWI8iFpIuJYh/+Qzgq5nOsUMNajPcBL1ilnU87tH1sCXT2D9L6/jooJR7HHy/3+c92hfVFcSb2l4/K5QGzvjyGS5HVSl9y1HQuI5jxkOZFhL4P1BFRCsnLJlLFJpZ4cNi2vv6Hu0b+gwgQRq2usclSLdVviCf6bj2FlYMMHsImJEzJa8bQoVRxyDFp7vl+p5FkhNe0hnB9lAPRqfI+qe0jmdfF7dIWclOYrLpQic9FYNZpQunPVY3E+YAvAQfR7ZMluIKUxaVWFAzkZTt94bEMKkzdO3akQDyvp29HzaDiqy9wl7dn+TO2B+DlBZ2mZV1fdYRofqGO9Z/drRZXoqvNQCCvuOQIfKoooKoajHs5kGFGYm0GB6OoPzhgnSK5+cqQd/xt+UhP4IdmaOPUPKKUQw0wFEL+Vbx13Ap8LstG3LpSo6jdMQudBRSKzbrYkRRCA==
    secretkey: AgCTF/uWwI9NhAhcVO2eNI8RbV2FD4b/ZCVyeazf9aLSREG6oU6TwSBRndoS0wGODXg8i41CEqkDaqXMQ5cWeMBbj7LZbebxVi2m4ZM8qzzsgko/oi/F+a4c01xrFbv8vjfZNoTbQPlB3da62cdwcUNVQNSODERkzydTrmP9fwwc7SoTe+HhZy6shhfr1bTSRXJaU3kWpOFa2jlvIhF9HM7ieYlTT0FnyR8ZQj2kb4gC0HO4dvB+RA/7IKWQKitQ74CkJqlyAW5Wbw6Q/ATFem3kftDFR5mKUbc6RHDATjlmrON+s48j9nVZThgsCcKY24ECUdCn0mQy/vnpRPVDgh7BIruj5fYKZPbsa64utqt1PpW/RuPQzMDbvdchIby1SRoEz1SfHD0TsTt+2ADVEEI1CXliAY2Kdn2IR3wbNmG5dX4wp3ivVDFcUWbtqZg/HgsCPZqo4lpnGqlYLcHDbBrmUVvZ3CiiE45NqqeO1C6cikglJmn2616J+XG16JN8KqO1PT0bTJnaAJFn7jI2lhgGzxuIbA6QyRiZL28oZdb+aVRhneU+zRa63XQ4C/zYyoYsW3t0KWgT9VzlYwk4gQrsl2Cyc2sdNHFH3fNgJGpujvkA6VE+5WZJ/+CmVVV2Wf37mGkCQuF8kUZeiMh9C6OCU1OBaeklUe64mYEgZ1a9u5PhpbV3GW8Kw0o8T6dO2eI78ANikuX/AlTwWxmkEwxElnnuKqSe8PyN7T6cNAxB1ythbg+7f/fM
  template:
    metadata:
      name: bucket-user-creds
      namespace: gitlab
