---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-connection
  namespace: gitlab
spec:
  encryptedData:
    connection: AgADjgI3HH7KkLcECz9OHqjIegGDWrveL2RrneR7cOSqR6V12rX1E7p05fljbr7CyF3OK80R5MChO+3f10Dui3597Qo9qsBES3ERrFViOr/fFKWbi6XYgLlULZ+XdahMEzVtEmvHzLA35ch4YIlhAcFKit/SzpQcFF/DSu2tMIsO5YIQo6HCcrSxOSh9cdsAkbSFc2eBOCJsCJkqZoXCMjDWJwLjhNAY9eDSxrGEplIqBomo/SRmUdeEU72XFT/4PRDQh2Pj1UUknn8oKP0ayjOSR9IcmOBAxNgHiIWubYX2bzWN+kgfb18B5Gxtqs1A6fQL45qdr76r5NT/a9udhZEgOuH+6DwwtpC4ADmBjZXAcLb6o7kH8Og/sOkk8sroHNKKskuje1dTMyLDcO1dG8EYJqHPwb6RgydAGtp+qx9TQzn7r4JyLicTfL/XL1YrmDusb3rHjRSwxZoDiAtBkvxBEontqUVOzBgRY7G1Wqs3cszjHcWDPwyrQZlLBST14xXa+zNCapX6FH6hXmjf8CLVcMElzlWVspn6F1GE9RyNo3l0plgamlMe0iR+XTflaXCjBNKxJMsh/sAYxlxdt6dlaSXYl+Fvl+//2u7WwZzH9P4qVm4QSXrjRS3kAkd1iHx5JJzo57YwuYVDbjDrEsZmzw9WmYyFtGcDYcY+FdF3r69nSdZKY5uC1LcyqmhxX2v7C+R3Gi0AVvoD60Ecp7cDgnS5thBaQOmt1rgU8oUCMOicv7mKQPPTjhGAgjG40vy9m4KTKz0ctsIWdBR8q5czVsQuybL9fmhASwRCG2bcRZ7CxbwTnqc5BMeLFg32NmZtVr9ker2W/kOonLjS+qUbzW/RNRappaLj87gVCzDDOVNEYuIw1OUQnejc8a/qM3eFGWajVj+cvApNAe1yGVSt3UIt8BRqFuEt0rDNloD1jvBiVLFcMz4EcPeSKn54Vb5L5MUPNQrqGKl0S1vlekfttmuAh1bAK/KL5XyGnX3V3+5etuXt5PUEbPPJOLsmu9DSgMw9wa0hOO5rUC04tsUzDyE2RXAX/O57v2Zz7kzm
  template:
    metadata:
      name: gitlab-registry-connection
      namespace: gitlab
    type: Opaque
