---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-connection
  namespace: gitlab
spec:
  encryptedData:
    connection: AgB/1Ta72glZt5g80Qb+jsbzYUDxJJqaBs6p8as8eDQjK02J84wu9xpsQIOQhDyQ3RXXuSuByjemH0u+kIklE9v4zHyxuPgaq2BimBbkmDs5JljHfRxBXPymGqL2Jn6ftd+tEHesgr+d4GGC7gN0A0FKdsdDzZ+MMpYjWRuvFxNb53WbPEIium7dV5IwautUp29iYdZYEAkFaoHkeq41EFdbknt8phOuYhwHPan72vxkPBYDewQJTu2AhNYDAEc8rEMjs19l+AImctyt1400N0ge0L+vBta08itnHP1VXvsHvE03OBWhasEzoXLcLwfnUWOr2AGjIi1tFSVTyhyy+CIg3d5Lo0ZR0uK5SIJA8j8kTTgAMujhhsKiteDOWQxB2ro21rm7k3w1QaRyuFFdFMK1IS+oiQyddms4xdpRPVS63pJrGweM3RAxnc7mo5195umQnMk6EmLLFVMDa2a7Dz0HZPiSd+PoRozDKD+kA0OO8quW1SjKHXBAnrwTkf2g68i1MMaBEm5SFw2+ynmbE8dryjq/8Im7Xt5pgOXImao+1KSi3NPx2o8GXGstAQw5sAKzq1ELXalu4cRn4vYNYF97enWFZq+HWKXwU6ZS7OvNxHDMvdS1N6mG0tQtFPYXjo4rnKdRWHa/yea7pIktQJHyVaiWrx+GRAMrQiumN9E1cw56ljfQIu7/2Fc5U9uh3kBk/NAehSnILVjRY7z4bwCJ7a0TgXIFyCGYvD8yfOvKk5vtjddFN5J5j+TZtbwD5cIOMhiHBSIdvLu+qzX85TQbO3TiwzwYbcD8L29kWKBbUq4gZ6GblAXhJG7OE8mKFulJSuFmsR1efNQnsZOr9gmg2cskrUEjVFM10FFnN9hD15dzTwmkyzLDnJ5iDBl9gvypcs9dgcj3mN8xvXXu4zlP/NkAvdxwMNUzPBLRye04UL88icRXTFh1UOQQmaE3OIPb35YMWlYH6+s/jz6QQvrIjWuvqC1EDptbQafDQPZ9pVvPhE+4cGxNwvR9JB4ioDIducBLXBoQpdbVXRNQuNIF8suMFO/+k/anyDFsjc2R
  template:
    metadata:
      name: gitlab-registry-connection
      namespace: gitlab
    type: Opaque
