---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-connection
  namespace: gitlab
spec:
  encryptedData:
    connection: AgAyiCICRnVZNuyfiWuU4IOolf0nLN7yfU72F4b5gj0PFw9e0/S7GZ7SoX++/suTRaQ6Ekp0dzGrT9XgsxfLwuBe7pFqMzG7K+ry8OAy30jP9F3GuyQYVCULDucDQoy86867Nl01yhU2oRfGxLvk+goGu0xXP8i2exPAJWTLdw6s+68/HWHiFobk2gzi/9cYkFnVQoNE036hYCwbGWqiqUmr1fdkTTo1wh4Ab1fJjTk+L1I+mlTOudVSNN0onBNb1eYKPT0CVUEYJVZ+OEdqxs1CPMCouVj+RYMWQdYtMwarytc5FVgw27VaVDCg8w0gBeT9ulhCJZQw7l6rskQlwaVcWhnS+A4TKwC6kDJgNx+CZSVdoeugsqXIlWEcsmnKI6R6tQ5e4/VMzUSmlb51nKeJ5m6cxVdFr30MXEQ5jSAtHW2TlUlBvjpu+zDwmvxs+90JTqind+WhIIY6he7wvgyeaapn6GcF8+UJYNJAC8GmNdpTfbIpCF7O175Z+N4lmLGTwYBxNl7zudihXRNqGKxWQmST3k9UYW1TnHrEbcodLznVVqrWD96Cnd/i9MFQ9RbfkGvJTlOpsd5mvkvNgNWvaq+BLCLa2kf01IPr6YnWmusHOd5e4Pvrze8XkUemERyhenjKaodcUL+pA8zNI2NCzSD6RtWjKlkvFi117IYQ7ruYL5SXpN7KGu+f9bJNIgK72wTa5bVjMNIYmjyfK+HcmACy03fngK8HXl+nXSx8RoSQnVe7las8fK8e9DSa1kKiL49Eyujy/Okb05KSq4DAjEjFKJ9SNvKBvQwwHnuOlkXQ3gZtK3sJmfwGAnXKCsRmzy7M7aFg6P2b1LQQfIvTq9UjC4gJr7B1RBvhDF/ZL0XKTMZ1UCN6ECurr9gjjieJu7e3tqzQjnJfSxDRdBHEoTP+MQEdPLypzpU3xv/sREsP4Oj2WedGXESmihDqZi+S3cVGim6baPoK74Lz6O7+Wxa4n+jfD1CNuLdDUU3749Fbw/1K4VvfeCAPVzBS
  template:
    metadata:
      name: gitlab-connection
      namespace: gitlab
