---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-valkey-password
  namespace: gitlab
spec:
  encryptedData:
    default: AgAQwtsOaVHc1BO1eeVsZVLGv1WHIrQSp0p3ESFX+qG7OeFPZGljIwAvtTQ6PCM+z/wZrx0FlVkS0ffn7e9P8WTAxn6G3lCrQeuP7jI5M/t33pANXNyVaz9ZJyqZPw2XaeS6/Qs3lbCfWiLxK6YhkQO3GmWyC/vh0/mV5x/OVA+onZcASXZhTVe/iTMqR+eXecD9VrskdDtLg5sS23sgFzczApxQtmINIMj9RGgpJC6pzkjHPnFk2tZCXaS+/TqGxKaSvOvFsL5pUc+RWLYznCs7jcqAYGLMacHbdJaf7tHmc18tynM02mvIE/RwGnOBfZV+GbooYyGjXPg2xu/JA8no6FW5TnI1vb7c3UE9a03I2ozTdL1Fhy+mkzDIccPNTLR33LR9rqbzXNL0JxIUtjrdyvDIl8Eqz5Fwo3mVZOQ5NREdAWS5xzwtmTw/1gtjqJMX5JRI0Ik4nIkZYSGBueqJdhkJVs777T1wKFmm7srUbBWKrYH6zbds97+KUs9Iu8jNXdHlhd/pHy6Qlrp18W5S0kLn+UHfOa+pkeiTdQWF9nIowOAJDned17hYy6aAEmILGHFgceZY1k2xprgVau3N5V1E6Pj9kya4XHYRmCgLzInbzuI9p5IcbIGhHZi7eNdbY/10bDa+vXOolLk2xUDO7XBfTXT/W0sVmbw2wxFIDgstnSfpej8HixxR4YzkMG9QK64vKgZBmGLEDu4b4TWTP08WJe2uuENX/zJI9q+XMshkA1oD9/Adw8dQ
  template:
    metadata:
      name: gitlab-valkey-password
      namespace: gitlab
    type: stringData
