---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-connection
  namespace: gitlab
spec:
  encryptedData:
    connection: AgAN24nL23StoUHzQZSpDgzmLjTiRwdw1KQ/t3CnvpRARfkJCNkeBmZf6gku+tKZ+9D/PO+Z9Rb0Zhmyna5ZUsK6GaB2OeeJiUwSne4yRidSkYckeQib0iFa2nbnc5GrwFc95gfS3Tp/CWDSR9wklGMBb6nE4W8tLK5uTEeKC3ri6wlLM2TOcfSDQxFFc+nFq0tJBSkcka+vPk8w4u9lfk+mQCQ2hVGxiGLBREl3oD4iA7W/271l7l+N5DInA3SNEb9MD60BbkNd2kBE0IdQWIhV8T0NeOQsbkyPAqjTSb8+6V8Ygj/IHwwdtazHPG3KtogrOPqPYiFMaq5Tir6cPcwT+WbjhlDWd9kYcSfJfRdaCGy/zzA5ijkGLouCVg5yc+5Tt1bAmrLqwucOHM53FvI/Ewtu4ppm4HvpJ2PZfbo7zZCxF8TCc+vXAXXBe+Xtsz3VQ1SAGKKO36R87Yh6+EMHznEIe49j44W7w4A5HzIniT4hmfmK70SaurN3x6vZMV31jvT6nbdZHcBaKjReKUiNMiO+i6cH+lkhKJEo3K3OVTlae+G7UOo2dhyzn9wv91aR890rI70lgzCFh9Hj2P8+3wJR5jKnUmUoSzgXMgEeNETGzORlkLmCKYH40dsKkoa+jgmSOJmTqeGTM52bD0BfclGA6K7qtyu8/J50XnWYptOXeAh4Ga306DTKZb4F4/gguphMSfTOv/jYbycwRMQtqphY8rPTBJNlRAxVGXXFIWXTChs3R32HXfWvKnOwv5i3OFYURbQOOlfDaVsOLFzfFTiY59pKzj/Nw4MW/frk1sdoFWDQ0mk5L0bHugQXbDiU5gAA7lt6vmPdCjs4xYob3oEyuTKPqdqcjHXnAtwnTQ/a24FtGvxcjUCcSHr5t+RG0XIKP0VwpzgYMCPmLbAUyI4cf4wMSQAjVeIimzFpd0J4M8ZAiQ+uKxrLlWXykxBfEieDlC8vkbAuO6+lEnjDy5wNMj9r0Ttu3VAIOCjt+uWhBx4Yn+HILuTMy1iz
  template:
    metadata:
      name: gitlab-connection
      namespace: gitlab
