---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-valkey-password
  namespace: gitlab
spec:
  encryptedData:
    default: AgDDcIIqg5Swj6vAzAuzaxgiKL6JVTC4hGOJuDq5Uw8bzIfad4QvQVYg9ZheuGSuLhA2jwhr74XQUF7kP1FiAE79cCpP36R1FNQyV4xFhC5eCx80pfZeJ9Ei9HRukE0rnrY/E5jxsM66y6Meb/YTu/L/8b14IPlhWllK98lZ92fr43WoS2kWqG4WGdrfqrrZbB2AYtlrdRq6bnGmruWXQB94y38zCuXTm6FCAGCuL7iSVQUg67ENF3pT/UzCIU1LNQj+bt3dLVmWjRsFchlHPSzQNNXbZleO/HGhs1UbueLyW6lvdf5nPr6ulVSeLopfstRB2cVPm8JVZQo3DCiUFcrN1jLlhe5YpW1KghJwUXwve8cM732U8/T/rvPptWIfxZDEn0E+dDR8n+3pui29k0b85ga+7IMsPWRT017B/l2InQUuE3GZzMHqg4mrVWBT4MlxjYvihiPCh+W6kelkdvg1JsF+5n+E99dkqpv6+BxnMTEpUgeDbwTcMnVkg5PRpphXfkVcKtFTw92nEtyc8rBzNDt2GH3Vw87uhCaPhwOhKLu5L1i6Gn77rCQjfqoUW/pcCKzktlIfLRpkcDGRdV6n10pEI055ovPKoD1U86vY0Adr8WYTF0foOEgucS0hCqkpO/OeeaKolBeoxJWS9N2I1iGwV50UUfvrqis/+pTIfmidPJqUANOdsRY0QNgDVhuZwC2SGKq6Njus6Fq51QIkgfMYR9II1fsZEhU08xUKo8f7xe3fMAAf3UFu
  template:
    metadata:
      name: gitlab-valkey-password
      namespace: gitlab
    type: stringData
