---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bucket-user-creds
  namespace: gitlab
spec:
  encryptedData:
    accesskey: AgDhlvhiLfy0ihfk2bf43XqCbXuWhbe9Q/RJdQ7gRHkTqrfYKRyJTllRWaVKgNfcvYZwqnVgXwR5OR3Mn9pTCswsTpglWQmKM4vZW++Ivk2SKkEO3+doHhhNl00fJh77oasLONcDESKTzFH+ttSp1ijiIoGs1d9zxkfHzeg46mUfwoMlqUPvRV0yBrpFVWbMITYBs85pCSZ5UsBjgtMyeUnZA0fFDkkEXt0DRPSuh/z6aHbsZ1Us+VDtxJUACR++SIGSwf9AHgen98ALtdcfN1y3hwV+rsTC+x8H/zyHMw5ffKEksA49Prtf2xspF9ZtTkz8m+UO4W8UQZgYFd25eUFwXODrqnSRpmsnrLqI4S365VGbsfAO5Et8tBYRyNteJEpKfzRkRbBjZ7G+t/PMnVWaACAl98/3G1pk2HBE9iGusv30ENYbTAmntAhKz0vHfUQX4lhw8d8l+5oQ1bS7E/lIWuN2z5upGmuvSX0y8JxtSM/nkywjqJc08wMqexjuexLaUQMchhCtkcoT6X8SoWGvJpfFrYqcrAsZQbhLimguyHFSVj84Gyyst3Hw7OxJKFvrmdaeESSxEBEyB/cVt8dL8EFFOHBtGcBhmplMOEbULaXfSGP6Os7nHenyvA53L2X/g+ESXXqunmklrVq2kCrFj2aY5q0bawAj2H8PvJwZUNCjAM/mGiEZtCBP5FPWrSkP4IUBO5UGMr2sxHxi+zS8IjGzqQ==
    secretkey: AgDIFvwUOEgmgnxVVXe5e8ICGITFqs9CJPdXFXV5da7KZkffyX9HXQlx9LwnLRtPLYY78qgEnjMxfiZaEWraC4TNWi8b7bNmwCBxSGWUuQEJb4zWQ6wwcfsTehtPYyPXuirnvUvjMvmNdQQIDQDXCGL6JD+OTLzIwsE/SJur+Qu1UGY5chN5u4LX+ASgxDbC8pDFA2wskcAoa6xYo08+KSHeOiJZzS9OjSJ/R/DGfNouDFvWgmlVZCMcEQk1dIJnZPhItucS3UyWMB1ibQ6RQBZ1aINhPzcuaPdoO6/gheU6OFixjHY7mkgpRSRdOUJ8HIaK7H0yjrChz78MsIZOrOpBbbduygAh/geCDjZ7Jy4+vW+kEjVICxopmRGH6JyUb6IXy9DIiCJvrVOpflyEvCyn4e+wReF45VvRcLkNR0bQdX0uJbemG1MvqvydvLvMLbUAxU7DY2t/Y3yUuu7LPwwKx0iGLQTaP8Bsan+PF71wFc3j+YDTJvVfeSUysCkytpL9P4ihdWa+cK6TzKPtG7ZPR5vTdaMYwuix74BiVBLVUAsRX9XywstE56as+5/KYZv2xprJKxnT9YuGLjINTb8POHNF3GcbkJQScdwfKbaevsLPhKdBuRfddRlySN44Y+di6s1PuCHRvox8YuUovMhTR4TNVczPYWA7gekZWH4jcX+dunyaGwqmVSD2/JEOzqihhpdaUKGj6P4zDmHKoai+miuvBZ3Ir/OlhQsc5Z8CiocV/PaazUdM
  template:
    metadata:
      name: bucket-user-creds
      namespace: gitlab
