---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-keycloak-client
  namespace: gitlab
spec:
  encryptedData:
    client-id: AgAt8h8gs5glGS4xIuh1UNM/QcSsBqXBp3502lcT6MabR1xOdiyM+12iyS16xESRlXZekzPNbl0TUaV8KHn3ZcNCMHjoJncbvOdmd/2d9QefTLGB5t/Ap7QnGN9e0gUv2a0u1tN/zb0zd5ZYMhn2qxB7Uig2GWtb2IBcsSAdaz7kK9r9jt2bVp+J1kpqYeY3xzL6TsCWkouZCWlJx2kmP1+K1v+u/jg2igLW/FQ1bu1fyeRZQlowUbQRX0vZCJoHFrBj4AGJohQktICA0x7xDAS7zRsbbEUdHoOu/ZkLrNcy9JX1cZIvyaOYuZOFkhH2ju3hEqq3uPcK3j/fiy+qOt7GBcaW8hThK8jY1ujzQ5nG636XR/AsEerOmEiDISQkSlWO166mIP7AebO4uX/zwjPLiV5RkmkZJ7Tq7hJZPAAuo4pRab1sSS12AAj0IMlwoXnYvHTOtWvZoIHyqHTEGExkXpAYaGhrc9VFADQjDoo+yGlU+QyHwDV+U63ix7GoppZPm++HvKvSdyB5lRQFZm6nIIegEG3Z9f6IH9s01FFaD1UrLnrxJagPJBVTHirdr/hfS1chyCPusn+f4PWl2C5Aboj0SOIlcbhKSkiVMOyEtO2pjbe+kP+QmSAU/dju2/WYOZJWeJoJhemTd5YpTgIoGfSp14TB2YeSgKQRfbTGgVLQzEnXhQdrwe3YNjCBy9UfAXj5rns=
    client-secret: AgAL7ldY5NOu+m3G0KaMYShE1LdEqw26nAesOX2Q/+3hGa1A2D64WwVuIf7qN/pACwg+N7g28dW7J/yQVRfmtJqorO7nVV03l6GscEws3L4nPb9tIhOY1LVg4+5c0qPoYHk9k3iln2qgnA4W2gmMxIQZOh5N07RWEmJ48fHgtzCks37nEElcxgIYM8cXv21KU9iU4dd8bqbkBBir95yx2OL8KCma8QgRbizYMIP4uKCkLjSZYMK/wS6baZEiqdHY8AtnQsCr2hzZcmK4c+gc2gdJgv8qv5eDUS0dixANq2xOiL8avAw0VZLNw+GNsXoaVeUax7/MS9yvSlj7jh4ssC/rkJaAIPpQ8pkTNaL0CMW5nCOL7VUhmHbcxbEv7wo1NTGQSudvrEJ81rgzblS6e3rcgLjXsMEiXGIa2LINy1++nzt5CnIruPkSeDfwF8nqJJ9Zu7MVLt7bQLDiCgLVRflRV9wfZbfmh8LgSPHWNi63xSFLwoPhiGNYrc4hPfujqS9tSIn0wX+HQWq/zeai1k1nAT0hHBsCVu+Bs6J61+vLiL16NT6MV5Ir1MzBfFmOv5wlYuk0BZa3LZfYhWuaTBSH2l1QxZn6rqkvqUSW0fHRkuYwzwAlUhv3T8Fx/2+HiTDNBM6rkcuCmtQJKTgEZlzseXwQgqAjVTiCvdJmb7jxi8nbfw+Lsoa6warw9XU+4jEFyMpNXY2YfwA3XQ+JZW3lO6C8aasPwvTae34FSC1WPw==
  template:
    metadata:
      name: gitlab-keycloak-client
      namespace: gitlab
    type: stringData
