---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-valkey-password
  namespace: gitlab
spec:
  encryptedData:
    default: AgACLNCcjOaC2evpvV9ZyRnx1RF3HCjB9q5Sl7UXrckXrJPix3UlQUpfkC/1LJ3MvpXeTTw8aJmyKhcoYtyg0ACorR8VomI22by+8++rSMKa2Lq3Jl4rZQC08XzPm78k6kg6GmGF0XrQEdwldNAkOVf2Spvbo3zOJVP0Zs8H9s3PluAXM86VaJM2cv12qKU3eQ5tcGlDm0Z5Rkl2qv7eTgf3lZ7mrUZmKvVJelcXdT6ka8i08E2UG2nbGv0buPAW1ODg7yXjV+OvpbDOVhPfUao7cg2ZOhwHEN0C0RFpxfRRebyBL5VDEBZ7yvM3p+gvkeV5+eooll5BVRM2iF89wTiPsl0dfdduG5nvRDCzENUnRTUHn98vF35mTavuLsMxsA5nuSoCDVbl0/5087W5Uo0GTvLXij84VnyiH6LPzbvLAtWuasx760SSdtfOiS6znRwt0noOuiZ0itYb4TAv/la9GqFVFrFxNVjF596/OkdPzTQKVocZv4Yxz4ACnRu0asBcWoSzpnkwCI0nzPXmKuilgR3/uVR2OqC7Zn2HKvCjYcdziq7c5aLSZqwdFr5p6GnOpG3yP/KzpTUu0WzQm0/FjENsFtPyHgeehMuXpm69aNQeUJlpNB0nqpNogso+VVp6ed2qMov2C72m+iDONxZEc99ltCRspN9BWemejrtB++UPpMMR/8FKPJ3siuANVZOtEZN9lFFxfXR4pPdBahNSVt0hbJ0wUr06KzPn/IyHxMHXK3DErmzH9IRV
  template:
    metadata:
      name: gitlab-valkey-password
      namespace: gitlab
    type: stringData
