---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-keycloak-client
  namespace: gitlab
spec:
  encryptedData:
    client-id: AgCe1dRYzxHjfcrZ4zA+4ONACGQ97MejU79xst6+KBoYBZ04OzV4BynSCtIJPRul9HPqrvLA3tV5VtWGyhEiU1iWr3D8JvOnUEP0rgGhu7JuDHBORu80Jtt2qJ4amRfCUohZw2cTX2pEGs9nQ0/EO386E/5yz2tuqMfzxXSjUT6prCZu8JmBh0ScAuE/WSUE1sBOu1H6Gw+Wpv7l4aUgwiQecRlyLsfR+bIzY2w9zQjtiaxxLDBO4pQEYTrEueZ6iJEGyAifcUIlpgYg4L2PHdg6Gj+AHgYgd2j11NubFH7DNqe8Q9mvUp/SsvOfIBRu2NyDB0zn9wTWle/1mfvF8ERnlIK2dbzsDJ66H5OWUyV0B2LolF0U0SCCLKM3McwUWTphPyIwavXy/zJdwWKV9buUjnR8/AWMcQGB4EqDMGFdL2Y8r5Xo84sAJ49UX75M//v9UElrdNDXvypjqUqZcDWEtLOB8lSb3RL/mI+qTlcCxMmOqgO+9mU3x0I/J74e/dgq0Sysmxh+8ZW2XLo6frI/MbRQT442Cibukt1XG0Fc7B5GgJkNFSH/KUuX/kbMndqo9LRDko9cW35FYXpoM1W6mjmRkEdyoUYLtNYpJV1c5yo+AsgFDJUmjjzVBR0i7VXBmv69vAEb52Bdd8xMrcqWnY7rEk8I07osMGXHK3lSheFLEThet4E387FjpG2DXjj2bgBU4yU=
    client-secret: AgAd0Sbr72fOX+sUzX5GlqmVrXC7LCKIMNNPcvq5Y2fLPlF5ps4O2UWNBU0TfQINEmykk/ZxJmtpyiLpuJZV68FiT1dvpzvuizhwA1JecndjE2l65Gw/vyD8AAHKsm1rwMAlSufxVGKL/Tj/6TrHDlgTSKTUOmULbjgZQXFMHIZe9jM7heWZH1/ZgaMwfyo7dqAN9+k99UFIvdB2CWlRztHCL+lPl/2oLLuG9XeuAcrK9HzD7HgpLeFnEylhInFHlOFrDmWUogw/X0H9s8x6vd7S8CEZq9ceLZjGWffYh0jLcO2lbWF01Oyd1zilw1gb0xCk3D9iSgjb9cHvaiPjVhaDVWkmmH9yuM0h3UDPaJ0V040u/78hF7/FqIPWWVHTlM3/BLZPeTEIwqQks8PedOFpWPDDFmzl8hGN6ira/eutHq/Wvfhw+yAK5pILgKvTvR+LcjTpvDQOZemncgq5+ozJasZZeW7Z0k6RbkDg19KbQMLtz6rBHPbWDXBOw8axpCG4UWhIO92It0islYSmszE8q/qKEUQaWy/KV4eLpN/CXGDuS3GsrJHC8PoKmP7PwP4Xm+HaTPeyCjG/9tZvEGD6LZhOu0yopbW8mQDQMRM+iWewa2VlZvVQeYMuEltsAFucjKsFRwzPPoFVfYSoOW+Si0X3wnMp+hdDrBOWDm9c/4EDIKLjLUhQsEs1DSTLdBFkYJb+dOLJYqcapuClXK0G8z6F+glxwgtcE85aZR34wg==
  template:
    metadata:
      name: gitlab-keycloak-client
      namespace: gitlab
    type: stringData
