---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-keycloak-client
  namespace: gitlab
spec:
  encryptedData:
    client-id: AgC2htMk75z5y6F+lf9L6tZSZqCekXb3+fgZAc+hVk/5M7sjj7pohU7TxXG1o5NbhGNf5ThqHFvAy7HdFBD0NX3ESDFOXtE/+Je/88Do6bKpNgL9kUf/gAQE6SQnwCp01m9MgsQCc/Fm9gQJ9RnxQGtAfk6Qo5Hr35vRyxQcGX7jpeaeaAW2hnX8Ezrf0G+0tzehTjlPeROn/lUJaUR+Qr8nptpx8tRrLDLT/il8OdhIGUkB9ALe7QFcWEZEx0mFUP9MIGV/Nbal6KYB4YhlfIImHk/BnG/JXxQY9QdlSTiWvRbWEWxv6LbNh8gUPVUwjDKEjBKeoHVnF7POlb5qN1m67DYPzpbmDI/gP51F8V/th0sVQHJNZWJzdjvMuGWq4t0ycYO4cthmww4VYbFkxrz1rcIBLTOrkyO4xZg92tTJNNRb4vfCygGhCjtMNQUWQNEBClGyIYkAYTTf1avUwOt2087zm2CI3qTvxKhRQTC8c3ceDmPVWhYCb+fxBqXeskknKBsDLBQydGISM5rVcofD+Eme2rub7t1/Ny1dePxyDX9do5Y5DLhpO1mxDYrfCl3eIQ/bRx/tqvrft/bzoM5lBnNiKQo5IeokbPnidmNd5oDeIX4cI2c2oOfhIzETEHItK+lxW/yiDS0vLOpLEEf1OB3oGcwgQzmLtYFkSEIKGYQy05le+HgFjtA9mFXnrkRk98ZfoMk=
    client-secret: AgBxvkPcEOPj/WILjrFDZqW4lo2lPnhgibN7gJHc49qwSAkX/lcS8sye8oWkNodjnhY9p8pNk6X3gvQlsTiTVqRqN4WoX6EO+VR/0TG6Uw7IgP54/GbDajM3QFW9/uM/GBrH07Efdv6yE2ldT4bqu3Tl3UeIdOuylXAqxmv0eaiP8xLq85W7n4GvuxA7S4ycSL8L1G8nShzwFms6xUu8pN2t89pmqJDbwQUiliEf8lgp3Fq/unIbXDHHoXNu2rHRtpUpJqAv/tXheWL1/Onv2bn/sam2DJMbvPKo6h2qRnGT47K5+KEqVkNtQ2hWgRP7t6cxrp3AQ07Ty5DEHTV7Z6SSmyEkGqcIyAPrXs7vFJkMfu1muXjn1BdPakuTYi4f5BqOAz6w0kl19CuwNZZ+nmvVzItRQIQJXPCmXfe9sI5t7t016f46aEgKPGwfNJdSRfQewPc0mRDQGyF+HohJ9TGP4EZM3lPcBsGp52wKPH+cWcyS1q0iiPz8DQGdrM+rd0nRh/3NkkLuAAuaQqRCqul6/P5YDJcWO57yXMnz1OJvVV7Qqnn/GovAbYFhNT3fhcwERBWL7ehaktyj4RSlqKOO7Zv2450+eqr4/6eT/0LKZ3jt0Ty/lr67AQyysPPydqeFIHWXeAT4q0VmWOuaSCalBLW2zRmh2nyOg11I2hhhjeXf+3T/8xr4yhYp6ofFfZ3Gj8+2G2Ep/WHNQTRYYgtR1UVfwKEjjgMvNds5sxIP3Q==
  template:
    metadata:
      name: gitlab-keycloak-client
      namespace: gitlab
    type: stringData
