---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-connection
  namespace: gitlab
spec:
  encryptedData:
    connection: AgCMXiM0a2MJxpYre73oduLxPIsp7Ybwm+0r2+mTbEFslbydeM7Bvw/PGveHVgUxtGpfuRDqi/um7oDRMpDw9dZqhE4iNUGF60wIB+w47XacgyTi8NbBQC8KU0SR3ObYqHGxWd5Bow6dw3DZCfhcM8ZNm4nURs98nrsvZGJEumLUMIAX+4MbbThSnVfcgEoXeuzy+XUkS4PgIODcplw9FKKkCSKSbqV2TTV2Dg1jROFfGoWMAcwS6EW+CTXxpjnVaFoC1fnapwkiza+Dnnw8czi6dr6XL0gJGVBa77S/AUOtMyq/wweG+nWvm1hm0ZQlNP5jXBbU26ApXschZyDniRaeHkOe6r1RvLzVI23OEyVp2G42fXM5XMcDBB1WnTghjuop/faz9Le22ohOCDzh4Q6or3nTxaKuK81IAffL0I7EjybJPpRmCyFU4pdSr9HoSy/ESt2Khyq971X4L2uuchqoqi9Q4vMOrWXzFl3fKm7P5EVK2exUg6t9dj3bOFO1iIFeSV5obBBDegnsanHgt8UuOH74zT/lQ0lw+nfCTquvw5gzAk30R/hAvHuBUitMnJrw6L5D1rCLdurmnpzE27QDS2yzwkA7h3NtQBjAK+hYE3QTcnv12Jjlc6FEEO3CkH2ydAYYm2rkiBeaweKtYcCJnkxpajg8IZY8DOwmzu+o/dvxLnwKDeAbHZRefEQV96Rgj/ND9ykhH0zpj8tFEewM4nH1UzsgqQiCuQzn9caNDzaaKuFyudM1YaQM/kcSbL4PKL1T5lLaIcVtL8Qix9B4YG1uB5hNRYfYPqMxkKvHVeYKDYcqEhA8crKxESCbscHEhgyaF54Q4wdq3Xkxq0qziWEJImxxPT1+BaORxjy28DrYsTLZsRL52PjK6/NSDFl1fvJ605yzWA3kmZXlCea6YgrTxR/vuyMTjwCexWVanSSRSmuHin7Ibc4gp4Gl8Y2X33wCaznVcRGShHo1TayfkkB6N9OMNxZgGtQT/EYfRrW9T7toL9UtObEAxyRq
  template:
    metadata:
      name: gitlab-connection
      namespace: gitlab
