---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-connection
  namespace: gitlab
spec:
  encryptedData:
    connection: AgAuIDRiJ/bs5k+NbTVNnZHeLu8O/cAIQvMksWevhUMpf2n27oVIoWghcKrkNg8ITLo1UsAyZvnavznLyO+NOz8OAtD++GA9xuRiAeHg0TqfvWjehz0HnF5k3bb+JmJ4DYLlkHp/V9llPGpPIOthgClcrKBeaZRTDL6tDb3rWSk936/Lg5aV2dHB+q7wgPUlB7u8oE245fWVrbvAuVGrG00RFD2StrFtwuw/h8GIcaRsuSUctgJ74I3kHnFU178wCSjM2MzILizP+2bOr4cC39hFZArVjFlFqmGGIX+Z+88ukxZujInR19P4Fnw/+lwOD3cwXvKERoyOYiGPEAubXdMrKGcEaBM3cj6e7ktsmVMqkOAyHLe6U1/+owibWAge+RSmnNAQv4nWVDclXcm3Nokv/F9/hMk3ZULl+aXxZoUVCfqerlxM0KfSERnGHHxNRnYBBINQEsGEZfY5J75iqMNsJ1c3vB/ZVpFLfBxw0F3aZPvjVsbM4/PIQvV+fi2eJJtSyMcJvuKl8pwMgWuECBcOTDp2LyCBrn3m5i1MDR707WDbKdGDcQtAVE5tESo7c+1otH/fjVTVzjr/vIe8DQ2fy5aUpWQSGTuR7UijHedRRRkL1j2w7p4G1qvBI/x76DC/3CM7KzgkdQFanLEzPLP2JvYj+8c9HQ9+kUOcKTTYXlkaLTAgBLGFLaJgCOBRbJImHUWZjbGqWOsTCyBFu7HaD+nqk1cQ+/C/fPawaGDRVWB9xVpdIRSQijV3b/W/pqMASaEJgJIWg1RV12CeiIKpYTcuPOTE/tS1y4vAx0h9eNL2lfbW1xQOoRid58poWSU+wuccCBQVwdhmrj5pfc8gHB+lOzYsWC8TGBBozjLeCZ9oX9UwBGDVaXCVW8s/nGu2ju3g5xn7HE24Zq+GY78Ktrj+FrkfSs0nFHPJe6n3DjjiYMUVOjysuS3IuTF9+b/0IVPelf10Xa9QY2PSI0SHUt6l8O/oUrDORI9/U3EBWR99WzGuAQgPq3ua2KeSo2/S2uf/KPSvmIm+KOeXBAJPtM2ec41+oYcMor7lvoRH
  template:
    metadata:
      name: gitlab-registry-connection
      namespace: gitlab
    type: Opaque
