---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bucket-user-creds
  namespace: gitlab
spec:
  encryptedData:
    accesskey: AgBpOvag6qsNHQFE/yNozGDRiDMVCPs0PyzgTTEiTMO9dRqQec11I7+QEZSY8yG/6MZ0kCjBmFBcNxLzEGJ4WeQSw6Y+cjjSJinHNArg3A3cXd5wYrgmp2hCes6+GLdcy+JQvHnSfdHS/VWeZwUB4xw+CSvIBqKPlpNfPpdaoCTHZAIB/qY6jHMmm1SpGN4my05HOOScX0jtJQ+CeL39Xh1PEDJXnAnYfmlwVIupO5w3wapZvzdkSPinietuzRYLNgiJl1pdJiZlXh7SJu9CoMft6Az7ET5NYmmb6fkUJTzQmbqeXCuj6EDckyF5c3eAyE8XFCs3PD50FvTC2GzKZN4C/Xit8aKFe/0XroQNc6MG2rlig0U42iXN4C39INCL8JIgm+ptGpQYPVFqcDU/To37Rsdx+JuN/KYvY3TNZ2Gx58FkcHWRTYf9uzmnvFeyxbr0L4qtZKJ7ZuJ+opzbTtW24r4BB2C8VAyyntSLnLLPk4TDLtVcZd7utS6ZRw19KtGo9DkDv9+Tpy79VDX7tgmTaRFIiAuZnzCgfIBM1fyRBcu2j5QWjE0B9uPp0mFJX0On5vSXL8TyDf/CJTVsXU0upm2S0mdBFMY36tTHmBsVZf7W9DD0Tj8JD+DSTyvCV+tbNy4kDHtd9qwnu/nJFBRPusqAQZmZNN9fCXiqjRcXzcTo4W68IVEQ/Kqea3/P+uHqhD6Lpy2rKFEi/zB6xUFrwhPnKw==
    secretkey: AgAeA3irXWhmY1KjDia7OwphgAS+PuOo1SWpaf13f0evjVhVMql4HfqOnp4Wky/PgGBz/hP9T4Vzh0Mc8AK9PhK/w57EyegWfnxpsg1aZHGj1qgIe7YuZv4/QZ2jFOMIlAC3uLEPyUkoa/YFe4VxrPhEpXm7NOEyAd4w19BFVqdGKPoiFk55EjBsjb+nXJDTrJqRGdjtbuT/bkgsPe1T5pXfCUD+8mV9QN3sQmTLdSBuLpLJPhheLkWywV96y1Xpwti4mxhLil4Fhj/UtPdDh/n9pv8SyQq7R9EXU5nWx8opm4aN0oe653XmfvVrRskXtYA+wBr00lArZWnsgEConP7PqTl1dwnSs3UvbEHRo1n8l82XIiveninl7MWNkqFPFNnjVbPbSsPaTxk6mzClmEwGeIHZuCezYR/HrDxXiMcRwRRGjCFfid4aXO6sFWbkwy5fpZILalndWKP5yHNpxCJZ1KcaQ9N94W8CLONV3brJHFPQV/1xsl8GeipnS6S5FTBr/KNEZoIeORwzoCOIQpfxSy5u++GRObuyTTdwGw7uqA8ylCl75jUsPjVx+I4MDPqdxTlciFB63oG9wCyrAiO3vwULdasG1sRP7rOL2gSR1SD+mMbRBvh0IzXz/7Iqe69mC5nQxELUNb3EO4oz4fFDFQ2pqeORLgnbyoUmPVpM2e5pBhqbnIZ+eVZUquukdPZTnqZtKvU/pTXxz5T2lkzB/OlleI4jnVFO7hleuMeEbGyNrv0YdFiB
  template:
    metadata:
      name: bucket-user-creds
      namespace: gitlab
