apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  # policy.csv: ""
  policy.default: role:admin
  # scopes: '[groups]'
  policy.csv: |
    g, argocd-admin, role:admin
    g, argocd-user, role:readonly
  # policy.default: role:readonly
  # scopes: '[roles,upn]'
