apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.william: apiKey, login
  accounts.william.enabled: "true"
  accounts.edward: apiKey, login
  accounts.edward.enabled: "true"
  # admin.enabled false is to disable the admin user
  admin.enabled: "false"
  # exec.enabled true is to enable the web based terminal
  exec.enabled: "true"
  # https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#kustomizing-helm-charts
  kustomize.buildOptions: --enable-helm
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.apps.iaas.wcooke.me/realms/iaas
    clientID: argocd
    clientSecret: $argocd-keycloak-client:clientSecret
    enablePKCEAuthentication: true
    refreshTokenThreshold: 2m
    requestedScopes:
    - openid
    - profile
    - email
    - offline_access
  #   - groups
  #   requestedIDTokenClaims:
  #     groups:
  #       essential: true
  oidc.tls.insecure.skip.verify: "true"
  # https://docs.cilium.io/en/stable/configuration/argocd-issues/#argo-cd-deletes-customresourcedefinitions
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
    - apiGroups:
        - project.openshift.io
      kinds:
        - Project
      clusters:
        - "*"
  resource.links: |
    - url: https://grafana.apps.iaas.wcooke.me/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?from=now-1h&to=now&timezone=utc&var-datasource=default&var-namespace={{.resource.metadata.namespace}}&var-type=$__all&orgId=1&var-cluster=&var-pod={{.resource.metadata.name}}&refresh=10s
      title: Pod Metrics
      if: resource.kind == "Pod"
    - url: https://grafana.apps.iaas.wcooke.me/d/a87fb0d919ec0ea5f6543124e16c42a5/kubernetes-compute-resources-namespace-workloads?from=now-1h&to=now&timezone=utc&var-datasource=default&var-namespace={{.resource.metadata.name}}&orgId=1&var-cluster=&var-type=$__all&refresh=10s
      title: Namespace Workloads
      if: resource.kind == "Namespace"
    - url: https://grafana.apps.iaas.wcooke.me/d/7d57716318ee0dddbac5a7f451fb7753/node-exporter-nodes?orgId=1&from=now-1h&to=now&timezone=utc&var-datasource=ceph&var-cluster=$__all&var-instance={{.resource.metadata.name}}&refresh=10s
      title: Node Exporter
      if: resource.kind == "Node"
    - url: https://grafana.apps.iaas.wcooke.me/a/grafana-lokiexplore-app/explore/hostname/{{.resource.metadata.name}}/logs?patterns=%5B%5D&from=now-15m&to=now&var-ds=loki&var-filters=hostname%7C%3D%7C{{.resource.metadata.name}}&var-fields=&var-levels=&var-metadata=&var-patterns=&var-lineFilterV2=&var-lineFilters=&timezone=browser&var-lineFormat=&var-jsonFields=&var-all-fields=&urlColumns=%5B%5D&visualizationType=%22logs%22&displayedFields=%5B%5D&userDisplayedFields=false&sortOrder=%22Descending%22&wrapLogMessage=false&prettifyLogMessage=false&refresh=30s
      title: Node Logs
      if: resource.kind == "Node"
  # https://argo-cd.readthedocs.io/en/stable/user-guide/status-badge/
  statusbadge.enabled: "true"
  url: https://argocd.apps.iaas.wcooke.me
