---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nifi-cluster-credentials
  namespace: nifi
spec:
  encryptedData:
    password: AgB6/cLsfK1W+w7pTEmb/qU/iNXHFROoJUFH+dpPwyDIq5u4m3S9No0x7Lf50dNVOIypbdrWVbLztoFIfsVu7gUc0eqCETHrdpfu6xRNiiCzuAZga4zWPwH4e6Num2KknBNP4w2v2T6cjXrc88iBPBqNYEiGRj0M+6xnMy43hnGOdUkiExkVgkM/DCF/o/Nx3/RdbanwyRZ+DHTgog0WyJw7/nL+swFzlVhWfIYBuYSTuf5nkguITQA+P97GVLHZYkrkGxZKohAgK3YJgnRB6P37OgGH/k4mb4P11pdaKgRdaih5f164sHaJywb0/MoVm/yFbexR5nptko7p9HsS+zJ+ceKgP5uT0onFpuqT4Tvqjp4Zad1NxQtcpuI4+GmuzvCo1f1OCTQF/Sc9a1btk2jhDhN58ROjsNnStsI33BMCkDe3X+J+5fjQDulJaI7CfsKbILd2ot4Xoja5KBt9quFulPlQ1OwnbfI0uidJI0qNFTuN6ZFf04ODnfXnm3hpr21iWgdK90zt6MDnMkg8GU5QKDHoYBvYKoIV/OPT7ro3d5ek5HpekqC7Mqm6SOOSax4K2Q9ZeI6Wkk3U6oXO3VZ6LY1VQDkEleJJkHt0YJWoUBo09nnlotEbpMKrE427l+r9vkCXCZEuTV1MO77xQ5MK/1iQxzpBsAEVY+MmlKkrQbCbgou4eXeAYb1YRS5dMW2z9UHwTbsxc0y7mGt9taHFGupJ0D4=
    username: AgBnjuGdr3kjNQf8pKDGUKqPOdsGpJxd0zouLU5KCObrfETEgk614tfYEE5g1cmyY2F/4SMeGsN8p72t/EJN+Dp+j/CfuM8H0D0EgtiaCX7Pxd/AHW07Rx7WTWGU4xHrCpLZ0V1VCULoHvy1IKDf95mi3D6kDR1aaWEa5phcBZ8ssguChf1K4MX6AwNTAUCVFXuhfID9ybkWBZSbNkaY1WZxOaBZMFJ8jUQ+CwdtWdX8UJAIODxs+zMjvVW8P3u//lgW6mkOPw3ZX+CL+xunpIOZS336b6Km0Jt5vITyp3VN1iW2TpJqbol4XvHG/0PP6DRuvc5LhK5WYxFukUCB05f/LTLGrW8fqitbtRDvgoq1Sjaa2rGSSoGIpzxTHmgNAKTBLy6zXxZNaW7WDSOsdG3Km1evdMSAFSnn4fI7T1PSQu4wr3oFyEj6z1ykMkGL4Jq6N6veRXzEapnAFDmJyd7pWVEkT6hjlKLSCSfEWgeGb410EW8IGSewgDnL5MF6jBAid62LRSaEZJFz6deR0gGJAVEjGgAyjuzdCWkgCqcUFiqVGARsmit3biPzBo4URKEALtrWehRJngCZApVR1x9mzRsfkebmR2UjcYdokrofpSFzjLtAEPtyp/VMZbO8467/0+/tsmbJZgTImH7y/8TvW4iGIqlMmC4O/Wwk+4ZiwHs3WSfvZzDWpuM+T+APZF9qLsRMLFb6ct4=
  template:
    metadata:
      name: nifi-cluster-credentials
      namespace: nifi
    type: stringData
