---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nifi-cluster-keycloak-client
  namespace: nifi
spec:
  encryptedData:
    client-secret: AgC8OtGntJ6tI405nvCNTcV6ctUU4i6/mu0qw7WDisCdXMI9gKJA+UQvHMDL9KzAqfLanvOPcsfx+1ZKS5K7M62eG8YtkFI0fbLSs6C+9XInCrxIPTRa1cuWt/Irj/sZ1nb8+Q/ovmDRpavWcubKcEDa9KZUFQxYNANLzHLBIoEAiRTcN4I2M/uVEvjHTGv3Nf2FYPkKrVHswpDHo0wD95qCvL8SoKTifOrPPLib0PP1lTp1xSOnrM5FXpa6hsRYP6r7cLU2yiixuztjRy2PRzRSb7o8FVtRo1DnzUbnvnlXvCMyF2TfOL6jlVdPY9f3Y+Dr8QaCytKsvXvZkCmApVmR9eurUyIuwE959bXIy4Nd3aRWN/lLQZCcjlL1eYmr/gQmY3yMgIeJjxgEu2t4lQGsap4Na89ybpzDUIQ5lTkvWoRGQVob3HT6u/7ZXfDN/Ml8a6dmEKkfZUD8a0Lnnzs1HGD5+NMaYhgRa4Xgo0eSaPGkzK3yNBq2+ioTqlmMqVHpz4cYtXWveSROd6MVcU0AzP+l9mvg0ObrVgMrMCYNL/znkCouf682IF4zzw/xNOAb/sPsGZ6OwQNd8gW3J3Eh3qS9OKmYPkw066d/rF2SfmF2yQunyxGAkuJhRkP9Z61pE5yNhsuqBEeVg2Ng1tQSaXnOtlHH71mhHpYQEW2qa7bKPNQPUabW9iTuYq2nKuwXadI41I9BhPis7Q3WsnEvBpt4DnKsG1B074AWfuyKKuU06sjnGEXkTlRYyA==
  template:
    metadata:
      name: nifi-cluster-keycloak-client
      namespace: nifi
    type: stringData
