---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nifi-cluster-credentials
  namespace: nifi
spec:
  encryptedData:
    password: AgAEXNsL1ZJkfnRGOq8Y9gaaFdzfTzy2NHGYqCdCPeQKRiAXPt76tdRlXphyKa9xFP8H0dt3iSr9Xjf2KPfqkLrDZkO4CLzUiUtwW2tMNtanBT9jqZSc4KyUclehregZA9axGqp8qNk1YefYWO6hCyg3q1cm2tgsZ4TPD4GuUTrXVAxF7VkCC6QE728HRpA8wZjM8cvnYeuJW6PgFjfmyKBkK6o24RTbjfMqxHLK/2f3QAda/VWKLRmclH+0fgULwty88llpvD5nWr2bQ8AUb5aEMtQD+1ANDDysmNm3FVVum37RCpKEIaH9lSTK9PrSqDHtGoh++vJvJAEzIPHM+R78Zk5LiZjHsu8Wmf5XG9f76TK5qfX7IdVNh2vufXFRh6WP+hr64AqjCwjuAROPY0xRp7GLJjwOXelAyznWo5b0nFcxfH2apSycs9jj6ipukB76rVhEKuqL5kLdiGj9t0+wprwCXqp8cxM810NnXAvlRrBhSsYsctB2vLXSptb3R68mlvy7/sXmqAQQx0YDrRGfLBQJu20RnWbJUhgFUD101YIsLjdmevEMY6HBOZ8TtkubcGOOYkYlJq00iYcf44bVA4tFLX7xeuuOTzdl3haHFIzJKOv2DcKMzvFUfDXc7yMAz96tvG+Zule4vCLpaxr9bFZbfZGErjwHHzqWyyh1OpApl/5l/3Ja5OO6GJ8JL8vbh1poA3KNdM5Z+w9hYCSkBZv+MKM=
    username: AgC7QxNUPe9SG5jUBzUDdoJL/E9UASyK7zCPpaARid0hn/8BYjwyjM5R34O9Nk2hg+B1YGQMGAM2pQ0tDLXtGBVPFGYdQkfdO6fdwUitih5NcIeCOPsZdittqof47DO86QGx9U8MRR21Sbcp54Hr3Xa6nhynqTK18FY0TCv27gO9ksNCjdXBtJ38tbNibjGNHCE+dclhe+wDcG5kxJVpkvjXExnTS2TxedT4dJWOCf8sNYVdlj0jLouXRmHlVacizkO285R05YsokpQuoFCAiLH/LkXY6chp55X3lDNa6GIaFNSm2Owz2tilKQPw9xLZ1Gmd/xIjNbNvH/L7nMWVeFjlFJ26cl8GSusj4psS/h8fUi5YdtmmHM6shMvgR9nxxo+HQwcmSuha53AgZNh0fJlRHd6Em4hewbz++bDgFBjwcRLFwadDu4TRkcx3ka1Jle0DSdz9SdYPMLpzy+kHcYYA16X7ReQpPV4mT+FKDsLXT+RVkxtI/+bBKYzz6onX2own9z35sbbo8nJJJguidsljrQF5A/osB5MKvyNaPrmzZjQarRKdWNWV4147fQiEAwd66jE2xQlAVcXgFaaIn+eQRnwUsjYnazG3Ah4+CLoH4xucby5G7Htl08FKhADcwkMHbthpojfS69o6yk2LW5sUblkaEi8dSuIOPFnLsoC+QhhK+AmG9NclVByvd+9IV1z1oadtgl9VIiY=
  template:
    metadata:
      name: nifi-cluster-credentials
      namespace: nifi
    type: stringData
