---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nifi-cluster-credentials
  namespace: nifi
spec:
  encryptedData:
    password: AgAmb4Ogp3hrHs5zRX1uwg8kE6OgFD0vvVcjjaVwCzZZuFpKmaXvkFmEc8PE186YmHUhHK7PZTbpeD0ELZ/ibJP2BLm8VfJjSi29YU64NUe6Fa8oyVI1WuVozMY0gaALCZeB2ToaHmSoVoahYCZeKbNtimouYh8HhcjkVyYmcibmorgDNgFsS4Cxe6MUvBSivOc045o0KhwtuKcGxSVThClk7jIN6CM0cDI6X3UGVYGSoXfOLQyWidfXMO7g3GvE0f6BgCvLnQJjjle9Bqg3WU9cJDmPVPJxUjSP17+e2YuMqnup1Vanw6FxwI0pfVQxnPFJ+VJywkUhe4pSm1REnjQtQVfDZ6JpnjIPqYWmxuiZTPJwO5vZlw1mRYSgwIER/B2k9BThzZ/s2fwrVYq76sg3YFPyiuS+axsyqcVZ8mr8KJNGN/ObXv3zasVYSNtImWG/3SehmlOSu84eUsxIZgbPmULxBB6xFXCOkTE2TmeHr7g5BjLaT42BfEIkDXunRpsDdVILFQN7Q/Fh6WOUWkwWHDKLUMt6rlG180RcQFrFI+Ij5XH94vPIGMVtH5yIWyCBMYWIY6dmj0eZldSP/nEKZRkgz94EW6XzYTWO11QfK32HE8hDvNe9sIdDTNK1/UnwRt63kXfJ8gdkIklafe9QGZUTcUpmhYM4JX5pH2RhbfGBFGPcSvHoTLtmSEFXY4n06NoWdE8pXB8=
    username: AgA1mmBtna+/iYdATrlLNYT8k6yk9ljA/jbJPDjUS/tENpxqfp5ILk/ZT39rONMzcX80MvbrIDITAoWgusv/qProZRfvywdS4l4jl7TUpPixs95e30h3kqwWQBIazHWMIXcgXtJRGlooUAs32rZGVIaJ3mUBxyJzt8H1uQmTpXcDsWKy4h+QUBYmhpvOVl1moctqM3jsdtGUPpLwvR6aEfxTOactdbP8Ndx4LuEz8iRtFIzBcMluIopQ2RYNvU/dLh/QWyEiKrkUJpH1jzRpqoUWddxEAHAjsDUg3ubTzsKuF7rD6uOUButgQD9+UG/H2pbs4dbYswNB61exLavC3eIY9CkroaGBH9qxl/ktrrFB1RcVt5bdYEEGRKiE9gieCX6yyU3uJK8RvAM8rl4/59ZbSRT6n9ws6ytUxXJsZjAuRY4WbSTyVJSOejOP6RqmvbLjtZ4opZFa234oDktCU2ef+Qh2XHwIZWBAnd7G6FG0YgmY3bDh7jCKu1f1Mqsr0Rr2zsUghOYymBEVowAjAKoRpJdOVBIaqLbUfbbJ2f0oHzOoVpX5+nitq1L+R02wD0xpBNtggGd+CR8/BImW21/TF8fCoq7c6d8WQDyvqK8zium3K7qnas3QMciwBHDCCL8QHqpIiNbKeWs0Bd3vnU8VXY9hTFHTZYn1vvVqDpBkYvRq3699aUFtqhGOTbszpnsvkPRf6PzAqtU=
  template:
    metadata:
      name: nifi-cluster-credentials
      namespace: nifi
    type: stringData
