---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-mcp-server-token
  namespace: grafana-mcp
spec:
  encryptedData:
    MCP_GRAFANA_SERVER_TOKEN: AgDLWX/z/mKEZSGnXizh3qx9xTH47agC2kBM6oUoCZ/I27jKzp3VHL5Tk0RBymcLIse0PQHsT4AVeZMmbHkGnPyiZVcmvd16jTF62llAwjMwSYuBl7UtWvroTvdLOzWT76OJvXQ3WVD8LwqpfJkLwx+G4um6Q6A6kHWxDahbhaB+QnkeMV9+fJFuYZMBjhhWzGI1bhO0Rw0UGsVoMUiuKJU2L1IwvLI3zVA23/WV+bGaQ8nDTv1XTDcz6Sc21ZR6xWSqBfeK813vTeFE1c/Qt66BPy7jMnhOx/0vltR3pZbPDhrU69RoTjk98mbNKaa5E9I75AVOW8KsqL2ojb2OkvriL0RYGwaylAG+OENgc6K3jEsq+r5f7j4xhYBYcTf+MfIl0txfupJuBHyLp9wcFyFzmZAWA9URmwYR95spznecLCYHDlNmfYpTxqaYh4yI575OsvhQjmzxosSTBQnCrrKmf0YNPZP/fPss/HUzAI3qJWX37ylXslXK/f2945lZuSxea8SJxCETbkVnBsO3HgxNtAMtJtPktMuT/dPAymt5bUZm29vgQi0h4pF+CfXJNlXNddeWBuqHdHNopz8H4uAFvylaxXSrUKcurq31o+GdLLAyORpV9RTpaWbA/RwXieL1FckQfYOG5OvEEvlwwW5CW3Z0vCCovHk0ksBu4D7rH2npaMThjBwOcMFiHooiiuoMpuAFk+OGYOktwH2a4qE/uc1gxnO8iLL3X+pLnRgIe35DwhNhV1GyvtTA5w==
  template:
    metadata:
      name: grafana-mcp-server-token
      namespace: grafana-mcp
    type: stringData
