---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-mcp-server-token
  namespace: grafana-mcp
spec:
  encryptedData:
    MCP_GRAFANA_SERVER_TOKEN: AgBh6Ac1ipKpb9EP1a8Tll8Ujs2UyfCMQ0z9CG5UeGJANvbDXl9+hf3B9poFSTVSDHf1tmMF0w5bgQpOq0FuelYitw39In+bO8FJ1lMmj+DP//Z0yv62C15JCm5TjwHbwF+mOS+fxx/DUhKh9nAG2dQ0ofQVRovfj2PfyH6qrK3WmGQU544BMXpM7f9p0aBHZSTniOHzj7LRatbZxBoLm3HxPQL9OYWQEwlQKJ+EU9uQu9b5fpOsgT1i+3xTGyGzNTfX/7qmeQOnx5FJnTWzMHmXCQNb4V8hyski0EFoqfALde97W2lRSCVqYaZ62at0yTjl3yYmARVA63GXZmokTq1OCGrdS7LNJ06zPQ8TvynaDjb2+wfxc01RksEXTaXewBgyoA3ppD2zO/WW2nfQsgBX9ZfqziSsGOsgs3zgkA+Jk/kdu2YfUcjNn64mgAYcbnUqIqbirM7hMTbaNncGe3ZKV9FUsJRwIixQEc8os3ojuWOR6geGvGH70p4wA7UrZEBEHTcDReTYCp4NGQah99thptEDFg4jhP1xitXqTA1Zkoe4u+ABjHqZ9WoIVV1nvbP58+vPm4M9hHP39uPzOk8ltiwhhKFLVOZBr5946Axor66uXU5h/0yifIRX7jpUZpB3+ohAkFoFhx7Mm3+mMH8Z3G1t8OeesXbbGpMdV1JDAj0u8W1y3q/DtP4rW2zzHF4xSaiu7OzrNcvWASDQFvyetDTHiZOF9ehxSdUNSMScZBOaRRJ19DgyReUDfA==
  template:
    metadata:
      name: grafana-mcp-server-token
      namespace: grafana-mcp
    type: stringData
