---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-mcp-server-token
  namespace: grafana-mcp
spec:
  encryptedData:
    MCP_GRAFANA_SERVER_TOKEN: AgCQFKIpHmf7UfZgm5ailC555J9S9EoiCDQUbX1ggfB0mzd2aUE5LuDATcBHEl7UV4eupnE6LzqgeSEoHgiSE11fTWGxLy/9bJqKQdaMH4xb7nIZX4OyfjJNumHjZkLTQN4j8rNov3peYuc/BGKeddn3m44Fa0ynK97Ww6Waj+3I+QJhiIRQhniiKJ2y9PBz4TWIjlHG176Nw8t9TavTbw4sKertMl+ybIpuctIoAVQAxleaf6qeYIJ6zesIygC6a1bXvKzqnxFIyoTkNe1YOkcTL7krymqFM0UVPZeokMTd9L9uBcTlc8KrSL9CoB/dx4R99skG6Ve09Kk8CY6fiz4e3L/K82TYU0rC3Pi8WAmKn5lB6uBZG6rrN7IT6RYKMItXXFlgfLrdPx73v033SDtZ5bCwEu42upt0a/B/tYb+gerXx+jlQ/gFu8/BrZaW9mop8dfrfAV/bh+OiM+4kC8tMWZADaT/u005CJlK2yKOveE1Ic1g+2HepmOmJo+OW/8ZjLtZnb8EH+hfTCK23Cz2rXN1hkRIKG/0DjUrvL5o23hw8jFUONxd0GpXAxAal5o3ZT0/VUdzCtfvA4/hA/zGFW36qc3NdDchMcZy68NkUjwqLdHQ7/gRkXbpB14yScZfdqto9lfX35EQHqdLS+b9BnTAnwCp3JTfdijIMErM0ovfTIhHGZ7psbG8qjnX1HvDB2El5lFFo548gBjchKVhVKrbsBAJTJ+NHA+YGG0Rf9KcQr6/wISeit8wAw==
  template:
    metadata:
      name: grafana-mcp-server-token
      namespace: grafana-mcp
    type: stringData
