---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: kubevirt-manager
spec:
  encryptedData:
    .htpasswd: AgCxf5Pkwsisbgn2zEO512V+hIkWYw42QZWoh1a5Oat8x0k2a4e3W24RGF44rij+NMeoGVU27izm5HmPo0mU856Y05Ta/XbVTZWrtq0UhcMGwVLVntrk/JGQafDFOhMwvOeQyk2OjIClJVUrT9d0Zx4uX+Dmfl+5TZC4wNUE4g6nYujN08hCRb8rRNZcJDqxjdrTypUQXsoDe12Rx/JyZC/rMbhtAtaGzZvf6XKkCGeu2N8TIlLqyW8Jk0z7Zkf2Uta7zPVCriEpNatDrhr8F09jPtrDpV+AOmH4NHQrkidJTilF++o2h6dFlCEsNrTGPvpP5XSzd0qNyxicrTiSX7lm+E5m2eKSlAXCa7XAh/imqhioeVaFXj3jtESI5IcAKDelSq13fVpNubYOD9TSzhk5ClrGJoh3AciPD4vMjGith62Kccrloey0vDw6lX0c1oM9/fcAmQzKkXGDaXneoN1O7lrvyaSQlUh+Kv4xD4tjF3xvlfnBHqEfpr4TWv0/MlOslWUMvVB30Rxi0e/a3qLthWgmDkTWMt4rlMpBPb6T1z2fe//0j+hh0q6D+3lC5h68ZZokOvNGXhezPFUOqbWzXkr+BtH8J/aF9nMZuSrqU3kNYVmZx30YiXLu5LdLcppaR6tkPlASe4ueiMqcDN2WZ/3seWihVrQGlhPgzLNd3Y6NgWX7rSSQ3xEPIoAZFg80R7QV+X6avcW0ctGaisHOFMgrSJUKK8zmhAieN7JYWRa2O4GwWuE3dySx
  template:
    metadata:
      labels:
        app: kubevirt-manager
        kubevirt-manager.io/managed: "true"
        kubevirt-manager.io/version: nightly
      name: auth-secret
      namespace: kubevirt-manager
    type: stringData
