---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: kubevirt-manager
spec:
  encryptedData:
    .htpasswd: AgB20IdWwbyVjDAZJR/GJnXel80UaLFGqDp4LByczqE8mbuMzUkEZy+1vfVU37dVotBR9S79wIUbBnW+easgw6i3jE9LxrpVOLI5VwOmHbXBwZp694Xef0COHtCE/0FT7qWuP48bir4g5X+lVk7RVXezIJ1txuHmX0OP5xSSxQdHXUzB+fKBWr/BBEFvY6JYUTKc/c4lhClt6xR87WxZsuB0prkJrOG4Y9e3PexqcSlkXiKrXtbOuXSkrRxhe5fP0ZlP/LACyshuEBnAuiWQ+hytUU+q8hOHYfjPInQngpCd61UGRab0emMJhkOiVOjFxu+8kfy5ZTqWCu0ZvPVUWykr11W+F0Mnwgknzh+vvkb+zo7S0p/ylCBZLF1ymiFpKDEyUTdvjCWDGm5n3EBVzxPmsgllkOcqPsFQU7HOMpx8ocC/vewsOIVmsgxzlvsUMIuJ3WY4rCSNxffD8b8ajM276dIb7cs17fDsFb8gcCQNq/OAgaPmDkyz7A9fMB2DNOR6BU+IjQItHaF4P83NDG7hvJirYIXrBF3Kg8FKfI4+l7Dp7yxP7l/8D715U23FkdkRcb5wYlDqDkm4MhiNBCtaBqufEYdO7UqtiXmW0O4aAe2/ATYB+D6uPM+KS1+hO1c6/R0nu/tlHc4Uac+7xX4ec+vFVE/kKd5bv5I7Bgxy/HjXLuecEp6DUuRxWG+RmF3utXVf5V+T3jLSoZWON7cvCcPlClA+HZtFVCIZ3BkY0Fzr5Fr5z/YnMRHt
  template:
    metadata:
      labels:
        app: kubevirt-manager
        kubevirt-manager.io/managed: "true"
        kubevirt-manager.io/version: nightly
      name: auth-secret
      namespace: kubevirt-manager
    type: stringData
