---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: kubevirt-manager
spec:
  encryptedData:
    .htpasswd: AgB19HJYiyeevzeMY/BX1+4etbZRxINU7xYgd1PolhUkFvOnEOdZABw4ASjTzkjY+Z1D9lYcxbVKpXLL1//K1/9PIBB643+V8IObQsGJVq30IRcIlWE/jCnm9g1mUO+fa4RbrUu+4gEYeVOmlWur55vG1TxpoVnz7DTGJ+u/qGXoZSeLn3pkjcum81NQsUq41re1dUfHXWYIWyBPu9UbquFFGPuvyoUsFO6FspI5+g56Cr0Xq8rr+p4PkyzdGc6gX3pnpsrS3kPNYHSWt7xr4w8xTeYTPLB5wEY41j6IytIXYs+PMxhd5Vvc6h+RLrDbF0HzUUztSefXZ4sHyUnkNeOC/wdtdTz/U470IrVM+uyRngqZmU/KffDM9HHVFHyRZm/hSrIcaXbQzymO3VXxVWtazvCDV5urT0nhzVg9R0U4ESC4ykgIcBWd53G8q7lgFw5mSSCxY9dag3Xe0fmI7RYrbguo3j1sz2rgW2/3PFQMTPdpS8keGkVTTLFf3Y+vK/Ltpl6Vs1usa0+SnZGUU6+cXQkWKY1fwcXfJZqof9G3HhiIZAOS7Od4W40D+O1CUREZCv1YCFzjbN8N8+EMI15ppHgPTz6F8bLB5yiZ/zN5ZtukV3fcISAioxDcEp5jyOrZKDV3Ucdd3QGrxzu3V0UUkdxzw6W3Cjx15EIbC6v4Ehni6zIAp760WHmOLTaosyR/DZQzuwfxHDlwCM+n6i0QMTO4qzEAVVsJ/LoDUNkWT41tNyN2mAE4O8c1
  template:
    metadata:
      labels:
        app: kubevirt-manager
        kubevirt-manager.io/managed: "true"
        kubevirt-manager.io/version: nightly
      name: auth-secret
      namespace: kubevirt-manager
    type: stringData
