# https://github.com/konpyutaika/nifikop/blob/master/helm/nifikop/values.yaml

namespaces:
- nifi-cluster-1

# createClusterScopedResources: false

metrics:
  enabled: true

# webhook:
#   tls:
#     certManager:
#       issuerRef:
#         name: nifi-issuer
