apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: kiali
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: confidential
    baseUrl: /
    clientId: kiali
    clientSecretSecretRef:
      key: oidc-secret
      name: kiali
      namespace: istio-system
    directAccessGrantsEnabled: true
    name: Kiali
    # pkceCodeChallengeMethod: S256
    realmIdRef:
      name: iaas
    rootUrl: https://kiali.apps.iaas.wcooke.me
    standardFlowEnabled: true
    # validPostLogoutRedirectUris:
    # - /
    validRedirectUris:
    - /kiali/*
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: kiali-admin
spec:
  deletionPolicy: Delete
  forProvider:
    clientIdRef:
      name: kiali
    name: kiali-admin
    realmIdRef:
      name: iaas
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: kiali-admins
spec:
  deletionPolicy: Delete
  forProvider:
    name: kiali-admins
    realmIdRef:
      name: iaas
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: kiali-admins-roles
spec:
  deletionPolicy: Delete
  forProvider:
    groupIdRef:
      name: kiali-admins
    realmIdRef:
      name: iaas
    roleIdsRefs:
    - name: kiali-admin
  providerConfigRef:
    name: keycloak-provider-config
