---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-valkey-password
  namespace: loki
spec:
  encryptedData:
    default: AgAKKcAQdNeb9iOe2ufsGIVz+rJQTggVF1UGfikko/O7h9xCbhkwCrjSoxBobJnbrRBuKagc81Bxr2mUaqTl86jiMfpPeCfY7MAGOK9WCYK5xjSkpGZ+URHzhPEWZqOSW7npSoIsLt74KJ2i+BUXcBqvUvUsRcOOSt1kvBvrAj7ZdjCd5GEf89d55snCkdsVKU5l+z3nKzOv7Ec6KHjxLHfaQVf0opI+pPQFdF+2IKMqhzfoNjmK0WZRcteiNWwpKVCr3z6TYxE1zhXSwWAOKj9eDTABLoTGySsMN274x0x6O61ltL6O4/oLh2W1LrotnSPu71EtETbU59OwWvM94rdA7ZxZqLHcMTG4acrA8QP6d4tEw5wwFx1GDAwVaRahHZi53SAfreebWJRy5Akg2zETuHupVIt6zWPZeT7MTT2aVGFGo1U6BfLBaQ2/TrLAp6RIfaMHURsha3kDuBFki9p82jrrNJQBe4tfrWlTLtGd0U0yWn++jvnHYCBYWHd43WQ4O8gZ0Wp5phrtv1LmVsd++xpHNZ8cGjCfvTET0JqW0tNuciQlvcAB104rxLkLMy88Q8biU4l2B7DMYPMDrDy0t21rvRxC+ZYN5n+jlZ4DTzUPGZFMHbdIUa2NywPuEIRMSiUtQp0r2aANcgBTw9fl5hqzSGCLX8ZsbF+JvFGrCqRZk6tsT7zSHHycxJ1UgLVjATDzwxtRJ0FRJoPGdwmOOgVBd7/+aDyXo4DkNLaQzzJeW3pBMMrPgWpC
  template:
    metadata:
      name: loki-valkey-password
      namespace: loki
    type: stringData
