---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-valkey-password
  namespace: loki
spec:
  encryptedData:
    default: AgAJLDrLVaiO70YNVWD4ejqDpTnhOtzwDayvXUFTWiPWmqaOWSgxxCukAFPB2O1D4pNJC2ybJmHYD3VqoWYqDtGLqSLZwir2CO3frb1sncW8R2L0MvsVuZ3k2t8+MoqeBp76Mo1FNwz/0ORNMJkJ12NTo4EerdVjWXniFnryCOZUd3amp9nbPcaJ/R/eOa9aEiER33qO6fkrC+I30l4CXuKVAHC5+4RtjSJBEQMWwwU95aBvZ/Nd8cNbCeLWXSnDnyxy2mieAyuJlJ8jYwgDsx8C+/3FujJ5TizdlLXimHzE5AKy5n5qtDiQNWjBUE+zkpgz3EV08nTuP5/NZaT1rVxQgfIRJXheeBeUh061QZMmdq60oyKmjb5bHgc4gyamOrpWRFekhRzndwMXX6IIpkrbb7hyM+DarkXJntk8SkIurK3UvnC/KB2c/GPcsE1fBC/NFCqIA//nE7pIwUBSCovjw6JedR+/lZELiUlASwu5p/eG9X6vYzmPi6PVWTjEyaqYI0mr44wt1LFYsSBnDJJ8VKEt7Vi0eDZatJFtD2irwlDWl7nY/H0+9Van9pSwjypKlwJuQo62yZ3R7KDK5Ds0kQcV64Sq9RsULX6ZoZVnnvdimt35WB7buYH62U68bdGjd4z13xE1dGAxc8lJBZ/4hZ+G7x8F7/G5lzcMq/DR4JKS0mjfl5kye0G0cLvxjTjPpCCYB5YzTGbIOp+PZpgXNKCs/YXSlccbeau9ojTIwBapPjV1UIeSpVbL
  template:
    metadata:
      name: loki-valkey-password
      namespace: loki
    type: stringData
