---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-valkey-password
  namespace: loki
spec:
  encryptedData:
    default: AgCfxseMbNQlvhfaCAcQVW+sNqBpKPWgmgCK954R3nGQWJcVrWH44F6ma6ZcsNGNi3SnMKZ26Z5b4FONIo3hJ6aQvD/DJ6XN6EOSwhvS7IhYzJNMUcibv85Z9D0L3HHTDYjPrydm6OXdK6hjLLi8/fraDDeaskhiKrn6vNFBD6JJalKBsxB/rIcJwD/bn1zN+JYkMbr0YkG7+IK64XaGxuGY1eHfSA93a1zMFC4+Ig0AXSF847/Xc8vSMbtm++mJDPY1RM0waX7PwR/QeQrCb2lSDj24KMvL2jXDjqtf+MovnY7wQdaRIozVPpRqDLb8Rm8h27AL4Gd+KAUa8dCCQLg0lhyN4ZgvK82Z79LN1pk5u1YrWXD3oIB73L1xv+N0ERaQvMKwCUX1zKTXxsTgNjHqs/9CTWxTiWEZ+4gnTArKWA6Fx9mb6pdYzjPgIFaD4kSrKjME5n0sBKBducojwSFaRrAyILLcp7BF67v7o2m5Vq2ex0YE211ebeTEt5mndDErEz64xEZEnU/mQJNCPZFjshGjSwE+ac9Dg0xv4YhBWOJhh2h4yeU/Ko+FlTS34EabgB2z2sXQ5Onv8yxGCcyLIXJrOhf4fa+2KI6o2bMRzd4eO0GKXCRmuzQP6GxX4Vvb64QnLGGum7fwf9EEaEa/Ibt2Bya38hZrZWrbqsMzLUen2j0Z20Cf1HVk4dBBYSv2dlFayp0fhxZPW6BR2rvNf7qgXgECKyhFG1nSyvTDp6+tmeaMeMdrAm2r
  template:
    metadata:
      name: loki-valkey-password
      namespace: loki
    type: stringData
