---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: crossplane-grafana
spec:
  encryptedData:
    credentials: AgA7tri9/vteSXzjUbJKQ0BhZ6cBrQs4IcljQpO13KpdGVL3cyMRmOaN6twRXaLTwpenLLGw8l+GxPgfaEwKL0j+WkQwqMGumga2KXj6l8ZAXw3ZZzvlCBdRTLQ79zf4smWpvpRBHOQKc789q0M1Siu2BN3WCKVX4VDWNAj+mTeXJYlTHYTQS8lRvoEXjosa6uiF1RRH29oqbMZ4nIx58iHK7TAsP2H74KDpXlx6Er/LbNrOQNkRdTG5kZeuKFgLLM1RatVUT19fbAHyzGZYGDK2cm/yQkJ6XTrHVEDvmpqHA2uBo/ffFdKLwZT+IRDSESpuN32RM2xVoCO8s76EFTAxK7dyUHL3VUtpKzt8KELzuoVs1hudb+F6LkP32fvt3gYysjOXZQ0zJ8uc+0PmDGc4Xf3If1Yo5DneLO3a+FVxWBl0ffH2P0qzoKzhjrkLGeLF1RLYD2qTbuR4lMSLlE4DOpEhWtZvPAVal3S1+sqh+lYLVAvVCu0vF1CuYlbRI9hKZ/GUmn0Z5gTH2Fxug5+HeC0NI6FkgTL2wdOZMbPD93x6pQ9X+t2AE7VwwqQrlz0d74XUk592DJdzEv91T8R513i1In/SYmCW8p8ZV2GXGht1XmsNw32E0sCWKWbnDm72/tv5sdZGEYyycuLcFRoPJmC/0L4ePUmDwUPcWL2uqkVJK2C80/Lv67uCrQEjnfXshVdRF0mY5ZLIM4dqc0QyY5B9GWgr+JHKKibEWYZymqiEFg0QPPNdTsNmig8OJlCpYgqXbSmGRr6kgBuAPOHztlyWGI8=
  template:
    metadata:
      labels:
        type: provider-credentials
      name: grafana-credentials
      namespace: crossplane-grafana
    type: Opaque
