---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: crossplane-grafana
spec:
  encryptedData:
    credentials: AgAwDhX1fglrf15kDZoU5lDQgWjz0OdiXyAyM/BZVZPkSE/pjPV/q8i6G63yp52fSTiJR7O4bkhMYgE5bLKiQOEUCa+cVatIUDBXB9w9Hk6tbJ2Vr1ZB3dCuYFiaxGPIPXdfylwLrBBnK+CERjsd2OmxLW0p5Cc9L4nzqcjAf6sARoIgAQyyIZHJX0M273j6SlTm4+6Xr7nRTFfsTd8QDvJPwzn4SsdZkJ4rtYfgh0wI6+ZPLYvr6jYhPKtHnugWAyOINZq4UrLEc+Ix28WR1mK/Knfz883rlZ3afGx90/tEPibfoiJgM2W1CZ2U7nXdzbQKntF5wH0e/IohUDsAEbws6jqL5XE1m1Xd4GsApGXrJvu4IkzkR3xVJgUMtVwdVc9w9gSwIxfpbfFXRpregDEorOEr38UY8TtToMEOS4Evm62ilYBuD8IIPj4ji3L6MG0QWuGKdaxwbFwMToiOGmzacyZtNvNBI2ZEcB52xKNt0gSORZRmbplC4PzANg3z5lndK68epPGZM627I57SbrxDuMGyfRYr+1GiRv8R+Q/Dl9xdIb3LLWm9rV+5hPrZEkCkekxQh8n6sXxmawT1IQaGUdLp1/vRVRyLhYhp36eqthigtcvrzDPOG7u3eKo469tv5KK3fXaTp5lxMFTu3z3bqpCFPiPVhIhM9w68wtPfU3FzTcF2mojW7Ois6GcUNJhYY0vt/jdhZoCziE96Q3jb13lyLr8EQImtKZqVcBRZ+wANZtv/pk6vmHs/fWFVkRGWYLAzTcBIUJNjblmvNcDOQs4gTO8=
  template:
    metadata:
      labels:
        type: provider-credentials
      name: grafana-credentials
      namespace: crossplane-grafana
    type: Opaque
