---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-credentials
  namespace: alloy
spec:
  encryptedData:
    password: AgDEuMAOvb3GmsM1p/ZxI1IYglJ6VWezkgxcOAYh52U8Z/+MW4T5BAmIbwHAtKD+chs3qf1QtqOwqOm1x0l7xgPH02MrgGrLMkXyb7MS2jXlD4iY9/uyv4NfxT9sHx8o8hQtV23NEZf6bvobzzJmaHAOPX6tFaSi+wIvexorW0ePO1xyCTJkvQt4MPvAv6foCJ4+8Vnf/e3rQIJ/zn3lbwZOZa+SnXVRgfPL8+FOX2bL44sNd/y/9to6xpZ5WsyROtfp4jzIRiUtwVS27J8GBm1aWHwR0v0mf5bWGa2DQ8inLsYcGXjyzcmnynQVRqGfoOyDc4bOmyky1VXJ7fKE0E/91tueeHlovIl1cbeBfNIiAQplF5Q5sVetoPYCWMdR48tJ9UrlmmOPJLF8UzlE1muCVY+UC7x0VUMVBaRLX3tb32RDWnUiNrAXH6zIxhW0pVOamCQhjnPElwFh8evcsMDdPgUVadjV5QZCtYuT23O1zdiGnNi1hMXwfrUBvA3PrIiWdglrDngmhqOf+U/o6SpSFIQR6REu3Hu3FZoA4FSGLOWw9Yzmc1evIBaQY5acHynEfO+KMwyTuerWT7RyLhchG522RAsD5bgz+fGd4u46MvRwIbN6K24ybw18oGLpWbMgcMcaaHu04730ASAMHDV6Q63zgBwiJ8LTYjMK4qZtJ81N76FfN+d6P0UCACZG86Bmk329GdDiuehYcQKT/CSxoG6g
    username: AgB85NBz0Bq/0paK+AgulOwgXUA4K9qE8a3IBkealDUigmWXciUSlvk7a5ARBouoNd3N/d7tWlYjCv4dj1/SRVQdCi0bzaWO2kmQOqktU0KgIRAv96BWBmIIqJ6O1QZyRSNhA+qANsFmGtSe/Po1eMAQl5NL4qs1Go3k3yOH5yFDeeH6Xe6tiu8n4x/iFm9jHrSyj1vOLE0ncXevwLpHkZs7e9MSjaY/qsvGgsbY0OIrKMuzl5FOJKx3xUDXjfVhoToBYFThu2GVmT35YpP6WlpCTGTepQeGoBWwe+4ebBBMDkzx4eOO2k3qK68XdwXgGivTv5zpSurBcUPqMkcFFgyYa0U6Fa1mKxjavM9dVerAup+ReNZ831LKd9fRm4G+BQE8k0Zrie9Wqlfu1DojgibqhbrF06yQkyMDKgaoE+2w1HRP4fI7LTHIQE9wBHYQar8Fms/4ary4k3h0QkqQyJpuiRgh5jtYNGGobGd0nm7U6ta/T88GT1uQ+rf253HFogg6j9Oo1FhyTyng3RjcdhKfSmrtJfLBbT7utS7RApkG4L2/wodtxI15IKE257ixlhadcbA7vEkgAxRO+CW0UyVGKCoh8ebEFZdJfby+0tFhUX9urj0J8MrOhQdpCqsr2JEu92eTdknMV/d6yVB2fcPfX0qn3UhcNAqOD7+VwkZImjjFRAC4oeaxnYgF6tezgptXjyyMS+eOLpk=
  template:
    metadata:
      name: client-credentials
      namespace: alloy
    type: stringData
