---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-credentials
  namespace: alloy
spec:
  encryptedData:
    password: AgCD04zcx5tdBgMe/eeGRw87HjmUUPtPX5zrFqVRv/e+XlKgrvt54GxmgmjBPZs+n3DwjTpyYeSgQb1mr6UK/VMDHhgr3+RHO7NSuTyIHPnsS5fyuDTPOHPn2D6/PGXWs3q5QuNoQipHkPGHfYkXL4dCYCCqi87vh0QFh0Hlw75fwj+rbjfmT4fRXWZLwaeYT4p+JHT16bfRtsRjKl2So0rjTat6ZspWDgAeNfHg+OK6IKo4WOhhI16ic8WCyvOVnRG8vTUjNiVJoAcOWGuf4gKTsRDQFz76P2rdF67wXHLs8+qRXzrzJYzDpiY78HmGOquiJTh8sHFKFTHXazzJctYROGUFXTJqxhHE6dVodLgdzS+B2+JuEALgrCqjOC4KS7kCrhF3FaBRVswhsw2oYt/ezt2rf6TcYobghWhlkq7g3jr6f2io655WZvRKyULFJUUCHsXs9RMTaj80gE2OT9pUlYng1G5IiqUP8z6zyTpNcwNI2q8Jh4Tv6Smm/WTP7ErI8wNRJ04Gvjxv5rVnwOdXAHsq4keg3iy65XW3ibWJ6mq/jF9cWa80nLhRXjym1XwJzmn2MEtnfciXPeLNyKp71BEguPU2a4q1Fq+GYnN6ld6hi8LruJaz/mcELbo/KYo+ruuuQJZXnOItYrv3hTXtd7YG3ObYYZKdOrlMC6TcxVRYrM+18QLF3N3iHiJDeHV/M2hg1OxKa7IsAlsngGAQ+EFY
    username: AgDaROGEdupuS0GSEIcMggfa307QTM2dozM8AQVjjk0ixA0RfdTpfHkLAzbrGEbxBouhH79x8OHt+tZ8cNrmrPBUogmdjv89alR58bToYNHdQeS70uNCUWiP+2FnlyEFCm5iiLh8n8hUlO3cDGsEwk1grw0O121VQc9AuhaLjvs59cIAF+KElz0wa4iQ4YdlPPWu7PaE9vsHgP6wpw6ptZ23cUOVN/0GThceLimmLi53Ami/ZJ6iJlOvtTOUSxXNR3xk/J20/QP/c+x6iLmqRK32lniG4r3xu3qBc2qWjy/FUvoiZMTWFWawQeo3vDc/Ja1zKHL9L9SrxH/VPWYOuVQ45of7lYAtqDCMaYan/9fyGg0KG4MFm2evCws9PolWAYjsIpn9e0zRq5vl+rVqFGCa2fsNxy/t//sKXrbppLF0t1sqwmTeWQj7kg8NB75uyTK/H3jz1xnBm1bAKDe3JZTZsO+LhxyxGy6Utm9c5fFEysrAflcY1Vie9pNx9sjPiLAyJb7aGWi5JbkS5R2GDYONRuDBxUbjsegjeRXwLnCKPqD4lde1c3PhdWzfrCppms4Zni1Z71pPaID6u/TIO21CNVc6NnkJh/zu1OVfHW3spG6BVVrDP11cmNoGiRS003Y0nUSjZgNmtUCexR99tIf4RKH2rLLfODjVGhK62P8DCqWdJjWO+so4h6+ylbqded7pZ8Q/QhGnpHY=
  template:
    metadata:
      name: client-credentials
      namespace: alloy
    type: stringData
