---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-credentials
  namespace: alloy
spec:
  encryptedData:
    password: AgA+q3kTYbnkbOSjGQoeQM40+vfEh+5/I1Ulws88biDp6VJor9GODzj+i4u/jetgrEUnMnae2TAPyRyweWdQpEA0Ryzhlqg7+P2617iNlvvr/CcEs0+qHxho02J/IETUX+NRnyajCGh/q2Rz/WGjMfZyA6ek/3ujutAs9Zf6qIf9n5aReLC3xvz2C7HY/nLttlZmDHt4FcIMy/9DWoRM7OyXrwe7ogAx8SuAHDzW+En/j7BJwZVQsNDiogigMlRiZSP+EMtqSEXn7fPA8dUsDzuMO5knYcvYfmhTyJS2PCHi8glf5Yr0/ch70tOWwn4bD3RbPPBWkEOyhMLUtRZeOz1VgNHnkU0UImFEVBCbkWdse+mHO1XMq9lfPD0m1Tss76GcjUvIwghG3sfhJ0CC+ql5L3eIo6G/lAaZhj7CPJPlh6sn01mxF12o3GvHkXQxCo+mw/UAcgnRiJvrW8TX4UylxrJdWSkvH7Kw9BdjBF24wJxGHyiU5ZA+PrlQXSvA/Tj9CHCozK3JShzinRo1ZlxVlTGuoRsbAKgi37ykYEdtQokbDhVfGwiUyx5g/3Q+MFVNK3ilBrpEMXXMS1l221aqBVMELJNCIgBXt5U14PSnQB0hsWchIUjS+Doju0ZsV3UVNc8TsdmbJWbTcNOwKpWvXTTjNmzGVZlxt6FPFMB08yjtXKp1BsSEu3FQ8w9jkSfbc2SehOUZF61+gAOMq+Of8MKU
    username: AgDc/1O6ihMKXAWHuQOCTXrPq8Qi+mhwlXQBMgx3yWgRb6At0ivSLV9O+xFOQb+jlc0YCjNvdLJUcaaWxVCawLneXSXZAeG/xs6qZx78beDY35v0iXfeKyPlTTUlal3MMpwZHVkVQKj60SvrVzgHqJVDh59iErcdJAZgh4LTlro3iATxY4so7CzEbvU/8mAkyGgb4BNFu7OLjMprgIV3gNgOZF9nw4CBR8yobtW+ue8nwb3lWZNuxpxIGKTeFMsjHNWS8vuLv8OxJ9uRsettnX1AYhFq9Jnla1EFjo/05vf2XuxOaSdqiIp1XRHI8SPQk3gnd60xq6Xx+o3P4VIiSsXMqv1T4Lgc8e93nwWJoek8DcYIQW/qMcubN6+paxOeygy8EAsnn+7rm58oSjvJlqeUNfIGVVasa9D5urMxVLza9ucrOgSAhb8CJwRqJuhuorUiRNSxiNr0hamdnuIjgrOzAoKDv9VrEHKSRGN7BekMAMqy/Yp55xzEQPIXdb1oQ7H1cl9e+UqdJNhblTo/IwmtaSeniUguvkbfQ0vZJeClnv9gjJoeZlTDhVQ9TtBtJMGFla8QtaJZ0hWufbm1ENLAyS1qy8CQnMQqVZ8sE5mVA4q6XpLdQfXBbZ9upe0yVdcYVP941ezcNKtPNjw4MFdkASZscXEbCiYL4Zg+sm57eJckkBXAqgMlDnSMWm3sUf2piY0+PW7qdw8=
  template:
    metadata:
      name: client-credentials
      namespace: alloy
    type: stringData
