# https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml

ollama:
  enabled: false

# -- A list of Ollama API endpoints. These can be added in lieu of automatically installing the Ollama Helm chart, or in addition to it.
# @section -- External Tools configuration
ollamaUrls: []

tika:
  enabled: true

websocket:
  # -- Override the Redis URL for websocket communication. If empty, automatically generates URL based on release name. Template: `redis://[:<password>@]<hostname>:<port>/<db>`
  # @section -- Websocket configuration
  url: ""
  redis:
    # -- Enable redis installation
    # @section -- Websocket configuration
    enabled: true
    # -- Redis resources
    # @section -- Websocket configuration
    resources: {}

workload:
  # -- Workload kind to use. Options are "Deployment", "StatefulSet".
  # If not set, the chart will determine the kind based on persistence settings.
  # NOTE: When using Deployment with local persistence and replicaCount > 1,
  # ensure persistence.accessModes includes ReadWriteMany (RWX).
  kind: ""

replicaCount: 2

revisionHistoryLimit: 1

serviceAccount:
  enable: false

ingress:
  enabled: true
  class: cilium
  annotations:
    cert-manager.io/cluster-issuer: iaas-wcooke-me
    forecastle.stakater.com/appName: Open WebUI
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: Apps
    forecastle.stakater.com/icon: https://open-webui.apps.iaas.wcooke.me/images/logo.png
    forecastle.stakater.com/network-restricted: "true"
  host: open-webui.apps.iaas.wcooke.me
  tls: true
  existingSecret: open-webui-ingress

route:
  # -- Enables or disables the route
  enabled: false

  # -- Set the route apiVersion, e.g. gateway.networking.k8s.io/v1 or gateway.networking.k8s.io/v1alpha2
  apiVersion: gateway.networking.k8s.io/v1

  # -- Set the route kind
  # Valid options are GRPCRoute, HTTPRoute, TCPRoute, TLSRoute, UDPRoute
  kind: HTTPRoute

  # -- Annotations to add to the route
  annotations: {}
  # -- Labels to add to the route
  labels: {}

  # -- Hostnames to match for the route
  hostnames: []
  # - "open-webui.example.com"

  # -- References to the parent resources (e.g. Gateway)
  parentRefs: []
  # - name: open-webui-gw

  # -- Enables HTTPS redirect for the route
  httpsRedirect: false

  matches:
    - path:
        # -- Path match type. Note that custom path prefix is not supported in Open WebUI, so any non-default value will break. See https://github.com/open-webui/open-webui/discussions/3431
        type: PathPrefix
        # -- Path match value
        value: /

  # -- Filters define the filters that are applied to requests that match this rule.
  filters: []

  # -- Additional custom rules that can be added to the route
  additionalRules: []

persistence:
  # -- Enable persistence using PVC for Open WebUI data
  # @section -- Persistence configuration
  enabled: true
  # -- Size of the Open WebUI PVC
  # @section -- Persistence configuration
  size: 2Gi
  # -- Use existingClaim if you want to re-use an existing Open WebUI PVC instead of creating a new one
  # @section -- Persistence configuration
  existingClaim: ""
  # -- Subdirectory of Open WebUI PVC to mount. Useful if root directory is not empty.
  # @section -- Persistence configuration
  subPath: ""
  # -- If using multiple replicas, you must update accessModes to ReadWriteMany
  # @section -- Persistence configuration
  accessModes:
    - ReadWriteOnce
  # -- Storage class of the Open WebUI PVC
  # @section -- Persistence configuration
  storageClass: ""
  # -- Selector to match to get the volume bound to the claim
  # @section -- Persistence configuration
  selector: {}
  # -- Additional annotations to add to the PVC
  # @section -- Persistence configuration
  annotations: {}
  # -- Sets the storage provider, availables values are `local`, `s3`, `gcs` or `azure`
  # @section -- Persistence configuration
  provider: local
  s3:
    # -- Sets the access key ID for S3 storage
    # @section -- Amazon S3 Storage configuration
    accessKey: ""
    # -- Sets the secret access key for S3 storage (ignored if secretKeyExistingSecret is set)
    # @section -- Amazon S3 Storage configuration
    secretKey: ""
    # -- Set the secret access key for S3 storage from existing k8s secret
    # @section -- Amazon S3 Storage configuration
    accessKeyExistingSecret: ""
    # -- Set the secret access key for S3 storage from existing k8s secret key
    # @section -- Amazon S3 Storage configuration
    accessKeyExistingAccessKey: ""
    # -- Set the secret key for S3 storage from existing k8s secret
    # @section -- Amazon S3 Storage configuration
    secretKeyExistingSecret: ""
    # -- Set the secret key for S3 storage from existing k8s secret key
    # @section -- Amazon S3 Storage configuration
    secretKeyExistingSecretKey: ""
    # -- Sets the endpoint url for S3 storage
    # @section -- Amazon S3 Storage configuration
    endpointUrl: ""
    # -- Sets the region name for S3 storage
    # @section -- Amazon S3 Storage configuration
    region: ""
    # -- Sets the bucket name for S3 storage
    # @section -- Amazon S3 Storage configuration
    bucket: ""
    # -- Sets the key prefix for a S3 object
    # @section -- Amazon S3 Storage configuration
    keyPrefix: ""

# -- Enables the use of OpenAI APIs
# @section -- OpenAI API configuration
enableOpenaiApi: false

# -- Configure database URL, needed to work with Postgres (example: `postgresql://<user>:<password>@<service>:<port>/<database>`),
# leave empty to use the default sqlite database. Alternatively, use extraEnvVars to construct the database URL by setting the `DATABASE_TYPE`, `DATABASE_USER`, `DATABASE_PASSWORD`, `DATABASE_HOST`, `DATABASE_PORT`and `DATABASE_NAME` environment variables. Each DATABASE_* var must be set or database will default to sqlite.

databaseUrl: ""

# -- Env vars added to the Open WebUI deployment. Most up-to-date environment variables can be found here: https://docs.openwebui.com/getting-started/env-configuration. Variables can be defined as list or map style.
extraEnvVars:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: open-webui-pg-cluster-app
        key: fqdn-uri
  - name: DATABASE_ENABLE_SESSION_SHARING
    value: "True"

  # - name: DATABASE_TYPE
  #   value: postgresql
  # - name: DATABASE_USER
  #   valueFrom:
  #     secretKeyRef:
  #       name: open-webui-pg-cluster-app
  #       key: user
  # - name: DATABASE_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: open-webui-pg-cluster-app
  #       key: password
  # - name: DATABASE_HOST
  #   valueFrom:
  #     secretKeyRef:
  #       name: open-webui-pg-cluster-app
  #       key: host
  # - name: DATABASE_PORT
  #   valueFrom:
  #     secretKeyRef:
  #       name: open-webui-pg-cluster-app
  #       key: port
  # - name: DATABASE_NAME
  #   valueFrom:
  #     secretKeyRef:
  #       name: open-webui-pg-cluster-app
  #       key: dbname

# -- Env vars added to the Open WebUI deployment, common across environments. Most up-to-date environment variables can be found here: https://docs.openwebui.com/getting-started/env-configuration/ (caution: environment variables defined in both `extraEnvVars` and `commonEnvVars` will result in a conflict. Avoid duplicates)
commonEnvVars: []
  # - name: RAG_EMBEDDING_ENGINE
  #   value: "openai"

# -- Env vars added from configmap or secret to the Open WebUI deployment. Most up-to-date environment variables can be found here: https://docs.openwebui.com/getting-started/env-configuration/ (caution: `extraEnvVars` will take precedence over the value from `extraEnvFrom`)
extraEnvFrom: []
  # - configMapRef:
  #     name: my-config
  # - secretRef:
  #     name: my-secret

# -- Configure runtime class
# ref: <https://kubernetes.io/docs/concepts/containers/runtime-class/>
runtimeClassName: ""

# -- Configure container volume mounts
# ref: <https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/>
volumeMounts:
  initContainer: []
  # - name: ""
  #   mountPath: ""
  container: []
  # - name: ""
  #   mountPath: ""

# -- Configure pod volumes
# ref: <https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/>
volumes: []
# - name: ""
#   configMap:
#     name: ""
# - name: ""
#   emptyDir: {}

sso:
  enabled: true
  enableRoleManagement: true
  oidc:
    enabled: true
    clientExistingSecret: open-webui-keycloak-client
    clientIdExistingSecretKey: client-id
    clientExistingSecretKey: client-secret
    providerUrl: https://keycloak.apps.iaas.wcooke.me/realms/iaas/.well-known/openid-configuration
    providerName: Keycloak
    scopes: openid email profile
  roleManagement:
    # -- The claim that contains the roles (can be nested, e.g., user.roles)
    # @section -- Role management configuration
    rolesClaim: roles
    allowedRoles: open-webui-user
    # -- Comma-separated list of roles allowed to log in as admin (receive open webui role admin)
    # @section -- Role management configuration
    adminRoles: open-webui-admin

# -- Extra resources to deploy with Open WebUI
extraResources: []
  # - apiVersion: v1
  #   kind: ConfigMap
  #   metadata:
  #     name: example-configmap
  #   data:
  #     example-key: example-value
