# https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml

ollama:
  enabled: false

# -- A list of Ollama API endpoints. These can be added in lieu of automatically installing the Ollama Helm chart, or in addition to it.
# @section -- External Tools configuration
ollamaUrls: []

tika:
  enabled: true

websocket:
  # -- Override the Redis URL for websocket communication. If empty, automatically generates URL based on release name. Template: `redis://[:<password>@]<hostname>:<port>/<db>`
  # @section -- Websocket configuration
  url: ""
  redis:
    # -- Enable redis installation
    # @section -- Websocket configuration
    enabled: true
    # -- Redis resources
    # @section -- Websocket configuration
    resources: {}

workload:
  # -- Workload kind to use. Options are "Deployment", "StatefulSet".
  # If not set, the chart will determine the kind based on persistence settings.
  # NOTE: When using Deployment with local persistence and replicaCount > 1,
  # ensure persistence.accessModes includes ReadWriteMany (RWX).
  kind: ""

replicaCount: 2

revisionHistoryLimit: 0

serviceAccount:
  enable: false

ingress:
  enabled: true
  class: cilium
  annotations:
    cert-manager.io/cluster-issuer: iaas-wcooke-me
    forecastle.stakater.com/appName: Open WebUI
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: Apps
    forecastle.stakater.com/icon: https://open-webui.apps.iaas.wcooke.me/static/favicon.svg
    forecastle.stakater.com/network-restricted: "true"
  host: open-webui.apps.iaas.wcooke.me
  tls: true
  existingSecret: open-webui-ingress

route:
  # -- Enables or disables the route
  enabled: false

  # -- Set the route apiVersion, e.g. gateway.networking.k8s.io/v1 or gateway.networking.k8s.io/v1alpha2
  apiVersion: gateway.networking.k8s.io/v1

  # -- Set the route kind
  # Valid options are GRPCRoute, HTTPRoute, TCPRoute, TLSRoute, UDPRoute
  kind: HTTPRoute

  # -- Annotations to add to the route
  annotations: {}
  # -- Labels to add to the route
  labels: {}

  # -- Hostnames to match for the route
  hostnames: []
  # - "open-webui.example.com"

  # -- References to the parent resources (e.g. Gateway)
  parentRefs: []
  # - name: open-webui-gw

  # -- Enables HTTPS redirect for the route
  httpsRedirect: false

  matches:
    - path:
        # -- Path match type. Note that custom path prefix is not supported in Open WebUI, so any non-default value will break. See https://github.com/open-webui/open-webui/discussions/3431
        type: PathPrefix
        # -- Path match value
        value: /

  # -- Filters define the filters that are applied to requests that match this rule.
  filters: []

  # -- Additional custom rules that can be added to the route
  additionalRules: []

persistence:
  # -- Enable persistence using PVC for Open WebUI data
  # @section -- Persistence configuration
  enabled: true
  # -- Size of the Open WebUI PVC
  # @section -- Persistence configuration
  size: 2Gi
  # -- Use existingClaim if you want to re-use an existing Open WebUI PVC instead of creating a new one
  # @section -- Persistence configuration
  existingClaim: ""
  # -- Subdirectory of Open WebUI PVC to mount. Useful if root directory is not empty.
  # @section -- Persistence configuration
  subPath: ""
  # -- If using multiple replicas, you must update accessModes to ReadWriteMany
  # @section -- Persistence configuration
  accessModes:
  - ReadWriteOnce
  # -- Storage class of the Open WebUI PVC
  # @section -- Persistence configuration
  storageClass: ""
  provider: s3
  s3:
    accessKeyExistingSecret: open-webui-bucket
    accessKeyExistingAccessKey: AWS_ACCESS_KEY_ID
    secretKeyExistingSecret: open-webui-bucket
    secretKeyExistingSecretKey: AWS_SECRET_ACCESS_KEY
    endpointUrl: https://rook-ceph-rgw-ceph-objectstore.rook-ceph-cluster.svc
    region: us-east-1
    bucket: open-webui

enableOpenaiApi: false

databaseUrl: ""

extraEnvVars:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: open-webui-pg-cluster-app
        key: fqdn-uri
  - name: DATABASE_ENABLE_SESSION_SHARING
    value: "True"
  - name: AWS_CA_BUNDLE
    value: /cacerts/ca-bundle.pem
  - name: CORS_ALLOW_ORIGIN
    value: 'https://open-webui.apps.iaas.wcooke.me'
  - name: S3_ADDRESSING_STYLE
    value: path
  # - name: REQUESTS_VERIFY
  #   value: "False"
  - name: SSL_CERT_FILE
    value: /cacerts/ca-bundle.pem
  # - name: DATABASE_TYPE
  #   value: postgresql
  # - name: DATABASE_USER
  #   valueFrom:
  #     secretKeyRef:
  #       name: open-webui-pg-cluster-app
  #       key: user
  # - name: DATABASE_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: open-webui-pg-cluster-app
  #       key: password
  # - name: DATABASE_HOST
  #   valueFrom:
  #     secretKeyRef:
  #       name: open-webui-pg-cluster-app
  #       key: host
  # - name: DATABASE_PORT
  #   valueFrom:
  #     secretKeyRef:
  #       name: open-webui-pg-cluster-app
  #       key: port
  # - name: DATABASE_NAME
  #   valueFrom:
  #     secretKeyRef:
  #       name: open-webui-pg-cluster-app
  #       key: dbname

volumeMounts:
  container:
  - name: cabundle
    mountPath: /cacerts

volumes:
- name: cabundle
  secret:
    secretName: tm-ca-bundle-secret

sso:
  enabled: true
  enableRoleManagement: true
  oidc:
    enabled: true
    clientExistingSecret: open-webui-keycloak-client
    clientIdExistingSecretKey: client-id
    clientExistingSecretKey: client-secret
    providerUrl: https://keycloak.apps.iaas.wcooke.me/realms/iaas/.well-known/openid-configuration
    providerName: Keycloak
    scopes: openid email profile
  roleManagement:
    # -- The claim that contains the roles (can be nested, e.g., user.roles)
    # @section -- Role management configuration
    rolesClaim: resource_access.open-webui.roles
    allowedRoles: open-webui-user
    # -- Comma-separated list of roles allowed to log in as admin (receive open webui role admin)
    # @section -- Role management configuration
    adminRoles: open-webui-admin
