apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: ceph-dashboard
spec:
  forProvider:
    email: ceph-dashboard
    login: ceph-dashboard
    name: ceph-dashboard
    passwordSecretRef:
      key: password
      name: grafana-ceph-dashboard-user
      namespace: rook-ceph-cluster
  providerConfigRef:
    name: provider-grafana-config
